### ISSUE TITLE
Avoid loading missing tiles outside of a defined area

### ISSUE THREAD

**Issue by lapo-luchini** [Leaflet/Leaflet#1021]
It could be nice to have a way to tell the `TileLayer` which tiles are available on the server; something like OpenLayers' [`displayOutsideMaxExtent`](http://dev.openlayers.org/releases/OpenLayers-2.7/doc/apidocs/files/OpenLayers/Layer-js.html#OpenLayers.Layer.displayOutsideMaxExtent).

Missing tiles which are returning 404 don't show up on the map and thus everything already looks good, but even if they are lightweight requests that will fail, it could be nice to avoid them.

I guess this could be done in `L.TileLayer._tileShouldBeLoaded`, but right now I don't have understood the source enough to try and do a patch.

**Comment by nmeln** [comment]
Is there any example of using `bounds` option?
I'm trying to use it without success, Leaflet still requests tiles out of bounds

**Comment by jordan314** [comment]
This was from a custom map:
```
var southWest = new L.LatLng(-252, 4);
var northEast = new L.LatLng(-5, 254);
var bounds = new L.LatLngBounds(southWest, northEast);

var commonsettings = {
            minZoom: 1,
            maxZoom: 5,
        	  ...
            noWrap: true,
            bounds: bounds
        };

var tileLayer = new L.zoomTMSLayer(commonsettings);
```

**Comment by jmuchaxo** [comment]
I have same issue, mapbox Tilemill avoid render/export transparent tiles, I made them less transparent with background: rgba(255,255,255,0.1) and now it does export all tiles, however the interactivity utf grid is not exported for tiles with missing data... so I still find 404 some grid tiles missing

**Comment by perliedman** [comment]
@jmuchaxo I don't see how Leaflet could fix this... if the tiles are not exported, they will be missing and there is not way for Leaflet to workaround this.

On the other hand, a 404 in itself shouldn't be much of a problem either...

**Comment by jmuchaxo** [comment]
thank you, I managed to fix the 404 for the grid, I created a polygon grid with Qgis then subtracted the region polygons so that all the area has interactivity and so all grid tiles are now exported with Tilemill.

**Comment by hjrobinson** [comment]
See my answer in https://github.com/Leaflet/Leaflet/issues/3066.

**Comment by etay-zas** [comment]
Hi there!
[My map](https://etay-zas.github.io/) has empty space in it's overlay tile layer.
Does anybody have a solution for this situation?
Thanks in advance,
Etay

**Comment by hjrobinson** [comment]
It's been a little while since I played with this.  Have you experimented with using QTiles or Tiles XYZ in QGIS to generate the tiles instead of TileMill?  Which tool (QTiles or Tiles XYZ) you use depends on the version of QGIS, but they're similar. You might be able to generate transparent tiles this way and get around the problem.  You still have to set maxBounds for your map.  You may also want to set maxBoundsViscosity if you want to limit panning to a given bounds. You can do a YouTube search for demos of QTiles and Tiles XYZ.  Here's the one I watched but there are others:
https://www.youtube.com/results?search_query=qtiles

**Comment by Aechee** [comment]
As per the solutions mentioned above, you must need to know the bounds of the tile layer, but in my case i don't know the bounds of tiled map layer, and so i can't specify the bounds. How would i cater situation in this case ? 

I have also specified the `errorTileUrl`, but it's still sending the call to the missing tile, and that's returning 403 forbidden. I have even registered an event to handle that, but it comes in the event after the error, that means it still fill the console with the forbidden messages. 

Any solution for it ?

**Comment by hjrobinson** [comment]
Good morning. I would like to help but it's been a long time since I've worked with this stuff. Off the top of my head the best advice I can give you is to figure out your map bounds.  A tool I used to figure this out was OpenStreetMap Nominatim. I've pasted the link below:

https://nominatim.openstreetmap.org/ui/search.html

I remember this requiring some trial and error because some of the x and y values might be flip flopped between Leaflet and Nominatim.

If you still can't get this to work then you may just have to live with the 403s. 

I don't want to send you down a deep rabbit hole and this is somewhat unrelated but It's been years since I've worked with Leaflet. I remember switching to use Mapbox GL JS so I could use vector tiles. Mapbox GL JS also supports image tiles/rasters.  I don't know if Leaflet supports vector tiles yet or even if it does if you can use them in a practical way. There used to be a Leaflet plugin where you could use vector tiles and that had a lot of limitations but maybe things have gotten better since I last experimented with it. I know two or three years ago Mapbox started charging to use Mapbox GL JS although if you use an older version of it you can avoid this.
