### ISSUE TITLE
destroy/re-use map

### ISSUE THREAD

**Issue by boredom2** [Leaflet/Leaflet#1030]
Hi,

is there any preferred way of removing/re-using the map object? 
when just "nulling" the L.map object and emptying the <div>, its ok as long as I dont try to restart the map.

map=L.map('content').fitWorld();
....
$('#content').html('');
map=null
....
map=L.map('content').fitWorld(); 
=> Error: Error: Map container is already initialized.

what is the preferred method to achieve something like that?

Thanks a lot - its a great library :P

**Comment by jbcoder** [comment]
@mourner Has there been any further development in reusing or reinitializing a map or is this still the best solution?

I'm in a situation where I am trying to use one div to be able to edit a map and then view it without editing tools. I need to store the data in the html so that it can be used elsewhere. However, I don't really want to have to make two maps for the same div (one for editing and one for viewing). So, I'd like to just reinitialize it without controls and without destroying the node. However, if that's what needs to be done, then so be it.

Sorry for exhuming this.

**Comment by mourner** [comment]
@jbcoder do you have a particular issue with `map.remove()`?

**Comment by jbcoder** [comment]
@mourner It is probably a user error, but I haven't been able to get that function to work.

I've created a work around for now though. Thanks!

**Comment by DevRapitow** [comment]
map.remove does not clear all listeners as I get:

renderer.js:55 Cannot read property appendChild of undefined

if I use map.remove() and then create a new map.

**Comment by perliedman** [comment]
@DevRapitow can you provide an example that reproduces this problem (preferably on [Leaflet Playground](http://playground-leaflet.rhcloud.com/?html,output))?

We have unit tests for `remove`, but maybe this is something we haven't covered yet.

**Comment by perliedman** [comment]
@DevRapitow hi, can you provide an example reproducing this problem, preferably on [Leaflet Playground](http://playground-leaflet.rhcloud.com/?html,output)?

**Comment by DevRapitow** [comment]
Yes I can. I will try to set something up in the playground.

**Comment by DevRapitow** [comment]
http://playground-leaflet.rhcloud.com/ruqa/edit?html,output

**Comment by catbadger** [comment]
ALL THE LINKS ARE 404. THIS SHOULD BE CLOSED.

**Comment by mrinalusp** [comment]
When I select any other map , for example  the ESRI Map to have a different look and feel and then click on the the aiports layer,  the icons dont show up.

![image](https://user-images.githubusercontent.com/18711965/36506413-8f2e9e06-1724-11e8-90f1-714ea055d798.png)
