### ISSUE TITLE
mouseenter & mouseleave events not firing on map object

### ISSUE THREAD

**Issue by robpvn** [Leaflet/Leaflet#1144]
The documentation refers to mouseenter and mouseleave events that are supposed to be fired from the map object, but when I listen to them they're not getting fired. (Example in this JSFiddle, use Firebug/Developer Tools to see the console output: http://jsfiddle.net/kEeGW/10/ )

I've tested this with both the stable 0.40 released version and the git master,  in IE, Firefox and Chrome. All exhibit the same behaviour.

**Comment by xDarkShadowKnightx** [comment]
I'm finding myself in need of this functionality in a project I'm working on. Is there a way to access mouseenter/mouseleave behavior? I need it for L.geoJson objects, but I can only use mouseover/mouseout.

**Comment by Eschon** [comment]
@xDarkShadowKnightx I don't know what exactly your trying to do but couldn't you just listen to the mouseover/mouseout event on the map container, or any other container inside it that contains the objects you want to listen to?

**Comment by xDarkShadowKnightx** [comment]
@Eschon Basically were rendering kml polygons (a layer) on the map (using omnivore.kml and L.geoJson), which have markers in them. Hovering over the layer fires the mouseover event, the problem is when I hover over a marker that is within one of the layers. As it fires the mouseout event, even though the mouse is still inside the layer. mouseleave (if implemented like the browser does it) would only fire when the mouse has actually left the layer.

Also I've tried many things to attach a mouseleave to these layers without success. How would you go about doing this?

**Comment by Eschon** [comment]
@xDarkShadowKnightx I don't know. Have you tried to attach the event to the actual HTML element? If that doesn't work I don't know what would.

**Comment by xDarkShadowKnightx** [comment]
It appears that mouseenter and mouseover are currently being interpreted as the same thing (DomEvent.js line 74: http://git.io/veoiK). Separating those into separate events may help. Could someone possibly add this as a minor feature? I feel that this could be really useful.

**Comment by metsfan** [comment]
I was able to work around this by attaching the mouseenter and mouseleave events directly to the underlying HTML element using addEventListener.  As long as you aren't using canvas-based rendering (i.e. using SVG or using a DivIcon), this method should work perfectly fine.  Seems silly that leaflet would exclude these events from ALL elements to work around issues with the map tiles.
