### ISSUE TITLE
Slow zoom animation in Chrome when using more than one tile layer

### ISSUE THREAD

**Issue by jfgirard** [Leaflet/Leaflet#123]
Hi,
I experience a weird behavior with a WMS layer (on top of the OSM layer) .  Using Chrome, if I zoom 2 times in row or pan then zoom quickly, the processor goes to 100% for many seconds (over 10 sometimes) until it come back.   Chrome event ask me to kill the page after a while.  But on both firefox and safari, the speed is fine. 

It's tested it with the latest leaflet.js and a version from 2 weeks ago and it's the same.
Any idea why ?

Jeff

If it makes a difference, i'm running on OS X 10.6.

**Comment by AdnanBoota** [comment]
Hi Guys,

After searching a lot about slow tile on zoom, i came to this link.

I am using the latest version of the leaflet, but facing issues with the zoom effect.  I have multiple layers on the map, and getting the slow zoom in leaflet.

1. The map tiles and wms layer tiles are taking more time to load when we zoom on it.

Please  let me know i am beginner in leaflet.

![imagen](https://user-images.githubusercontent.com/14972616/31679995-34a192aa-b373-11e7-9058-eea9a9454d8a.png)

**Comment by cherniavskii** [comment]
If I understand correctly, it is not a Leaflet issue.
Most probably it's because of parallel http connections limit in browser.

Please note that this issue tracker is used for bugs. For support or questions please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet).
If you really sure it's Leaflet issue, please fill up issue template and provide link to minimal example reproducing the issue.
