### ISSUE TITLE
Wider clickable area for polylines on touch devices

### ISSUE THREAD

**Issue by DennisSchiefer** [Leaflet/Leaflet#1264]
Some ideas to improve the touch experience of Leaflet - with regards to fingers, not pens. This could be implemented by the end-user, but having these feature available directly in Leaflet would be convenient:
- While dragging a marker, the marker should not be beneath the fingertip and thus be invisible. Instead, move the marker a delta to the top left. When releasing the marker it should should rest under the fingertip again, though.
- Polylines should have an active width separate from the drawing width, so that it is easier to click on them with a big finger.

**Comment by mngyng** [comment]
For the SVG counterpart, I find this following useful-- if the polygon/layer is small enough that you don't mind the extra response time:
https://github.com/perliedman/leaflet-touch-helper
I did that along with the popup binding. For example:
```
function popUpGeojson(feature, layer) {
    layer.bindPopup(feature.properties.description);
    layer.on("add", function(e){
        L.path.touchHelper(this, {extraWeight: 15}).addTo(map);
    });
}
var geoJSONLayer = new L.GeoJSON.AJAX("foo.geojson",{onEachFeature: popUpGeojson});
geoJSONLayer.addTo(map);
```
It might be simpler if I set the polygon rendering globally using canvas, but I have problem figuring out how I can click through another canvas layer that I'm using for vector tiles. Since SVG sits happily with canvas, I'm going to stick with this "leaflet-touch-helper" for now.
