### ISSUE TITLE
TileLayer.setOpacity not working with Android browser

### ISSUE THREAD

**Issue by omjokine** [Leaflet/Leaflet#1334]
TileLayer.setOpacity doesn't work with Android's (4.1.2) default browser. Works fine with Chrome for Android and all desktop browsers I've tested.

Tested with Leaflet 0.4.5 and 0.5.

Here's JSFiddle which uses MapQuest as base layer and OSM as overlay. OSM overlay  opacity is set to 0.5 with setOpacity.
http://jsfiddle.net/CHJCJ/5/

**Comment by iippa73** [comment]
Unfortunately propably not just an emulator issue :( Samsung Galaxy Trend Plus (GT-S7580) running android 4.2.2 (API 17) and default browser seems to be having exactly the same problem. See the screencaptures taken from device the fiddles listed above.

Nonworking opacity on http://jsfiddle.net/CHJCJ/5/
![screenshot_2015-03-10-19-01-36](https://cloud.githubusercontent.com/assets/11397044/6580310/60a89baa-c758-11e4-9d42-f6d7dfc08823.png)
Workaround on http://jsfiddle.net/CHJCJ/9/
![screenshot_2015-03-10-19-02-29](https://cloud.githubusercontent.com/assets/11397044/6580321/79c1f06e-c758-11e4-99d7-3f20049f77f3.png)

Clear difference.

0.7.2-release and stable-branch seem to be having the problem, current master is ok. I tried out some bisecting and following commit seems to be fixing it: 22cfd12956f6dcf4e3f5d3e2ee34b8046bdf1fe4
"Fade tiles with requestAnimationFrame rather than CSS"

ps. Thanks for the great and light map engine :)

**Comment by mourner** [comment]
@iippa73 thanks for looking into this! Glad it's fixed on master. 
Another Android WTF... cc @jfirebaugh :)

**Comment by iippa73** [comment]
Any thoughts to patch it to stable-branch on some timeframe?

**Comment by yemaw** [comment]
Tiles opacity is not working on Android 4.x real devices. Any official fix for this issue?
I'm using Leaflet version 1.0.0-beta.2.

**Comment by RicardoSnow** [comment]
@yemaw Did you found any solution for your problem?

**Comment by madgrizzle** [comment]
IIRC, it worked fine on an actual device and was an issue with the emulator.. 


-------- Original Message --------
Subject: Re: [Leaflet/Leaflet] TileLayer.setOpacity not working with
Android browser (#1334)

**Comment by carlosgracite** [comment]
I can confirm this problem is occurring in real devices using the stock browser or webview (the problem doesn't shows up on Chrome). I reproduced it using Samsung Galaxy SIII (Android 4.3) and Samsung Galaxy Advance (Android 4.1.2).

Using @RobertSasak tweak I managed to make it work on Leaflet 0.7.7, but even with this fix, it still occurs in the RC builds.

**Comment by carlosgracite** [comment]
I just made a dirty workaround that seemed to solve the problem (at least for my use case it doesn't appear to create any unwanted side effect). 

What I did was modify the [_updateOpacity() method](https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/GridLayer.js#L291) method by removing the `L.DomUtil.setOpacity(this._container, this.options.opacity);` line and using `this.options.opacity` instead of 1 in the tile fade loop. So in the end it became this:

```java
_updateOpacity: function () {
     ...
    if (L.Browser.ielt9) { return; }

    // setOpacity() for container removed.

    var now = +new Date(),
	    nextFrame = false,
	    willPrune = false;

    for (var key in this._tiles) {
		var tile = this._tiles[key];
		if (!tile.current || !tile.loaded) { continue; }

		// Change here
		var fade = Math.min(this.options.opacity, (now - tile.loaded) / 200);

		L.DomUtil.setOpacity(tile.el, fade);
		if (fade < this.options.opacity) {       // And here
		 ...
```

(at least for my use case it doesn't appear to create any unwanted side effect)
