### ISSUE TITLE
Clicking on Control causes DragStart event on map

### ISSUE THREAD

**Issue by dannychua** [Leaflet/Leaflet#1343]
I created a popup using a L.Control and some HTML passed in as `hoverContent`.

```
App.control = new HoverControl(hoverPoint, hoverContent, options);
```

**Problem:** When a user clicks/drags on this popup, the map starts moving as if the user has clicked through the popup and onto the map, causing a `dragstart` and `dragend` to fire. When the user drags on the scrollbar on this popup, the `dragstart` occurs but the `dragend` does not fire.

Is this a known problem? I fixed this issue for my case by disabling map dragging when necessary.

**Comment by techieshark** [comment]
I think Control.Zoom.js changed since [the comment](https://github.com/Leaflet/Leaflet/issues/1343#issuecomment-13059621) above. 

I believe it was referring to this line (linking to a specific commit instead of HEAD so the link remains accurate even if the code changes later): https://github.com/Leaflet/Leaflet/blob/8f3a353d84909f7b6cf27d6a37b162af01cc2dc0/src/control/Control.Zoom.js#L65

But the following (using `disableClickPropagation()` is simpler and works for me:

````
    var el = L.DomUtil.create('div', 'my-control leaflet-bar');
    L.DomEvent.disableClickPropagation(el);
````
