### ISSUE TITLE
binding to "touchstart" events on map?

### ISSUE THREAD

**Issue by gr2m** [Leaflet/Leaflet#1542]
I try to make this work on iOS / Safari:

``` js
var map = L.map('map').setView([51.505, -0.09], 13);
map.on('touchstart', function() {
  // does not get here when touching the map
  alert('touchstart')
})
```

But couldn't figure out how. It's not listed in the [API reference](http://leafletjs.com/reference.html#map-events) but I wonder if there is any way to support this event?

Or maybe there is even a better way to achieve the following: 
I want to add a marker to a map, by touch and holding for a second. It was easy to set this up for mouse events, but I can't find a way to make the same for touch events.

Any idea?

**Comment by levijackson** [comment]
Expanding on the post above... for touch events the `touch.clientX` and `touch.clientY` may not be accurate if the map is not full screen. When I tried the above code the coordinates were off by a bit. I took a look at the way Leaflet figures out the coordinates from event data in `L.DomEvent. getMousePosition()` and replicated the logic with touch events.

Instead of doing
```
touch = e.touches[0]
containerPoint = L.point(touch.clientX, touch.clientY)
```
I did
```
var touch = e.touches[0],
    rect = this._container.getBoundingClientRect(),
    lat = touch.clientX - rect.left - this._container.clientLeft,
    lng = touch.clientY - rect.top - this._container.clientTop,
    containerPoint = L.point(lat, lng),
```
