### ISSUE TITLE
Inserting Map into a hidden div doesn't work correctly

### ISSUE THREAD

**Issue by crofty** [Leaflet/Leaflet#159]
A map that is inserted into a hidden div (which is then shown) behaves differently to a map inserted into a visible div.  The viewport appears messed up - some tiles load but often they are outside the viewport.

**Comment by zhen1991** [comment]
Hi
I am facing the same problem,please can you answer i have tried with map.invalidateSize() but is not working!
thnx for helping :)

**Comment by ghybs** [comment]
Hi @zhen1991, great to hear that you find Leaflet useful!

You will find **plenty** posts solving this issue in many situations and with many frameworks on [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) and [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

For example: https://stackoverflow.com/search?q=%5Bleaflet%5D+invalidatesize

If you still need help on using Leaflet, please open a new question on [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) with a reproduction example, instead of commenting such a very old and closed ticket.
