### ISSUE TITLE
Is it possible to determine how 'moveend' event was triggered?

### ISSUE THREAD

**Issue by mbektimirov** [Leaflet/Leaflet#1686]
Hi! I need to determine how 'moveend' event was fired - by mouse or programmatically. Is it possible?

**Comment by af7** [comment]
My use case is the following:

I want to capture all position-related changes on the map with only the `moveend` event handler (so that no replication exists if also using the `zoomend` one).

So, I just want a way to determine if **zoom** was the reason of the moveend so that I can do some extra stuff on the 'movend' handler. 

I see that you have `e.type: "moveend"` but I would also need the extra property of `e.subtype: "zoom"` (for example)

**Comment by zdila** [comment]
I have another usecase. On button click I want map view to follow GPS (calling `map.locate({ setView: true, watch: true })`) but when user moves the map manually I want to stop the map to follow GPS (calling `map.locate({ setView: false, watch: true })`).

Or is there a workaround for this usecase, @mourner?
