### ISSUE TITLE
Polyline and Polygon drawing/editing

### ISSUE THREAD

**Issue by elcuervo** [Leaflet/Leaflet#174]
Is there any plan or idea about adding drawing tools or something? i've playing with Path and writing a custom handler for it but perhaps there are better approaches.

**Comment by carrbrpoa** [comment]
Hello,
I know this issue is a lot old, but it's about Polygon editing:

There's a way to avoid performance issues when enabling edit in a feature such the following?

![image](https://user-images.githubusercontent.com/10212618/95641531-50ed9480-0a79-11eb-8d0e-391a69614541.png)

It takes several seconds to the browser just enable those markers.

(PS: I can open a new issue about that, if it feels better)

Thanks in advance!

**Comment by johnd0e** [comment]
> There's a way to avoid performance issues when enabling edit in a feature such the following?

Leaflet itself does not have edit features.
Perhaps you are using Leaflet.draw plugin, which is not supported here.
