### ISSUE TITLE
Document layerGroup id option

### ISSUE THREAD

**Issue by tmcw** [Leaflet/Leaflet#1805]
`L.layerGroup` has a function `getLayer` that finds layers by ids, but how layers _get_ ids is unexplained

```
L.layerGroup({ foo: L.tileLayer('') }).getLayer('foo') // no dice
```

Is there an id option for layers? This needs better explaining around.

**Comment by vamsiampolu** [comment]
This looks like a snake biting it's own tail,I am trying to use this with the `L.geoJson` in order to allow removing of features if nessecary,it looks like one needs a `layer` in order to get the `layerId` and one needs a `layerId` to get the `layer`. The only way I can think of for my situation has to be:

1. Use a loop to convert each feature to geojson to check for my unique id from the database and get the `index` of that 
2. Use the getLayers method and obtain the _leaflet_id of the feature using the `index`.
3.  Remove the layer from the `L.geoJson` layer group.

Instead,one could save me so much iteration and return the `_leaflet_id` from addData in `L.geoJson` and `addLayer` in `LayerGroup`. I would then use the `_leaflet_id` to retrieve or remove the feature directly.

**Comment by Lacroute** [comment]
Is there a getter implemented ? I'm trying to acces to my layer id but it returns undefined...

**Comment by tmcw** [comment]
Closing; focus is on 1.0

**Comment by mn113** [comment]
Leaflet 1.0 came out but there is still no way to access layers other than with `getLayerId(layer)` and `getLayer(id)`...

**Comment by zakjan** [comment]
@tmcw Could you reopen this issue?

**Comment by ghybs** [comment]
Hi @Lacroute, @mn113 and @zakjan,

Please can you kindly provide more context on your issue?

From what @vamsiampolu described, I understand that there is a "hole" when using `L.geoJSON` factory and/or its `addData` method, in that you provide GeoJSON data in, get a Layer Group full of Leaflet layers out, but you lose the one-to-one association between them in the process.
Therefore you have to loop through all items in the Layer Group to scan their `_leaflet_id` and match it with whatever `id` you have in your GeoJSON properties.

In the case of `addData`, this may be especially frustrating, as you may provide just a single new feature, but you do not directly get the newly created Leaflet layer. Therefore you have to scan through _all_ items in the group to find the new layer.

On the other hand, as for the `addLayer` method of Layer Group, I do not see the issue as you have to provide a Leaflet layer in the first place, on which you can get the `_leaflet_id` using [`L.stamp`](http://leafletjs.com/reference-1.0.0.html#util-stamp).

If this is your situation, then it seems to me that you could simply build a specific method, similar to `addData`, assuming that you provide a single feature (because adding an array of features / feature collection would make things much more complicated):

```javascript
L.GeoJSON.include({
    addSingleFeature: function (geojson) {
        // Same as addData, without the management of array / feature collection.
        var options = this.options;

        if (options.filter && !options.filter(geojson)) { return this; }

        var layer = L.GeoJSON.geometryToLayer(geojson, options);
        if (!layer) {
            return this;
        }
        layer.feature = L.GeoJSON.asFeature(geojson);

        layer.defaultOptions = layer.options;
        this.resetStyle(layer);

        if (options.onEachFeature) {
            options.onEachFeature(geojson, layer);
        }

        this.addLayer(layer);

        // Return the newly created layer instead of this.
        return layer;
    }
});
```

Then you have to call it on individual GeoJSON feature, but you directly get the Leaflet layer that has been created.
Note also that you can no longer chain calls, since you get the new individual layer, not the parent Layer Group.

**Comment by Lacroute** [comment]
@ghybs 
Thank you for your detailled answer. `L.stamp` seems to fix the problem, I'll try it soon.

To be more specific on my probelm, I was working on a GeoJSON dataset, and I used `[onEachFeature](http://leafletjs.com/reference-1.0.0.html#geojson-oneachfeature)` to loop through my features and bind some behaviors and store data. Then, when I wanted to update styles on the fly I was stuck beacause I couldn't use `[getLayer](http://leafletjs.com/reference-1.0.0.html#layergroup-getlayer)`. the _leaflet_id was unaccessible... So after the onEachFeature loop, the only solution available was to loop again my LayerGroup returned from the L.GeoJSON method to store the id for later.

If you want to take a look, this was the [project I worked on](https://github.com/Lacroute/tdf2016/blob/master/src/components/Tdf.vue#L184) but be gentle, I did this piece of code in one weekend !

**Comment by Pushplaybang** [comment]
would the simplest solution to this, not be to set and get a custom id?

currently, my only option seems to be to add markers individually (storing them in an es6 map) and then modify them via the custom id that I use to store them there, which doesn't allow me to add them and manipulate them as a layer or feature group as far as I can tell.

**Comment by perliedman** [comment]
@Pushplaybang not sure I fully understand the problem you're seeing, so feel free to expand with an example of what you mean by "doesn't allow me to add them and manipulate them as a layer or feature group"? Storing layers in a hash or ES6 map should work well.

As mentioned above, you can always get unique identifiers for an object using `L.stamp(obj)`, if you don't want to generate identifiers yourself.

**Comment by skipjack** [comment]
Note that there is a fair amount of interest in something like this, you can see that in these two so questions that have garnered a decent number of votes:

- https://stackoverflow.com/questions/13004226/how-to-interact-with-leaflet-marker-layer-from-outside-the-map/37681431?noredirect=1
- https://stackoverflow.com/questions/25683871/assign-id-to-marker-in-leaflet

> Disclosure: I do have answers on both of those but in neither are the "leaflet recommended" approach. Would be happy to update my answers if there is one or for someone else to submit a new answer if there is a better/simpler built-in approach.
