### ISSUE TITLE
bindPopup after click event

### ISSUE THREAD

**Issue by diegoguidotti** [Leaflet/Leaflet#1823]
The following code stops working on 0.6 library. Clicking on the marker seems to create a popup, the autopan works but the popup is not visible.

``` javascript
var marker=new L.Marker(new L.LatLng(43,10)).addTo(map);    
    marker.on({
    click: function (e) {
        var html='Test content';
        marker.bindPopup(html).openPopup();
    }});
```

**Comment by robertleeplummerjr** [comment]
Why is the current strategy to have one event handler per element?  Why isn't it a much more performant one click handler on the parent element?  Example:

```javascript
map.on('featureclick', function(e, feature) {
  L.popup()...
});
```

Notice you have one event handler for all features, rather than an event handler per feature.  This feature doesn't exist that I know of, but would be easy to implement and would cut down substantially on resource usage during map initialization.

**Comment by mourner** [comment]
@robertleeplummerjr this is how it's done in Leaflet 1.0 beta under the hood. All DOM events are delegated to the map object.

**Comment by hafiqsalleh** [comment]
how to remove the click event? i want it to show all the time.

**Comment by perliedman** [comment]
@hafiqsalleh see [`closePopupOnClick`](http://leafletjs.com/reference-1.1.0.html#map-closepopuponclick), [`closeOnClick`](http://leafletjs.com/reference-1.1.0.html#popup-closeonclick) and possibly [`autoClose`](http://leafletjs.com/reference-1.1.0.html#popup-autoclose)
