### ISSUE TITLE
SSL support for cdn.leafletjs.com

### ISSUE THREAD

**Issue by jfirebaugh** [Leaflet/Leaflet#1824]
Is this possible?

We're switching over to use protocol-relative URLs in all the MapBox.js documentation and examples, and it would be nice to be able to use them for the cdn.leafletjs.com URLs with [Standalone MapBox.js](http://www.mapbox.com/mapbox.js/api/v1.1.0/#Standalone MapBox.js).

**Comment by jfirebaugh** [comment]
This should be possible now with SNI. /cc @miccolis

**Comment by mourner** [comment]
SNI has a significant gap in browser support though — e.g. https://www.digicert.com/ssl-support/apache-secure-multiple-sites-sni.htm states that "No versions of Internet Explorer on Windows XP support SNI".

**Comment by althaus** [comment]
Aren't IE and XP death enough to dump them in this case? Without proper security updates it's shouldn't be a risk to use SNI for all the other browsers?

**Comment by michaelkirk** [comment]
Hiya! 

Found this thread after getting a certificate error while serving off a protocol relative url. I'm trying to use Github Pages + Leaflet as an easy platform for people to learn and publish maps. However, one of our students just hit a mixed content error because GH Pages (and the rest of the internet) is moving to SSL-by-default hosting, yet the CDN in leaflet docs doesn't support SSL.

It looks like you're still on Cloudfront. I'm sure there's a really cool solution involving let's encrypt machinery, but if that seems like too much research/automation, you can upload a regular old SSL cert to AWS and cover 99% of your users for the next 3 years for [$26.55](https://www.namecheap.com/security/ssl-certificates/domain-validation.aspx). The [1% XP Rearguard](http://www.w3schools.com/browsers/browsers_os.asp) will continue to see a cert error when they request the page over SSL, same as now.

This is an operations issue - there's unfortunately no code I can provide, and I don't have the keys to your domain. However, I'm happy to walk through it with anyone who does have the keys. Let me know how I can help get the official leaflet CDN on https so that people just learning how the web works don't have to hit this wall on day 1.

**Comment by michaelkirk** [comment]
In fact... looks like you can now get a basic certificate for free through AWS Certificate Manager: https://aws.amazon.com/blogs/aws/new-aws-certificate-manager-deploy-ssltls-based-apps-on-aws/

💸 💸 💸 💸 💸 💸 💸

**Comment by tstibbs** [comment]
Note cloudflare host leaflet anyway:
https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.js
https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.7/leaflet.css

**Comment by IvanSanchez** [comment]
The Leaflet docs now point at `https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js`, so closing.
