### ISSUE TITLE
getBounds() returning longitudes greater than 180

### ISSUE THREAD

**Issue by bstubbs** [Leaflet/Leaflet#1885]
Longitudes range from -180 to 180. But sometimes, Leaflet returns longitudes like 474.2578215, which then of course nothing gets returned in my database. I say sometimes, because oddly enough, some days the code works just fine on all parts of the map. Should I not be using the google code hosted Leaflet?

Here is my basic code, on a drag event ending, I do this:

var bounds = map.getBounds();
console.log(bounds);
var min = bounds.getSouthWest();
var max = bounds.getNorthEast();

Here is my output from console (on bad results):
o.LatLngBounds {_southWest: o.LatLng, _northEast: o.LatLng, extend: function, pad: function, getCenter: function…}
_northEast: o.LatLng
lat: 21.542511366159946
lng: 474.7384643554688
__proto__: Object
_southWest: o.LatLng
lat: 20.00174140284379
lng: 472.2335815429687
__proto__: Object
**proto**: Object

This isn't an issue of grabbing bounds beyond the zoom, but bounds that don't exist. That latitudes are correct. I tested to see if it was a decimal point moved over by one, and that doesn't seem to be the issue either. Any ideas on how to fix this bug, or what is causing it?

**Comment by voltagex** [comment]
I have the same problem when getting coordinates from a MouseEvent. Should I have access to .wrap()?

e.g. 
```javascript
        map.on('mousemove',function (event) {
            control.getContainer().innerHTML = "lat: " + event.latlng.lat + ", long: " + event.latlng.lng;
        });

```

**Comment by danwild** [comment]
Ahh thanks for pointing that out @voltagex

**Comment by uxitten** [comment]
why closed this issue? i have this problem. what is solution?

**Comment by ghybs** [comment]
Hi @uxitten,

No, the PR you link to has nothing to do with this.

> why closed this issue?

As explained by mourner 5 years ago:

> It's intended behavior

Unfortunately there is not enough code provided by OP to reproduce the issue, in case there were actually a bug at that time.

Now you may be in a different situation, in which case I invite you to ask for help on how to use Leaflet on [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet), instead of commenting an old and closed thread.

If you are _really_ sure that there is a bug in Leaflet, please open a new issue and provide an [effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.
