### ISSUE TITLE
Markers Don't Repeat

### ISSUE THREAD

**Issue by deliriousrhino** [Leaflet/Leaflet#1945]
I need markers to repeat across as different world maps are shown as you pan.

I have created a jsfiddle at: 
http://jsfiddle.net/deliriousrhino/u387Q/3/ 

If you look at New Zealand you will see my issue. There should be markers on either side of the country.

I tried worldCopyJump = true, however it throws an error "Set map center and zoom first."

Also I am no sure worldCopyJump is the functionality I am after since I need all the markers around the -180 and 180 longitude to be shown together.

**Comment by fstricker** [comment]
3 years later: Is it nowadays possible to do what was out of scope (show two markers of the same node at lower zoom)?

**Comment by yhaiovyi** [comment]
+1

**Comment by landswellsong** [comment]
Subscribed here

**Comment by ooMICAHoo** [comment]
Another year later. Is it possible?

**Comment by perliedman** [comment]
@ooMICAHoo nope, no work has been done in this area, to my knowledge. IMO, this is a pretty niche use case and as mentioned above and in #1293, any suggested method to approach this has performance implications.

To resolve this, we would need someone who thinks this is a relevant feature to step up and actually do the work, it will not be resolved by itself. Having said that, if you want to take this on, please discuss the changes before actually making them, since it is likely we would turn down a pull request which affects performance significantly for normal use cases.

**Comment by ooMICAHoo** [comment]
Thank you for responding! I understand. It's not a big deal for my project so I am fine without the capabilities.

**Comment by landswellsong** [comment]
@perliedman I'd like to volounteer, but I'm pretty newbish to JS (not to coding per se though) so I wonder if you can give some guidelines for performance testing so that I can check whether my code would result in a significant overhead.

**Comment by chrisregner** [comment]
+1

**Comment by wttttt-wang** [comment]
Another year later 🤣

**Comment by perliedman** [comment]
Hi everyone,
while we as maintainers appreciate that you open issues and provide information on missing features in Leaflet, also understand that Leaflet is open source and maintained by volunteers: opening issue does not mean someone is going to fix it. Contrary to paid software, it's not someones job to go through all issues and fix them. Adding "+1" or similar comments also doesn't mean a solution to this problem suddenly comes up.

I'm not trying to be difficult or say that this particular issue should not be addressed, but the reality is that no maintainer has this on their priority list, so none of the quite limited time we have is going into fixing this issue at the moment (or for the last couple of years).

If _you_ think this is important, please consider spending some time figuring out how this could be fixed, or find someone who can do it for you. The fact that maintainers are volunteers at the moment does not mean it is prohibited to pay someone to solve issues.

My [comment from a year ago](https://github.com/Leaflet/Leaflet/issues/1945#issuecomment-309720698) still stands, though: this is not an important feature for a lot of Leaflet users, so it will have to be addressed in a way that doesn't make performance worse for the majority. Ideally, like a lot of specialized use cases, it could be solved by a plugin (which also makes the performance issue goes away, since no one is forced to using the plugin).

**Comment by pmochine** [comment]
It's 2019. Thanks to @IvanSanchez  there is a plugin. 

If you don't want to have any plugins this could help as well: 
https://stackoverflow.com/questions/33632608/markers-do-not-appear-on-continuous-world-in-leaflet
