### ISSUE TITLE
watchPosition support for locate method

### ISSUE THREAD

**Issue by Mathbl** [Leaflet/Leaflet#212]
Hi!

I'm looking for some kind of advice from leaflet experts. 

I'd like to watch the user position and show it on the map. I know it's easy to get the current position once by using the method locate. But i'd like to know if you think it would be possible to call a method each x seconds that would recall the locate and redraw the circle of the user location?

I know that circleMarkers are kind of sloppy on android and tend to overlay when using setLatLng to move them.

Thanks for the advices.

**Comment by Bezaleli** [comment]
Having the same issue
 map.on('locationfound', onLocationFound);
    map.on('locationerror', onLocationError);
is there built in function other than 'locationfound' that can watch position

**Comment by IMQ1987** [comment]
Have an issue with the map.locate function. When i include it in the deviceready function it doesnt work in offline mode. When i just type it in the js file it works fine, even in offline mode, but it shows at the beginning an ugly allowance request for geolocation like this one:
https://i.stack.imgur.com/PkxeA.png
Any idea why it is like that or what else i can do?
Thanks in advance and for any help.

**Comment by perliedman** [comment]
@IMQ1987 not entirely sure what you believe the problem is here... geolocation requires explicit permission from the user, so the user will have to approve; the exact format of the message is outside Leaflet's control.

Also, it sounds like this is a Cordova specific issue, and not specific to how Leaflet uses the geolocate functionality.
