### ISSUE TITLE
Getting Marker instead of Circle, when reusing geoJson I got from Layer.toGeoJson . 

### ISSUE THREAD

**Issue by Kash56** [Leaflet/Leaflet#2241]
I am trying to take GeoJson from drawn-shapes layer and reuse to remake the layer. All other shapes give back the original shapes drawn but circle gives marker form geoJson (because, geoJson converted from drawn circle layer, is 'marker' type geoJson itself ). I am using Leaflet.draw  v"0.2.3-dev" and Leaflet.js v0.6.4.  How to get GeoJson specific for circle only, that can let me draw the same circle again.

**Comment by l0oky** [comment]
I am having the same problem.. Tried the solution from issue #2888 but It only added point_type and radius in geojson properties. Looking something like this `{"type":"Feature","properties":{"point_type":"circle","radius":3062.5599801672683},"geometry":{"type":"Point","coordinates":[18.522262573242188,43.867950634753456]}}` and when I try to show this geojson on map like so : `L.geoJson(JSON.parse(data.geojson)).addTo(drawnItems);` It just draws me a marker.. How can I fix this? 

Thank you.

**Comment by perliedman** [comment]
@l0oky you need to add the option [`pointToLayer`](http://leafletjs.com/reference.html#geojson-pointtolayer) to your GeoJSON layer, and check if the point has a radius property - in that case, generate a `L.Circle`, otherwise a standard marker (or whatever you like).

Since the GeoJSON spec does not describe circle geometries, Leaflet's GeoJSON layer does not support the either.
