### ISSUE TITLE
Ditch Events mixin, make Evented base class instead

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#2280]
Currently we copy all Events functions into each Leaflet class. For some reason I initially thought standalone mixins are a great idea in Leaflet, but now I see that the `includes` property is only used to include `Events`, and most of the Leaflet classes are evented. 

So it seems to me that it makes more sense to ditch the `includes` concept and make the event methods inherited instead of mixed in. This will improve memory footprint because the methods will be reused from the prototype chain, and will look cleaner in the code:

``` js
// proposed (or we could call it EventEmmiter)
L.Layer = L.Evented.extend({...});

// old
L.Layer = L.Class.extend({
    includes: L.Mixin.Events, ...});
```

People will still be able to to use the methods manually without inheriting if there's a need:

``` js
L.Evented.prototype.on.call(this, 'myevent', handleEvent);
L.Evented.prototype.fire.call(this, 'myevent');
```

cc @tmcw @danzel

**Comment by luiscamachopt** [comment]
> Keeps backwards compatibility for now (includes: L.Mixin.Events syntax)

L.Mixin.Events now includes a `constructor` property meaning that if I use:
` myChildClass = myBaseClass.extend({includes: L.Mixin.Events});`
then `myChildClass.prototype.constructor` is (unexpectedly) `L.Evented`

**Comment by perliedman** [comment]
Hi @luiscamachopt,
use of `L.Mixin.Events` is actually deprecated in 1.0, although it hasn't been very clearly documented (it was just dropped out of the docs), see #5358 for some more information; next version will include a deprecation warning when you use it.

**Comment by luiscamachopt** [comment]
Hi @perliedman,
I have protected my code against this. 

Something being deprecated, you would expect it to still behave as it used to. And this is a pretty strange thing to debug and figure out.

I would suggest replacing:
`L.Mixin = {Events: L.Evented.prototype};`
with:
```
var eventsMixin = L.extend({}, L.Evented.prototype);
delete eventsMixin.constructor;
L.Mixin = {Events: eventsMixin};
```

Or define eventsMixin first with all the methods, and then `L.Evented = L.Class.extend(eventsMixin);`. This avoids the weird deletion of constructor.

BTW, I have classes that I don't want them to inherit from L.Evented but I want them to have the Events behaviour, so I think removing L.Mixin.Events is a bad call. Same arguments as @jfirebaugh. Don't see a reason why you can't have L.Evented for simplicity and L.Mixin.Events for flexibility.

**Comment by perliedman** [comment]
@luiscamachopt bad wording on my part: `L.Mixin.Events` wasn't officially deprecated, it's just _dropped_ from 1.0.0 (not documented), but since it was a significant change, and also happened to continue to mostly work, we decided to put a warning to hint that you should probably stop using `L.Mixin.Events`.

While I can sympathize with your opinion, the time for reverting this change has passed long ago: note that this was merged in 2013 (!).

I like your suggestion of removing the constructor for the mixin; there is the potential problem if we would actually put code into `Evented`'s constructor, but I don't think that is something we would need to do. A PR would be very welcome, or at least open a new issue to track this.
