### ISSUE TITLE
overlayremove also fired when manually removing layer

### ISSUE THREAD

**Issue by jack-kerouac** [Leaflet/Leaflet#2568]
The documentation says for the `overlayremove` event: 

> Fired when an overlay is deselected through the control.

But it is also fired if I programmatically remove a layer that is controlled through the layer control: `map.removeLayer(layerThatWasAddedToLayerCnotrol)`.

So either the documentation for this event should be update to reflect this behavior, or, preferably, the **`overlayremove` should only be fired when layers are removed from the map through the layer control**.

Same probably applies for `overlayadd`, though I did not check.

**Comment by sstenn** [comment]
I'm using Leaflet version 1.3.1

The problem seems not have been solved. 

When I remove the layer with `map.removeLayer()` it fires `overlayremove` and `layerremove`, when I remove the layer by clicking the layerControl it fires only `overlayremove`

**Comment by nathanjss** [comment]
The problem seems to come from using on(overlayremove) to trigger another overlayremove.  In the _onInputClick function control.layers looks at the checkboxes and pushes all of the layers into arrays based on the checkbox status.  Then it runs its own map.removeLayer for each layer that is unchecked which fires the overlayremove flag.  the problem is that the arrays are stored before the flags, but handled after the flags.  This works wonderfully for everything but triggering another overlayremove.  So an overlayremove actually happens, but because no checkmark was removed from the layer control, the layer is still in the addedLayers array, so it is immediately added back to the map. 

The solution I came up with was to add a Waitfor function in my code which waits for _handlingClick to be false. 

function waitUntil(check,onComplete,delay,timeout) {
    // if the check returns true, execute onComplete immediately
    if (check()) {
        onComplete();
        return;
    }
  
    if (!delay) delay=100;
  
    var timeoutPointer;
    var intervalPointer=setInterval(function () {
        if (!check()) return; // if check didn't return true, means we need another check in the next interval
  
        // if the check returned true, means we're done here. clear the interval and the timeout and execute onComplete
        clearInterval(intervalPointer);
        if (timeoutPointer) clearTimeout(timeoutPointer);
        onComplete();
    },delay);
    // if after timeout milliseconds function doesn't return true, abort
    if (timeout) timeoutPointer=setTimeout(function () {
        clearInterval(intervalPointer);
    },timeout);
  }

Then it runs my map.removeLayer events. 

map.on('overlayadd overlayremove', changeChildLayers);

 function changeChildLayers(e){
        let parent = e.name;
        let type = e.type;
        waitUntil(
            function(){
                if(layerControl._handlingClick == false){
                    return true;
                } else {
                    return false;
                }
            },
            function(){
        for(layer in layerControl._layers){
            if(layerControl._layers[layer] && layerControl._layers[layer].layer.category == parent){
                if(type == "overlayadd"){
                    map.addLayer(layerControl._layers[layer].layer);
                    layerControl._update();
                } else {
                    map.removeLayer(layerControl._layers[layer].layer);
                    layerControl._update();
                }
            }
        }
    }
    )
 }

 This works, but I don't know if there is some solution that could be handled within leaflet.
