### ISSUE TITLE
Mouse wheel scrolls too much in Firefox (custom delta)

### ISSUE THREAD

**Issue by moneytoo** [Leaflet/Leaflet#2732]
Scrolling using mouse wheel in Firefox isn't level by level but several zoom levels at once. It is caused by custom wheel delta which results in high values returned from ``getWheelDelta()`` (``e.detail`` was 18 in my case). It is because of:

1. Settings panel for my mouse (Logitech SetPoint) contains settings "Scrolling Size" which is set to "3 Lines by default" but I changed it to "6 lines".
2. To further increase scrolling I increased Firefox property ``mousewheel.default.delta_multiplier_y`` from 100 to 300.

I do not think this is something desirable. Both Google Maps and local maps (mapy.cz) work even with my settings. I have no idea why delta is even read but wouldn't moving from obsolete ``DOMMouseScroll`` to ``wheel`` solve this? https://developer.mozilla.org/en-US/docs/Web/Reference/Events/wheel

**Comment by mourner** [comment]
Can you check if https://github.com/Leaflet/Leaflet/pull/3653 fixes the issue?

**Comment by CramericaIndustries** [comment]
I can test it if you tell me how I do get that version. I've no idea how to check it out from Git and how to build it. And what tools I do need to for that.
If your fix is already applied in the master branch, then the bug is still there. (tested with this: http://leaflet-cdn.s3.amazonaws.com/build/leaflet-master.zip on FF 39.0)

**Comment by mourner** [comment]
Try with this JS: https://www.dropbox.com/s/r0ftoe11q8yow2w/leaflet.js?dl=0

**Comment by CramericaIndustries** [comment]
Thanks for the link. I tested it and it works fine now on FF 39.0. However the problem appears in Chrome now (tested with v43.0.2357.134 m).

**Comment by IvanSanchez** [comment]
Closing in favour of #3653.

**Comment by bluenote10** [comment]
I don't think #3653 has resolved the issue, reopen?

I'm using Firefox 68.0.2 and I have increased my `mousewheel.default.delta_multiplier_y`, because I prefer an overall faster scrolling speed:

![image](https://user-images.githubusercontent.com/3620703/64210021-6b326780-cea2-11e9-8490-72084f87054e.png)

This is how leaflet behaves on a single mousewheel up/down, it is basically unusable for me:

![Peek 2019-09-03 23-25](https://user-images.githubusercontent.com/3620703/64210139-c8c6b400-cea2-11e9-9e3f-85fb618451d5.gif)

All other map frameworks don't have this problem in Firefox.
