### ISSUE TITLE
Tiles not showing up for Custom CRS or L.CRS.Simple

### ISSUE THREAD

**Issue by Jakobud** [Leaflet/Leaflet#2776]
I have this custom projection and CRS setup.  This worked fine in Leaflet 0.6.4:

```
// Custom Projection
L.Projection.LatLon = {
    project: function (latlng) {
        return new L.Point(latlng.lat, latlng.lng);
    },
    unproject: function (point) {
        return new L.LatLng(point.x, point.y);
    }
};

// Custom CRS
L.CRS.Screen = L.extend({}, L.CRS, {
    projection: L.Projection.LatLon,
    transformation: new L.Transformation(1, 0, 1, 0),
    scale: function (zoom) {
        return Math.pow(2, zoom);
    }
});

// Map Creation
map = L.map('map',
{
    crs: L.CRS.Screen ,
    minZoom: -10,
    maxZoom: 7,
    attributionControl: false,
}).setView([0,0],0);

var tileUrl = "//cdn.mysite.com/tiles/zoom{z}/tile_{z}_{x}_{y}.jpg";
var tiles = L.tileLayer(tileUrl, { subdomains: '0123', noWrap: true }).addTo(map);
```

Now, upgrading to Leaflet 0.7.3, my tiles don't show up.  I have also tried `L.CRS.Simple` and my tiles don't show up for that either.  I don't get any JS errors or 404 errors.

If I don't specify a `crs` then my tiles do show up just fine using the default `CRS`.  What am I missing here?

**Comment by davidostermann** [comment]
I have the same problem

**Comment by perliedman** [comment]
@davidostermann if you believe this is a bug in Leaflet, please elaborate a bit, preferably with a jsfiddle or similar that reproduces the issue.

If it's more a question on how to work with Leaflet, please post on the Leaflet forum (https://groups.google.com/forum/#!forum/leaflet-js) or on [Stack Overflow](http://stackoverflow.com/) or [gis.stackexchange.com](http://gis.stackexchange.com).

**Comment by Jakobud** [comment]
It's been awhile since I looked at this and I'm not sure if the same issue exists in the master branch or not. I'll get back to you.

**Comment by davidostermann** [comment]
Sorry for the late answer. I'll come back to you in few days when my tile assets will be publicly accessibles.

**Comment by davidostermann** [comment]
@perliedman As promised, here a jsfiddle that show the problem :
http://jsfiddle.net/davido/r2ms3dnp/
If you turn off continuousWorld on line 27, the map failed. 

Otherwise thank you for the library. Here is our job http://magical-mystery-zee.zeeagency.com/

**Comment by perliedman** [comment]
Yeah, I remember this now when I look through your code. Basically, this issue is a duplicate of #2897 and #2231 - Leaflet 0.7 introduced `L.CRS.getSize`, which by default just calls and returns the same value as `L.CRS.scale`, which works great for the default CRS (spherical mercator) and not necessarily so great for other CRSs. I'm sorry to say that this flawed design was my creation.

In this particular issue, using `CRS.Simple` returns very small values for the CRS's size, and since Leaflet ignores loading tiles outside the CRS's bounds unless `continuousWorld` is enabled, you will simply get no tiles.

I'm happy to say that the CRS and projection handling has been quite heavily refactored in 1.0, it will be much easier to understand and work with.

**Comment by alexcroox** [comment]
Falling back to leaflet-0.6.4 allows you to use L.CRS.Simple again.
