### ISSUE TITLE
CSS3 scale the container breaks calculations for eg. zooming

### ISSUE THREAD

**Issue by pjuke** [Leaflet/Leaflet#2795]
I'm in a situation where I want to scale my map container with CSS3 (transform:scale(2,2)). Yes I know it blurs my images, anyway.

Doing so breaks the calculations for eg. zooming, especially  `setZoomAround()`. When panning around using the cursor, it pans twice as quick as well, which makes sence since I'm scaling it the double.

Can this be remedied in any 'simple' way? If not only temporarily since I'm in a big need of this feature for my current large project.

**Comment by wandergis** [comment]
@pjuke that's pretty good.

**Comment by kimmobrunfeldt** [comment]
Just wanted to let you know that I'm also experiencing this problem. What about handling this in a similar way to container resize? One could manually trigger a resize/similar event for leaflet map instance when the scale/zoom changes. When that would be called, leaflet could go up the DOM parent tree and find all scale/zooms and start taking those into account in getMousePosition. 

For the time being, I hacked my own fork of leaflet which provides a static method which you can use to set the scale value. That scale value is used in getMousePosition as explained by @pjuke above (thanks for the explanation btw)

**Comment by IvanSanchez** [comment]
I had a look at #5370, and according to https://stackoverflow.com/questions/5603615/get-the-scale-value-of-an-element , it *should* be simple to call `map._container.getBoundingClientRect()` in `L.Map.getSize()` - that will give the scaled pixel size and the rest of the functionality *should* just work in cascade.

I'm reopening because it seems that there might be a simple solution.

If somebody (@kimmobrunfeldt, @Hyno) could try this hack and report if it works (or how well it works), maybe send a PR, it would be very helpful.

Note that `getBoundingClientRect()` is [present from IE4](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect#Browser_compatibility), so there's no compatibility problems. Just make sure to account for IE8 where the result contains no `width` nor `height` properties.

**Comment by kimmobrunfeldt** [comment]
@IvanSanchez didn't get to test your specific commits, but this is now fixed in leaflet@1.3.4. Thanks for the efforts!
