### ISSUE TITLE
Instructions to upgrade plugin

### ISSUE THREAD

**Issue by zheffie** [Leaflet/Leaflet#2883]
Can you give some directions on upgrading plugins?
For example. I'm trying to use leaflet.heat (https://github.com/Leaflet/Leaflet.heat) but it returns errors combined with 0.8-dev

Uncaught TypeError: Cannot read property 'call' of undefined leaflet.js:5
o.Map.o.Evented.extend.whenReady leaflet.js:5
o.Map.include.addLayer

Any idea if this an be easily fixed?

In any case: thanks for a great piece of software!!!

**Comment by rsboarder** [comment]
Is it possible to get instructions before release? I've decided to use latest master version because it closes blocking bug. But after update Google Tiles can't initialise because of the the same issue

`
TypeError: Cannot read property 'call' of undefined
    at L.Map.L.Evented.extend.whenReady (vendors.js:2705)
    at L.Map.include.addLayer (vendors.js:2869)
`

I'm using this plugin for Google layers: [https://github.com/shramov/leaflet-plugins](https://github.com/shramov/leaflet-plugins)

**Comment by mourner** [comment]
@rsboarder yes, there will certainly be an upgrade guide for plugin authors before release.

For most Layer plugins, it's a matter of extending from `L.Layer` rather than `L.Class`.

**Comment by rsboarder** [comment]
@mourner when do you plan to release 0.8?

**Comment by mourner** [comment]
There's no release date. But we want to make a beta release really soon, see #2984

**Comment by rsboarder** [comment]
Ok, thx :)
