### ISSUE TITLE
when using setIcon to change a png icon to an svg one, the old png is still visible (except Firefox)

### ISSUE THREAD

**Issue by sbocconi** [Leaflet/Leaflet#2913]
When I use setIcon on a marker to substitute an icon, it works if it is from png to png, or svg to svg, but not from png to svg. Firefox works, Chrome, Safari don't. The old png icon is still visible on top of the svg one.

**Comment by moravcik** [comment]
The problem is still present. Here is the sample: https://embed.plnkr.co/lY4yqS/

Click on marker will cause switching its icon.

The Northern marker is toggling SVG icons only
The Southern marker is toggling PNG <-> SVG icons

SVG -> SVG switching is basically ok (some flickering is visible in Chrome)

PNG -> SVG switching is buggy:

- Chrome: new icon size is set, but still old icon is displayed until some action is done, e.g. drag the map
- Safari: after switching to SVG icon both icons are displayed (worst case)
- Firefox: flickering is visible, but more-less ok
