### ISSUE TITLE
Events inside popup don't propagate outside the map

### ISSUE THREAD

**Issue by jones139** [Leaflet/Leaflet#301]
I am trying to create a popup on a marker, which contains buttons, but I am having trouble with events not firing from the buttons on the marker popup.

I create the popup with 
  function addMarker(e) {
     var marker = new L.Marker(e.data.latlng,{clickable:true, draggable:true});
     map.addLayer(marker);
     var content = "Marker " +
                   "<button id='deleteMarker'>Delete Marker</button>" +
                   "<button class='cancel'>Cancel</button>";
     marker.bindPopup(content);
     marker.on('dragend',onMarkerDragEnd);
     map.closePopup(popup);
  }

And try to catch the event from the button with:
  jQuery('#deleteMarker').live('click',function(e) { alert('delete'); });

Similar code that just adds a popup to the map works, but the above does not when the popup is bound to a marker.

I have tried modifying Popup.js to remove the disableClickPropagation command (line 81 - https://github.com/jones139/Leaflet/commit/117db3515c6b8070e0d2c42ff4bc1030fe5feef4), and this gets my events working, but the clicks also propagate down to the map.   Therefore I think it is an issue in Leaflet somewhere?.....Or I may be doing it wrong!

**Comment by lentyaishe** [comment]
Hi,

It seems that this bug now occurs only in a specific setup...

I'm developing a hybrid app that is ported to android and ios. I'm running leaflet v.1.0.3. This version fixed this behavior for web and android setups but in ios events on elements within popup do not fire.

This is my original code that does work for android and web:

`var container = $("<div class='leaflet-marker-actions-wrapper' />");`
`var icon = $("<button class='button icon icon-back'></button>");`
`container.on("click", ".icon-back", function (e: JQueryEventObject) {
	console.log("action fired");
});`
`container.append(icon);`
`var popup: L.Popup = L.popup(popupOptions).setContent(container[0]);`
`marker.bindPopup(popup).openPopup();`

I've tried multiple approaches also:

1. `icon.on("click",  function (e: JQueryEventObject) {
	console.log("action fired");
});`

2. `icon.click(function (e: JQueryEventObject) {
	console.log("action fired");
});`

3. `L.DomEvent.addListener(container.get(0), "click", function () { console.log("action fired"); });`

None of those log anything in the console. Yet, the click on marker works perfectly.

Unfortunately I can't supply an example of this behavior since it should be actually tested on an iOS device.

BTW the same behavior is experienced on iOS 9.1 and 10.2.1.

Can anything be done with it?

Thanks in advance

**Comment by lentyaishe** [comment]
Well, found the solution.
It's not the leaflet, it's the iOS. Just replace the `click` by `mousedown` or `mouseup` events and it will work.
