### ISSUE TITLE
Tiles don't always fade-in with the new tile loading logic

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3053]
After merging the new tile loading logic #2382, background panes that become the main panes don't fade in, so there's an impression of tiles not always fading in.

**Comment by jfirebaugh** [comment]
The issue is that with [throttled pruning](https://github.com/Leaflet/Leaflet/blob/2ee1aa2c2365e0cf4404817b4d268d5ed788a653/src/layer/tile/GridLayer.js#L32) and [deferred removal](https://github.com/Leaflet/Leaflet/blob/2ee1aa2c2365e0cf4404817b4d268d5ed788a653/src/layer/tile/GridLayer.js#L234), tiles can remain in the DOM and get reused during quick zoom-in-zoom-out operations. When that happens, the [CSS transition](https://github.com/Leaflet/Leaflet/blob/2ee1aa2c2365e0cf4404817b4d268d5ed788a653/dist/leaflet.css#L142-L153) for loaded tiles is not trigged.

Even if pruning wasn't throttled, we don't want to remove the `leaflet-tile-loaded` class from background tiles immediately, because they need to be cross-faded with loading tiles from the current layer. The other thing that I tried was to remove and re-add the `leaflet-tile-loaded` class from existing tiles in the current layer at the end of `_updateLevels`, but it doesn't look like this triggers CSS transitions. You probably have to remove the class in one frame and then re-add it in another for the transition to animate, and that would add even more asynchronous complexity to tile loading, which I'd like to avoid.

My preference would be to switch to JS-based transitions, which would also allow us to fix [the _deferRemove hack](https://github.com/Leaflet/Leaflet/blob/2ee1aa2c2365e0cf4404817b4d268d5ed788a653/src/layer/tile/GridLayer.js#L234). But I know that you are resistant to that. So what do you suggest?

**Comment by mourner** [comment]
Several years ago, I always assumed native transitions would be faster than animating manually frame by frame. For some cases, that is a valid assumption, but for others, it has proved me wrong. For example, I recently ditched transition-based panning animation. 

So if we try it out and measure, it may turn out that it works pretty good, especially considering that we can calculate each tile in the view in one running context, without having to keep lots of independent timers for each tile and try to handle hard to track race conditions. Lets make a simple naive implementation, just to evaluate performance, and if it works, implement it properly.

**Comment by mourner** [comment]
The PR above fixed a lot of issues with tile loading behavior and flickering and made it awesome, but now that I clearly see a big difference between transitions & reqAnimFrame performance (on a full screen map), we should see if it's possible to bring transitions back while keeping the current behavior:

> You probably have to remove the class in one frame and then re-add it in another for the transition to animate, and that would add even more asynchronous complexity to tile loading, which I'd like to avoid.

We can't afford degrading performance significantly with a 1.0 release, so if there's no way to get around this without adding complexity, we'll have to add it.

**Comment by mourner** [comment]
Done here after `will-change` changes
