### ISSUE TITLE
Error 404 in loading tiles

### ISSUE THREAD

**Issue by Vikash-Mehta** [Leaflet/Leaflet#3066]
![screenshot from 2014-11-28 23 36 49](https://cloud.githubusercontent.com/assets/6582757/5231091/4dc475dc-7757-11e4-959b-f7cc79564a68.png)
Is there a way to block console error, when some of the images are not found. for example [GET http://dev.gro-intelligence.com/mtiles/v2/gro-basemap-waterbody/2/2/1.png 404 (Not Found) ].

**Comment by hjrobinson** [comment]
This doesn't work when using a transparent background in tilemill.  This is particularly problematic with line features. There may be a workaround per the comment from jmuchaxo in https://github.com/Leaflet/Leaflet/issues/1021 but it seems like a pain. If there were a way to disable leaflet from sending requests for missing tiles or auto assigning some kind of value for the missing tile information it would be helpful.

**Comment by hjrobinson** [comment]
In QGIS 2.18.24 you can install the QTiles plugin.  Select your target layer as the layer extent. Set the transparency to zero then make sure your bounds are more narrow than than the extent of your layer. 

I got the bounds by opening my shapefile in TileMill using the export option (mbtiles, png, etc.) then setting tight boundaries around the layer.  Then I copied and pasted the bounds numbers into the tilelayer options (bounds) for leaflet. 

Example: var bounds = [[47.00,-122.00],[47.00,-122.00]]; 

Make sure to swap the values longitude and latitude because leaflet lists latitude first. Then those terrible 404 errors should be gone.
