### ISSUE TITLE
getBoundsZoom fails after shrinking the map

### ISSUE THREAD

**Issue by goiadantudor** [Leaflet/Leaflet#3131]
The **getBoundsZoom** method fails after resizing the map from big to small, but works great after resizing the map from small to big.

For the exact usecase, see this: http://jsfiddle.net/pnvghf0e/4/
#### This usecase works:
- set map's height as 100px
- call _getBoundsZoom_
- the result is 0
- set map's height as 600px
- call _getBoundsZoom_
- the result is 2
#### But this one doesn't:
- set map's height as 600px
- call _getBoundsZoom_
- the result is 2
- set map's height as 100px
- call _getBoundsZoom_
- the result is **STILL** 2

Feel free to toggle this block, to see the two cases:

``` javascript
// data preparation and switching
var FIRST_SIZE = 600;
var SECOND_SIZE = 100;
//var FIRST_SIZE = 100;
//var SECOND_SIZE = 600;
```

**Comment by Falke-Design** [comment]
Wrong user handling:
```
map.options.minZoom = map.getBoundsZoom(
    L.latLngBounds(
        L.latLng(-180, -1800),// south-west
        L.latLng(180, 1800)// north-east
    ),
    true
);
```

he overwrites the `minZoom` to `2`and then he calculates the new zoom of the bounds (after changeing the height to 100) and expects `0` but because of `minZoom = 2` a lower zoom like `0` is not allowed.

Without setting the zoom value to `minZoom` the zoom is calculated correct.
