### ISSUE TITLE
flyTo generates many moveend events

### ISSUE THREAD

**Issue by jfirebaugh** [Leaflet/Leaflet#3134]
Reported [here](https://github.com/mlevans/leaflet-hash/issues/38#issuecomment-69810963) and replicated with `debug/map/zoompan.html` (uncommenting the logging there for move events).

Expected behavior would be to emit a single moveend event when the animation completes or is canceled.

**Comment by mourner** [comment]
Yep, going to fix this.

**Comment by Jakobud** [comment]
Need any help with this mourner? It appears to me that the `zoompan.html` debug example generates many `move`,`zoomend` and `moveend` events. All of the events are firing in `L.Map._resetview()`. What was your plan for fixing this? Passing an optional variable to the method that forces events to not be generated or something like that?

**Comment by Jakobud** [comment]
Also, I noticed that `map._panAnim` is not registered during a flyTo. Is this because it isn't considered a panning animation? I also see that map._panAnim has an `._inProgress` property. Maybe FlyTo needs a similar thing. What if we added a `map.flyTo._inProgress` or something like that, so you could determine if a flyto was currently happening and if it is in progress then the events dont get fired on the _resetView method?

**Comment by mourner** [comment]
This would be a hack — for a proper solution, generally I'd like to rethink the map movement events globally, see #3216.

**Comment by mourner** [comment]
Fixed by #3278
