### ISSUE TITLE
Map projection in iOS App modus get scrambled

### ISSUE THREAD

**Issue by Bart-Holland** [Leaflet/Leaflet#3155]
Hi I don't know if this is the place to be, but thought at least you needed to hear about this.

I am creating an app with a leaflet map. 
Everything works great and it is realle a bless to work with leaflet. 

I tested the app on a website and for every browser all seems to work fine.
Even on mobile browsers it looks great. 

So I run the code through cordova (using Telerik) to create an IOS app.
After installing it on the iPad, and opening the map I see all tiles scrambled on the screen. I seems that the tiles (WMS or WMTS) do not get placed on the correct spot. So it gives a scrambled effect. 

I tried several things, but all settings I change make that all other browsers also fall.
I looked into iPhone as well, however the tiles are so big that only a few fit on the screen. 
The chance that this issue will occur here is rather small because of that.

So if anybody seen this before it would be a great help to know why this happens, only in apps

**Comment by perliedman** [comment]
@Bart-Holland Hi, hard to tell without at least a screenshot, but my guess is that the CSS does not load properly. That will give the impression that the tiles are scrambled, since they're not properly positioned in the grid.

It does not sounds like a Leaflet issue, given that it works as expected in browsers, so I'm going to close this for now, but feel free to add more information if you think it's a bug, rather than something related to your Cordova environment, and we can re-open the issue.

**Comment by Bart-Holland** [comment]
@perliedman Just added more info.

**Comment by perliedman** [comment]
@Bart-Holland so the WMS/WMTS uses the EPSG:28992 projection? Which version of Leaflet are you using, and what lib/code are you using for handling the projection?

As long as it works well in the browser (or, as in your case, multiple browsers), it's quite likely that it's the Cordova environment rather than Leaflet that is the issue.

I'm not familiar with Cordova myself, but I would try to strip down the environment to create the minimal  version that still causes the problem. For example, check what happens when you remove the stylesheets not related to Leaflet.

Also, some screenshots illustrating the problem could help.

**Comment by Bart-Holland** [comment]
Hey @perliedman I am using version 0.7.3 for adding this map I am using this code which includes proj4 and proj4leaflet:

    proj4 = '+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 ' +
                   '+ellps=bessel +units=m ' +
                   '+towgs84=565.2369,50.0087,465.658,-0.406857330322398,0.350732676542563,-1.8703473836068,4.0812 +no_defs';

    RD = L.CRS.proj4js('EPSG:28992', proj4, new L.Transformation(
            1, 285401.920, -1, 903401.920
        ));

    new L.Map("map", {
            continuousWorld: true,
            crs: RD,
            center: new L.LatLng(52.23, 5.3),
            zoom: 2,
            scrollWheelZoom: true,
            loadingControl: true,
            minZoom: that.prevZoom,
            maxZoom: 13
        });

    new L.TileLayer('http://geodata.nationaalgeoregister.nl/tms/1.0.0/brtachtergrondkaart/{z}/{x}/{y}.png, {
            tms: true,
            continuousWorld: true,
            attribution: "blah blah"
        });

I will strip down or create a small project to test iOS in wider screen sizes.

I also made some screenshots from the iPad:

![img_0010](https://cloud.githubusercontent.com/assets/2439873/5854441/1056ad9e-a22e-11e4-9431-cefadb255cd0.PNG)
![img_0011](https://cloud.githubusercontent.com/assets/2439873/5854442/105b4ff2-a22e-11e4-835f-d0936172a4a8.PNG)
![img_0012](https://cloud.githubusercontent.com/assets/2439873/5854443/105c4a6a-a22e-11e4-9f0c-29de92a0b292.PNG)
