### ISSUE TITLE
map.getZoom() has old value during GridLayer.createTile() when changing zoom levels

### ISSUE THREAD

**Issue by bb-generation** [Leaflet/Leaflet#3222]
During the execution of GridLayer.createTile(), the zoom level is correct in coords.z, but is still wrong in map.getZoom().
Although this may seem like a minor inconvenience, this can have unintended side effects when using functions like map.project().

# How to reproduce

Open debug/map/grid.html and insert a ```console.log(this._map.getZoom());``` statement right at the beginning of createTile (or use this Gist here: https://gist.github.com/bb-generation/51c2f55a7b184c0e8d8d)
Then open the file and start zooming. You will see that it will output the old zoom level in the console, while the tiles will show the correct ones (because the actual drawing uses coords.z).

# git-bisect

A short git-bisect revealed the first commit with this bug is bbf32ebfcdb0d24d187dbb54eecbea367fd7b72d

# Tested Browsers

* Chrome 40.0.2214.111 m (64-bit)
* Firefox 35.0.1

**Comment by jfirebaugh** [comment]
This is by design. During zoom animation, new tiles are being loaded for the target zoom level. Because the animation is done with CSS transitions, the current zoom level is still returned by `map.getZoom()`. And in general code should not assume that tiles will be loaded only for the zoom level currently returned by `map.getZoom()` -- overzooming and retina tiles also contradict that assumption.

**Comment by linghuam** [comment]
Hi, recently, I also meet this problem, and it took a few days to find the problem. Now, I want to use the map method 'latLngToLayerPoint' in 'createTile' method, but the zoom level is old, how can I use the newest zoom level in 'latLngToLayerPoint' method? @bb-generation @jfirebaugh
