### ISSUE TITLE
Move website to docs subfolder, remove docs and dev branches divergence

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#3277]
Currently docs are in the `gh-pages` branch, which diverged from `master` in the very beginning and gets all the docs-related commits, and merges `stable` on every release, with `gh-pages-master` getting master-related docs changes correspondingly. This is very inconvenient.

Instead we should keep docs in the same branch the development is going on, in the docs subfolder. This will make managing docs updates (in sync with branches) much easier, e.g. allowing people submitting feature PRs include docs in the same PR instead of submitting a separate PR to `gh-pages-master` that will get later merged into `gh-pages`.

To make it right and keep all the history, I'd probably have to do an EPIC rebase of `gh-pages` on top of `stable`, and then branch out and rebase on `master`, moving over `gh-pages-master` commits to it too. I guess it's quite a lot of hassle, but probably worth it.

cc @jfirebaugh cc @patrickarlt

**Comment by jfirebaugh** [comment]
The [pattern we're settling on for mapbox-gl-js and Mapbox.js](https://github.com/mapbox/mapbox.js/issues/939) is to do mainline work in `master` with docs in a `docs` subdirectory. A separate `gh-pages` branch sticks around, but it's used solely for decoupling mainline work for what gets immediately published.

> To make it right and keep all the history, I'd probably have to do an EPIC rebase

Why is a rebase necessary? My approach would be:

1. Create a temporary branch off `gh-pages` named `stable-docs-merge`.
2. In that branch, move documentation into a `docs` subfolder.
3. Merge `stable` into `stable-docs-merge`
4. Follow up with cleanup commits.
5. When satisfied, merge `stable-docs-merge` back into `stable` (should be a fast forward).
6. Merge `gh-pages` into `stable` (should be a fast forward).
7. Repeat 1-5 for `gh-pages-master` ⇢ `master`. (Don't do 6 because you don't want master branch docs live yet.)

This is the process I used for mapbox.js:

https://github.com/mapbox/mapbox.js/commit/3ad6eec27046c224cc7c148a32d88f2f7d884ec9 (2)
https://github.com/mapbox/mapbox.js/commit/aac44d6340dfe1aece016866fc011a9b35167d72 (3)
https://github.com/mapbox/mapbox.js/commit/a1a95b66a1c8b6855b76aca5ddcfe8c8b79cb94c (4)

**Comment by mourner** [comment]
@jfirebaugh Thanks for the instroctions! Rebase would be to avoid commits like https://github.com/mapbox/mapbox.js/commit/aac44d6340dfe1aece016866fc011a9b35167d72 with 80111 additions :) but I guess that's OK for docs, as git blame/etc. is not that important. BTW, in step 6, did you mean "merge stable into gh-pages` instead?

**Comment by jfirebaugh** [comment]
I think the "80111 additions" is just be an artifact of how GitHub displays merges. Blame is able to follow the history of all those files.

> in step 6, did you mean "merge stable into gh-pages` instead?

No. The history will look like:

```
     * Cleanup (4) <-- stable-docs-merge
     |
     * Merge stable into stable-docs-merge (3)
    /|
   / |
  /  |
 /   * Move docs to subfolder (2)
|   /
|  * <-- gh-pages
|  |
|  ⋮
|
* <-- stable
|
⋮
```

And then you fast-forward stable (5) and gh-pages (6):

```
     * Cleanup (4) <-- stable, gh-pages
     |
     * Merge stable into stable-docs-merge (3)
    /|
   / |
  /  |
 /   * Move docs to subfolder (2)
|   /
|  *
|  |
|  ⋮
|
*
|
⋮
```

After which development continues on stable, and gh-pages is updated only when there's a release or hotfixes to docs.

**Comment by jfirebaugh** [comment]
> in step 6, did you mean "merge stable into gh-pages` instead?

Wait, no, you're right. The terminology is confusing when it's a fast forward, but yes, gh-pages is the ref that gets updated in step 6.

**Comment by mourner** [comment]
@jfirebaugh oh crap, turns out GitHub Pages doesn't allow changing `source` property in the Jekyll config — it always builds the top level directory. So this task is just not possible :(

**Comment by jfirebaugh** [comment]
WTF... that sucks. :disappointed:

**Comment by mourner** [comment]
Here's a note for reference: https://help.github.com/articles/using-jekyll-with-pages/#configuring-jekyll

> Keep in mind that if you change the `source` setting, your pages may not build correctly. GitHub Pages only considers source files in the top-level directory of a repository.

**Comment by mourner** [comment]
Sucks to close this, will reopen when GitHub removes the limitation.

**Comment by jfirebaugh** [comment]
Saw this today: ["Deploying a subfolder to GitHub Pages"](https://gist.github.com/cobyism/4730490).

https://twitter.com/zeke/status/661638961979219968

**Comment by IvanSanchez** [comment]
@jfirebaugh I just tried that, and apparently subtrees are just local; I cannot commit/push them (maybe I'm doing something wrong?). As far as I can tell `git subtree push --prefix dist origin gh-pages` pushes a (sub)directory to the `gh-pages` branch, but does *not* keep it in sync.

It *might* be possible to add a git *submodule* (instead of a git subtree) pointing to a different branch of the same repo.

**Comment by jfirebaugh** [comment]
I just set up https://github.com/jfirebaugh/animations to work this way, in preparation for replacing jekyll with a node-based static site generator. Works great! @IvanSanchez, not sure what issue you ran into but for me it definitely does keep `gh-pages` in sync with a subdirectory on `master`. I did have to use [this tip](https://gist.github.com/cobyism/4730490#gistcomment-1374989) to force-push to `gh-pages` to get things started.
