### ISSUE TITLE
IE loses focus after panning twice

### ISSUE THREAD

**Issue by lee101** [Leaflet/Leaflet#3314]
Works fine in Firefox Safari and Chrome.

If you click and drag to pan, the map gets focus, if you do it again the map loses focus in IE.

**Comment by IvanSanchez** [comment]
I just noticed a few things:
* The bug is also reproducible using Leaflet 0.7.3.
* If there is at least a L.Path (line, polygon), the SVG root element will grab focus (instead of the `leaflet-tile-container`). This means that #3411 would not suffice to fix the bug.
* There is no need to drag, clicking also steals focus.
* Behaviour of the `focusin` event is weird - I should get the previously focused element with `ev.srcElement`, but I don't.

For my own sanity's sake, I won't even try to see what happens with VML layers.

**Comment by IvanSanchez** [comment]
It seems that this might just be an upstream bug from MSIE:

https://connect.microsoft.com/IE/feedback/details/1028411/ie-11-span-and-div-elements-without-the-tabindex-attribute-should-not-be-focusable

**Comment by mourner** [comment]
Does adding `tabindex="-1"` help?

**Comment by IvanSanchez** [comment]
No, that will make an element explicitly focusable. As MDN says in https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex : 

> a negative value means that the element should be focusable

There is no way (that I know of) of making an element explicitly non-focusable.

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
