### ISSUE TITLE
Handle 'focus' and 'blur' in L.Evented

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3430]
If we want to attach a handler to the `focus` event (or the `blur` event) to a marker, the way to do it right now is `L.DomEvent.on(marker._icon, 'focus', doSomething)`. Even though it's pretty much syntactic sugar, it'd be nice to be able to write `marker.on('focus', doSomething)` instead. (see #3429)

I've seen that `L.Marker` delegates all events to its icon via `L.Layer.addInteractiveTarget`, but right now I cannot understand all the interlocking parts of the code that make events work. It seems that the `L.Map` captures all (possible) events within and then delegates the handler, but the `focus` event doesn't bubble so it's not captured by the code in `L.Map._findEventTarget` and so on.

Should `L.Evented._on` handle `focus` and `blur` (and/or other non-bubbling events) differently to attach these directly to their target instead of adding it to the targets list? I'm unaware of the performance implications.

Also: 
[ ] add `focus` and `blur` as possible events triggered from a `L.Map`, at `L.Map._initEvents`. 
[ ] skip the `data.latlng` calculations in `L.Map._fireDOMEvent`.

**Comment by mourner** [comment]
This is tricky. I implemented delegated events so that we don't actually attach DOM listeners to every marker, which slows things down considerably when dealing with lots of markers. If we have that in place already, I wouldn't want to add attaching listeners directly again. On the other hand making a special treatment in L.Evented to add listeners lazily adds complexity to an already comlex system, adding headache and potential source of bugs. So I'd punt on this for now.

**Comment by IvanSanchez** [comment]
I wonder if using `useCapture` set to true on `addEventListener` will solve this **and** not cause a performance hit. I might give it a shot.

**Comment by mourner** [comment]
See https://github.com/Leaflet/Leaflet/pull/3444#issuecomment-109070911, will reopen in case there will be a strong need for this.

**Comment by Taekjoon** [comment]
ㅗㅕㅍ
숏다리?ㄷ
