### ISSUE TITLE
Any idea how do I get the boundary coordinates of a region from Google maps ?

### ISSUE THREAD

**Issue by bismoy2013** [Leaflet/Leaflet#3468]
Google Map has started highlighting search areas in Pink color. How do I get all the boundary coordinates of that place? Google doesn't provide any apis for that, Hope this question is clear enough :)

Reference : http://stackoverflow.com/questions/12194046/google-maps-api-v3-how-to-get-region-border-coordinates-polyline-data

**Comment by IvanSanchez** [comment]
This is the issue tracker for **Leaflet**, not a help forum for Google Maps.

You might want to have a look at OpenStreetMap's data and APIs, though. https://www.openstreetmap.org/relation/2978650  http://wiki.openstreetmap.org/wiki/Overpass_turbo

**Comment by bismoy2013** [comment]
I understand & sorry for that, but needed help on this thing in particular since you guys deal with maps . DO you think the link provided by you should help ?

**Comment by IvanSanchez** [comment]
Leaflet deals with map display and interactions. Your problem is about querying data. You'll need to do your own research on where you want to fetch data from (Google? OSM? Natural Earth?), and how (server query? cached data? UTF grids?).

Please keep in mind that the issue tracker of project A is **not** the right place to ask questions about project B, even when project A and B are in the same field. HI encourage you to read http://catb.org/~esr/faqs/smart-questions.html

**Comment by bismoy2013** [comment]
Sure, thanks for the info and apologies for all these :)
