### ISSUE TITLE
delete a map

### ISSUE THREAD

**Issue by Mathbl** [Leaflet/Leaflet#352]
HI!

I have some problem reinitializing a map. It's similar to this problem : https://github.com/CloudMade/Leaflet/issues/258

Now with the new release, I get an error telling the map is already initialized. I'm trying to delete the map and all it's event before initializing a new one, but it seems that it's not working.

Any idea how I can do this?

Thanks

**Comment by jbcoder** [comment]
@mourner Has there been any further development in reusing or reinitializing a map or is this still the best solution?

I'm in a situation where I am trying to use one div to be able to edit a map and then view it without editing tools. I need to store the data in the html so that it can be used elsewhere. However, I don't really want to have to make two maps for the same div (one for editing and one for viewing). So, I'd like to just reinitialize it without controls and without destroying the node. However, if that's what needs to be done, then so be it.

**Comment by vko-online** [comment]
@mourner More generic solution would be great
Still not able to resolve this, my current dirty workaround is 
```js
elem.html('<div id="map" data-tap-disabled="true"></div><div ng-transclude></div>');
var map = L.map('map', {
       attributionControl: defaults.attributionControl
});
```
and remove map with
```js
$rootScope.$on('$stateChangeStart', function(){
      elem.html('<div id="map" data-tap-disabled="true"></div><div ng-transclude></div>');
      elem.remove();
);
```

**Comment by Rikaelus** [comment]
I'd appreciate this functionality, too.
I'm creating a high level API for end users to build pages a piece at a time, and some pieces can have maps placed within them. While the user can technically delete a piece and start fresh for a new map, it'd be nice not to require them to.

**Comment by IvanSanchez** [comment]
@Rikaelus http://leafletjs.com/reference-1.0.2.html#map-remove
