### ISSUE TITLE
Non-square tiles and overscaling probably broken

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#3600]
cf511130 introduced a change in the behaviour of `L.GridLayer._getTileSize`, but we forgot to modify `L.TileLayer._getTileSize`. As a result, overscaling non-square tiles is probably broken.

**Comment by IvanSanchez** [comment]
@fabiosantoscode We don't have a readily available source of non-square tiles. Could you please check if overscaling is in fact broken?

**Comment by yohanboniface** [comment]
(Use http://leafletjs.com/reference.html#tilelayer-maxnativezoom for overscaling)

**Comment by fabiosantoscode** [comment]
When I get home I'll try it out and tell you how it went

**Comment by fabiosantoscode** [comment]
Oh my.

I can't do this at all.

Nothing works, but I can't tell if it's because of my changes being one year out of sync with master, my TileLayer derived class which overrides getTileUrl to generate dynamic URLs, my custom CRS which does not work well with the current version of Leaflet and I had to swap it out, or the bug you're reporting.

There is no longer a single image on my screen, I get an endless tile screen of them. When I zoom in (a single level), they just become half the size, and some disappear. Then I zoom out and they become 4 times bigger.

Last time I looked at this code, I had bugs like this one all the time, but it may very well be the bug that this issue refers to. Unfortunately, I can't wrap my head around this code any more (I couldn't when I wrote it, even).

**Comment by IvanSanchez** [comment]
@fabiosantoscode Don't worry, we'll find a way to try and replicate the bug. Obrigado mesmo :-)

**Comment by ktoto** [comment]
@IvanSanchez it seems you rename `getTileSize` in `GridLayer` from `_getTileSize` and forget rename in `TileLayer`.
And now `_getTileSize` in `TileLayer` not called.

**Comment by IvanSanchez** [comment]
@ktoto I know. That's why I created #3601. Now we need somebody to confirm that #3601 fixes the problem introduced by that renaming.

**Comment by ktoto** [comment]
@mourner @IvanSanchez #3601 not work for me.
Forget change here https://github.com/Leaflet/Leaflet/blob/master/src/layer/tile/TileLayer.js#L112
to `tileSize.divideBy(map.getZoomScale(zoomN, zoom)) :`

**Comment by mourner** [comment]
Thanks! Fixed.

**Comment by ktoto** [comment]
thanks! :+1:

**Comment by IvanSanchez** [comment]
@ktoto Good catch! :-)
