### ISSUE TITLE
Firefox bug when using setView with animate and zoom > 19

### ISSUE THREAD

**Issue by yohanboniface** [Leaflet/Leaflet#3608]
JSFiddle to reproduce it (only Firefox): http://jsfiddle.net/heu9hsrL/4/
Removing `animate: true` makes it work.
Changing zoom in `setView` from 19 to 18 makes it work.
Works on Chrome.
According to the network panel, tiles are loaded, and inspecting the img elements I can't see any obvious reason they are not shown. Seems they are out of map view.
Removing the `transform3d` CSS property from both the img element and the `leaflet-map-pane` element make the img appear in view.
I've not seen any difference with Chrome values, while comparing the situation with FF.
I had a quick look at the code some days ago, but I didn't find anything yet. I may have another look in the incoming days, but please anyone feel free to check it anyway :)

**Comment by cmulders** [comment]
(Sorry for the large screenshots)

I've found some more weirdness with the this specific test case  in Safari 8.0.7. The zoom buttons are visually hidden behind the tiles, while the element is on top of the tile. I can inspect the buttons with the web inspector and does not snap to the tiles, as it would when the tile is on top. This is only the case when the map just had zoomed in from zoom layer 15 to 16 and below, then the buttons disappear, zooming out does not cause any trouble. However, this is fixed when the control layer also has a transform of `-webkit-transform: translate3d(0px, 0px, 1px);`So rising the layer up by one pixel. 
![zoom-hidden-safari](https://cloud.githubusercontent.com/assets/8112493/8658872/d56bdaaa-29a6-11e5-851b-739f198aabcd.png)
![zoom-shown-safari](https://cloud.githubusercontent.com/assets/8112493/8658873/d58691a6-29a6-11e5-98b9-5f56a3788b2c.png)

Furthermore, I indeed experience the same bug in Firefox and is possibly due to the extreme transformations. When I artificially modify the transforms in web inspector, I get the tile visible. (Check the transform values, -1.3e7 vs 1.3e5). I think it is a bug in firefox, when it modifies its transform values to scientific notation, but why, I do not know.. Safari and Chrome did not change the transform values to scientific notation.

![transform-extreme-values](https://cloud.githubusercontent.com/assets/8112493/8658974/a6540f70-29a7-11e5-820d-d756d988a65c.png)
![transform-lowered-values](https://cloud.githubusercontent.com/assets/8112493/8658975/a6752ee4-29a7-11e5-904e-3cd0a64fef74.png)

**Comment by cmulders** [comment]
Although.. Should have been fixed in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=964529

**Comment by cmulders** [comment]
Definitely a Firefox bug in the transform function: http://jsfiddle.net/dg6r5hhb/
Doesn't happen Safari, but Chrome also breaks (red square goes to left suddenly), positioning the element wrong, but still renders it.

**Comment by cmulders** [comment]
I am not sure how, but it seems that 'bootstrapping the coordinate system' with `setView(L.latLng(0, 0), 1)` fixes the large coordinates. This is a kind of dirty hack, because the proxy layer still has the abnormally large transform values. Somewhere in the initial load, `setView` or `_resetView`, the coordinate system needs to be reset to 'normal' values.

Currently I know that the first setView function call (with high zoom values) causes the high values for the transform. If the initial setView is with low zoom levels, subsequent setViews do not cause large transform values. Very strange..

This also fixes the bug I mentioned above, that the UI disappears in Safari with these high (initial) zoom levels.

http://jsfiddle.net/heu9hsrL/8/

**Comment by mourner** [comment]
Hmm, I wonder if we could adapt something like the fix in #3491 (adjusting the thresholds)...

**Comment by cmulders** [comment]
That idea indeed works just fine. As you can see, it checks whether the current position of the mapPane is still in the 'transform' bounds and redraws the map (resetting the transform origin). The redrawing of the map is noticeable for the user (quick flash), but should not happen too often due to the large bounds.

```javascript
L.Map.mergeOptions({
	transformBounds: new L.Bounds(L.point(-1000000,-1000000),L.point(1000000,1000000))
});

L.Map.addInitHook(function () {
	this.on('moveend', function () {
	
		var mapPaneTransform =  this._mapPane._leaflet_pos
		if(this.options.transformBounds && !this.options.transformBounds.contains(mapPaneTransform))
		{
			this._resetView(this.getCenter(),this.getZoom());
		}
	
	});
});
```

Let me know what you think, kind of simple solution ;)

**Comment by IvanSanchez** [comment]
Upstream Firefox bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1203873
