### ISSUE TITLE
Map mouseout event fired by TileLayer change of DOM element (in master branch)

### ISSUE THREAD

**Issue by fminuti** [Leaflet/Leaflet#3648]
Please see http://jsfiddle.net/v1so6m56/
If you move the mouse inside the map, every time you change the img DOM element of tilelayer the map "mouseout" event is triggered.
Reproducible in every browser.
Works fine in LF 0.7.3

**Comment by mourner** [comment]
Looks like a regression cc @yohanboniface, previously it acted as mouseenter/leave.

**Comment by mourner** [comment]
@fminuti thanks for the report, I think we'll fix this for the next beta.

**Comment by yohanboniface** [comment]
I'm looking at it.

**Comment by yohanboniface** [comment]
So basically we have a conflict between two scenarios:
- the case where a child element is the initial target of an event, and we want to manually traverse the DOM to find the marker div, and thus the connection to the Marker instance; here we are happy to traverse the DOM until we find a target that listens to the fired event;
- the case described here, where a DOM element (the tile img) fire the event, and thus we traverse the DOM manually to find the first possible target that listens to it, which in this current case is the map; so we would like not to traverse the DOM if the initial target is not in the registered targets

That may be an argument to switch back to using internal parent events instead of traversing the DOM for the marker<=> map connection, but I'll look for a fix without changing the pattern we are using first.

Going to eat now, I'll have a deeper look today I think.

**Comment by fminuti** [comment]
Perfect. Thanks.
