### ISSUE TITLE
How to delete the Feature from the FeatureCollection

### ISSUE THREAD

**Issue by Odjey** [Leaflet/Leaflet#3670]
Hi! Sorry for my English)
Example:
<pre>
var geojsonFeature = { "type": "FeatureCollection",
		   "features": []
	 };
var geoJsonCol = L.geoJson(geojsonFeature , { 
           onEachFeature: onEachFeature
      }).addTo(map);

feature1 = { "type": "Feature", 
                         ...........
                       };
feature2 = { "type": "Feature", 
                         ...........
                       };

geoJsonCol.addData(feature1);
geoJsonCol.addData(feature2);
</pre>
How to delete feature1 or feature2 ?

**Comment by patrickarlt** [comment]
Currently this isn't possible since your GeoJSON features will get turned into Leaflet layers.

However since your GeoJSON `Feature`s will have an `id` property you can use some of the LayerGroup http://leafletjs.com/reference.html#layergroup (which GeoJSON inherits from) methods to do something like this.

```js
geoJsonCol.eachLayer(function(layer){
  // layer.feature is the original geojson feature
  if(layer.feature.id === feature1.id) {
    geoJsonCol.removeLayer(layer);
  }
});
```

**Comment by Odjey** [comment]
Thank's
