### ISSUE TITLE
openPopup() broken in 1.0

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#3745]
There are two serious bugs with openPopup():

1. It doesn't open popup, when it needs to pan first.
<img width="397" alt="screen shot 2015-08-14 at 12 19 07" src="https://cloud.githubusercontent.com/assets/494223/9272076/3921f3f4-427f-11e5-8a66-b5a9215ad00d.png">

2. If the user pans the map, and it's still in the inertia animation (including the time where it only moves invisibly small distances), the map arrives at a totally wrong position. 
<img width="403" alt="screen shot 2015-08-14 at 12 18 05" src="https://cloud.githubusercontent.com/assets/494223/9272067/2f8b2220-427f-11e5-815f-9192329a41a9.png">

Wanted result:
<img width="398" alt="screen shot 2015-08-14 at 12 19 20" src="https://cloud.githubusercontent.com/assets/494223/9272082/59133ede-427f-11e5-9aa3-654b09906e88.png">

JSFiddle: http://jsfiddle.net/858asofb/3/

Presents both on latest Chrome and Firefox under OS X 10.9.5.

**Comment by hyperknot** [comment]
Some more information about what functions are called (just by inserting console.logs into leaflet-src.js).

```
Layer openPopup
Popup update
Map openPopup
Popup setLatLng
Popup update
_adjustPan
panBy
```

**Comment by yohanboniface** [comment]
So, AFAIK, the issue is that on popup `onAdd` call, `update` is called, which then calls `_adjustPan`, which triggers the viewreset; but at this time the `Popup.getEvents` method as not yet been called given that the popup is not yet fully added (we still are in the middle of `onAdd` subcalls), and thus the popup not yet listens to the `viewreset` event.

I'll try to look for a fix.
