### ISSUE TITLE
No .closePopup() method

### ISSUE THREAD

**Issue by imaginalis** [Leaflet/Leaflet#3775]
Hello. Thank you for this amazing library.
I've got a problem with closing popups.

When I bind a popup to marker there's no default closing button, the only way to close it is to click somewhere on the map. 
I managed to add button by myself using Awesome Fonts and some closing method. 

```js
var popup = L.popup()

    .setLatLng(latlng)
    .setContent('<i class="fa fa-times icon-popup" onclick="closePopup()">        </i><br> My content ');

    marker.bindPopup(popup);
    popup.addTo(layer);
```
                                

I've tried almost everything on this 'onclick' map.closePopup(), layer.closePopup(), this.closePopup(), or invoking .getPopup() and then .closePopup() and still nothing - it doesn't work.

Of course I've tried to set the close button ({closeButton:true} as a param for popup) and it doesn't show.

Thanks in advance

**Comment by IvanSanchez** [comment]
> there's no default closing button

That shouldn't be the case. Can you link to an example? (lots of people here use jsfiddle to demonstrate bugs)

> I've tried almost everything on this 'onclick'

1. `onclick` is in disuse. Consider using `querySelector` and `addEventListener` instead.
2. `onclick` takes a function reference as a parameter, not a function call. Do read https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclick
3. `onclick` runs on the global scope. If your function is not defined in the global scope (i.e. as `window.functionName`), it won't work. Once again, use `querySelector` and `addEventListener` because they will run in the local variable scope.

**Comment by mourner** [comment]
@IvanSanchez better not to waste time making detailed assumptions before you see a JSFiddle test case :)

**Comment by imaginalis** [comment]
Hi, I've already tried it. On separated example it performs well and button shows, the popup is closing and so on.
Maybe it's because of angular-leaflet-directives using.
Will try @IvanSanchez advices.

**Comment by mourner** [comment]
Will reopen if reproduced in a minimal JSFiddle test case.

**Comment by gaveen5555** [comment]
You can include a close button like this

 newMarker.bindPopup(note, {closeOnClick: false, autoClose: false, closeButton: true}).openPopup();
