### ISSUE TITLE
L.control.layer removeLayer does not remove layer from map

### ISSUE THREAD

**Issue by toxygene** [Leaflet/Leaflet#3819]
While trying to dynamically add and remove overlays from a Control.Layers, I encountered an issue where a layer I had removed from Control.Layers was still on the map. I've reproduced the issue here: http://jsfiddle.net/a16aq2b2/1/

The documentation doesn't mention anything about this situation and I had assumed Control.Layers removeLayer would remove the layer from the map (similarly to how layer groups work).

If this is the intended behavior, I believe the documentation should mention this behavior.

**Comment by IvanSanchez** [comment]
The [documentation for 1.0-beta1](https://mourner.github.io/Leaflet/reference.html#control-layers-removelayer) clearly states:

«Remove the given layer from **the control**.» (emphasis mine)

And the [doc for 0.7.x](http://leafletjs.com/reference.html#control-layers-removelayer) states:

«Remove the given layer from **the control**.»

So, expected behaviour. The layers control doesn't promise to remove a layer from the map when it's removed from the control.

:-)
