### ISSUE TITLE
Can't re-enable dragging on mobile browsers

### ISSUE THREAD

**Issue by skalb** [Leaflet/Leaflet#3825]
Using leaflet master, I'm unable to re-enable map dragging after it's disabled.

Simple example: https://jsfiddle.net/skalb/otwgyutn/7/
Complex example: https://jsfiddle.net/skalb/otwgyutn/5/

Works:
- Desktop browsers

Doesn't work:
- Chrome/Safari on iPhone 6
- Safari on iPhone 6 simulator

**Comment by IvanSanchez** [comment]
The problem lies in the `Tap` handler somehow. 

On a normal scenario, the `Drag` handler receives a `touchstart` event. If it's disabled and re-enabled, the `Tap` handler somehow takes precedence, so the `Drag` handler receives a synthetic `mousedown` event instead.

Receiving a `mousedown` makes the `Drag` handler's `Draggable` to expect `mousemove` and `mouseup`, but `Tap` doesn't fire synthetic `mousemove`s.

I see two possible solutions: either add `mousemove` to `Map.Tap.js`, or make sure that `Draggable` ignores synthetic `mousedown` events and uses the raw `touchstart` instead.

**Comment by skalb** [comment]
Third (maybe bad) solution is to just never disable the handler, e.g. move line:

https://github.com/Leaflet/Leaflet/blob/master/src/dom/Draggable.js#L40

to the initializer.

This fixed the issue for me.
