### ISSUE TITLE
Uncaught TypeError: Cannot read property '_leaflet_id' of undefined

### ISSUE THREAD

**Issue by asotoopensky** [Leaflet/Leaflet#3877]
Hi,

I got this error using Leaflet 1.0 Beta:

**Uncaught TypeError: Cannot read property '_leaflet_id' of undefined**

on this line:
**obj._leaflet_id = obj._leaflet_id || ++L.Util.lastId;**

on stamp function

Can you help me with this please?

**Comment by IvanSanchez** [comment]
> Can you help me with this please?

No, or at least not with the scarce information you're providing. Please post a reproducible failing example, using jsfiddle or jsbin or playground-leaflet.rhcloud.com. And read http://catb.org/~esr/faqs/smart-questions.html if you have the time, it'll help you create better issues in the future.

**Comment by tinproject** [comment]
I've come here because I got the same error while trying to register an event. After some time debugging I notice that I had been passing the function with parenthesis so Leaflet is trying to calculate the stamp of the result of the function (undefined), not the function itself.. Silly JS novice mistake...

This error it's a sign of that you are not correctly register an event with L.DomEvent.on()
