### ISSUE TITLE
webkitMovement deprecated use movementX instead.

### ISSUE THREAD

**Issue by kyriacos** [Leaflet/Leaflet#3943]
I get this warning in the console:
```
'webkitMovementX' is deprecated. Please use 'movementX' instead.
leaflet-src.js:49 
```
Using 1.0.0-beta.2.rc

**Comment by IvanSanchez** [comment]
So this *warning* (nor an error) happens when a native `MouseEvent` is extended into a leaflet event. The Leaflet code has no hardcoded references to `webkitMovementX`/`Y`.

I don't think this is worthy of any attention. The moment Webkit stops exposing a deprecated attribute, the warnings will cease.

**Comment by mourner** [comment]
Yeah, not actionable probably.

**Comment by kyriacos** [comment]
Thanks for the explanation. Wasn't sure.
