### ISSUE TITLE
Marker with open popup disappear after fitBounds

### ISSUE THREAD

**Issue by Tanrikut** [Leaflet/Leaflet#3953]
Hi,

I have a leaflet with one feature group with one marker that has an open popup. When I update marker location and call fitBounds to zoom to marker in its new location, I see nothing. Marker and popup disappears from the map. I make a small pan with mouse, marker reappears in the view. Also I noticed tiles in the osm layer also disappears and reappears with marker.

Here is the jsfiddle example: http://jsfiddle.net/6fqufue2/1/
In the example, popup is open after 1 sec and location update/fitBounds call happens after 2 secs. If you like you can remove timeouts but results will be same.

Tankut

**Comment by IvanSanchez** [comment]
Not reproducible on 1.0.0-beta2, only in 0.7.x.

**Comment by perliedman** [comment]
Probably caused by two map moves being initiated at the same time:

* Leaflet will automatically pan the map to the marker's new location after the `setLatLng` call when the popup is open, to ensure the popup is still in view
* The explicit call to `fitBounds`

Removing the call to `fitBounds` moves the map so that the marker appears in the map's corner, tiles are loaded correctly. Adding a timeout between `setLatLng` and `fitBounds` also works.

A workaround is to set the popup option `autoPan` to `false`, like this: http://jsfiddle.net/6fqufue2/2/

**Comment by peterkowalsky333** [comment]
I am having also this issue.Setting autopan to false dont help. My pop up is still closed after i call fitBounds. Any news on this ?!

**Comment by johnd0e** [comment]
@peterkowalsky333 
This is closed issue and nobody is working on it.

Are you still using Leaflet 0.7.x? Apply workaround suggested by **perliedman**.

In case if you encountered this bug in latest Leaflet version - please open new issue providing complete details.
