### ISSUE TITLE
Custom projection causes visible geojson shape to be clipped in 1.0.0 beta

### ISSUE THREAD

**Issue by cgoessen** [Leaflet/Leaflet#3968]
Hi,

I've recently moved a leaflet application from 0.7.x to 1.0.0-beta2 (nice performance improvements by the way).

I'm using various custom projections (epsg3035 mainly), in this projection the shape clipping behaves strangely, some countries are clipped while they should still be visible.

I've built a minimal exemple here:
http://plnkr.co/edit/84JBRgw5ZzqzjG5dETE0

The most noticeable glitchy country is Russia.

My guess is that it has to do with the bound checking being done using unprojected coordinates, but that's a wild guess.

I'm not totally sure if it's related to leaflet or proj4leaflet.

**Comment by IvanSanchez** [comment]
Thanks for the reproducible example! It makes debugging these kinds of things easier.

**Comment by IvanSanchez** [comment]
I found this is even easier to reproduce by using just a bounding box for Brazil: 

```js
	var rectangle = L.rectangle([[5.244486, -34.729993],[-33.768378, -73.987235]]).addTo(map);
	map.options.crs = epsg3035;
        map.fitBounds(rectangle.getBounds());
```

In this case, the rectangle disappears when panning vertically. Live demo at http://playground-leaflet.rhcloud.com/pos/edit?html,output

I'm not sure whether that bbox should show as an actual rectangle in the map's CRS.

**Comment by IvanSanchez** [comment]
I've tracked the bug down to `L.Polyline._project`, [here](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Polyline.js#L140).

That code assumes a rectangular projection, and uses only two corners from the bounding box. For non-rectangular projections, all four corners must be projected into pixel coordinates, and *then* expand the pixel bounds by the tolerance.

**Comment by perliedman** [comment]
Some testing reveals that using four points doesn't really solve this, at least not with this naïve approach:

```js
if (this._bounds.isValid()) {
	var map = this._map,
	    bounds = this._bounds,
	    pxBounds = new L.bounds([
	    	map.latLngToLayerPoint(bounds.getSouthWest()),
	    	map.latLngToLayerPoint(bounds.getNorthEast()),
	    	map.latLngToLayerPoint(bounds.getSouthEast()),
	    	map.latLngToLayerPoint(bounds.getNorthWest())
	    ]);

	pxBounds.min._subtract(p);
	pxBounds.max._add(p);

	this._pxBounds = pxBounds;
}
```

This gives more or less the same results, as far as I can tell. The problem, like in #4020, is that with this projection, what is lat min/max, isn't at all the same as projected y min/max: since the projection curves, y at some point becomes parallel with longitudes instead.

Considering _all_ points in the polygon when calculating bounds, rather than just the bounds, works well in this case, though. This test code works well:

```js
		if (this._bounds.isValid()) {
			var map = this._map,
			    bounds = this._bounds,
			    pxBounds = new L.bounds([].concat.apply([], this._rings));

			pxBounds.min._subtract(p);
			pxBounds.max._add(p);

			this._pxBounds = pxBounds;
		}
```

Needless to say, this has performance implications though, since polygons might have a lot of vertices.

An idea would be to breaking this out into the CRS class somehow, to keep the simple and performant implementation as a default for this built-in CRSs, while things like Proj4Leaflet could override it with the implementation above. I guess #4020 could also be solved in a similar, if not the exact same, way.
