### ISSUE TITLE
L.marker.setIcon() removes .leaflet-interactive

### ISSUE THREAD

**Issue by chronixlo** [Leaflet/Leaflet#3976]
Calling setIcon on a marker strips the leaflet-interactive -class.

Demo: http://playground-leaflet.rhcloud.com/mal/edit?html,output

**Comment by IvanSanchez** [comment]
So when `L.Marker.setIcon` is called, `_initIcon` sets a flag and skips the logic for adding interactivity to the new icon. The solution is to review the behaviour of the `addIcon` flag in `_initIcon`, and/or make an explicit call to `L.Marker._initInteraction` from within `L.Marker.setIcon`.

This looks like a pretty easy task, so I'll ask newbies to stand up for the challenge and submit a pull request for this.

**Comment by gorshkov-leonid** [comment]
Hi, we have problem with marker dragging:
https://jsfiddle.net/goleon/qo7a9no4/ -beta2 with hack (same as fix above)
https://jsfiddle.net/goleon/qo7a9no4/

If during handle of dragstart we changes icon then dragend will not be occurred and marker will jump during next drag because new position was not saved.

**Comment by gorshkov-leonid** [comment]
this fix brokes https://github.com/Leaflet/Leaflet/pull/3687?
