### ISSUE TITLE
Ability to hide/show markers and layer groups

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet#4]

**Comment by rwwagner90** [comment]
+1 I need this

**Comment by Jakobud** [comment]
FYI, this is all solved when using the new custom pane management and creation. You can use css to easily hide/show the pane DOM elements. It will be available for v1.0.

**Comment by rwwagner90** [comment]
@Jakobud I am using 0.8-dev, which appears to have some support for custom panes. However, the changelog isn't very specific on how to use this functionality. I have a FeatureGroup, which I am storing shapes in, and I would like to have that FeatureGroup live in a custom pane, instead of the overlay pane. I tried this:
```js
var filterPane = map.createPane('filterPane');
var drawnItems = new L.FeatureGroup({pane: filterPane});
map.addLayer(drawnItems);
```

This does create the new filter pane, as I wanted it to, but then it adds the FeatureGroup to the overlay pane, and not the filter pane, as I specified.

**Comment by Jakobud** [comment]
This is because in the current 0.8-dev branch there was not yet support for adding vector elements to custom panes. They were still added to the overlay pane because the map only had a single renderer. 

Several months ago I created a custom branch with support for vectors in custom panes. See this pull request here: #2786 

It works really great and I am currently using this custom branch for a project without any issues. However @mourner wants the code refactored and changed up a bit because of I broke some backwards compatibility regarding plugins and some other stuff in the code. So take it with a grain of salt.

**Comment by rwwagner90** [comment]
@Jakobud I implemented a solution using custom renderers. It's not as clean as it would be if I could just set the pane for the FeatureGroup and be done with it, but it does work. I would like to see your PR merged in, so we could do vector pane support out of the box. How goes the refactoring of it?

**Comment by Jakobud** [comment]
Eh I'm kind of in a holding pattern at the moment. I'm not sure how to do some of what @mourner is suggesting. Please feel free to look at yourself and contribute. The current PR is not going to make it in since he wants these changes.

Essentially my solution works like this:
1. Create new pane
2. Create layer and in the layer options, specify the custom pane
3. If it's a vector element, a new renderer will be added to the custom pane and used for the vector element

The solution @mourner would like to see:
1. Create new pane
2. Create new renderer and add it to a custom pane
3. Create new vector layer and instead of `.addTo(map)` do `addTo(renderer)`

I personally don't feel that's as straightforward but @mourner likes it so thats what I'm aiming for. My biggest confusion in the code is how to differentiate between a map and renderer object and whether or not I need to keep track of a list of renderers on the map object (just like how panes are kept track of). Also what happens when you want to remove the vector layer from the map? Do you do `map.remove(vectorLayer)` or `renderer.remove(vectorLayer)`? If its the later then a bunch of shared code will need to happen between and map and renderer I think... I dunno. I'm confused at this point. I'm not 100% familiar with the Leaflet source either. There aren't many comments so it's hard to tell exactly what certain things do.

Take a look in the PR comments and you can try to follow along. I could use some help if you have any ideas. Since you are using custom renderers for your solution maybe this would be right up your alley. Handling of custom panes is one of the primary items left to do before 1.0 is ready for release.

**Comment by vool** [comment]
+1

**Comment by Kalix86** [comment]
fwiw +1

Can't wait for v1.0. Keep up the good work guys.

**Comment by birdage** [comment]
:+1:

**Comment by af7** [comment]
Hello, I wonder if this solution work OK now for every case:

````
var filterPane = map.createPane('filterPane');
var drawnItems = new L.FeatureGroup({pane: filterPane});
map.addLayer(drawnItems);
````

**Comment by Jakobud** [comment]
Yes you can show/hide panes on-demand in 1.0. I've been meaning to put together a tutorial on it.

**Comment by af7** [comment]
Hello, can you please show me how? I cannot make it work, since the FeatureGroup is **not** added to the Pane despite I use the 'pane' option. Is the code above correct?

**Comment by KarelWintersky** [comment]
+1

**Comment by bimalgrg519** [comment]
+1

**Comment by davidaparicio** [comment]
+1

**Comment by perliedman** [comment]
Shouldn't this issue be closed? AFAIK, this is solved by panes from 1.0 upwards.

**Comment by KarelWintersky** [comment]
> Shouldn't this issue be closed? AFAIK, this is solved by panes from 1.0 upwards.

have you an **example** of solution?

**Comment by perliedman** [comment]
@KarelWintersky for basics on panes, see the [Panes tutorial](http://leafletjs.com/examples/map-panes/). Since a map pane is just a DOM element, you can set it's `display` property to `none` to hide it.

So:

* create a pane
* put markers into that pane (or a layer within that pane)
* set pane's `display` CSS property to hide/show it

**Comment by KarelWintersky** [comment]
[Useless example](http://leafletjs.com/examples/map-panes/).

```
 var positronLabels = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png', {
        attribution: cartodbAttribution,
        // pane: 'labels'
    }).addTo(map);
```
with settings `panes` option and without it have no difference. 

How can I hide or show layergroup using panes?

**Comment by perliedman** [comment]
@karelwintersky the last two comments in this thread describe that, please clarify what's missing. (Also, I would suggest not referring to other people's work as "useless" if you want them to help you.)

**Comment by phloose** [comment]
As i had a similar use case and thought it would be helpful to others i created a small plugin that adds `hide` and `show` methods to `L.Layer` and `L.LayerGroup`: [leaflet-layervisibility](https://github.com/phloose/leaflet-layervisibility)

**Comment by johnd0e** [comment]
@phloose 
Cool!
Have you added your plugin to `plugins.md` already?

**Comment by phloose** [comment]
> Cool!
> Have you added your plugin to `plugins.md` already?

Thanks! No not yet. Will do that later...

**Comment by phloose** [comment]
@johnd0e i am not really sure in which category my plugin fits in... I would think at most into `Overlay Display > DataViz`. What do you think?

**Comment by johnd0e** [comment]
May be https://leafletjs.com/plugins.html#markers--renderers
