### ISSUE TITLE
Font size readability when detectRetina is true  

### ISSUE THREAD

**Issue by creativestudio** [Leaflet/Leaflet#4005]
I noticed the font size is hard to read when using detectRetina, tested on Chrome, Firefox and Safari all latest versions on Mac OS X running el Capitan.

<img width="1372" alt="detectretinafalse" src="https://cloud.githubusercontent.com/assets/1229860/11078963/e84187e0-87bd-11e5-8d73-38c9ea625292.png">
<img width="1372" alt="detectretinatrue" src="https://cloud.githubusercontent.com/assets/1229860/11078962/e8412b2e-87bd-11e5-80b4-1186f1043511.png">

**Comment by IvanSanchez** [comment]
Which tileserver are you using? How does your tilelayer definition look like? Leaflet 0.7.x or 1.0.0 betas?

**Comment by mourner** [comment]
This is by design, since you're essentially getting tiles that are designed for non-retina screens and then displaying them at 2 times smaller scale. `detectRetina` is a hack for cases when you don't have a proper retina source. Proper solution is just using a tile URL that loads 512px retina tiles (usually with `@2x` prefix) in place of 256px ones.
