### ISSUE TITLE
Regression: embedded maps on Android devices will prevent drag-scroll in v0.7.7 (and in 1.0.0-beta)

### ISSUE THREAD

**Issue by louh** [Leaflet/Leaflet#4051]
The trick specified in #2031 to add `tap: false` to the map options in order to prevent Leaflet from swallowing `touchmove` events is broken in Leaflet 0.7.7, as well as in 1.0.0-beta.1 and 1.0.0-beta.2. So, for maps that are embedded in part of a page, Leaflet 0.7.5 is the last version I could recommend using if you want to prevent that map from not hijacking touch-scroll (edit: on Android devices).

I have a very simple page you can load in a mobile browser or mobile simulator to test this effect on each of the four versions I've specified: http://louh.github.io/nyc-community-boards

The code for this lives here: https://github.com/louh/leaflet-embedded

**Comment by louh** [comment]
Addendum: I just tried this on iOS Simulator (iOS 9.1, iPhone 6) and it does not appear to affect iOS. My normal devices are on Android Chrome and also the mobile simulator of Chrome on OSX.

**Comment by littleiffel** [comment]
in 0.7.7 in the CSS file .leaflet-container received the property

```
touch-action:none
```

Removing this line made the page scroll again even while touching/dragging on the map container.

Currently this line is still present in the CSS.

**Comment by perliedman** [comment]
@louh can you clarify exactly what the problem is with this example on mobile: http://louhuang.com/nyc-community-boards/#11/40.6051/-74.1055

When loading it in mobile mode, it shows a header and search field on top, the map in the middle, and an information text below. I can pan the map with touch, but there's nothing I can scroll on this page. Or is that example running a working version?

Also, I would suggest you put the examples, with different versions of Leaflet, on http://playground-leaflet.rhcloud.com/ , where it is easy to switch library version, and also easier for Leaflet devs to work with.

**Comment by louh** [comment]
Hi @perliedman, thanks for responding! The http://louhuang.com/nyc-community-boards/#11/40.6051/-74.1055 link is probably not the best to look at since I did a bunch of work on it since then. 

I've done the leaflet playground as you suggest:

with Leaflet v1, drag-scrolling the page fails on Android or Chrome mobile simulator when the user touches the map:
http://playground-leaflet.rhcloud.com/fuzo/edit?html,output

with Leaflet v0.7.5, drag-scrolling the page using the map works:
http://playground-leaflet.rhcloud.com/los/1/edit?html,output

**Comment by IvanSanchez** [comment]
Note to self: see if the `prosthetic-hand` emulated events can trigger a page scroll.

**Comment by perliedman** [comment]
There must have been a mixup, since the first link above also uses Leaflet 0.7.5, and works :)

Here's an example that actually shows this problem in latest master: http://playground-leaflet.rhcloud.com/juge/edit?html,output - it reproduces the issue both in Chrome on Android as well as in desktop Chrome with mobile emulation, as @louh mentions.

**Comment by heldchen** [comment]
as a workaround until this is fixed `.leaflet-container { -ms-touch-action: inherit !important; touch-action: inherit !important; }` can be added to the embedding page's css. tested in chromes device emulator.
