### ISSUE TITLE
L.control.layers missing call to L.Map.getSize()

### ISSUE THREAD

**Issue by Brobin** [Leaflet/Leaflet#4062]
In version 1.0.0-b1 I am noticing a very weird bug.

I am using this code to create a control layer with options

```javascript
function generateMap(map) {
    var mapTiles = getMapTiles();
    var overlayMaps = getMaps();
    var options = {
        collapsed: false,
    };
    L.control.layers(mapTiles, overlayMaps, options).addTo(map);
}
```

When I include the `options` variable, rendering fails with the error `ncaught TypeError: Cannot read property 'y' of undefined.

the script works perfectly when I omit the options.

```javascript
function generateMap(map) {
    var mapTiles = getMapTiles();
    var overlayMaps = getMaps();
    L.control.layers(mapTiles, overlayMaps).addTo(map);
}
```

**Comment by IvanSanchez** [comment]
Do you have a stack trace?

**Comment by Brobin** [comment]
Stack trace

```
o.Control.Layers.o.Control.extend._expand	@	leaflet.js:8
o.Control.Layers.o.Control.extend._initLayout	@	leaflet.js:8
o.Control.Layers.o.Control.extend.onAdd	@	leaflet.js:8
o.Control.o.Class.extend.addTo	@	leaflet.js:8
generateMap	@	Map.js:119
```

**Comment by Brobin** [comment]
Here's the stack trace on the unminified version retrieved from the dowloads page

```
L.Control.Layers.L.Control.extend._expand	@	leaflet.js:9112
L.Control.Layers.L.Control.extend._initLayout	@	leaflet.js:8957
L.Control.Layers.L.Control.extend.onAdd	@	leaflet.js:8885
L.Control.L.Class.extend.addTo	@	leaflet.js:8460
generateMap	@	Map.js:119
```

**Comment by IvanSanchez** [comment]
Aha. It seems that the layers control is asking the map size via `this._map._size` instead of `this._map.getSize()`. This is a trivial fix, so I'll let any newbie coder to make the change and issue a pull request.

Normally, `_expand` gets executed on a user interaction after the map size has been init'ed. But, in your case, `collapsed:false` means that the control tries to get the size as soon as possible, which in your case happens before any calls to `L.Map.getSize()`.
