### ISSUE TITLE
Image overlay not working

### ISSUE THREAD

**Issue by angua1210** [Leaflet/Leaflet#4111]
Hi,

I was using imageOverlay in a project and it was working perfectly fine.
Now it's not working anymore, even the example provided in the documentation.
Here is a basic example which is not working: 
http://codepen.io/anon/pen/PZbwrJ
I tried on Chrome/firefox/ie. i don't get any error message on the javascript console.

Any idea why?
Regards.

**Comment by ghybs** [comment]
Hi,

You have specified your map with `maxZoom: 4`, which is far too low for your image overlay which is displayed on a very small area (`[[40.712216, -74.22655], [40.773941, -74.12544]]` with `L.CRS.Simple`). So you do not see it even though it is there.

Also, you should use `map.fitBounds()` to center the map directly on your image overlay to avoid having to look for it.

Please use Stack Overflow or GIS Stack Exchange in priority when you need trouble shooting help on your projects. GitHub repository issues should be used when the problem is tracked down to be the library itself.

Hope this helps.
