### ISSUE TITLE
Animate the movement of the popup

### ISSUE THREAD

**Issue by Top-tompak** [Leaflet/Leaflet#4217]
```
var popup = L.popup()
    .setLatLng([39.56864645674724, -104.96269226074219])
    .setContent('Its Popup')
    .openOn(map);

setTimeout(function() {
    popup
        .setLatLng([39.59907503753918, -104.96131896972656]);
}, 100);
```

I tried:
```
.leaflet-popup {
    transition: left linear 1s, bottom linear 1s;
}
```
Popap starts moving from the top left. As I understand it, the DOM is re-created when setLatLng()

**Comment by perliedman** [comment]
No, `setLatLng` will just adjust the position, without recreating any elements. Check the code here: https://github.com/Leaflet/Leaflet/blob/stable/src/layer/Popup.js#L233

Anyway, this looks like a question on using Leaflet rather than an issue in Leaflet. It's better to ask this type of questions on sites like [gis.stackexchange.com](https://gis.stackexchange.com/) or [stackoverflow](https://stackoverflow.com). The issue tracker is for reporting bugs and discussing new features.
