### ISSUE TITLE
Uncaught Error: No value provided for variable {x16}

### ISSUE THREAD

**Issue by kennethhutw** [Leaflet/Leaflet#4240]
Hi 

I tried to use qq map tiles with the leaflet.js but it has an error "Uncaught Error: No value provided for variable {x16}" and cannot show map. 

How to solve it? thank you for taking time to read this issue. 

http://plnkr.co/edit/VhYnmd?p=preview

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com/questions/tagged/leaflet](https://gis.stackexchange.com) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

Having said that: your problem is in how you're using `{z}/{x16}/{y16}/{x}_{y}` in the template. If you use `leaflet-src.js` instead of `leaflet.js` you'll have a much easier time debugging.
