### ISSUE TITLE
Attribution text not removed when tileLayer is removed from map

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4285]
Since 66397822, the attribution control text isn't removed when the tile layer is removed from map.

cc: @IvanSanchez

**Comment by IvanSanchez** [comment]
@hyperknot Can we have a playground/fiddle, please?

**Comment by hyperknot** [comment]
@IvanSanchez sure, I realised it's not as straight-forward as I thought, working on the playground example.

**Comment by hyperknot** [comment]
@IvanSanchez wow, deeper things here!

1. The master build (e0c17bff ) is not from the master commit (66397822).
2. Is it because unit tests failed, or because it was pushed without a PR?
3. So the playground does not produce the issue, but only because master is from an old build.
http://playground-leaflet.rhcloud.com/zak/4/edit?html,output
4. If you copy the code to a debug html, it'll trigger the bug.
5. I wonder why is your spec file not triggering a fail, possibly because removeFrom vs. removeLayer?

**Comment by IvanSanchez** [comment]
Yeah, it might be due to to being pushed without PRs, and due to the recent Travis CI jobs on PRs failing. Gotta check that first.

(The tests pass because the `L.Layer`s define the `getAttribution()` method)

**Comment by hyperknot** [comment]
@IvanSanchez I mean it seems that tileLayer's attribution behaves differently to your custom L.Layer, as the test passes on L.Layer but is behaving wrong on a real tileLayer.

**Comment by dr-itz** [comment]
Had the same problem, please see PR #4293.

**Comment by hyperknot** [comment]
@dr-itz thanks for your contribution, I'm reviewing it! 

We also need to fix the tests, as it should not pass like it does now, with the wrong behaviour.

**Comment by dr-itz** [comment]
@hyperknot Tests are fixed :) Maybe I should have mentioned it in the commit message...

**Comment by hyperknot** [comment]
@dr-itz so, you have basically reverted the change in 6639782, which caused the original problem. That change was there because of a reason, I need to look more into what was that fixing and what would be a proper way to implement it correctly.

About dummylayer(), it's a separate issue, I need to look into if this properly simulates a tileLayer or not, and what causes the tests to pass while tileLayers produce a different behaviour.

**Comment by dr-itz** [comment]
Switching tile layers is exactly how I noticed the double attribution. I'll have a look what #4257 was about.

That `dummyLayer` is there so we don't crash because of missing `onAdd` and `onRemove` callbacks.
Those get called once the map is "loaded" by the `setView()`, necessary to exposes the problem of this bug in the first place. So it's not separate...

So without looking closer (I'll do later), removing the `addAttribution()` in `_layerAdd()` instead of in `addLayer()` would fix this problem (#4285) and #4257...it's just that it _feels_ right in `_layerAdd()`.

**Comment by dr-itz** [comment]
So..I tested with the example from #4257 (http://playground-leaflet.rhcloud.com/jad/1/edit?html,output),
modified to use my local Leaflet. Works just fine.

Looking closer, PR #4263 merged commit fb79bbf that actually fixes the problem of #4257.
Just to be sure, I tested this by reverting the commit on top of my PR.

The real bug was in fact introduced with the change in to Layer.js in 6639782. So yes, my PR
reverts that part and instead fixes the broken test case.

**Comment by hyperknot** [comment]
@dr-itz your tests are behaving correctly, but I really wonder if we shouldn't be testing a standard gridLayer instead? @IvanSanchez any reason why we should not test on a standard gridLayer here?

@dr-itz I need to properly understand how #4263, #4257 and #4280 all comes together before deciding on a solution, please give me a day to look into it.
