### ISSUE TITLE
Implementing a different CRS for each L.TileLayer.WMS instance is confusing or incomplete?

### ISSUE THREAD

**Issue by arctelix** [Leaflet/Leaflet#4291]
This is in reference to the features introduced in pull request #945 

@mourner I'm a little confused on how to properly implement a TileLayer.WMS with a crs that differs from the map's crs. Currently i do have it working but, only with the addition of @mhotby 's modification which he posted to the pull request. Without that, it seems impossible to implement.. Was this not the point of your integration of the crs option in the TileLayer.WMS?

For example If i define two TileLayers as follows:

1) Open Stree Maps with EPSG:3857

    osm = new L.TileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png')

2) and a WMS with EPSG:2263

     nycCrs = new L.Proj.CRS("EPSG:2263" etc..)
     nycMap = L.tileLayer.wms('http://maps.nyc.gov/geowebcache/service/wms/', {
     crs:nycCrs,
     tileSize: 512,
     etc...}
Define a map with the default, osm compatible crs of EPSG3857:

```
var map = L.map('map', {
    layers:[osm]}

var baseMaps = {
    "nyc": nycMap,
    "osm": osm};

L.control.layers(baseMaps).addTo(map);
```
With the configuration above all requests to the nycMap WMS server fail due to incorrect scale and or origin issues.

However If i use the setCrs() method and and 'baselayerchange' event listener suggested by mhotby (modified for my setup):

```
L.Map.prototype.setCrs = function(newCrs) {
    this.options.crs = newCrs;
}

map.on('baselayerchange', function(layer) {
    if(layer.name == 'osm')
        map.setCrs(L.CRS.EPSG3857);
    else if(layer.name == 'nyc')
        map.setCrs(nycCrs);
    map.setView(map.getCenter(),map.getZoom());
});
```
Now everything works as expected. I'm just wondering if this is what you intended or if i have missed something in my configuration. Also, if this is the correct way to implement it , why are mhotby 's mods not implemented along with the TileLayer.WMS.options.crs. It seems to be incomplete without them...

Thanks for everything, leaflet is nothing short of awesome!

**Comment by perliedman** [comment]
Hi,
please note that the issue tracker is not intended for support questions, but rather bug reports or discussion for new features.

Having said that, I more or less duplicate my comment in #945:

@arctelix are you trying to mix more than one CRS on the same map? That has been discussed a couple of times, for example see #2553.

My opinion on this is that CRS switching should not be supported by Leaflet core, since I can't see it working in an intuitive way. It could, however, probably quite easily be be supported by a plugin. So far, no one have written such a plugin, as far as I know. @mhotby's code is probably a reasonable start for a plugin.

I was actually a bit surprised to learn about the WMS functionality added by #945, since it seems to add at least partial support for multiple CRS!

**Comment by arctelix** [comment]
@perliedman Thanks for the responce, in both locations ;) I figured nobody would see it in a closed pull request.  

That is exactly what confused me... Partial implimentation of a feature.  What other use could there be for permitting each instance of a tile layer to have a unique crs? Thats why i thought it was a bug, not support.
