### ISSUE TITLE
Markers move erratically while zooming on mobile

### ISSUE THREAD

**Issue by delner** [Leaflet/Leaflet#4315]
Given a Leaflet map, if you initialize the map, add a circle marker, and invoke the following:

```
map.dragging.disable();
map.dragging.enable();
```

Then when you "pinch-to-zoom" on mobile via touch, the markers on the map move erratically while zoom is in progress, snapping back to the correct position after the zoom is complete. This makes for an ugly user experience.

http://i.imgur.com/O7ZlME5.gif
![markers moving on zoom](http://i.imgur.com/O7ZlME5.gif)

Replicated on Leaflet latest (1.0.0), on Android Chrome, and Chrome on a MS Surface Pro 3 running Windows 10 (using the touch screen.) Cannot replicate on desktop using a scroll wheel.

See [playground here](http://playground-leaflet.rhcloud.com/nuh/edit?html,console,output).

**Comment by IvanSanchez** [comment]
Note to self: try to make a test case using prosthetic-hand.

**Comment by delner** [comment]
@IvanSanchez ![hand](https://media.giphy.com/media/7TtvTUMm9mp20/giphy.gif)

**Comment by perliedman** [comment]
What I think happens is that disabling and again enabling the dragging, event handlers switch order.

After dragging is enabled again, a pinch zoom suddenly initializes _both_ a drag and a pinch zoom, which in turn makes the markers use twice the offset, probably once from the drag handler and once from the pinch zoom.

If you do it on desktop with touch support, it becomes even more obvious, since after stopping the pinch zoom, the mouse is still in drag mode, dragging the map around even if no mouse button is pressed.

**Comment by perliedman** [comment]
Some further detail: without the `disable`/`enable` map drag, a drag _only_ touches the `leaflet-map-pane` transform, and a pinch zoom _only_ touches the `leaflet-tile-container` and `svg` element transforms.

After the `disable`/`enable` map drag, a pinch zoom touches the `leaflet-map-pane` transform, the `leaflet-tile-container` and `svg` element transforms, which of course results in a double offset.

**Comment by perliedman** [comment]
Yet another update: the root cause is the order of map handlers, and in turn the order they register event handlers.

I have reproduced the issue _without_ enabling/disabling map drag, by just making sure the `Map.Tap` handler is registered _before_ the drag handler.

When the tap handler is registered before, it catches touch events and turns them into simulated mouse events. These mouse events only have one touch, so the drag handler will interpret them as a drag, even though they are in reality a touch zoom with two touches.

When the handlers are in the opposite order, the drag and/or touch zoom handlers will call `preventDefault` on the events, and they will not be turned into simulated events.

**Comment by yohanboniface** [comment]
Have we been able to bisect this issue?

**Comment by perliedman** [comment]
Haven't tried it, but given that your comments in #3872 more or less exactly describe this issue, it sounds likely it might be the source. Don't have time to do a bisect right now.

**Comment by perliedman** [comment]
1) `L.Draggable` receives a touch event, causing it to initiate a drag
2) `TouchZoom` handler receives two fingers down, causing it to initiate a touch zoom
3) Once the touch zoom is going, `TouchZoom` will prevent any touch events from reaching `Draggable`, it will however not prevent the simulated events (which it doesn't listen to)
4) `Draggable` receives all simulated events, and since it has initiated a drag in step 1, it will continue to interpret them as drag events
5) Draggable will never exit dragging, since it doesn't receive the finger up events, since they're caught by `TouchZoom`.

**Comment by yohanboniface** [comment]
Answering my own question ('why firing both touch and simulated in the same time'):

- we want Leaflet users to be able to just listen for mouse events while having code working also on touch
- we still want advanced users to be able to listen for the original touch events, to have more control when needed
- we can't merge both events in one ('mousemove' with touches sounds too weird, and those advanced users will anyway keep listening on 'touchmove' for example)
- this means that when listening for both mouse and touch events in a same listener, it's better to ignore simulated ones

**Comment by perliedman** [comment]
For now, we'll keep the flag `_simulated` private in simulated events, but consider making it public when/if we get any feedback on anyone using this outside of the Leaflet codebase.

**Comment by patrik-owly** [comment]
This is still a problem on mobile devices (using Chrome or Safari on iOS). Desktop is ok.

**Comment by Miniontoby** [comment]
> This is still a problem on mobile devices (using Chrome or Safari on iOS). Desktop is ok.

Desktop WITH touchscreen is still NOT oke! That is what I meant in my comment.

It is just the touchscreen support that is not working properly
