### ISSUE TITLE
TMS doesn't work with L.CRS.Simple in 1.0

### ISSUE THREAD

**Issue by hyperknot** [Leaflet/Leaflet#4338]
As provided by a user in #4333 using L.CRS.Simple with tms: true results in an exception where `this._globalTileRange` is uninitialised in tileLayer / getTileUrl.
https://github.com/Leaflet/Leaflet/blob/b60e18d5c6c1ceacdcccfc03f184c0afa516607b/src/layer/tile/TileLayer.js#L77

http://playground-leaflet.rhcloud.com/jac/1/edit?html,output

It works untouched in 0.7, but is broken in 1.0

Related issue: https://github.com/Leaflet/Leaflet/issues/2298

cc: @perliedman

**Comment by perliedman** [comment]
The problem is that `L.CRS.Simple` is an so called "infinite" CRS (https://github.com/Leaflet/Leaflet/blob/master/src/geo/crs/CRS.Simple.js#L24), which means it does not have any bounds.

TMS, on the other hand, needs an upper bound for the CRS's Y coordinate, to be able to flip the tile row.

This means that TMS will not work with `L.CRS.Simple` out of the box in 1.0. On the other hand, the only reason it worked in 0.7 was that `L.CRS.Simple` had implicit bounds, and from what I remember a lot of people ran into weird problems because those implicit bounds were rarely the same as the actual limits.

If you want to use TMS and a CRS that resembles `L.CRS.Simple`, you should extend it, set `infinite: false` and give it the bounds you want. This could, of course, be made clearer with a tutorial or some kind of warning in the docs.

**Comment by jieter** [comment]
Regarding #4337, should we not try to replace `{-y}` if `map.crs.infinite === true` to prevent this error ?

**Comment by perliedman** [comment]
@jieter yes, sounds like a good plan. In general it would of course be very nice to provide a better error message than that some internal variable is `undefined`!

**Comment by balciseri** [comment]
Yes at the moment if i reference the master version with the {-y} fix i can't use crs: L.CRS.Simple,
because it will not work.

**Comment by jieter** [comment]
Hang on, working on it...

**Comment by jieter** [comment]
@perliedman Leaflet doesn't seem to do much explaining in error messages. I've added an example of the error produced by a small `L.CRS.Simple`-example to the description of #4344 .
