### ISSUE TITLE
Zoomstart/zoom event / LatLngToContainerPoint not behaving as expected

### ISSUE THREAD

**Issue by alvinsight** [Leaflet/Leaflet#4505]
Hi guys,
Thanks for the great work on Leaflet, it's a very straight-forward library to work on, and very solid too, awesome job.

I'm getting an issue when placing an overlay on top of the map, I'm using `LatLngToContainerPoint` which does its job perfectly until a zoom is involved.

In the test here (http://alvinsight.com/leafletTest/index.html) I"m listening to a few events to overlay a div on the map(relevant file here: http://alvinsight.com/leafletTest/js/LeafletMap.js)  and you can see that the square is in the correct place but when you change the zoom (controls/mousewheel), there's a delay before `LatLngToContainerPoint` adjusts to the correct zoom level.

My guess is that when the `zoom` and `zoomstart`events are fired the `_zoom` property of the the Leaflet Map isn't updated straight away, a quick fix to this would be to add a `zoom` property to the `zoomStart` event, that we can then pass in to the `LatLngToContainerPoint` method.

It's a bit hard to guess but it also looks like there is a slight delay before the `zoomStart` event is fired.

Thank you in advance,
Alvin

**Comment by nathancahill** [comment]
Is there a reason you're not using a Leaflet Rectangle instead of a div? http://leafletjs.com/reference.html#rectangle. It handles all of the transformations.

**Comment by alvinsight** [comment]
Hi,
Thanks for the link, but the div is just for the test, I'm planning to overlay many more things top of the map, it's probably going to be a WebGL canvas in the end, I'm not 100% sure yet.

**Comment by nathancahill** [comment]
In that case, have you looked at TileLayer.Canvas? http://leafletjs.com/reference.html#tilelayer-canvas

**Comment by alvinsight** [comment]
Interesting, thanks, but ideally I'd like to keep the dependency on leaflet to a minimum, do you reckon we found an actual bug?

**Comment by nathancahill** [comment]
My point is that trying to re-create the overlay functionality outside of the Leaflet context is going to be an uphill battle. Better to use the builtin overlays and get all that stuff for free. Timing a independent zoom animation with event hooks just won't be as smooth. So no, I don't think it's a bug. I think not updating the `zoom` property of the map until the transition completes is desired behavior.

**Comment by alvinsight** [comment]
You're right, how about adding a property to the `zoomstart` or `viewreset`events ? According to the documentation it looks like the latter was created for people to build overlays, so it's not something that is completely out of the scope of Leaflet.

**Comment by danzel** [comment]
You could use an ImageOverlay with a canvas? (which has the webgl rendering happening on it)

We don't update the zoom variable during a zoom as it is performed using css transitions.

**Comment by IvanSanchez** [comment]
@danzel @alvinsight No, the right way to put a webgl canvas on top of a map would be to fetch a map pane and `appendChild` the `<canvas>` directly there.

@nathancahill `L.TileLayer.Canvas` is only for 0.7.x and we're trying people to use 1.0.0, remember? :-P

**Comment by IvanSanchez** [comment]
> [...]there's a delay before LatLngToContainerPoint adjusts to the correct zoom level.
> 
> My guess is that when the `zoom` and `zoomstartevents` are fired the `_zoom` property of the the Leaflet Map isn't updated straight away

You're right in the delay - it's done at 
https://github.com/Leaflet/Leaflet/blob/master/src/map/anim/Map.ZoomAnimation.js#L90 to prevent artifacts.

But it's not that simple. Leaflet uses a very clever tricks for the zoom animation - CSS transitions. This means that, if an element is inside a Leaflet map pane, zooming in/out will trigger a CSS transition for the zoom animation, and the position of the element only has to be recalculated when it ends.

There is no (good) programmatic way of fetching the pixel position during a CSS animation - bezier curves are involved, and those cannot be easily read.

So, turning back to the title of the issue: `LatLngToContainerPoint` does behave as expected - but its expected behaviour is to provide a pixel offset from within a container which undergoes a CSS animation during zoom animation, not an absolute pixel offset.

**Comment by IvanSanchez** [comment]
@alvinsight [Getting zoom animations to work smoothly with WebGL is hard](https://github.com/IvanSanchez/Leaflet.gl/blob/master/src/map/anim/Map.GlZoomAnimation.js). And the amount of work involved into making `LatLngToContainerPoint` returning an absolute value is very high, and it might break existing stuff.

**Comment by alvinsight** [comment]
Thanks for the link, I think I understand where the problem is now, how about fixing it like this : 

``` 
map.on('zoom',function(e){
    var inferedZoom = e.inferedZoom;
    var pt = LatLngToContainerPoint([lat,lng], inferedZoom)
}); 
``` 
If we could get an "infered zoom" (i.e what the next zoom level would be after the animation) based on the delta of the mousewheel or the pinch action, it would solve my problem and we would have all we need to create custom layers, whether in WebGL or CSS, SVG, etc.
I'm happy to open another issue as a feature request for this.
Cheers,
Alvin

**Comment by Liu-Eroteme** [comment]
Heya! Stumbled across this just now, it's been closed since forever, but ykw i like yelling into the void

> [@alvinsight](https://github.com/alvinsight) [Getting zoom animations to work smoothly with WebGL is hard](https://github.com/IvanSanchez/Leaflet.gl/blob/master/src/map/anim/Map.GlZoomAnimation.js). And the amount of work involved into making `LatLngToContainerPoint` returning an absolute value is very high, and it might break existing stuff.

I disagree. It took me a day or so, but it's pretty easy. The only thing that makes it difficult is the fact that leaflet does not just give me the zoom pivot on zoomstart events..

> [@danzel](https://github.com/danzel) [@alvinsight](https://github.com/alvinsight) No, the right way to put a webgl canvas on top of a map would be to fetch a map pane and `appendChild` the `<canvas>` directly there.

Bleh - the css transforms mean the canvas either has to be resized once per frame, or the edges aren't gonna draw in until you stop (e.g.) dragging. its annoying.

Here, maybe it helps - [this is my sync overlay](https://gist.github.com/Liu-Eroteme/315f44a2c3347c482a9363a4110a1495)  (leaflet 1.9.4)
