### ISSUE TITLE
v1.0 replacement for L.DomUtil.getTranslateString ?

### ISSUE THREAD

**Issue by jywarren** [Leaflet/Leaflet#4517]
Hi, sorry if I'm just not looking in the right place, but trying to make [Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage/) compatbile with the Leaflet 1.0 API, and I can't find the recommended way to deprecate a dependency on the method `L.DomUtil.getTranslateString`.

We're tracking the compatibility here: https://github.com/publiclab/Leaflet.DistortableImage/issues/64

We use `L.DomUtil.getTranslateString` on just two lines, seems pretty simple:

1. https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/DistortableImageOverlay.js#L135
2. https://github.com/publiclab/Leaflet.DistortableImage/blob/master/src/DistortableImageOverlay.js#L162

I've searched the repository itself, and [both sets of docs](http://leafletjs.com/reference.html) (0.7 and 1.0), but wasn't able to figure out the new way to get this information. 

Grateful for any hints, and happy to help contribute a deprecation notice and pointer where appropriate!

**Comment by IvanSanchez** [comment]
So the original definition of `getTranslateString` is at https://github.com/Leaflet/Leaflet/blob/stable/src/dom/DomUtil.js#L189 in the `stable` branch.

Right now `L.DomUtil.setTransform` does that job - but instead of returning a string, it assigns it to the `transform` CSS property of the element, too.

I guess you can copy-paste that code, or create something like a `L.DomUtil.setTransformWarp()` function.

**Comment by jywarren** [comment]
Excellent, thanks!
