### ISSUE TITLE
fitBounds with padding zooms the map really far out

### ISSUE THREAD

**Issue by theashyster** [Leaflet/Leaflet#4528]
I am not sure if this is a regression or not, but I have experienced that since the RC1 release the map `fitBounds` function with `padding` option does not work the same way as it worked before.

Some examples:
Leaflet 0.7.5 http://playground-leaflet.rhcloud.com/niv/edit?html,output
Leaflet 1.0.0-beta.2 http://playground-leaflet.rhcloud.com/jasi/edit?html,output
Leaflet 1.0.0-rc.1 http://playground-leaflet.rhcloud.com/cipe/edit?html,output

The padding is just really big and the map is zoomed far out. We have used this function with the padding on layer containing SVG polygon also and since RC1 that also started to act strange by zooming the map really far out.

I can get the same result on RC1 by setting the `padding` option on a point that is really small `L.point(0.001, 0.001)`.

**Comment by jieter** [comment]
Sounds like a perfect chance for a simple unit test and some git bisecting...

**Comment by IvanSanchez** [comment]
The culprit seems to be [this line](https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L509):

```
boundsSize = this.project(se, zoom).subtract(this.project(nw, zoom)).add(padding),
```

That's getting the size (in pixels) of the bounds to fit, **at the current zoom level**, *then* adding the padding.

What we really want is to have the padding at the *destination* zoom level, not at the *original* zoom level.

**Comment by IvanSanchez** [comment]
A possible solution would be to subtract `padding` from `size` - but that needs testing.

I think this is a rather self-contained, explained bug, so I think any newbie can try fixing this. (Hello, @yourfirstpr!).

Things to be done:

* [ ] Let people know you're interested
* [ ] Fork the leaflet repo and clone it locally
* [ ] Modify `src/map/Map.js` around line 509 so that `padding` is subtracted from `size` (instead of being added to `boundsSize`)
* [ ] Add some unit tests to `spec/map/MapSpec.js`, next to the tests for `getBounds()` - ensure that calls to `getBoundsZoom()` with small areas and big padding returns high levels of zoom (currently it returns low levels like 0 and 1)
* [ ] Run `npm install`, `npm test`
* [ ] `git commit`, `git push`
* [ ] Create merge request

**Comment by Charlotteis** [comment]
:wave: Thanks so much for another wonderful guide, @IvanSanchez! Will post this out to @yourfirstpr shortly :)

**Comment by theashyster** [comment]
@IvanSanchez Looks like this is related then https://github.com/Leaflet/Leaflet/issues/4172

**Comment by theashyster** [comment]
Tried subtract `padding` from `size` and not adding `padding` to `boundsSize` and it seems to have helped with this case.

**Comment by dianjin** [comment]
I would love to do this! Thanks for the guide, I'll follow it and let you know my results. 😄

**Comment by hyperknot** [comment]
I'd just like to add to the list:
- [ ] test it with the default zoomSnap: 1 option
- [ ] test it with a fractional zoomSnap, like 0.25
- [ ] test it with zoomSnap: false or 0

For development of fitBounds I believe the best is to use zoomSnap: 0, as snapping to an integer zoom level will usually add a big padding on it's own.

**Comment by dianjin** [comment]
Here's what I have so far: https://github.com/Leaflet/Leaflet/pull/4532

Please let me know if I did everything correctly!

**Comment by hyperknot** [comment]
@dianjin code looks good for me, wrote a comment about the test. Feel free to tick the completed checkboxes on this page.

**Comment by IvanSanchez** [comment]
Closed via #4532

**Comment by theashyster** [comment]
Thanks again for fixing the issue :+1:

**Comment by eldamsheety** [comment]
how could I start joining an open source here?

**Comment by aalsiuser** [comment]
As Iam new to open source community so how can i help you in contributing over here?

**Comment by qwertypool** [comment]
hello, how may i join and start contributing to this open source ??

**Comment by qwertypool** [comment]
hello, how can i just start contributing to this project??

**Comment by ghybs** [comment]
Hi @eldamsheety, @aalsiuser and @qwertypool,

Thank you for your interest in Leaflet!
Sorry for not getting back to you earlier.

There are many ways of [contributing to this project](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md), and to [Open](https://opensource.guide/how-to-contribute/) [Source](https://github.com/freeCodeCamp/how-to-contribute-to-open-source) [projects](http://www.firsttimersonly.com/) [in](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github) [general](https://code.energy/open-source-contributing/).

This thread is already closed, since the bug it describes has already been fixed in PR #4532.
Avoid commenting on closed threads, as you may remain unnoticed, unless what you have to say is absolutely relevant to the thread (e.g. when the bug is actually not fixed). And even in that case, it is probably better opening a new issue and mentioning the closed thread.

As for contributing, you could have a look at threads with label "[help wanted](https://github.com/Leaflet/Leaflet/labels/help%20wanted)" and/or "[good first issue](https://github.com/Leaflet/Leaflet/labels/good%20first%20issue)".

Keep up the good work and feel free to ask! 😄

**Comment by Reshwanth** [comment]
Hi I am new to this open source community projects. So, how can i start contributing in the projects?

**Comment by angelhen2020** [comment]
👾 I would like to contribute !

**Comment by SAG17hande** [comment]
Hi I am new to this open source community projects. So, how can i start contributing in the projects, how can i learn as well as contribute ?

**Comment by ugofine** [comment]
I am new here, will like to contribute.

**Comment by ibrogenius** [comment]
I guess I'm late to the party... I'm new to the open source community and how do i contribute

**Comment by akshat-max** [comment]
I'm new to the open-source community and how can I contribute.

**Comment by yakim228** [comment]
Hi, I would like to contribute to the open-source community, how can i get started ?

**Comment by ghybs** [comment]
Hi @johnd0e,

I am taking the liberty to draw your attention on this closed thread, which seems to be for some reason the landing page of potential new contributors.

Please what kind of entry point do you think could be more appropriate, so that newcomers can receive better information?

They may also be interested in the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) event, which you can leverage by tagging issues that you would like contributors to work on with a new "hacktoberfest" label, and tagging meaningful Pull Requests with a new "hacktoberfest-accepted" label (see https://hacktoberfest.digitalocean.com/details#rules).

I hope this can be helpful somehow!

**Comment by IvanSanchez** [comment]
The point of entry *should* be https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md . Maybe there's a need to rewrite parts of that.

Regarding the hacktoberfest thing, I've read that it has spawned [vandalism](https://twitter.com/shitoberfest), so I'm kinda against that.

**Comment by johnd0e** [comment]
Hi @ghybs.
I am not sure why you address me personally, but anywhere I agree with @IvanSanchez.

> this closed thread, which seems to be for some reason the landing page of potential new contributors.

And I really doubt that these strange people are really able to be useful for Leaflet.

**Comment by IvanSanchez** [comment]
The reason people are coming to this issue is probably the link from https://opensource.guide/how-to-contribute/ . This (at least the first few comments) is a good example of how a (good-ish) bug report looks like.

So, to any lost souls coming here: if you want to do something with Leaflet *specifically*, read https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md , see the list of open bugs, go fix something. For general stuff about FLOSS, go read https://www.gnu.org/philosophy/floss-and-foss.en.html and https://opensource.org/resources and the parts of the https://opensource.guide/ thing that you skipped. *Read*.

I'm locking the issue to prevent any further comments from newbies.
