### ISSUE TITLE
fixed position div modal for map div

### ISSUE THREAD

**Issue by azimot** [Leaflet/Leaflet#4551]
how to fix map position in fixed position parents ?  https://jsfiddle.net/hpfe07yy/ 
if you a little drag result panel (panel of fiddle) and you see map will be correct but without trick not correct

**Comment by perliedman** [comment]
That fiddle doesn't load Leaflet, because of https issues. Try [Leaflet Playground](http://playground-leaflet.rhcloud.com/), it's a bit easier to work with for this reason among others.

From the looks of it, you need to call `map.invalidateSize()` after the map becomes visible, since its size has changed.

Also, please note that this is not a support forum, you should only report issues and feature requests here. You're better off asking questions of Stackoverflow or gis.stackexchange.com.
