### ISSUE TITLE
GeoJson,Polygons, Fitbounds and the Dateline

### ISSUE THREAD

**Issue by jonturgeon** [Leaflet/Leaflet#4584]
Hi all, been searching around here and there seem to be several closed issues regarding polygons and the dateline but I am still seeing this problem.I am loading state/country borders and am running into issue with Fiji. I am loading these polygons using geoJson and relying on fitbounds to locate and scale the map. For the other 18 countries I display this works great, Fiji displays the entire world. Is there any way to get this to display correctly? Below is a snippet of the code I use

`		var geojson = L.geoJson(borders, {
			style: function (feature) { return feature.properties && feature.properties.style; },
			url: function (feature) { feature.properties.url },
			onEachFeature: onEachStateFeature
		});

		var map = L.map('map', { zoomControl:false }).fitBounds(geojson.getBounds());
		map.dragging.disable();
		map.touchZoom.disable();
		map.doubleClickZoom.disable();
		map.scrollWheelZoom.disable();
		map.keyboard.disable();
		
		tileLayer.addTo(map);
		var bordersLayer = geojson.addTo(map);
		map.fitBounds(geojson.getBounds());`

Thanks for any help

**Comment by yohanboniface** [comment]
Dateline management is a [tricky one](#1293).
Depending on what you do with the data, one workaround may be to have a "continuous world longitude", thus bumping Fidgi's longitude above 180° (i.e. 180.505 instead of 0.505 in short).

I'm closing here, please use preferably stackoverflow or gis.stackexchange for help support.
