### ISSUE TITLE
Calling circle and then getDiameter causes an exception

### ISSUE THREAD

**Issue by NRaf** [Leaflet/Leaflet#4629]
The following code breaks in In 1.0.0-rc1 (was working in the latest stable version):

`var circle = L.circle([-37.814, 144.963], 10000);
circle.getBounds();`

This throws an exception: `Uncaught TypeError: Cannot read property 'layerPointToLatLng' of undefined`

The getBounds function is defined as:

```javascript
       getBounds: function () {
		var half = [this._radius, this._radiusY || this._radius];

		return new L.LatLngBounds(
			this._map.layerPointToLatLng(this._point.subtract(half)),
			this._map.layerPointToLatLng(this._point.add(half)));
	},
```

`this._map` is undefined here because the circle hasn't been added to the map.

Looking at the source for 0.7.7, the code is as follows (with no reference to `this._map`):

```javascript
	getBounds: function () {
		var lngRadius = this._getLngRadius(),
		    latRadius = (this._mRadius / 40075017) * 360,
		    latlng = this._latlng;

		return new L.LatLngBounds(
		        [latlng.lat - latRadius, latlng.lng - lngRadius],
		        [latlng.lat + latRadius, latlng.lng + lngRadius]);
	},
```

**Comment by perliedman** [comment]
The old version was hardcoded against the default CRS and the earth's lat/lng system. In 1.0.0, it uses the map's CRS instead, and will always produce the correct bounds for the selected CRS. This of course has the side effect that it also needs a reference to the current map instance, since there's no way to know the CRS otherwise.

In other words, this is as intended.

**Comment by bassena** [comment]
So, I'm getting a similar issue. I'm using `L.circle` in conjunction with `L.featureGroup`. Should the created `L.circle` object be added to the map _before_ it gets passed to the initialization of `L.featureGroup` (which then in turn gets added to the map) ? I hope this makes sense.

**Comment by bassena** [comment]
Actually, it seems that I still get that error even if I add the circle to the map before calling `L.featureGroup`.

**Comment by perliedman** [comment]
@bassena can you specify more exactly what problem you're running into? Ideally a runnable example to illustrate the problem.

**Comment by bassena** [comment]
@perliedman , sorry for the very belated reply. In coming up with a JSFiddle for you, I happened to pinpoint my issue. It related to not having called `setView()` initially on my map object. Go figure. We've been using an older version of leaflet (which we did not have this issue before), but now after updating the library this issue came about.
