### ISSUE TITLE
Touch-zoom is broken after #4669 has been merged

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet#4702]
Just tried master branch on my touch screen. Tiles don't update when you touch-zoom.
It is due to a recent fix:
https://github.com/Leaflet/Leaflet/pull/4669
and this commit in particular
https://github.com/Leaflet/Leaflet/commit/87e38f1aa4e03ca42912be8adf22610ccb02f258
tileZoomChanged is false during touch-zoom as tileZoom is a discrete level, so 
```javascript
(tileZoom !== this._tileZoom)
```
is false in most cases, unless you zoom in a lot and actually change zoom level

Fix is to remove this test, but I am not sure why it was added in the first place

**Comment by yohanboniface** [comment]
I see two options (but I may be missing some other):

- test for real zoom changed instead (but that would also means duplicate the check for `minZoom`/`maxZoom` and `updateWhenZooming`)
- go back to the initial commit of the PR https://github.com/Leaflet/Leaflet/pull/4669/commits/1a8a30cc82541af8847cd2ce06959aad539e9b86 : that would be my preference actually, because in the first place I'm don't get why we would want to reset the view after moving the map (given that _update already takes care of loading new tiles, and thus of pruning tiles).

**Comment by fnicollet** [comment]
I would vote for the second option
