### ISSUE TITLE
Tooltip offset not moving the labels in the right direction?

### ISSUE THREAD

**Issue by junyian** [Leaflet/Leaflet#4772]
Positive numbers for x-axis moves the label towards the left, while negative numbers moves it to the right. I'm not sure if this is how this is designed though, couldn't find much references for this.
But for y-axis, the label doesn't move at all in any direction.

Sample code:
<code>
var lc = L.latLng(51.505, -0.09);

var map = L.map(document.getElementById('mapid'), {
	renderer: L.canvas()
});

var osm = new L.TileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png',
	{ attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a>' }).addTo(map)

map.setView(lc, 14);

var featureGroup = new L.FeatureGroup()
featureGroup.addTo(map)

var c = L.circle([lc.lat, lc.lng], { radius: 500 })
c.addTo(featureGroup)
c.bindTooltip('test', { permanent: true, offset: L.point({x: -80, y: 80}) })
</code>

**Comment by yohanboniface** [comment]
This is by design.
The `offset` option is only taken into account for the tooltip in the `direction` axis, while the `tooltipAnchor` option is used to position the tooltip relatively to the Marker icon (mainly if you are using a custom one).
See http://leafletjs.com/reference-1.0.0.html#tooltip
Here is a playground with circlemarkers: http://playground-leaflet.rhcloud.com/lag/edit?html,output

What is your need exactly?

**Comment by junyian** [comment]
Right... so this somewhat explains the relationship between the offset and direction.
I was actually trying to place the labels at a certain angle, for example 30 degrees from the North of the circle.

**Comment by yohanboniface** [comment]
@junyian hold on, I'm working on a way to have offset [0, 0] by default, and always honored on both directions.

**Comment by yohanboniface** [comment]
@junyian see https://github.com/Leaflet/Leaflet/pull/4773
