### ISSUE TITLE
Vector Renderer support for end markers.

### ISSUE THREAD

**Issue by SuberFu** [Leaflet/Leaflet#4804]
Is there plan to support setting SVG's marker-start, marker-end, marker-mid properties?
http://vanseodesign.com/web-design/svg-markers/
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker

It would make creating simple arrows easier, and potentially with better performance than creating a separate layer for the arrow heads.

I'm guessing this should be done inside the SVG/Canvas renderer (since L.SVG handles the actual SVG element generation and Canvas handles the actual drawing), plus some properties on the L.Path class to define the marker-start, marker-end and marker-mid.

P.S. Is now a good time to introduce new feature? Or should I wait until 1.0.0 is out of RC?

**Comment by IvanSanchez** [comment]
> Is there plan to support setting SVG's marker-start, marker-end, marker-mid properties?

No, because any change to a renderer should be applied to both renderers. So, if `L.SVG` would support end markers, then `L.Canvas` should support them too, and coding that would get quite messy (parsing the attributes, recreating the rendered shapes, etc etc).

Besides, there are [plugins](http://leafletjs.com/plugins.html#markers--renderers) to fill that feature niche, like e.g. https://github.com/makinacorpus/Leaflet.LineExtremities

If you can create a plugin which supports these features for both renderers, we'll be happy to have a deeper look.

> P.S. Is now a good time to introduce new feature? Or should I wait until 1.0.0 is out of RC?

Non-critical features will be pushed into a later milestone: https://github.com/Leaflet/Leaflet/milestone/28
