### ISSUE TITLE
z-index of popup is below controls

### ISSUE THREAD

**Issue by mhines-usgs** [Leaflet/Leaflet#4811]
On a mobile device-sized leaflet map, the zoom/legend and layer switcher controls are above the pop-up. It's difficult to read without awkward dragging. Can this be adjusted? It doesn't seem like any amount of shifting z-index values makes any difference.

**Comment by IvanSanchez** [comment]
This is a feature, not a bug - controls should be visible regardless of map contents. And this cannot be changed due to the controls and the layers belonging to different separate [stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) internally.

Other solutions like temporarily removing the controls, or overlaying full-screen block elements instead of using popups, are available.

**Comment by pmacMaps** [comment]
I've implemented a solution where on the open event for a pop-up, I set the opacity for the map controls to 0, and then change it back to 1 on the popup's close event.  While this works decently, I've encountered a quirk when adding a layer control to the map.

If you close the popup, and the close button is located on the hidden layer control, the basemap changes or a layer is toggled, because of the z-index issue.  This does not seem like the expected behavior to the user, but makes sense because of the z-index issue.

I personally believe a map would function better on smaller screen sizes if the pop-up would be above the map controls.  It's a design issue, and it appears the maintainers of Leaflet have decided in a different direction.

**Comment by joomlafun** [comment]
I've implemented a solution where on the open event for a pop-up, I set the opacity for the map controls to 0, and then change it back to 1 on the popup's close event. While this works decently, I've encountered a quirk when adding a layer control to the map.

Hi, could you share this code please?

**Comment by pmacMaps** [comment]
@joomlafun, within the `onEachFeature` function of the GeoJSON data-type, you can use the code below.  You could substitue `windowArea` for just a window width variable.

Window Area Code:
```javascript
const windowWidth = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
const windowHeight = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
const windowArea = windowWidth * windowHeight;
```

```javascript
onEachFeature: function(feature, layer) {
        // leaflet-top elements
        const leafletTopElements = document.querySelectorAll('div.leaflet-top');
        // leaflet-bottom elements
        const leafletBottomElements = document.querySelectorAll('div.leaflet-bottom');

        // Pop-up control for small screen sizes
        if (windowArea < 315000 ) {
            // Hide leaflet controls when pop-up opens
            layer.on('popupopen', function() {
                leafletTopElements.forEach(function(element) {
                    element.style.opacity = 0;
                });

                leafletBottomElements.forEach(function(element) {
                    element.style.opacity = 0;
                });                               
            });            
            // Display Leaflet controls when pop-up closes
            layer.on('popupclose', function() {
                leafletTopElements.forEach(function(element) {
                    element.style.opacity = 1;
                });

                leafletBottomElements.forEach(function(element) {
                    element.style.opacity = 1;
                });                              
            });
     }
}

**Comment by joomlafun** [comment]
Thanks a lot sharing Patrick.

**Comment by Zerquix18** [comment]
This is very annoying for mobile users.

**Comment by stovefix** [comment]
I've been using element.style.display = "none" and "block" (instead of opacity 0 and 1) in pmacMaps' code above. Then you can't accidently click on the layers icon.

But I wish it could go on top of those icons.

**Comment by vincerubinetti** [comment]
This shows why CSS and HTML architecture is so important. It's always just styling/aesthetics, it can actually prevent features.

>This is a feature, not a bug - controls should be visible regardless of map contents

It should be designed in such a way that the developer can easily choose what is most important and should be shown on top.

Here's my CSS to to hiding hack. It includes giving the controls a fade out animation to hopefully make it more clear to the user why it's happening, and making them unclickable at opacity 0 so it wont block interaction with the underlying map.

```css
.leaflet-control {
  transition: opacity 1s;
}

.leaflet-container:has(.leaflet-popup)
  :is(.leaflet-control-container, .leaflet-control-container *) {
  pointer-events: none;
}

.leaflet-container:has(.leaflet-popup) .leaflet-control {
  opacity: 0;
}
```

The technical debt and decisions here is disappointing. I'll be switching to Open Layers at my earliest convenience.

**Comment by sascha-meissner** [comment]
Thank you [vincerubinetti](https://github.com/vincerubinetti) i really like this
