### ISSUE TITLE
ImageOverlay makes chrome freeze for a while

### ISSUE THREAD

**Issue by Arrowana** [Leaflet/Leaflet#4821]
I use leaflet to navigate over an jpg with zoom capabilities
I have a large jpg 11000x8000. When the imageOverlay is added to the map, the window is frozen for more than 10 secs.

I am fine with this loading time, I tried to attach a load event on imageOverlay but it is triggered way before the browser becomes usable again.

So I wonder if something is not right with this load event fired too early or if this is only because my overlay is way too big.

**Comment by IvanSanchez** [comment]
An image that size will take some time to be decoded and shown **anyway**, even without Leaflet. And it's an operation that involves inserting nodes in the DOM, which means the main thread, which means I really doubt it can be improved by using tricks like web workers and the such.

And even in that case, we would be facing CORS issues now and then from users which don't read the docs :-/

I'm not sure this can be fixed in a clean way. If you have some idea on how to load images off the main thread and then push the data into the DOM faster (off-screen canvas rendering??), I guess the way to go would be to make a plugin to change the behaviour of `L.ImageOverlay` and see how well it performs.

> …attach a `load` event on `imageOverlay` but it is triggered way before the browser becomes usable again.

Well, the `load` event means that the image [has been loaded](https://developer.mozilla.org/en-US/docs/Web/Events/load), not that the main UI thread is not locked anymore, right? Besides loading the image, the browser has to do some decoding and uploading the image to the GPU and compositing.

I do suggest you run the performance tools in your browser (e.g. https://developer.mozilla.org/en-US/docs/Tools/Performance ), and see what is exactly blocking the UI thread.

**Comment by IvanSanchez** [comment]
@Arrowana It would also be nice if you could provide a sample image for debugging.

**Comment by mourner** [comment]
I think we can't do anything about this on the Leaflet side — it's a browser limitation. For such a huge image, I would recommend slicing it into tiles.
