### ISSUE TITLE
'moveend' event handlers can be removed by a previous handler and throw an error

### ISSUE THREAD

**Issue by joongtang** [Leaflet/Leaflet#4833]
Reproduce the issue

1. Go to url https://jsfiddle.net/joongtang/zr0qxq8g/
2. Zoom out from level 10 to level 8 at once
3. View console tab.
4. Shown error message : "Uncaught TypeError: Cannot read property 'fn' of undefined"

Reproducible using Leaflet-1.0.0-rc3

**Comment by IvanSanchez** [comment]
Somehow I think that one of the event handlers is being removed by another event handler, and the `L.Evented.fire()` code doesn't check for that.

**Comment by perliedman** [comment]
I think this happens when an object listens to its own event (A), and in turn fires another event (B) inside the listener.

In that scenario, firing event A will set `this._isFiring = true`. When the event listener for A fires event B, `_isFiring` is still `true`, but when the firing finishes, it _resets_ `_isFiring` to `false`, even though it's still firing event A.

A fix should be to not use a boolean for `_isFiring`, but rather a counter, so that recursive firing is supported.
