### ISSUE TITLE
Distance Calculations and projection correction when used with polygons and circles.

### ISSUE THREAD

**Issue by danmatthews** [Leaflet/Leaflet#4917]
We have a "drop this item within a certain radius" feature in our app.

For example, we try to illustrate how far away from the center point the user can drop something using an `L.circle` instance, with a radius of `x` meters. So if a user can drop something within 100km:

![screen shot 2016-09-15 at 16 31 07](https://cloud.githubusercontent.com/assets/149426/18556014/e9286db6-7b61-11e6-9d26-9d691ff0bedb.png)

The problem is that when we use the `click` event from the map to obtain the `LatLng` of where the user has clicked, then use the `distanceTo` method to determine if the user has clicked within an appropriate distance - the result sometimes does not reflect the illustrated distance shown with the circle.

Demo: http://jsbin.com/falewuqusi/1/edit?html,css,js,output

Try the demo to see what i mean: click anywhere near the edge of the circle in the bottom-right quadrant of the circle itself. It's almost like there's a shifted margin for error.

This works to the opposite if clicking in the top-right quadrant - you can click a certain distance outside the circle and it still registers as a distance measurement within the limit.

I understand this is something to do with the projection and how the circle's radius is altered to adjust for the projection, but does the distance calculation not take into account the same information?

Can someone please let me know if this is a bug, or if there is something i can do to make the distance calculation account for this difference.

PS: Using `contains` on the circle's bounds also yields false positives for some reason.

Thanks Guys.

**Comment by IvanSanchez** [comment]
> the user can drop something using an `L.circle` instance, with a radius of `x` meters.

Well, here's the thing: map projections are hard. The earth is round, not even a perfect sphere. And a circle in the default map projection will **not** cover all the points which are at less than a given (geodetic) distance to a given point.

When you draw a circle in the surface of the geoid, and project that into a cylindrical projection, the result looks closely like a circle but is not, and the deformation is more evident the closer to a pole you are, see for example https://gist.github.com/jsanz/4564f98c197106432f1b8bf8c9d0230e

This is pretty much in line with the fact that [straight lines on a geoid are not straight lines on a cylindrical projection](https://github.com/henrythasler/Leaflet.Geodesic).

> but does the distance calculation not take into account the same information?

Nope. `L.Circle` = circles in the map's CRS. `distanceTo` = haversine formula.

I guess you want to learn to do geodesy right (hint: it's hard). If you need proper calculations, rely on `geographiclib`. You might want to do like Leaflet.Geodesic and make your "circles" out of a lot of points calculated via a geodetic formula, instead of assuming that cartesian distance works.

**Comment by danmatthews** [comment]
Thanks for the answer @IvanSanchez - i can imagine the circle calculated with a lot of points will be a nightmare for performance.

As a workaround - one that might not be accurate, but would provide the effect i'm looking for, could i just attach the click handler to the circle?

**Comment by IvanSanchez** [comment]
> I can imagine the circle calculated with a lot of points will be a nightmare for performance

Every computer nowadays has half a dozen cores, and won't even care about a few thousand floating point operations. Unless you're making loads of buffers, you should at least try. If the points and radiuses are known, then calculate all the things server-side once.

The solution is up to you. You'll have to decide whether you want precise but computationally heavy algorithms, or cheap&dirty.

**Comment by ghybs** [comment]
@danmatthews You would probably be interested in [leaflet-geodesy](https://github.com/mapbox/leaflet-geodesy) plugin.

A nice page that compares Leaflet-geodesy with the standard L.Circle: https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-geodesy/

See also: https://stackoverflow.com/questions/33526678/how-to-draw-tissots-ellipse-tissots-indicatrix-in-leaflet/33538895#33538895

**Comment by IvanSanchez** [comment]
Why is @mapbox's leaflet-geodesy plugin **not** in the plugins registry?
