### ISSUE TITLE
Issue with scroller bar + rtl + chome on windows 10

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#4922]
I'm creating a legend much like the following: http://map.hotosm.org/ but using angular etc.
I'm using a sidebar for that to host it.
When the direction is ltr everything is working as expected.
but when I change the direction to rtl (of the entire document) and there is a scroller bar on the div where a map is (a map that is not full screen). the map is shifted by the size of the scroll bar.

workaround: make the scroll appear on the right hand side always by setting direction=ltr on the parent element where the scroll appears and setting dir=rtl on the child element to adjust the direction to the wanted one.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by HarelM** [comment]
Do you have something I can clone and manipulate?

**Comment by HarelM** [comment]
https://playground-leaflet.rhcloud.com/vudi/edit?html,css,output
Chrome on windows 10.
Does not manifest on firefox.
When the scroll bar is not visible or the scroll bar is in the right hand side (removing the dir attribute) does not manifest.
Please let me know if you need anything else.
BTW I love this library and I feel it's my duty to make an effort and reproduce this issue for you guys, keep up the good work :-)

Also note that the link above to playground is somewhat broken - when selecting the leaflet library from the navigation menu nothing happens - I needed to copy the links from the documentation...

**Comment by Malvoz** [comment]
> https://playground-leaflet.rhcloud.com/vudi/edit?html,css,output

That link has stopped working.

@HarelM do you think you could provide a new fiddle/codepen/playground? Or are you otherwise able to reproduce on http://map.hotosm.org/? Which element exactly is overflowing to reproduce the issue?

**Comment by HarelM** [comment]
No, sorry, I'm not using leaflet anymore...

**Comment by Malvoz** [comment]
Okay, well, the issue was either a browser bug or the expected behavior of scrollbars pushing content.

If anyone encountered the issue reported here; there are ways to manipulate scrollbars such as CSS [`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter), `overflow`, the non-standard [`overflow: overlay`](https://caniuse.com/css-overflow-overlay) and `:-webkit-scrollbar`. And I don't think scrollbars on the leaflet-container itself is ever desired, if that was the case.

I think it's reasonable to close this issue now.
