### ISSUE TITLE
Speed improvement by using "passive" event handlers

### ISSUE THREAD

**Issue by fbonzon** [Leaflet/Leaflet#5004]
Background: https://blog.chromium.org/2016/05/new-apis-to-help-developers-improve.html

When inspecting a simple Leaflet 1.0.1 map (from the [Leaflet Quick Start Guide](http://leafletjs.com/examples/quick-start/)) on my Android 6.0 phone with USB debugging on Chrome on my desktop machine, I see repeated entries of this warning in the Console:

> Handling of 'touchmove' input event was delayed for … ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.

Is there any code in Leaflet that prevents a scroll to happen, and if not could we declare the touchmove event listeners (and maybe others) as passive ?

**Comment by IvanSanchez** [comment]
From https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md (linked from that blog post):

> **By marking a touch or wheel listener as passive, the developer is promising the handler won't call `preventDefault` to disable scrolling.**

Fact is, Leaflet **does** call `preventDefault` whenever a touch drag happens: it needs to prevent the browser's behaviour (scrolling or zooming the whole page) in order to do stuff on the map (pan it or zoom it).

While *theoretically* it should be possible to use some clever `overflow` properties in the map container to allow touch-capable browsers to pan it around, it would be very finicky and prone to misbehaviours across different browsers (and then there would be the question of how to attach that to two-finger touch gestures and prevent things like https://github.com/Leaflet/Leaflet/issues/3798 from happening).

> Is there any code in Leaflet that prevents a scroll to happen

Yes, and in a few critical places: https://github.com/Leaflet/Leaflet/search?q=preventdefault

**Comment by sandstrom** [comment]
I have [asked the Chrome team](https://bugs.chromium.org/p/chromium/issues/detail?id=489802#c42) to consider removing the warning if passive is explicitly set.

**Comment by dtapuska** [comment]
FWIW... Chrome supports pointerevents so I believe new versions of leaflet detect that and should use that code path instead of touchstart/touchmove.

**Comment by vinayakkulkarni** [comment]
Just did a Lighthouse scan:

<img width="848" alt="screen shot 2018-07-04 at 5 14 00 pm" src="https://user-images.githubusercontent.com/19776877/42275370-b0da1430-7fad-11e8-83a3-0c657a15eb8a.png">

https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

**Comment by vinayakkulkarni** [comment]
https://github.com/Leaflet/Leaflet/blob/95b34edbbad10f58b6ae90e0915e614166c87a4f/src/dom/DomEvent.DoubleTap.js#L62

```diff
- obj.addEventListener(_touchstart, onTouchStart, false);
+ obj.addEventListener(_touchstart, onTouchStart, {passive: true});
```

Is this correct?

**Comment by laoneo** [comment]
@vinayakkulkarni perhaps you should open a pull request to get more attention. I do still have that issue with the latest version of leaflet.

**Comment by Ivan-Perez** [comment]
Is it possible to disable this behaviour (passive events)? I think it's breaking some of the functionality of my app. Just to check whether this is the cause or not.
