### ISSUE TITLE
Calling fitBounds with a keepInView: true popup present can cause Leaflet to lock up

### ISSUE THREAD

**Issue by grantHarris** [Leaflet/Leaflet#5035]
## How to reproduce
- Leaflet version I'm using: 1.0.1
- Browser (with version) I'm using: Chrome Version 53.0.2785.143 (64-bit)
- OS/Platform (with version) I'm using: macOS Sierra
## What behaviour I'm expecting and which behaviour I'm seeing

If you have a popup present on your map with its keepInView option set to true and then call fitBounds on a range outside of the current view, Leaflet locks up. Effectively the two 'fight'. Pan operations called by the leaflet events cause the stack to blow up (Console displays Uncaught RangeError: Maximum call stack size exceeded). In my experience this often totally locks up my browser requiring me to kill the process.

I'm willing to submit a PR for this, but I'm unsure of the correct behaviour in this case. Which one should 'win'? KeepInView or fitBounds?  Some possible approaches:
- Have keepInView win. Make fitBounds do a no-op if popup would be outside bounds.
- Extend fitBounds bounds to include the popup.
- Ignore the keepInView flag in such a situation.
- Throw an error.

Thoughts?
## Minimal example reproducing the issue

http://jsfiddle.net/granth/L4du3L4j/

This example creates a popup with keepInView: true, then triggers a setTimeout after 5 seconds that calls fitBounds with a bounds far away from the popup location.

**Comment by grantHarris** [comment]
Anyone?

**Comment by omeysalvi** [comment]
I have the exact same issue. Any luck?

**Comment by IvanSanchez** [comment]
@grantHarris I haven't looked at this problem, but it seems to me that the saner solution would be to expand the bounds as to include the popup somehow. I'd certainly like to see a PR for this :smile:

**Comment by rbavery** [comment]
I have the same issue as well!

**Comment by mikaelmeulle** [comment]
same issue too

**Comment by forger** [comment]
I have a similar issue with Leaflet freezing up (due to an overflowing stack) when minimizing / reducing the map to a size that doesn't fit an open keepInView popup.

It seems to me that the priority of these features needs to be negotiated. In my (resizing) scenario for example the solution "Have keepInView win" that @grantHarris suggested could be interpreted as "don't allow the map size to be reduced beyond the size of an open keepInView popup" which is not acceptable widget behaviour IMHO.

**Comment by HamidOsouli** [comment]
Same issue here, any found solution yet ?

**Comment by Quanda** [comment]
+1 Same issue

**Comment by Quanda** [comment]
I was able to solve this by attaching `onpopupopen` and `onpopupclose` event listeners and respectively disabling/enabling the maps maxBounds property. In my case I am using React, and I use refs to target the map instance and it's `setMaxBounds` method.

`onpopupopen={() => mapRef.current && mapRef.current.leafletElement.setMaxBounds(null)}`
`onpopupclose={() => mapRef.current && mapRef.current.leafletElement.setMaxBounds(maxBoundsUsa)}`

**Comment by lapo-luchini** [comment]
I have a bug related to this… this code does not fire `popupopen` event:

```JavaScript
new Popup(opt).setLatLng(pos).setContent(popup).openOn(state.map);
```

While clicking on rectangles created with `rect.bindPopup(html, opt)` _does_ call the event.

Here I'm first clicking on a rectangle (the events are shown) and then call the "new Popup" code… and it crashes without the event being triggered.

![image](https://user-images.githubusercontent.com/420454/107623526-be911380-6c59-11eb-8fb9-4d8ac0ef91e0.png)

**Comment by lapo-luchini** [comment]
…turns out the stack overflow is not caused by the `keepInView:true` on the popup, but on the (implicit) `autoPan` which happens before the popup even opens, so it is right that the event didn't fire yet.

And it also happens if I disable maxBounds beforehand. 🤔
Seems like a related but different bug.

Right now I'm trying this kind of work-around and it seems to work (but I don't like it too much… is it possible to call a function at the end of a specific animation instead of binding a generic event like this?)

```JavaScript
state.map.on('moveend', () => {
    state.map.off('moveend');
    opt.autoPan = false;
    new Popup(opt).setLatLng(pos).setContent(popup).openOn(state.map);
});
state.map.panTo(pos, { animate: true });
```

**Comment by lapo-luchini** [comment]
Fork of original poster's minimal test case, but based on "open a remote popup" (without any `maxBounds`) instead of "force remote maxBounds":
http://jsfiddle.net/lapo/wxfjcu6y/

**Comment by varadero** [comment]
Something similar just happened to me but I cannot reproduce it. What my app does is to add markers with `marker.addTo(this.map).bindPopup(content).openPopup()` in a loop - about 5 markers had to be added but the browser froze and the tab used 100% CPU. I didn't drag the map or anything, just clicked on check boxes that are checked in a `window.setTimeout` to see whether markers for them must be added. I probably checked 4-5 check boxes before the timeout occur so it had to add 4 or 5 markers. What I can say for sure is that the problem happens when Leaflet tries to bring the newly added popup into view.

**Comment by varadero** [comment]
I tried to debug the reproduction code specified in the @lapo-luchini  comment https://github.com/Leaflet/Leaflet/issues/5035#issuecomment-777383897 (leaflet version at this jsfiddle is 1.0.1)

and found that the following code is called multiple times in a cycle:

```js
    o.DomEvent = {
        on: function(t, e, i, n) {
...
}
```

The second parameter switches between `"load"` and `"error"` multiple times before stack overflow occurs. Both `"load"` and `"error"` are bound in `createTile` function:
```js
        createTile: function(t, i) {
            var n = e.createElement("img");
            return o.DomEvent.on(n, "load", o.bind(this._tileOnLoad, this, i, n)),
            o.DomEvent.on(n, "error", o.bind(this._tileOnError, this, i, n)),
            this.options.crossOrigin && (n.crossOrigin = ""),
            n.alt = "",
            n.src = this.getTileUrl(t),
            n
        }
```

I also put a breakpoint at:
```js
        splitWords: function(t) {
            return o.Util.trim(t).split(/\s+/)
        }
```

And this is the result of calls to it with the parameter `t` values:
```
splitWords: function(t)
t = "remove"
t = "click"
t = "touchstart mousedown"
t = "mousewheel"
t = "contextmenu"
t = "load"
t = "error"
t = "leaflet-tile"
t = "load"
t = "error"
t = "leaflet-tile"
...
continues with "load" then "error" then "leaflet-tile"
```

**Comment by Falke-Design** [comment]
Are you able copy your code into www.leafletjs.com/edit.html ?

**Comment by varadero** [comment]
> Are you able copy your code into [www.leafletjs.com/edit.html](http://www.leafletjs.com/edit.html) ?

Yes. The page does not cause stack overflow but after a couple of drags and zoom in/out, the tab starts using 100% CPU and it end up in a "Aw, Snap!" Chrome tab and `Error code: Out of Memory` text below it. If the tab does not crash, I cannot drag it anymore - only zoomig works.

This is how I modified the code (just got the text from @lapo-luchini jsfiddle and changed `'map'` to `'leaflet`':
```
var map = L.map('leaflet').setView([39.5, -0.5], 5);
L.tileLayer(
    'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 18
    }).addTo(map);

map.panTo([40.712, -74.227]);

setTimeout(function() {
    L.popup({
            keepInView: true
        }).setLatLng([36.83711, -2.464459])
        .setContent('<p>Hello world!<br />This is a nice popup.</p>')
        .openOn(map);
}, 5000);
```

**Comment by itse4elhaam** [comment]
Setting `autoPan : false` fixes the issue in my case.
