### ISSUE TITLE
Adding autoZIndex or sortLayers to a new L.Control.Layers produces uncaught TypeError

### ISSUE THREAD

**Issue by grischard** [Leaflet/Leaflet#5140]
- [❤️] I'm reporting a bug, not asking for help
- [❤️] I've looked at the [documentation](http://leafletjs.com/reference-1.0.2.html) to make sure the behaviour is documented and expected
- [❤️] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [❤️] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.2 or master
- Browser (with version) I'm using: Chrome 54
- OS/Platform (with version) I'm using: macOS 10.12

1. Create a new L.Control.Layers
2. Add the option 'sortLayers' or 'autoZIndex'

## What behaviour I'm expecting and which behaviour I'm seeing

Expected: layer gets sorted, 

Actual:

 ```
Uncaught TypeError: layer.on is not a function(…)
_addLayer @ Control.Layers.js:219
initialize @ Control.Layers.js:86
NewClass @ Class.js:21
```

## Minimal example reproducing the issue

- [❤️] this example is as simple as possible
- [❤️] this example does not rely on any third party code

https://playground-leaflet.rhcloud.com/nuve/edit?html,console,output

## Notes

This is strange, because the test in Control.LayersSpec.js tests sortLayers.

This could be related to #5076.

**Comment by perliedman** [comment]
I believe this is because you forgot to pass the overlays parameter when creating the control. This makes the control interpret the options as overlays, and fails when it tries to add the layer with the name `sortLayers`, where the layer instance is `true`.

Changing the initialization of the control like this fixes the provided example:

```javascript
    var layersCtrl = L.control.layers({
        'OSM Positron': positron
    },null,{
        sortLayers: true
    }
    ).addTo(map);
```

I'm closing for now, but feel free to add more info if this still seems to be an issue!

**Comment by grischard** [comment]
Ahhhh, pebkac indeed. Thank you!
