### ISSUE TITLE
Remove tolerance on mouse events in IE/Edge mouse+touchscreens

### ISSUE THREAD

**Issue by Ernie23** [Leaflet/Leaflet#5144]
## How to reproduce

- Leaflet version I'm using: Leaflet 1.0.2
- Browser (with version) I'm using: IE11 and Edge
- OS/Platform (with version) I'm using: Windows 10

1. Important: set map option preferCanvas on true
2. Loading GeoJson layer with options
    - onEachFeature: register mouseover and mouseout event on layer
3. Set map on Zoomlevel 15

## What behaviour I'm expecting and which behaviour I'm seeing

When I move the mouse close to the border, I expect the correct area to highlight immediately.
Right now, I have to move the mouse a bit further into the area. The best way to see this is at zoom 15+.

The left area should be highlighted and not the right one, because the cursor moves over the area.
![hittest](https://cloud.githubusercontent.com/assets/5499652/20664863/5aad5a52-b55d-11e6-9ce7-fac900531b81.PNG)

## Minimal example reproducing the issue
Sample:  https://jsfiddle.net/qd68r2wt/12/

**Comment by perliedman** [comment]
Hi, and thanks for your report.

I think is because your browser supports touch.

For touch enabled browsers, Leaflet sets click tolerance to at last 10 pixels (https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Path.js#L134).

This click tolerance is later used when determining if a point is on the edge of a polygon (https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L476 and https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L436).

Forcibly disabling touch support makes this error go away for me: https://jsfiddle.net/uL565rks/

The increased click tolerance makes sense for things like points, but I agree it gives an unexpected and undesired effect in cases like this. We should probably look into improving this.

**Comment by Ernie23** [comment]
That's interesting.
Can you tell me, why Leaflet thinks that IE supports touch?
How does the leaflet decide?

I've no touch hardware connected with my pc. 
Chrome and Firefox works fine without setting L.Browser.touch = false.

**Comment by perliedman** [comment]
@Ernie23 the code is your friend, remember this is open source. Here's the code that checks for touch support: https://github.com/Leaflet/Leaflet/blob/master/src/core/Browser.js#L41

**Comment by IvanSanchez** [comment]
@Ernie23 Because IE/Edge **report** that they are touch capable, even if you don't have a touchscreen connected.

This kind of feature detection is very very hard to do properly, specially when you take into account edge cases like hot-plugging your laptop to an external touchscreen.

It should be possible to know whether a pointer event came from a touchscreen/touchpen, a mouse or a touchpad with the aid of the [`InputDeviceCapabilities` API](https://developer.mozilla.org/en-US/docs/Web/API/InputDeviceCapabilities_API), but I don't think IE/Edge implement that yet (or anything remotely similar, for that matter.

Needless to say, if you've got a Win10 system with a touchscreen + mouse, and can devise a method to tell apart the DOM events for each input device, we could really use that. AFAIK, none of the current Leaflet maintainers have access to such a setup.

See also https://github.com/Leaflet/Leaflet/issues/3712 - might be tangentially related to this.

**Comment by IvanSanchez** [comment]
See also: https://hacks.mozilla.org/2013/04/detecting-touch-its-the-why-not-the-how/ for background.

I think we're wrapping the DOM event somehow when we emulate the `click`s and `mouseover`s from `pointer` events. We might want to use the technique used in https://wicg.github.io/InputDeviceCapabilities/inputdevicecapabilities-polyfill.js and do something like `if (originalEvent instanceof window.TouchEvent)`

**Comment by perliedman** [comment]
Closed by #5922 .
