### ISSUE TITLE
Vertical lines while moving over canvas elements in Chrome

### ISSUE THREAD

**Issue by Ernie23** [Leaflet/Leaflet#5145]
## How to reproduce

- Leaflet version I'm using: Leaflet 1.0.2
- Browser (with version) I'm using: Chrome Version 54.0.2840.99 m
- OS/Platform (with version) I'm using: Windows 10

1. Important: set map option preferCanvas on true
2. Loading GeoJson layer with options
3. onEachFeature: register mouseover and mouseout event on layer
    - Set map on Zoomlevel 10
4. Move your mouse over the areas

## What behaviour I'm expecting and which behaviour I'm seeing

There are some vertical red lines coming up, when you move your mouse over some areas. During MouseOver the area will be highlighted and the style will be resetted in MouseOut Event.
I expected none of these vertical red lines.
![strokes](https://cloud.githubusercontent.com/assets/5499652/20671305/145bbef2-b57d-11e6-910a-1f3b162b6f32.PNG)

After you pan the map, the canvas are redrawn. The verticle lines are gone until next area highlighting.

## Minimal example reproducing the issue

https://jsfiddle.net/qd68r2wt/13/

**Comment by IvanSanchez** [comment]
@perliedman I guess this might be related to https://github.com/Leaflet/Leaflet/pull/5034 ??

**Comment by Ernie23** [comment]
@IvanSanchez  your right, sorry for double post

but in some cases I've seen this in Firefox....

**Comment by IvanSanchez** [comment]
I can reproduce on Chromium 53 (feels like an off-by-one error on the cleared bboxes), but not on Firefox 51.0a2.

@Ernie23 Do you know if this one can be reproduced in Safari or IE/Edge?

**Comment by Ernie23** [comment]
I can reproduce this in IE/Edge, but only in one of my customer solutions.
This fiddle above works fine in IE/Edge.
![ie](https://cloud.githubusercontent.com/assets/5499652/20672932/4d5e5344-b583-11e6-8c93-ae38c6387038.PNG)

Same issues in Safari (v. 10.0.1) on Mac OS Sierra (v. 10.12.1)
![safari](https://cloud.githubusercontent.com/assets/5499652/20672757/a7aa71da-b582-11e6-9860-18b471a98549.PNG)

**Comment by IvanSanchez** [comment]
Hhhhmm, that's good info.

The artifacts makes me feel that there is some weird rounding of the rectangle areas to be re-drawn.

I'll point to [this one line of code](https://github.com/Leaflet/Leaflet/blob/4c484462dc4d646cb43adc0585401d28d878330d/src/layer/vector/Canvas.js#L191):

>	`this._ctx.clearRect(bounds.min.x, bounds.min.y, size.x, size.y);`

I think that the `_redrawBounds` are not integers (or the browser is not rounding them up to integers properly). I've been able to modify the behaviour of the glitch by rounding the numbers in different ways and I *think* this is a possible solution:

```js
L.Canvas.prototype._clear = function(){
  
  var bounds = this._redrawBounds;
  
  if (bounds) {
    bounds.min.x = Math.floor(bounds.min.x);
    bounds.min.y = Math.floor(bounds.min.y);
    bounds.max.x = Math.ceil(bounds.max.x);
    bounds.max.y = Math.ceil(bounds.max.y);
  
    var size = bounds.getSize();
    this._ctx.clearRect(bounds.min.x, bounds.min.y, size.x, size.y);
  } else {
    this._ctx.clearRect(0, 0, this._container.width, this._container.height);
  }

};
```

See here: https://playground-leaflet.rhcloud.com/sipin/1/edit?js,output

@Ernie23 Would you be so kind to try that out in several browsers? I can't do it right now. BTW, if you can make a pull request with the changes, that'd be extra nice. Also I wonder what happens when fractional zoom gets in.

@perliedman This shouldn't affect #5115 and so on, right?

**Comment by perliedman** [comment]
@IvanSanchez I had these problems for a while when refactoring the canvas, and I'm pretty sure you're right they are the consequence of pixel bounds sometimes not being integers.

The weird thing is that the problem "went away" after some of my fixes, but it appears they still exist in some circumstances. I'll try to have a look, this shouldn't be too hard.

**Comment by perliedman** [comment]
The important thing is that you have to clear _exactly_ what you later redraw. If you you have a off by one, you'll redraw the same semi-transparent surface twice, or you'll leave single pixel lines that are never repainted. I think the problem is that `clearRect` and canvas clip handle non-integers differently in some way.

**Comment by IvanSanchez** [comment]
Yeah, and I guess that:

* Replacing the `_redrawBounds` in-place like I did in that playground is not the cleanest thing ever
* Different browsers behave differently about `clearRect` and canvas clip

**Comment by Ernie23** [comment]
@IvanSanchez I've tested your modification in different browser
          IE11/Edge - ok
          Chrome (v54) - ok
          Firefox (v51 beta) - ok
          Safari (v. 10.0.1) - ok

As far as I can see this solution from you works in my customer solution also!

If nobody has anything against it, I will make a pull request. :-)

**Comment by IvanSanchez** [comment]
@Ernie I suggest you wait a bit, at least until @perliedman says if he wants to fix this himself or not. I don't want to see two PRs for the same bug at the same time and reject one of them just because of the timing :wink:

**Comment by perliedman** [comment]
From just looking at it, I think a better place to put the rounding would be in [`_extendRedrawBounds`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L171), or maybe in [`_redraw`](https://github.com/Leaflet/Leaflet/blob/master/src/layer/vector/Canvas.js#L178), so that it's `_redrawBounds` that are rounded, and we are sure we clear the exact same bounds as we then draw.

Apparently it looks like fixing the clearing is enough, but I imagine clearing and redrawing exactly the same area would be less confusing and also more future proof.

Having said that, feel free to submit a PR, @Ernie23!
