### ISSUE TITLE
[FR] Set trigger event for L.Draggable

### ISSUE THREAD

**Issue by kaynz** [Leaflet/Leaflet#5147]
Hello,

quick and small feature request:

I'd like to choose  the event which triggers dragstart. Actually it is click-only but I'd like to use a click and hold (contextmenu) in some cases to begin the dragging.

Thank you :) :+1:

**Comment by perliedman** [comment]
To make contextmenu start dragging, it is probably better to listen for the `contextmenu` event and then enable dragging once it fires, rather than changing how draggable works.

This is an edge use case, and given the complexity of getting dragging and its events to work in all browsers as it is, it's not likely we will add even more complexity to it. Like a lot of things, a plugin might be the right place for something like this.
