### ISSUE TITLE
Marker.setLatLng sets x and y based on pre-zoom projection during zoom animation.

### ISSUE THREAD

**Issue by mohsen1** [Leaflet/Leaflet#5181]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported
  * I tried but there might be duplicates. Maybe I'm not using the right keywords.

----

When putting animated overlays or markers on map, during the zoom transition those animations will look off because the underlying tiles pane translate and make the marker or overlay look off location. 

For example [Leaflet Ant Path](http://rubenspgcavalcante.github.io/leaflet-ant-path/) looks bad during zoom transition:

![lag](https://cloud.githubusercontent.com/assets/543633/21067304/25d0d65e-be1f-11e6-9d41-e7af1c75410c.gif)

[Leaflet Animated Marker](http://openplans.github.io/Leaflet.AnimatedMarker/) is suffering from similar issue:

![bike](https://cloud.githubusercontent.com/assets/543633/21067320/4d418d96-be1f-11e6-9cd5-50d051c408e3.gif)

I think Leaflet should provide an API that allows markers and overlays attach themselves to the element that zoom CSS transition is applied to so they are scaled with the tiles layer.

**Comment by ghybs** [comment]
Hi,

As for Leaflet Ant Path demo, it seems to me that this is due to mismatch between Leaflet CSS and JS versions: the demo page uses CSS from Leaflet 0.7.7 but JS from Leaflet 1.0.0-rc.3. See #4774.
You might want to report it on that specific plugin issue tracker, or even better, open a PR to fix it.

Regarding Leaflet Animated Marker, I think it is because this plugin makes use of CSS transition property, which overrides Leaflet default property on markers.
Hence it overrides the smooth translation that Leaflet applies by default on markers during animated zoom.

Therefore it seems to me that these 2 issues are not related to each other.

Hope this helps.

**Comment by mohsen1** [comment]
Thanks! That's helpful.

What's your recommendation for animating markers between two latLngs on the map? We don't want to get this jumpy behavior when user zooms the map.

**Comment by ghybs** [comment]
Not sure.

Even forcing using chunked intervals instead of CSS3 transition in AnimatedMarker plugin exhibits a jumpy behaviour:
http://playground-leaflet.rhcloud.com/bipu/1/edit?html,output

**Comment by mohsen1** [comment]
Leaflet should add CSS transform animation value for markers during the zoom animation. The CSS transform origin will be the zoom origin and the transform should be a translate 2d that is equal to translate of point that marker is pointing at on the tiles layer. 

That way the marker "zooms" with the tiles during the animation and the jumpy animation will go away. The math is kind of hard to figure out exact translate values though

**Comment by mohsen1** [comment]
Actually, Leaflet does all of that math and works perfectly when Marker is static. 

When we animate the marker, **during the zoom, `setLatLng` is using pre-zoom projection** and that's causing the marker to jump to inaccurate places. 

There are two options to solve this:
* Provide `zoom_started` and `zoom_ended` events so our code is not setting latLng during the zoom
* Update `setLatLng` to be aware of zoom state and in takes into account current (mid-zoom) projection.

Option 2 is better because it makes markers not depend on map state.

**Comment by ghybs** [comment]
It seems to be that this should probably be handled by that plugin, rather than Leaflet core.

See for instance https://github.com/openplans/Leaflet.AnimatedMarker/pull/12, https://github.com/openplans/Leaflet.AnimatedMarker/issues/35 and https://github.com/openplans/Leaflet.AnimatedMarker/issues/42

**Comment by mohsen1** [comment]
Just published a module based on those suggestion: https://github.com/mohsen1/leaflet-moving-marker


But still, while zoom animation is going on, the `setLatLng` function should not behave like that.

**Comment by TGMorais** [comment]
Hi, I ran into this issue as well.

In my case, I have a map with a lot markers updating their location in real time (websockets).
Some markers will update their `latLng` while the zoom animation is running, causing those markers to update then "jump" to the new projection.

Listening to `zoomstart` and `zoomend` sort of mitigates the issue.
I eventually removed the marker zoom animations (`markerZoomAnimation=false`).
