### ISSUE TITLE
getBoundsZoom return max zoom with proj4leafet and EPSG:25833

### ISSUE THREAD

**Issue by computerlove** [Leaflet/Leaflet#5195]
## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome 53
- OS/Platform (with version) I'm using: Windows 7, Ubuntu 16.04

## What behaviour I'm expecting and which behaviour I'm seeing
When using `fitBounds` on a featureLayer it always zooms to the max zoom level. 

I am using an unreleased version of proj4leafet, but comparing my previous version using Leaflet 0.7 and proj4leafet 0.7.2 I don't see how it could be an issue with proj4leafet. 

## Minimal example reproducing the issue
http://playground-leaflet.rhcloud.com/rira/edit?html,output

The reason as far as I can see is in `getBoundsZoom`:
```
boundsSize = this.project(se, zoom).subtract(this.project(nw, zoom)),
```
One of the sizes in boundsSize is negative, so 
```
var scale = Math.min(size.x / boundsSize.x, size.y / boundsSize.y);
```
is negative, and 
```
zoom = this.getScaleZoom(scale, zoom);
```
becomes infinity.

As a workaround I use a custom version of `getBoundsZoom` with 
```
var scale = Math.min(Math.abs(size.x / boundsSize.x), Math.abs(size.y / boundsSize.y));
```

But before creating a PR with this I wanted feedback to know whether this is a sound solution.

The problem may be related to some parts of https://github.com/Leaflet/Leaflet/issues/4886, the code with Math.abs is mentioned there, but I cannot find any issue or PR that follows up on this.

**Comment by IvanSanchez** [comment]
It sounds like a good analysis and a sane solution.

However, instead of...

```
boundsSize = this.project(se, zoom).subtract(this.project(nw, zoom)),
```

...maybe we shoud use something in the lines of...

```
boundsSize = L.bounds( this.project(se,zoom), this.project(nw, zoom) ).getSize()
```

...since that will ensure that the size of the `L.Bounds` will always be positive.

Alternatively, we might want to add a `.abs()` method to `L.Point`, which would return the point filtering each coordinate through `Math.abs()`. My intuition tells me that this will perform a tiny bit better than calculating a `L.Bounds` or clamping things around (which might not work anyway if both dimensions of the bbox are negative).

**Comment by computerlove** [comment]
Created a PR with the change. Tried to create a test as well.
