### ISSUE TITLE
Event model is broken and poorly documented

### ISSUE THREAD

**Issue by joukewitteveen** [Leaflet/Leaflet#5199]
## How to reproduce

Consider the leaflet 1.0 map of https://playground-leaflet.rhcloud.com/qal/edit?html,console,output
Below is a table of the console output when clicking the circle marker for two different versions of the playground code. The first version runs in the playground itself, the second version is the code of the playground page as an isolated html file. The developer tools of both Chromium and Firefox include a mobile device simulator ("responsive design" with simulated touch events in Firefox).

.  | playground  | standalone
----  | ----  | ----
Chromium  | mousedown  | mousedown
Chromium - device simulator  | mousedown  | _nothing_
Firefox  | mousedown  | mousedown
Firefox - responsive design  | mousedown _twice_  | mousedown _twice_

## Expected behavior

The double mousedown event in Firefox when simulating touch is probably a result of simulation, but still undesirable. The lack of any output with the Chromium device simulator in standalone mode surely must be a bug.

The events in the Leaflet Evented class are synthetic. Regardless of the input method, events will be Mouse Events (mousemove, mousedown, mouseup, click). A more method agnostic scheme is available in the form of [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events). Conceptually, pointermove, pointerdown, pointerup would be better names for synthetic events since they do not imply a specific input method.

## Documentation

Apart from the synthetic events fired by the Evented class, there is the DomEvent class which operates on Dom events. Although Mouse Events can be captured through this interface too, an important distinction is that these events are not (or at least less) synthetic. It is not documented that a mousedown event in the Evented class is aggregated from multiple input methods, whereas the event by the same name in the DomEvent class is not aggregated, i.e. strictly separated from, say, touchdown.

## Resolution

The 'correct' solution will break backward compatibility and is therefore not ideal. It consists of renaming all Evented events to pointer events, fixing the behavior in the above table and discouraging the use of the DomEvent class for end users. The DomEvent class is not flexible as, for example, it is not easy to obtain the container of a Vector layer to bind a DomEvent to. Additionally, more detailed documentation of event processing in Leaflet would be welcome.

### Playground Code
```
<!DOCTYPE html>
<html>
<head>
<link href="https://unpkg.com/leaflet@1.0.0/dist/leaflet.css" rel="stylesheet" type="text/css" />
<script src="https://unpkg.com/leaflet@1.0.0/dist/leaflet-src.js"></script>
  <meta charset="utf-8">
  <title>Leaflet JS Bin</title>
  <style>
    #map {
      width:600px;
      height:400px;
    }
  </style>
</head>
<body>
  <div id='map'></div>


  <script>
    var myCenter = new L.LatLng(50.5, 30.51);
    var map = new L.Map('map', {center: myCenter, zoom: 15});

    var positron = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
    }).addTo(map);

    var marker = new L.CircleMarker(myCenter);
    map.addLayer(marker);

    marker.on('pointerdown mousedown', function(e){
        console.log(e.type)
    });
  </script>

</body>
</html>
```

**Comment by IvanSanchez** [comment]
So I've read through this, and my takeaway is:

- Mouse clicks or touches in Chromium while using the "device toolbar" are not recognised
- Mouse clicks or touches in Firefox in "responsive design mode"
- Reporter did not specify OS of browser versions where this might be reproduced (a piece of information which is incredibly important to have since Chromium 55 implemented native `PointerEvent`s)
- Reporter is annoyed at the `L.Evented` logic
- Reporter hasn't read the [bit of the documentation that says that a `click` event might happen because of a touchscreen tap, not a mouse click](http://leafletjs.com/reference-1.0.2.html#interactive-layer-click) and thinks that all `L.Evented`s can fire `click`s.
- Reporter thinks that `PointerEvent`s are a [silver bullet](https://www.merriam-webster.com/dictionary/silver%20bullet) to the problems previously exposed.

There are problems with this bug report.

Besides the lack of browser versions, there is no good analysis. What native DOM events happen in the device simulators? Sure you can throw a `L.DomEvent.on(map.getcontainer(), 'touchdown pointerdown mousedown', ev=>console.log(ev))` in a playground and provide useful information.

**This should be a separate bug report, providing as much information as possible**.

Instead of an analysis, we've got a leap of faith. How can the reporter be so sure that calling the Leaflet synthetic event `pointerdown` instead of `mousedown` will solve the problem???

Making the interactive layers and the map fire `pointer*` events **should be a separate feature request**, specifying the pros and cons of polyfilling mouse/touch events with the missing info when appropriate, and pros/cons of existing pointer polyfills.

Also:

> Additionally, more detailed documentation of event processing in Leaflet would be welcome.

Documentation is wrong? No problem, just create a **separate issue** or, better even, **create a pull request** to improve it (after reading the [contributing guide](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#improving-documentation)).

You've taken the time to write a lengthy bug report with your ideas, but unfortunately we cannot accept this in its current form. Please take a bit of time to read ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["Reporting Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html), make a better bug report, and consider sending PRs for documentation improvements (or even in-length tutorials).

**Comment by joukewitteveen** [comment]
I am well aware of all the documentation you have linked to but thought a tracking bug for the state of event handling, which is known to be near impossible to get right, would be nice. I would have liked to have found something such as this report before having to find things out through reading code. I apologize for the title of the report, which may be a bit too opinionated.

I am disappointed by the ad hominem response and will probably not pursue this any further with PRs or whatnot. Environment is Firefox 50 / Chromium 55 on Linux.
