### ISSUE TITLE
Part of Layers didn't display when the map was initialized but became normal when I resize the browser window?

### ISSUE THREAD

**Issue by hijiangtao** [Leaflet/Leaflet#5207]
- [x] I'm reporting a bug, not asking for help
- [x] I've looked at the [documentation](http://leafletjs.com/reference-1.0.0.html) to make sure the behaviour is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.0.2
- Browser (with version) I'm using: chrome
- OS/Platform (with version) I'm using: ubuntu16.04
- step 1
- step 2

## What behaviour I'm expecting and which behaviour I'm seeing

It shows that the mao just display the layers normally around the top of the map view, like the pic shows below, which left the other part of the view blank.

![download 1](https://cloud.githubusercontent.com/assets/4990015/21301603/1325af8e-c5ea-11e6-9f13-4e8bff2e386f.png)

The console didn't hint any bug info logs, and the situation can be fixed by I resize the window of chrome browser, exactly, any resize operation (excepts zoom and scale in the map) like open the console of chrome can help me get the other layers that didn't display normally at first.

I wonder if there is any potential rule in leaflet css or js can influence the layer's loading behavior?

The codes shows here (I just delete my accessToken and id here): 

```
var baseLayer = L.tileLayer(
		'https://api.mapbox.com/styles/v1/{id}/{z}/{x}/{y}?access_token={accessToken}')

map = new L.map(id, {
		center: L.latLng(39.914,116.396),
		zoom: 12,
		layers: baseLayer
	  })

map.zoomControl.setPosition('topright');
```

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

Using http://playground-leaflet.rhcloud.com/ or any other jsfiddle like site.

**Comment by perliedman** [comment]
@hijiangtao this sounds very much like a resizing issue. If the map container `div` changes size after the map is initialized, Leaflet isn't automatically aware of this, and you will have to call [`map.invalidateSize()`](http://leafletjs.com/reference-1.0.0.html#map-invalidatesize) to notify Leaflet about the size change.

Leaflet _will_ however [notice window resize](http://leafletjs.com/reference-1.0.0.html#map-trackresize), and call `invalidateSize` for you.

So, can you check if invalidating the size fixes this problem for you? Otherwise, please create a playground example illustrating the issue - the code pasted above in itself clearly will not cause this problem, it's more or less the example on Leaflet's front page, and that does work.

**Comment by hijiangtao** [comment]
Well then, I'm really sorry for that.

`invalidateSize` method didn't fix it, but this is definitely my problem. I usually put the stylesheets after `<body>` tag, which means the javascript file will initialize the map first and then change the size of my map container, the problem has been fixed by putting the stylesheets forward into the `<header>` tag, before the javascript code, thanks very much.

My silly code goes here: [gist](https://gist.github.com/hijiangtao/1bcab3154afa08d1b5d97f7944216208), the effect above screenshot goes here: [playground](http://playground-leaflet.rhcloud.com/soce/1/edit?html,output)

**Comment by hijiangtao** [comment]
@perliedman  Really sorry about putting my bugs in a wrong place, I think it's time to close the silly issue and I will double check my codes and Leaflet documents next time, thanks very much.
