### ISSUE TITLE
Tooltip binded to polygon displacement on zoom in

### ISSUE THREAD

**Issue by walterfn2** [Leaflet/Leaflet#5216]
## How to reproduce

Leaflet version I'm using: 1.0.2
Browser (with version) I'm using: Chrome & FF
OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

Binded tooltip to polygon changes its place on zoom in. I'm attaching jsfiddle examples. 

In first example problem occurs once map is zoomed to polygon.

In second example problem does not occur if we initialize map with higher zoom.

## Minimal example reproducing the issue

https://jsfiddle.net/cco2v6vq/

https://jsfiddle.net/cco2v6vq/1/

**Comment by andy-kay** [comment]
I'm pretty new to leaflet source code, but from what I could find, the _openTooltip_ method in _Tooltip.js_ tries to get the correct center of the polygon. 
Now, when we have a small scale, the layer.getCenter() returns a wrong value, because all points of the polygon in the example have the same coords.
A quick fix to get it working would be to replace
`latlng = layer.getCenter ? layer.getCenter() : layer.getLatLng();`
with 
`latlng = layer.getBounds ? layer.getBounds().getCenter() : layer.getLatLng();`
 in line 328 in _src/layer/Tooltip.js_

but that does not solve the problem that the _getCenter()_ returns not reliable values.

**Comment by neesonqk** [comment]
@andy-kay agree that caused by `getCenter()` function doesn't return consistent value upon different zoom levels, I use below temp solution as a workaround before a proper fix.

```js
const lbl = layer.bindTooltip("my tooltip text", {
     direction: 'center',
     permanent: true,
}).getTooltip();

lbl.setLatLng(layer.getBounds().getCenter());
```

**Comment by johnd0e** [comment]
At the moment Polygon's `getCenter` make use of (already) projected coordinates, that are dependent on zoom level.
To return consistent values we should use same zoom value, so instead of reusing pre-projected values we have to make all the calculations from scratch.

Well, perhaps performance is not so important in this case. But the code will be slightly more complicated.
