### ISSUE TITLE
L.Browser.pointer in Chrome

### ISSUE THREAD

**Issue by blq** [Leaflet/Leaflet#5229]
Regarding `L.Browser.pointer`. I think this commit is an error: https://github.com/Leaflet/Leaflet/commit/a1371507bfe898eac1dabbb34c8f7692195e74d9

After the change `pointer` is no longer a boolean but the function `Pointerevent`. I.e the flag goes from false to true in Chrome.  This seems to have gone unnoticed for quite a while but it causes problems with dragging on a custom layer I have.

Regards
/Fredrik Blomqvist

**Comment by blq** [comment]
Ok. Might actually be my code that is somehow incompatible with thew new PointerEvents in Chrome 55, flag seems correct. Maybe you guys have some pointer or clue on what could have caused this? Or would exposing an option to disable the use of PointerEvents make sense?

**Comment by perliedman** [comment]
This sounds very similar to #5189.

The fact that `L.Browser.pointer` is not a boolean is not relevant, we use truthy values instead of boolean `true` all over the place.

The problem you're seeing is most likely due to the fact that Chrome now uses `PointerEvent`s, which breaks some older code that assumes `PointerEvent`s means touch, which is no longer the case.

Feel free to add more information if you believe this is indeed a Leaflet bug, but I'm closing this for now.

**Comment by IvanSanchez** [comment]
If this is a problem, we can just do the usual `L.Browser.pointer = !!(....)` to force things into a `Boolean`
