### ISSUE TITLE
In the case of L.CircleMarker, popup latlng is wrong in popupopen event

### ISSUE THREAD

**Issue by yafred** [Leaflet/Leaflet#5232]
Consider following code

```
map.on('popupopen',function(e) {
   var latlng = e.popup.getLatLng();
});
```
 
In the case of a L.CircleMarker it seems to be the position of the click that opened the popup instead of the position of the marker.

Please see: https://yafred.github.io/leaflet-tests/20170106-circle-marker-popup/

Is it something known ?

**Comment by danzel** [comment]
You are using `e.popup.getLatLng()`.
This returns the position of the popup, which is where the mouse is clicked ;)
Not sure if you can get the element that caused the popup to appear in that event.

**Comment by yafred** [comment]
OK. 

Still, L.Marker has the behaviour I'm expecting ... e.popup.getLatLng() returns the position of the marker.

**Comment by danzel** [comment]
On a marker where does the popup appear?
Based on what you've said, I'd guess it always appears at the markers position, not where the mouse is clicked. This is why the behavior differs.

Instead of using `bindPopup` you could listen to `click` events and add a popup at the position of the circleMarker (rather than the position of the mouse click), then it'd work like you want

**Comment by yafred** [comment]
Yes, with a L.Marker, the popup position does not depend on the click position (it is anchoring to the marker icon).

Just of the records, I realize I was just mislead by the word marker in CircleMarker. 
L.CircleMarker is a vector layer and follow the same rules as L.Circle

All vector layers are showing the popup at the click position: http://leafletjs.com/examples/quick-start/example.html
