### ISSUE TITLE
An option to pan with two fingers on a touch pad

### ISSUE THREAD

**Issue by Zverik** [Leaflet/Leaflet#5255]
I'd like an option to pan not with dragging (which is not simple on touch pads), but with scroll events. Like on [this website](http://geo.omskportal.ru/rgis/rest/services/OSM/OpenStreetMap/MapServer?f=jsapi) (which uses ArcGIS API). Is it technically possible to add it to Leaflet?

**Comment by IvanSanchez** [comment]
> Is it technically possible to add it to Leaflet?

The answer is "yes".

First read http://leafletjs.com/examples/extending/extending-3-controls.html, as to understand how the concept of "Leaflet handlers" works.

Then, write your own "wheelpan" handler:

```js
L.WheelPanHandler = L.Handler.extend({
    addHooks: function() {
        L.DomEvent.on(map, 'wheel', this._wheelpan, this);
    },

    removeHooks: function() {
        L.DomEvent.off(map, 'wheel', this._wheelpan, this);
    },

    _wheelpan: function(event) {
        var panAmount = L.point(event.deltaX, event.deltaY);
        
        // Normalize lines
        if (event.deltaMode === 1) { panAmount = panAmount.multiplyBy(20); }
        // Normalize pages
        if (event.deltaMode === 2) { panAmount = panAmount.multiplyBy(60); }

        this._map.panBy(panAmount);
    }
});
```

Should work right out. The problem is that laptop touchpads with horizontal scrolling are (a) hard to find (b) pretty much impossible to detect properly from JS (c) invisible to some legacy browsers which don't implement the `wheel` event or implement it poorly (d) glitchy when touchscreens are involved.

So while this might be a good idea, this code is probably never going to be in mainstream Leaflet for compatibility reasons.

**Comment by IvanSanchez** [comment]
Slightly related: https://github.com/Leaflet/Leaflet/pull/3581

**Comment by Zverik** [comment]
I wouldn't say such laptops are hard to find, since every macbook supports horizontal scrolling. Thanks, Ivan, I'll test this.

**Comment by IvanSanchez** [comment]
@Zverik If you can, try to test this with a couple of 2-4 year old random windows laptops, and see how badly things break ;-)
