### ISSUE TITLE
Popup event documentation

### ISSUE THREAD

**Issue by danzel** [Leaflet/Leaflet#5311]
The popup events documentation says it supports the popupopen and popupclose events, but I don't think it actually does...

http://leafletjs.com/reference-1.0.3.html#popup-popupclose

http://playground-leaflet.rhcloud.com/kib/edit?html,console,output
Close the popup.
You will get these events:
```
"map popup close"
"popup remove"
```
But the docs make it sound like we should get `popup close` too.

Looking at the implementation, I think the docs are wrong?
https://github.com/Leaflet/Leaflet/blob/master/src/layer/Popup.js#L127-L146

**Comment by IvanSanchez** [comment]
The [documentation says](http://leafletjs.com/reference-1.0.3.html#layer-popupclose), I quote:

> `popupclose` 	`PopupEvent` 	Fired when a popup bound to this layer is closed

Note that this event is a `L.Layer` event, *not* a `L.Popup` event. So this is fired for markers for which you have done a `bindPopup()` previously.

It can be a bit confusing, as the `Popup` functions also appear for the `Popup`, because it inherits from `Layer`. This would mean that if you manually instantiate a `L.Popup`, and then run `bindPopup` to it, and then and open and close the bound `Popup`, the first `Popup` would fire a `popupclose` event.

So while I agree that it is confusing, this is not a bug.

(If you can come up with better wording for the docs, please send a PR as usual)
