### ISSUE TITLE
Ensure popup is not cut off when it pops up

### ISSUE THREAD

**Issue by thomasneirynck** [Leaflet/Leaflet#5320]
## How to reproduce

- Leaflet version I'm using: 0.7.5
- Browser (with version) I'm using: chrome
- OS/Platform (with version) I'm using: ubuntu

Position a L.popup on the center of a feature. If it is close to the edge of the map, the pop-up will be partially cut off by the edge of the map.

## What behaviour I'm expecting and which behavior I'm seeing

Consider adding the behavior, perhaps as an optional parameter, that the popup is offset automatically so it is always completely visible when it pops up.

**Comment by IvanSanchez** [comment]
Is this reproducible with 1.0.3?

**Comment by danzel** [comment]
Did we even have tooltips in 0.7.5? Are you using a plugin?

**Comment by thomasneirynck** [comment]
@danzel I'm using the `L.popup` API. The reason for this is that we want formatted HTML as content. Perhaps there is a better API feature to use?

@IvanSanchez thanks, I'll try upgrading to 1.0.3 and check behavior there.

**Comment by thomasneirynck** [comment]
I edited the issue to reflect that we're using the L.popup API.

**Comment by thecristen** [comment]
Someone created a plugin solely addressing this issue: https://github.com/yafred/leaflet-responsive-popup

**Comment by drzraf** [comment]
This does not seem with 1.2.0. There is like autoPanPadding, so the map position move in order to display the tooltip.
*but* I have a use-case where I *don't* want this to happen.
In my use-case visible map' markers match a list of item `<ul>/<li>`.
Hovering an item show the marker's tooltip.
If the tooltip is on a map's border, map's position change, and the item's list change.

Is there a mean to "lock" the map's position, even when the tooltip shows up? (I'd prefer tooltip's text to overflow the div's rather than moving the map)

**Comment by perliedman** [comment]
@drzaf I'm a bit confused by your description - are we talking about `Tooltip`s or `Popup`s? To my knowledge, tooltips will not move the map to fit them. If we are talking about `Popup`s, it sounds like you should use `autoPan: false`. Anyway, I think you should open a new issue if you really think this is something not already supported by Leaflet.

**Comment by drzraf** [comment]
Oh, I'm sorry for polluting that thread, I was speaking about tooltip (I think that I'm looking to an autoPan=false for tooltips)
