### ISSUE TITLE
Map.getBounds() never reports a latitude coordinate of 90/-90 when the map is fully visible

### ISSUE THREAD

**Issue by dmccormack3** [Leaflet/Leaflet#5324]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Windows 7

The map.getBounds() function only returns the maximum latitude coordinate 90/-90 when the map is no longer visible. If we continue to zoom out on a map we will never see the northEast or southWest properties hit 90/-90.

## What behaviour I'm expecting and which behaviour I'm seeing

The map.getBounds() should return a northEast/southWest latitude coordinate of 90/-90 when the map is fully visible.

## Minimal example reproducing the issue

I have created a fiddle to demonstrate this behaviour: http://jsfiddle.net/LnzN2/694/

If you continue to zoom out on the map, you will notice in the dev tools console that the northEast latitude coordinate never hits 90 when clearly the full map is in view. If you continually pan upwards however, the latitude coordinate will finally hit 90, with the map no longer in view.

**Comment by IvanSanchez** [comment]
Not a bug. Leaflet uses the EPSG:3857 map projection by default, the so-called "web mercator" cylindrical projection. The north/south poles have no representation on a cylindrical map projection. See https://en.wikipedia.org/wiki/Map_projection#Cylindrical and https://en.wikipedia.org/wiki/Mercator_projection

If you want to display the poles, use a different map projection. See the EPSG:4326 CRS.

**Comment by ghybs** [comment]
Hi,

Somehow related to https://github.com/Leaflet/Leaflet/issues/4721#issuecomment-231736823

As pointed out by IvanSanchez, this is the expected behaviour of Web Mercator projection. It stretches high latitudes (that is why northern countries like Greenland look so big). I.e. the pole (at 90 degrees latitude) is placed at infinity.

You probably panned quite far away to get the bounds to display 90 degrees. Which is probably not actually 90, but rounded to that value.
