### ISSUE TITLE
Layers control dont work right in Opera 44 

### ISSUE THREAD

**Issue by erkinsergey** [Leaflet/Leaflet#5440]
In my Opera 44 leaflet layers control work wrong and not select layers and overlays. Layers pane is hidden after click without select layer and apply state.
- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Opera 44.0.2510.1159
- OS/Platform (with version) I'm using: Linux Mint 18 Sarah 64 (Ubuntu 16.04 LTS (x86_64; MATE))
This example not work right [http://leafletjs.com/examples/layers-control/example.html](http://leafletjs.com/examples/layers-control/example.html)

**Comment by olzraiti** [comment]
I have this issue also with Chrome 57. Chrome 56 work fine. I tested also with Chromium, with same outcome. I tested on the demo page mentioned above.

Selecting layers work, if the unexpanded control is behind the clicked point. If I click a point where the unexpanded control isn't, the control is unexpanded without changing the layer. Try for example clicking directly at the checkpoints or at the overlay to click outside the unexpanded layer control. Clicking on tile layer labels works because the unexpanded layer control is behind them.

Leaflet version: 1.0.3
Non-working version: 57.0.2987.133 (64-bit)
Working version : 56.0.2924.87 (64-bit)
OS: Arch Linux

**Comment by perliedman** [comment]
Hm, I can't reproduce this on Chrome 57.0.2987.133 on Ubuntu 16.04 x64. Clicking just about any part of the layer control works as expected.

Any more details on what the difference might be between our systems?

**Comment by olzraiti** [comment]
Setting the 'Use hardware acceleration when available' to true in the Chrome settings fixed this issue.

**Comment by erkinsergey** [comment]
Option 'Use hardware acceleration when available' has always been true in the my Opera. But by next version of the Opera this issue has been disappeared.
