### ISSUE TITLE
Feature: new option "draggable" for circle, circleMarker, polygon points

### ISSUE THREAD

**Issue by ppete2** [Leaflet/Leaflet#5459]
Using Leaflet v1.0.3 it's possible to drag Markers by its option `draggable=true`
But not so for other point features like **Circles, circleMarkers, points of polygons or polylines**.

There are some drawing Plugins providing this possibility, like _Path.drag.js_

The following method using some Events doesnt'work any more with Leaflet v1.0.3:

```javascript
circle.on({
  mousedown: function () {
    map.on('mousemove', function (e) {
      circle.setLatLng(e.latlng);
    });
  }
}); 
map.on('mouseup',function(e){
  map.removeEventListener('mousemove');
})
```

Since there  already an option `"draggable"` for Markers, it would be consistent to provide such an essential option for the Vector point features as well. And not make the Users have to look for drawing plugins or needlessly complicated event-based constructions to reach this goal.

**Comment by perliedman** [comment]
Hi and thanks for submitting this suggestion.

This topic has been up before, and discussed at quite some length IIRC, although I couldn't really find a link to the discussion at the moment; the only related thing I can find now is https://github.com/Leaflet/Leaflet/pull/4628.

The consensus among Leaflet maintainers was that this is not a feature we like in the core, since it adds quite some complexity and is not such a common use case (while dragging markers arguably is a common feature).

So, we'll keep path dragging and other vector edit operations as plugins for now.
