### ISSUE TITLE
ImageOverlay build environment image issue

### ISSUE THREAD

**Issue by burnout87** [Leaflet/Leaflet#5467]
Hi everybody!

I am facing quite an annoying issue adding an imageOverlay on my map, using a simple png image.

This is the code I use to add the layer to the map:

     this._map.options.crs = L.CRS.Simple;

      var bounds = [[0, 0], [1080, 1980]];
      var loc = this.mediator.$location;

      L.imageOverlay(url, bounds).addTo(this._map);

      this._map.fitBounds(bounds);

For the development environment I use gulp+WebPack setting up a WebPack development server for convenience, and everything seems to be working fine.

If I then build the self contained war file and deploy it to Tomcat, I don't get any error, but I simply can't see the image over the map, that instead I could see (and flawlessly interact) in the other case.

I am not sure this is a Leaflet related issue, as it could also depend on webpack or gulp.

What do you think ? Anyone already faced this kind of problem ?

Cheers

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by burnout87** [comment]
Can we open this again ? Is the title more appropriate now ?

**Comment by perliedman** [comment]
Hi @burnout87,
the problem is not in the title, the problem is that, like you say, the issue very likely isn't with Leaflet, but rather with something in your Gulp/Webpack/Tomcat setup.

Please understand that the (currently very small) team of Leaflet maintainers have a limited amount of time to put into this. This means that we have to focus on issues in Leaflet, and simply do not have time to debug a complex setup like the one you're describing, involving components that we don't necessarily have any knowledge about or control over.
