### ISSUE TITLE
invalidateSize does not work in Firefox when print view triggered

### ISSUE THREAD

**Issue by nyikesda** [Leaflet/Leaflet#5481]
When print view event triggered, then leaflet map.invalidateSize() works in Chrome, but not in Firefox.
Firefox version: 53.0 (32-bit)
Chrome version: 58.0.3029.81
Leaflet version: 1.0.3

## How to reproduce
On page: http://leafletjs.com/index.html
To console:
JS code:
- Chrome:
```javascript
window.matchMedia('print').addListener(
   function(printView){
      if (printView.matches){
         map.invalidateSize();
      }
   }
)
```
- Firefox:
```javascript
window.addEventListener('beforeprint', 
   function() {
      map.invalidateSize();
   }
);
```
## What behaviour I'm expecting and which behaviour I'm seeing

**Expecting:** You should see same center on map in print view after map.invalidateSize() triggered, than you see in screen view.
**In Firefox:**  map.invalidateSize(); is triggered, but map does not rendered to the new size.

**Comment by IvanSanchez** [comment]
What's the map container size, and the output of `map.getSize()` after and before the `map.invalidateSize()` call? What are the expected values?

As this is written right now, it's difficult to know what's wrong.

**Comment by nyikesda** [comment]
**After copy+paste the code to leaflet home page and press ctrl+p on Chrome you see that:**

![image](https://cloud.githubusercontent.com/assets/16609748/25432245/f50afcda-2a83-11e7-9dae-aeb8206ec648.png)

**It is right because i see same center then screen view.**

**but in Firefox:**

![image](https://cloud.githubusercontent.com/assets/16609748/25432324/442b6a48-2a84-11e7-84e4-3b4d809269ad.png)

**Comment by IvanSanchez** [comment]
...but the `beforeprint` event is fired ***once*** when the document is about to be printed, and the printing UI allows to reflow the document by tweaking the zoom factor. Those reflows are, AFAIK, impossible to catch.

**Comment by nyikesda** [comment]
window.matchMedia('print') event is fired once too, but it works, so it is a Firefox bug?

**Comment by IvanSanchez** [comment]
No, you have the same "problem" in chrome if you fiddle with the "custom margins" functionality:

![screenshot_20170426_135517](https://cloud.githubusercontent.com/assets/1125786/25433296/2db089b6-2a88-11e7-9a49-3d04d33ec58a.png)
![screenshot_20170426_135534](https://cloud.githubusercontent.com/assets/1125786/25433295/2db017b0-2a88-11e7-9497-1483cf1dbd8a.png)

Again, that's reflowing content without triggering more events.

This is one case of "it's just not possible to detect this in a web browser". Detecting reflows in a reliable and performant is impossible. That's why we still have `map.invalidateSize()`. :-(

**Comment by nyikesda** [comment]
Thank you.
