### ISSUE TITLE
window.L not set if using a module system

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#5489]
With the new Rollup build, the UMD loader will not set `window.L` if you're using a module system, like when building with Browserify. 

This is a breaking change, and breaks a number of plugins, which rely on `window.L` being set instead of explicitly importing or requiring Leaflet.

Related discussion in #2364, where the conclusion was that 1.0 (or 0.8 as it was back then) _should_ set `window.L`.

**Comment by ghybs** [comment]
Hi,

FWIW, many developers that I see asking questions (SO, GIS SE…) and using build tools (not so many people in the end, to be honest) indeed seem to expect `window.L` to be set.
E.g. see [this post on SO](http://stackoverflow.com/questions/42428251/initializing-leaflet-map-in-angular2-component-after-dom-object-exists/42431059#42431059), and even https://github.com/Leaflet/Leaflet/issues/4964.
And so do many plugins, as already mentioned.

Here is an [interesting post](http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/#update) that does propose a workaround to expose globally even through the UMD wrapper (it also cites the d3 example BTW).
Unfortunately I guess that would require making a Feature Request to Rollup?

As a side note, I think it could be interesting to provide a simple ES module entry file for power users actually using an ES module loader and expecting their build tool to optimize the bundle (I guess that it is what is implied in [that comment](https://github.com/Leaflet/Leaflet/issues/2364#issuecomment-285853971)).

Here is a [quick example](https://plnkr.co/edit/v44CXnKqxrRoSVxwMOfx?p=preview) in SystemJS.
It basically uses an entry file almost like [`src/Leaflet.js`](https://github.com/Leaflet/Leaflet/blob/master/src/Leaflet.js), but without the `version` import from `package.json` (which would require a special plugin for JSON in SystemJS, if I understand correctly) nor the `noConflict` code.

And [with a simple plugin](https://plnkr.co/edit/Z8yRSu3aN5F6zfhnTGfZ?p=preview) wrapped with a new `import` and `export` wrapper, instead of the standard UMD.
(using [Leaflet.FeatureGroup.SubGroup](https://github.com/ghybs/Leaflet.FeatureGroup.SubGroup) plugin, but could probably be applied to most plugins that have a build process)

As previously, even that example demonstrates that the biggest drawback is breaking plugins that do not adapt to the new pattern…

But at least this is just an extra option that is cheap to add.
And I feel this was one of the [potential benefits](http://leafletjs.com/2016/11/21/leaflet-1.0.2.html#next-plans) of switching to Rollup?

**Comment by perliedman** [comment]
@ghybs I read your post above in detail first now. I haven't read carefully enough to get all the details, but I think this sounds very good.

Is this something you think you could make a PR of, so that we have something more to discuss around going forward? It seems we need to come up with a plan on how to move forward with ES6 modules, plugins and bundlers.

**Comment by ghybs** [comment]
Hi,

Sure let me set up something simple.

I feel we could get a lot of inspiration from d3 build process.
