### ISSUE TITLE
pressing Enter key results in click event

### ISSUE THREAD

**Issue by egoroof** [Leaflet/Leaflet#5499]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Browser (with version) I'm using: Chrome 60 (also firefox, safari and others)
- OS/Platform (with version) I'm using: macOS Sierra 10.12.4 (also Windows 10 and Ubuntu)
- go to http://leafletjs.com/examples/quick-start/example.html
- open browser console
- click to map
- press Enter key

## What behaviour I'm expecting and which behaviour I'm seeing

Press Enter key results in click event (you may catch it by adding click event listener on map). This behaviour causes issues in different modules. In the example clicking on geometry (circle or polygon) and press Enter key logs `Cannot read property 'toString' of undefined`, clicking in other point and press Enter key logs `Cannot read property 'lat' of undefined`.

I expect suppressing Enter key as click event so I wont need to check it in every module manually.

![screen shot 2017-05-04 at 18 11 54 2](https://cloud.githubusercontent.com/assets/2605831/25701977/022733a4-30f9-11e7-834c-963e25529de6.png)

![screen shot 2017-05-04 at 18 09 07 2](https://cloud.githubusercontent.com/assets/2605831/25701976/02257f96-30f9-11e7-852d-40fa8d4b43c7.png)

**Comment by perliedman** [comment]
The conversion from `keypress` to `click` stems from 40179ed11f8f74958ea6da5789486913df2fb397, which addresses #1355. Originally this only applied to markers, but apparently we do this for any enter keypress now.

Firing `click` events without `latlng` seems like a bad idea, but on the other hand keyboard accessibility is a good thing. We need to come up with a better solution.

**Comment by IvanSanchez** [comment]
This is made by the browser, by design, for accessibility purposes. If you press `Tab` to cycle through clickable (and focusable) elements in the page, then press `Enter`, the browser itself will fire a `click` event.

I cannot reproduce any problems in my main machine (Linux) when the map is focused. Can any other user with MacOSX confirm?

**Comment by IvanSanchez** [comment]
Note that these clicks are fired by the browser and not by Leaflet, by trying out something like:

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <a id='mylink' href='#'>Foobar</a>

  <script>
    
document.getElementById('mylink').addEventListener( 'click', (ev)=>{
  console.log(ev);
  console.log('Link has been "clicked"');
} );
    
  </script>
</body>
</html>
```

See e.g. http://playground-leaflet.rhcloud.com/doru/edit?html,console,output

**Comment by egoroof** [comment]
> I cannot reproduce any problems in my main machine (Linux) when the map is focused.

I can reproduce it in Windows and Ubuntu too. Maybe you do something wrong? Click using mouse (not in the marker) and then press Enter key..

**Comment by HarelM** [comment]
Please note that this error creates a way worse bug which I just encountered on my map.
Using the example follow these steps:
1. Go to: http://leafletjs.com/examples/quick-start/example.html
2. Click anywhere on the map to create a popup with the location coordinates.
3. Hit the Enter key (which creates the error in the console).
4. Zoom in using the mouse or the zoom buttons

Bug: popup stays in the same location instead of moving according to projection. This is also true for tooltips.
Expected: popup should move as usual.
I can open a different issue for this if you need me to, but I think this is around the same area...
My scenario is a bit different - I have a marker with text area, when I hit enter in the text area to end a line I get this error, I couldn't find a way to turn it off...

**Comment by HarelM** [comment]
Thanks @perliedman!
When can we expect this fix to be released?

**Comment by perliedman** [comment]
@HarelM we're actively working on releasing 1.1.0, so "soon", but I can't provide a definitive date.

**Comment by HarelM** [comment]
@perliedman, OK, Thanks! keep up the good work!
