### ISSUE TITLE
Emulating click events for acceptance testing

### ISSUE THREAD

**Issue by knownasilya** [Leaflet/Leaflet#5519]
## How to reproduce

- Leaflet version I'm using: 1.0.3
- Leaflet Draw: 0.4.9 (only in one example)
- Browser (with version) I'm using: Chrome 58
- OS/Platform (with version) I'm using: macOS 10.12

## What behavior I'm expecting and which behavior I'm seeing

I'm expecting the click to open the popup on the top most marker.
You can see that if you click the marker, the console prints the container point, which is the same one that is printed for the map on the auto click.

The use case is for acceptance testing, where I don't have access to the geometry directly.

### Using just leaflet and plain geometry

- http://jsfiddle.net/knownasilya/ZkC5M/458/
- Automatically fires a click event (line 31) after 500ms

### Using with leaflet draw

This example requires clicking the map directly and is my primary issue.

- http://jsfiddle.net/knownasilya/qj6oghsb/2/
- Automatically fires a click event (line 83) after 500ms

The example enables draw mode, but the auto click doesn't create a vertex marker.

**Comment by perliedman** [comment]
Hi there!

There are tests in Leaflet's code base that emulate firing clicks as well as touch gestures like pinch zoom. Have you looked at those?

While we understand the need for and encourage the use of tests, this is outside the list of "normal browsers" we support. We're happy to help and include any reasonable fix if this actually turns out to be a problem in Leaflet, but from the info I have now this will not be high priority for us.

Also, the fiddle you linked to looks like it's using Leaflet 0.4.5, which is probably not representative.

**Comment by knownasilya** [comment]
I just updated the fiddle and added another one for a similar example.

**Comment by perliedman** [comment]
@knownasilya stepping through the code, I'm pretty certain the problem is with the fired event's `target`/`srcElement`: for your event, this is set to the map element, while for a normal `click` event, they are set to the marker's `img` element.

So, the event you fire is missing the information on what element was actually clicked. It's like you're clicking the map behind the marker.

**Comment by perliedman** [comment]
You can examine this closer in `Map`'s [`_findEvenetTargets`](https://github.com/Leaflet/Leaflet/blob/7a068122c78bf5b112385cf0484c896654bef907/src/map/Map.js#L1283) if you like.

**Comment by knownasilya** [comment]
Thanks for looking at this issue, really appreciate it.

I found a way to handle if for leaflet-draw, seems like they use an invisible marker that is placed where the cursor is.. for anyone looking to see how I did it, see here:

https://gist.github.com/knownasilya/d7fc8f0555b563f981543b43be570cfb

For regular geometry, I guess I could generate ids on the elements, and target them that way.
