### ISSUE TITLE
Leafleat privacy policy

### ISSUE THREAD

**Issue by ericchanf** [Leaflet/Leaflet#5528]
Hi,

I want to use leaflet in an internal web application, using private data (like showing information in a marker/popup). 
I would like to know if the js sent information in their server and 
if it is written somewhere officially that they don't retrieve data.
I checked in their licence or the FAQ but I didn't find anything about that.

Thank you

**Comment by perliedman** [comment]
Leaflet doesn't "report home" in any way. There is no data collected from the Leaflet library itself. If you host the library on your own server, there's no way to know you're even using Leaflet.

**Comment by jsemander** [comment]
@perliedman Was a privacy policy created within the last time this issue was closed?

**Comment by perliedman** [comment]
@jsemander no, not to my knowledge. In general, open source projects do not have a privacy policy, since, like I mentioned above, no data is stored by Leaflet. The library does not use cookies, a central server or anything like it. If you look at other popular open source libraries, like for example React, you will notice they do not have a privacy policy either, and I assume for the same reason.

**Comment by jsemander** [comment]
@perliedman Thanks for your help.
