### ISSUE TITLE
No way to track when L.Icon is removed

### ISSUE THREAD

**Issue by kuuup-at-work** [Leaflet/Leaflet#5558]
Hi.

When using L.Marker you can listen to the `remove` event. This is not possible with `L.Icon` or `L.DivIcon` so there is not way to run cleanup code when an icon is removed. Extending `L.Marker` doesn't help because you can attach a single `L.Icon` factory to multiple markers. This approach also fails when you use markercluster.

**Comment by SONUSADDAM8** [comment]
hi

**Comment by perliedman** [comment]
Revisiting this issue, I think a quite straight forward solution would be to add methods `destroyIcon` and `destroyShadow` to `Icon`; these correspond to already existing methods `createIcon` and `createShadow`. The default implementation would be to do nothing, but extending `Icon` you could add custom actions here.

We would then need to call `destroyIcon`/`Shadow` in `Marker`'s `_removeIcon` and `_removeShadow`.

**Comment by williamscs** [comment]
Hey @perliedman. I was taking a look at this issue... it looks like the _option member of Marker.js isn't actually an Icon object. It's the actual DOM object.

I see that in `setIcon` that we use this.options.icon to assign the actual Icon object. We don't seem to clear that in the `_removeIcon` or `_removeShadow` methods. I think that value should probably be set to null when `_removeIcon` is called, if nothing else, for clarity.

I intend to use this.options.icon to call the `destroyIcon` method. I'm not sure how to continue with the _shadow member, though. I'm probably just not going to create the `destroyShadow` method

**Comment by perliedman** [comment]
@williamscs what you're describing is intentional: the `Icon` instance does not represent a single icon, it is an instance shared by any marker using that icon. The `Icon` instance acts as a factory for DOM elements, so the marker calls `createIcon`/`createShadow` to make new DOM elements - but it's still just a single `Icon` instance.

So, since `createIcon` returns a DOM element, not an `Icon` instance, the `destroyIcon`/`destroyShadow` methods should accept the same DOM elements as arguments, and clean them up.

If you clear `this.options.icon`, it's no longer possible to re-add a marker to the map after removing it, since its icon is now cleared, which isn't what we want.

**Comment by johnd0e** [comment]
`L.Icon` is removed only when it gets unreferenced and [garbage-collected](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#garbage_collection).

And there is no possibility to track that in js code, so you should consider some alternative approach in your own code.
