### ISSUE TITLE
zIndexOffset for marker is not working as expected

### ISSUE THREAD

**Issue by lentyaishe** [Leaflet/Leaflet#5560]
Hi,

Leaflet is a very useful component but I'm facing currently a behavior which seems very weird and I could not find a workaround for it.

I'm using Leaflet 1.0.3.
I'm using Chrome Version 58.0.3029.110 (64-bit). The same happens on mobile devices my app is ported to (android/iOS).
I'm running Windows 10 Pro 64 bit

1. I'm adding a marker to the map and I want to affect its ordering by zIndex means:
`var marker = new L.Marker(location,
                {
                    icon: new L.Icon(
                        {
                            iconUrl: iconUrl,
                            iconSize: [size.width, size.height],
                            iconAnchor: [anchor.leftOffset, anchor.topOffset]
                        }),
                    draggable: draggable,
                    clickable: true,
                    zIndexOffset: zIndexOffset
                });`
In my example I'm using zIndexOffset of 202.

2. After adding the marker to the map (marker.addTo(map)) immediately I see that the marker object changes and get a zIndex of 619. Actually each application run with the same initial zIndexOffset I get a different zIndex on marker object after adding it to the map.

3. I have an event listener on 'mousedown' event and when I inspect the marker object received by the listener zIndex is again different (477). Meaning it has changed even from the arbitrary value set in setp 2.

4. In case I zoom in and out the map the zIndex will change again.

All of this doesn't allow me to set different markers on top of others since step 2 change ruins any logic I may use in my code.

Here's the example of what happens in the [leaflet playground](http://playground-leaflet.rhcloud.com/gexa/edit?html,console,output):

How could this be fixed or maybe any workaround?

Thanks in advance

**Comment by IvanSanchez** [comment]
This is not a bug, this is behaviour as expected.

You have to keep in mind that the option name is zIndex**Offset**, and **not** `zIndex`. The `zIndex` of each marker depends on the *vertical coordinate of the marker*. 

Look at this screenshot from https://github.com/Leaflet/Leaflet.Icon.Glyph:

![](https://camo.githubusercontent.com/09ba35cbec1a15aaf2a599be333a85d701f69ead/68747470733a2f2f6c6561666c65742e6769746875622e696f2f4c6561666c65742e49636f6e2e476c7970682f64656d6f2e706e67)

Do you see how you can only see the tip of the bottom-most markers? That's because the `zIndex` of the markers in the bottom row is greater than in the second row, which have a `zIndex` greater than those in the third row, and so on. The `zIndex` is not arbitrary. It grows by 1 for every pixel down. It also gets recalculated on zooming and some view resets.

Thus, the zIndex**Offset** option is an **offset** which applies to the seemingly arbitrary `zIndex`. Thus, if I wanted the center marker to be on top of the rest, I'd set a `zIndexOffset` of at least the height of a marker, and it would look like:

![image](https://user-images.githubusercontent.com/1125786/27128107-a2a6bbb4-50fd-11e7-8244-12efd37cc3d3.png)

> All of this doesn't allow me to set different markers on top of others since step 2 change ruins any logic I may use in my code.

> Here's the example of what happens in the leaflet playground:

If the problem is that you can't set which marker goes on top, *show me an example of how that fails*, because that playground only logs a value, it does not show me markers failing to display on top of other markers. You have felt into the [XY problem](https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem).

If you still need fine control over things on top of things, consider [using map panes](http://leafletjs.com/examples/map-panes/), or post a more obvious example.

**Comment by lentyaishe** [comment]
Hi,

Thanks for your quick response.

I've found this behavior right now and from my perspective it's definitely wrong...

Suppose you have only 2 markers on the map, A is above the B in pixels perspective. Then A will always appear below the B in zIndex means. But if I'll drag the A to be positioned below B in pixels perspective and leave it, after this action A will appear on top of B in zIndex meaning. Each marker dragging recalculates its zIndex. This results in incorrect behavior in our app.

What we need is to allow drawing several segments of polylines. Each segment is just several polylines connected while each tip of the segment and each connection of 2 polylines are marked with markers.

Then suppose I have 2 such segments while their markers appear wherever you like on the map in a mixed mode. But what I need is the ability to have one of the segments active and each of its markers shown on top of markers of inactive segment. But in case any marker of the active segment is very close to a marker of inactive segment and the marker of active segment appears below the marker of inactive segment in pixels perspective, it will appear under the marker of inactive segment which is wrong and I have no tool to make it work in a correct way with the logic you provide.

What can be done about it?

**Comment by IvanSanchez** [comment]
> Each marker dragging recalculates its zIndex.

...and it should definitely reapply the `zIndexOffset`, does it not?

> But what I need is the ability to have one of the segments active and each of its markers shown on top of markers of inactive segment.
> What can be done about it?

As I've already said: [map panes](http://leafletjs.com/examples/map-panes/). You can have the markers for the ""active"" segment drawn on a different pane, which has a static `zIndex` relative to the other panes. Note that `zIndexOffset` applies to the `zIndex` of the DOM elements *inside* a pane, but you can control the `zIndex` of the parent DOM element, which is the pane.

**Comment by lentyaishe** [comment]
Okay, I'll check the panes. It may help me solve the segments problem but then appears a problem with markers of the same segment.

In case 2 markers are close to each other and the one that should be active is below the other that is inactive the same problem will reappear..

So what is your suggestion? Use pane for each marker?

**Comment by IvanSanchez** [comment]
I don't know. Show me an example of the problematic case (playground or screenshots or anything) and we might be able to have ideas.

But please remind that this is a bug tracker, for bugs in Leaflet. Don't expect us to offer consultancy on how to build X using leaflet, that's out of the scope.

**Comment by themre** [comment]
perhaps use some `marker.on('mouseover', function(l) { l.bringToFront() })` and `marker.on('mouseoout', function(l) { l.bringToBack() })`. I'm not 100% certain names of events are correct, you can maybe check them out.

**Comment by lentyaishe** [comment]
@themre Unfortunately this solution is not perfect also. Suppose there are 2 markers exactly at the same location from map's perspective but different coordinates. There always be only one marker on top and mouseover event won't bring the marker that's below on top of the one that's on top.

**Comment by lentyaishe** [comment]
@IvanSanchez Look at the problem on the picture. The marker with the black arrow is the active marker.
![1](https://user-images.githubusercontent.com/14091163/27130503-297b3b54-510f-11e7-8c39-ccea05ce53d8.jpg)

**Comment by IvanSanchez** [comment]
@lentyaishe And what are the `zIndexOffset`s and the computed `zIndex`es of both?

**Comment by lentyaishe** [comment]
@IvanSanchez 
The active marker: zIndexOffset = 5, zIndex = 239
Inactive marker: zIndexOffset = 10, zIndex = 567
Do you want me to try artificially update the zIndexOffset of the active marker on click and check whether it will reappear on top of inactive one? I really doubt it'll happen.

**Comment by IvanSanchez** [comment]
@lentyaishe No, I want you to set the `zIndexOffset` of the "active" marker to a much higher value than the inactive one (which I'd suggest letting at zero). Try 50 or 100, or 500.

**Comment by lentyaishe** [comment]
@IvanSanchez Actually it did.. I've used marker.setZIndexOffset(100) on the clicked active marker (A) that was below and it appeared on top of inactive one (B) but then the click on B made it on top and clicking A again has left it behind. This means that I'll need to recalculate all markers zIndexOffsets on the map to make it work as I need which is too much. Also in our setup we may have dozens of markers on the map. This way we'll reach enormous values for zIndex which also seems not good...

That's the point that in case I could have managed the actual zIndex of markers on the map it would solve everything since I could have just decided that all active objects may have zIndex above 500 and all others will have below that. Then I should have just change values of last active objects zIndexes below 500 and the newly activated one above etc. And zIndexes of markers within a specific segment also could have similar logic, i.e below 550 inactive, above 550 - active. Anyway then it's my problem to make zIndexes work for me as expected. And currently since the map component decides for me the actual zIndex value, it messes all my logic up.

**Comment by IvanSanchez** [comment]
> Actually it did.. I've used marker.setZIndexOffset(100) on the clicked active marker (A) that was below and it appeared on top of inactive one (B) but then the click on B made it on top and clicking A again has left it behind. This means that I'll need to recalculate all markers zIndexOffsets on the map to make it work as I need which is too much.

No. It means that you have to reset the `zIndexOffset` of a marker whenever it changes state from inactive to active, or from inactive to active.

> This way we'll reach enormous values for zIndex which also seems not good...

A `zIndex` is an integer which can go up to the millions, and we *never* had any issue with high values. We do know that some browsers have a limit on integer CSS properties of 2^23 (see https://github.com/Leaflet/Leaflet/commit/c5172f3088b820325e726f57f0b09b16b1ec498d, https://github.com/Leaflet/Leaflet/commit/17c180e1eff97932c3450447d5d17fda199f7c2c), but `zIndex`es have never been a big problem, because Leaflet recalculates them once in a while on every `viewreset`, so the values for both the CSS transforms and the `zIndex`es are within a manageable range.

In my experience, it's better to learn about the [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index) than to be afraid of misusing `z-index`.

> That's the point that in case I could have managed the actual zIndex of markers on the map it would solve everything [...]

No you wouldn't, because if you're not resetting the `zIndex`es of the markers which transition from active to inactive, you would end up with the same problem.

I mean, if you want to *really* try if your logic would work without Leaflet's management of `zIndex`/`zIndexOffset`, you can manually disable it with something like

```js
L.Marker.prototype._updateZIndex = function(offset) {
  // this._icon.style.zIndex = this._zIndex + offset;
}
```

So far, you've been subtly suggesting that Leaflet is the culprit and that your logic is infallible. [Programmers like myself don't react well to this kind of bug reporting](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#symptoms). I bet you a beer that the problem is in the logic in your side, and that it won't matter if you manage raw `zIndex`es or `zIndexOffset`s.

If you can *isolate* a case where Leaflet fails to raise a marker's `zIndex` when raising its `zIndexOffset`, of fails to lower it, please do share a playground or similar.

**Comment by lentyaishe** [comment]
> you can manually disable it

Thanks for the suggestion. I'll try it out. It also gave me an insight on how you implement the layouting.

> your logic is infallible

Not at all. :) I just think that the API should allow disabling the recalculation of `zIndex`es and allow the API customer break his own head on how to implement what he needs.

> If you can _isolate_ a case where Leaflet fails...

The scenario is extremely simple. Use `zIndexOffset` for 2 markers with difference of 5. Since the zIndex that each marker gets from your algorithm is hundreds you may come up with the following:
`zIndexOffset(A) > zIndexOffset(B)` set by the code
but
`zIndex(A) < zIndex(B)` calculated by leaflet
And since `zIndex` is recalculated on each map operation: drag, move, zoom etc. there's no way to get the actual difference in `zIndexOffset` for markers to make it work correctly for `zIndex`es that will be calculated.

**Comment by lentyaishe** [comment]
Well, finally I came up with a solution that works fine for me:
Since in your algo you just sum the `zIndex` calculated by leaflet and `zIndexOffset` provided from outside and since all `zIndex`es you deal with are hundreds I'm just working with `zIndexOffset`s in multiplications of 1000s. A bit dirty but it does the job.

Anyway, **thanks a bunch for your rapid help**!

**Comment by NormandoHall** [comment]
@lentyaishe I was used this gist an run like a charm. Maybe this can be a Feature Request?

https://gist.github.com/up209d/4c68f2391f2302e510eb81aa8bcd4514

**Comment by catherinezhxj** [comment]
> Well, finally I came up with a solution that works fine for me:
> Since in your algo you just sum the `zIndex` calculated by leaflet and `zIndexOffset` provided from outside and since all `zIndex`es you deal with are hundreds I'm just working with `zIndexOffset`s in multiplications of 1000s. A bit dirty but it does the job.
> 
> Anyway, **thanks a bunch for your rapid help**!

I have the same problem as you. Marker's Z-index changes when scaling, but I don't want to change z-index. I want to know your final solution.

**Comment by lentyaishe** [comment]
> > Well, finally I came up with a solution that works fine for me:
> > Since in your algo you just sum the `zIndex` calculated by leaflet and `zIndexOffset` provided from outside and since all `zIndex`es you deal with are hundreds I'm just working with `zIndexOffset`s in multiplications of 1000s. A bit dirty but it does the job.
> > Anyway, **thanks a bunch for your rapid help**!
> 
> I have the same problem as you. Marker's Z-index changes when scaling, but I don't want to change z-index. I want to know your final solution.

This is my final solution.

**Comment by andrewhodel** [comment]
The documentation says:

```
By default, marker images zIndex is set automatically based on its latitude. Use this option if you want to put the marker on top of all others (or below), specifying a high value like 1000 (or high negative value, respectively).
```

It should mention that the "automatic" setting based on the latitude shall not be greater than N, instead of "specifying a high value like 1000".

**Comment by andrewhodel** [comment]
It's not explained correctly here.

zIndexOffset difference of 40000 does not place marker visibly above/on top of another marker that is 10 degrees lower vertically on the cartesian map

Here's a perfect example:


https://plnkr.co/edit/hyWro1sGgmjbeDPk

**Expected behavior**

The Google logo should be visually above (per z-index) the Yandex logo.

**Current behavior**

The Yandex logo is shown as on top of the google logo.

**Comment by Falke-Design** [comment]
@andrewhodel use the `zIndexOffset` in the marker options not in the icon options:
```
var n = L.marker([30.505, 0.57], {icon: myIcon, zIndexOffset: 80000}).addTo(map);
```

**Comment by andrewhodel** [comment]
@Falke-Design does not work.

<img width="638" alt="Screen Shot 2022-02-07 at 4 22 30 PM" src="https://user-images.githubusercontent.com/741705/152796083-55234af0-474a-4d07-97ad-e894016f3662.png">

**Comment by Falke-Design** [comment]
It does work, look into the updated sampel: https://plnkr.co/edit/GcnZAG6c5vjPaXIl

**Comment by andrewhodel** [comment]
@Falke-Design I think it's simply a sad reality of the layers and how things don't understand beyond them.

I've already confirmed it.  It does not work with zIndexOffset with svg icons as shown in the screenshot.

It's all being set with marker_opts{}.zIndexOffset

**Comment by andrewhodel** [comment]
@Falke-Design it's very simple to understand that when a DOM element has a z-index of 4231 and shows beneath a DOM element with a z-index of 4220 that something is awry.

The marker layer maximum is 600 and set to never change in leaflet.

It's really easy to read that in the code with `grep`.

**Comment by Falke-Design** [comment]
Please provide a sample that doesn't work. I already showed you in the current sample from you that it is possible.

**Comment by andrewhodel** [comment]
There's nothing but the DOM here, really.

There's no need to explain anything else, if 600 is the containing element limit set statically in the library it doesn't matter what you set them at and that is based on how the layers are applied.

@Falke-Design

**Comment by Falke-Design** [comment]
It is not always that simple to understand what somebody else tries to explain. 
I hope for you that you find someone who wants to help you because I will not and I don't think that anyone is willing to help you if you keep that attitude.

**Comment by andrewhodel** [comment]
> It is not always that simple to understand what somebody else tries to explain. I hope for you that you find someone who wants to help you because I will not and I don't think that anyone is willing to help you if you keep that attitude.

If you are worried about the attitude they will all take advantage of your work, you might as well accept that it's no big deal to not think of every layer and just respond as "I wasn't trying to make fun but only trying to help".

The reality is that many people take advantage of others with this type stuff.

Be sincere here in regards to the library, you should be searching through and finding out why a layer would limit it's z-index at 600 if it allowed elements inside it to be beyond that.  That's the real problem and I provided a screenshot that shows that happening.

Don't be so petty about it, it's more about why is nobody saying that an arbitrary limit on the layer is a terrible idea?

Seriously, the next layer is 650!

Here's the documentation from leaflet.

<img width="960" alt="Screen Shot 2022-02-07 at 4 45 32 PM" src="https://user-images.githubusercontent.com/741705/152799764-9d4e636e-7aac-4989-b526-7da6b778255e.png">
