### ISSUE TITLE
Pop-up size and scroll bars

### ISSUE THREAD

**Issue by Sven74Muc** [Leaflet/Leaflet#5579]
Not 100% sure if this is a leaflet or a CSS issue mapsmarker pro neads to solve

Please see the picture and the red arrow:

![scroll](https://user-images.githubusercontent.com/27951109/27508807-998dd768-58ed-11e7-8d5a-24a71807dcb8.jpg)

As you see there is an issue with the image with. The horizontal scrollbar should not be there. The image is exactly the with of the pop-up, but needs to be the pop-up size excluded the width of the scroll bar. 

I tested this in different browser:

1. Chrome cutts the image by the size of the scrol bar (does not show 100% width of the image 
2. Firefox shows 100% width of the image but you need to scroll horizontal 
3. Thunderbird is the same like with Crome 
4. Microsoft Edge is the same like with Firefox

On a touchscreen device like my iPad there is no scroll bar and no issue.

The pop-up (marker) width (CSS) is set to auto. There is a min-width of 250px and a max-with of 600px. Setting the pop-up width to 100% will open the pop-up in the min-with of 250px (which is wrong.
So correct is with the popup- width:auto... just the horrizontal scroll is wrong.

Is there a way that the image will shown 100%, not be overlaped with the vertical scroll and there is no vertical scroll bar?

**Comment by ghybs** [comment]
Hi,

Please can you reproduce your issue with _just_ Leaflet, no Mapsmarker Pro?
You can use the [Leaflet playground](http://playground-leaflet.rhcloud.com/sudu/edit?html,output) for example.

Thanks!

**Comment by Sven74Muc** [comment]
Don't know how to do this. If I replace the Lorem ipsum text of the marker with an image I get an empty output.

I replaced the text with an image link like this:
<img src="http://domain.com/image.jpg" alt="" width="750" />

**Comment by Sven74Muc** [comment]
http://playground-leaflet.rhcloud.com/qasu/edit?html,output

**Comment by ghybs** [comment]
@Sven74Muc,

I had to fix your quoting, but still it does not reproduce your issue.
http://playground-leaflet.rhcloud.com/cofe/edit?html,output

The image being too big and not being resized, it extends beyond the popup, but if I understand correctly, you are changing the popup settings to account for it?

Please reproduce your issue in the playground, otherwise it is impossible for us to figure out what could be wrong.

Thanks.

**Comment by Sven74Muc** [comment]
mapsmarker implementet a pre-load function for the image to lad the image befor opening the pop-up. with this they got ridd of the issue we see in your link that the image is to big. they reduce the image to the max-with size of the pop-up (image is set to with:auto)

think this is more a general styling issue... to add "overflow-x:hidden" somewhere (???) could be a workarround. this could be easy, but is not perfect, would mean that the image will be cutted by the with of the scroll bar.

Where do I need to place the "overflow-x:hidden"?

The image needs to be set to with:auto, not to width:100%. Auto means that the image will be reduced to the pop-up size. Is there a way to set the image size to auto-"scroll bar width", means to identify the pop-up with excluding the scroll bar?

**Comment by ghybs** [comment]
Thank you for the additional details.
Next time please make sure you check all the items in the issue template.
These ensure that you provide all the required details for people to be able to provide you with relevant help, instead of wasting time.

From your description, a wrapper plugin (Maps Marker Pro) is adjusting the CSS of your image and/or the popup.
As explained in the issue template, Leaflet maintainers cannot spend time supporting 3rd party libraries, especially when we do not even have access to the code to understand exactly what is going on.

You should have the plugin vendor work on your issue, and if they are sure there is a bug in Leaflet, please provide a live test case to reproduce it.

You might also be interested in trying libraries that emulate on desktop browsers the auto-hiding scrollbars like on touch devices, like [nanoScroller.js](https://jamesflorentino.github.io/nanoScrollerJS/) or [perfect-scrollbar](http://noraesae.github.io/perfect-scrollbar/), but there is no guarantee it would also be free of bugs when used within Leaflet.
