### ISSUE TITLE
L.Util L.DomUtil is not extensible in leaflet 1.1.0?

### ISSUE THREAD

**Issue by rendrom** [Leaflet/Leaflet#5589]
Сan not add a custom property to an L.Util or L.DomUtil object since leaflet version 1.1.0:
https://jsfiddle.net/rendrom/Lj63c72u/

But it works in 1.0.3 and earlier:
https://jsfiddle.net/rendrom/scvpb4s2/

This is a new behavior or ES6 Rollup build result?

Example incompatibility in plugins:
https://github.com/w8r/Leaflet.Modal/blob/master/src/modal.js#L16

**Comment by IvanSanchez** [comment]
This is a byproduct of the Rollup build. If you look at the built files, you'll find:

```
var Util = (Object.freeze || Object)({
	extend: extend,
	create: create,
	bind: bind,
        // etc
```

This happens because if you code something like this in ES2015...

```
import Util from 'leaflet/Util';

Util.somethingNew = 'foo'; // Error here, can not add things to an imported module
```

You can check this by [visiting this link to the Rollup REPL](http://rollupjs.org/#%7B%22options%22%3A%7B%22format%22%3A%22cjs%22%2C%22moduleName%22%3A%22myBundle%22%2C%22globals%22%3A%7B%7D%7D%2C%22modules%22%3A%5B%7B%22name%22%3A%22main.js%22%2C%22code%22%3A%22import%20*%20as%20Maths%20from%20%27.%2Fmaths.js%27%3B%5Cn%5CnMaths.foo%5Cn%5Cnconsole.log(%20Maths.cube(%205%20)%20)%3B%20%2F%2F%20125%22%7D%2C%7B%22name%22%3A%22maths.js%22%2C%22code%22%3A%22%2F%2F%20This%20function%20isn%27t%20used%20anywhere%2C%20so%5Cn%2F%2F%20Rollup%20excludes%20it%20from%20the%20bundle...%5Cnexport%20function%20square%20(%20x%20)%20%7B%5Cn%5Ctreturn%20x%20*%20x%3B%5Cn%7D%5Cn%5Cn%2F%2F%20This%20function%20gets%20included%5Cnexport%20function%20cube%20(%20x%20)%20%7B%5Cn%5Ct%2F%2F%20rewrite%20this%20as%20%60square(%20x%20)%20*%20x%60%5Cn%5Ct%2F%2F%20and%20see%20what%20happens!%5Cn%5Ctreturn%20x%20*%20x%20*%20x%3B%5Cn%7D%22%7D%5D%7D)

The current situation is that plugins are able to modify Leaflet's namespaces (I'm guilty as charged, as I'm defining [`L.Browser.gl`](https://gitlab.com/IvanSanchez/Leaflet.GLMarkers/blob/master/src/GLMarkers.js#L6) in one of my plugins). The problem is that another plugin could come, reimplementing that very same namespace, and making the previous plugin fail.

The ""right"" approach would be to either:

* Put that functionality into the plugin's namespace, without touching the `L` namespace
* If that functionality is to be used elsewhere, make it its own module, and import it accordingly.

**Comment by MuellerMatthew** [comment]
Since this is a breaking issue with the previous versions of Leaflet, would it make sense to rollback the change temporarily, and issue a console warning or an alert of some sort saying that the ability is depreciated and that it will be removed in the next version?  There appears to be numerous published and unpublished plugins which used this feature.

**Comment by perliedman** [comment]
@MuellerMatthew in hindsight, it might have been a bad idea to introduce this change without bumping the major version, as you say this is a breaking change, or at least breaks a pretty common pattern, even though I don't think it has been explicitly documented or supported.

Unfortunately, we are way beyond reverting the ES6 change, it touches an extremely large portion of the source and backing it out would also undo almost all changes we made since 1.0.3.

I think the only way forward is to clearly state that plugins can/should only add methods to real classes, not namespaces.

**Comment by MuellerMatthew** [comment]
Thats fine.  I think we should probably updated the documentation for plugins then so that we say that for plugins after 1.0.3 there are different rules.  

Under the **Plugin API** title it currently says:
> If you have a new class, put it directly in the L namespace (L.MyPlugin).
If you inherit one of the existing classes, make it a sub-property (L.TileLayer.Banana).
Every class should have a factory function in camelCase, e.g. (L.tileLayer.banana).
If you want to add new methods to existing Leaflet classes, you can do it like this: L.Marker.include({myPlugin: …}). 

https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md

**Comment by oberhamsi** [comment]
I would suggest also putting this into the changelog.i guess there are lots of plugins extending L.Util - i found utgrid and filelayer do that.

**Comment by calvinmetcalf** [comment]
so fyi the issue is actually `import * as foo from 'bar'` vs `import foo from 'bar'`

**Comment by calvinmetcalf** [comment]
actually it's slightly worse as L is never exported as an object you can't add anything to L either

**Comment by mourner** [comment]
Merging this issue with #5650.
