### ISSUE TITLE
[1.1] Extending L.Control.Layers with `collapsed: false` -  Cannot read property 'length' of undefined at NewClass._checkDisabledLayers

### ISSUE THREAD

**Issue by kofronpi** [Leaflet/Leaflet#5590]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using:   Chrome Version 57.0.2987.133 (64-bit)
- OS/Platform (with version) I'm using: Ubuntu 16.04 x86_64 4.4.0-59-generic
- Step 1 : Import this snippet of code which should be compatible with Leaflet 1.1 new API : https://github.com/davicustodio/Leaflet.StyledLayerControl/blob/master/src/styledLayerControl.js and change option `collapsed` to `false`
- Step 2 : Use the previously imported code:

```
var arr, baseMaps, control, i, len, options, overlays, poiGroup, ref;

overlays = [];

baseMaps = [];

options = {
  container_width: '180px',
  container_maxHeight: '350px',
  group_maxHeight: '300px',
  exclusive: false
};

control = L.Control.styledLayerControl(baseMaps, overlays, options);

ref = data.match.transport_list_meta['Transports'];
for (i = 0, len = ref.length; i < len; i++) {
  arr = ref[i];
  poiGroup = L.geoJson(data.match[arr[0]], {
    pointToLayer: (function(_this) {
      return function(feature, latlng) {
        return L.marker(latlng, {
          icon: _this.transportIcon
        });
      };
    })(this),
    onEachFeature: (function(_this) {
      return function(feature, layer) {
        return layer.bindPopup(feature.properties.name);
      };
    })(this)
  });
  control.addOverlay(poiGroup, arr[1], {
    groupName: 'any_name'
  });
}

this.map.addControl(control);
```

## What behaviour I'm expecting and which behaviour I'm seeing

This extended ControlLayer worked well with Leaflet 1.0.3.

It still works, but triggers an error in the web console:

```
leaflet-src.self-2632dc6….js?body=1:5110 Uncaught TypeError: Cannot read property 'length' of undefined
    at NewClass._checkDisabledLayers (leaflet-src.self-2632dc6….js?body=1:5110)
    at NewClass.expand (leaflet-src.self-2632dc6….js?body=1:4870)
    at NewClass._expandIfNotCollapsed (leaflet-src.self-2632dc6….js?body=1:5121)
    at NewClass.addTo (leaflet-src.self-2632dc6….js?body=1:4821)
    at NewClass.addControl (leaflet-src.self-2632dc6….js?body=1:4676)
     [...]
```

## Minimal example reproducing the issue

- This example relies on third party code.

Full example without overlays: (it's the same error with or without overlays)
https://playground-leaflet.rhcloud.com/heki/edit

**Comment by ghybs** [comment]
Hi,

Thank you for reporting this issue.

However it seems to me that the proper place to raise this bug would have been first in the [Leaflet.StyledLayerControl plugin repository](https://github.com/davicustodio/Leaflet.StyledLayerControl)'s own issue tracker?

I guess it uses Leaflet private methods, which may not be backward compatible even just for minor version changes.

In the specific case of the example you provide, it looks like the plugin overrides the [`_addItem`](https://github.com/davicustodio/Leaflet.StyledLayerControl/blob/8425179eeeee2d2aabbd3ce2ecb11949ba31caee/src/styledLayerControl.js#L302-L394) private method of [`L.Control.Layers`](https://github.com/Leaflet/Leaflet/blob/v1.1.0/src/control/Control.Layers.js#L326-L361).

The latter has been modified in Leaflet 1.1 to overcome a bug when the Layer name includes an `<input>` (see PR https://github.com/Leaflet/Leaflet/pull/5544 and initial issue https://github.com/Leaflet/Leaflet/issues/5116).

Therefore it seems to me that the plugin should update its method override in order to maintain compatibility with Leaflet 1.1 and above.

If you are really sure there is a bug in Leaflet itself, please re-open and provide a minimal test case reproducing the issue, without any 3rd party library.

**Comment by kofronpi** [comment]
@ghybs thank you for your insight, I will indeed check with the repo's owner.

**Comment by gilbertoss** [comment]
@kofronpi Hi, did you find out why? I have the same problem.

**Comment by kofronpi** [comment]
@gilbertoss hi, no, despite updating to leaflet 1.2

**Comment by gilbertoss** [comment]
@kofronpi hi, I'm also using version 1.2, actually the error started when I migrated to 1.2.
I have a call that triggers the error now:
`lcontrol = L.Control.styledLayerControl (mapTiles, mapFeatures, layerOptions) .addTo(map);`
It ends up invoking `_checkDisabledLayers()` before starting the `_layerControlInputs` variable from leaflet.js

TypeError: inputs is undefined[Learn More] leaflet.js:5111:22
	_checkDisabledLayers http://d8ox.docker.localhost:8000/themes/d8ox/scripts/vendor/leaflet.js:5111:22
	expand http://d8ox.docker.localhost:8000/themes/d8ox/scripts/vendor/leaflet.js:4876:13
	_expandIfNotCollapsed http://d8ox.docker.localhost:8000/themes/d8ox/scripts/vendor/leaflet.js:5122:17
	addTo http://d8ox.docker.localhost:8000/themes/d8ox/scripts/vendor/leaflet.js:4827:20
	initMap http://d8ox.docker.localhost:8000/themes/d8ox/scripts/d8ox-map.js:203:14
	initDegMap http://d8ox.docker.localhost:8000/themes/d8ox/scripts/maps/degradation/d8ox-degmap.js:53:3
	<anonymous> http://d8ox.docker.localhost:8000/themes/d8ox/scripts/maps/degradation/d8ox-degmap.js:201:1

And you, @ghybs, any ideas?

**Comment by ghybs** [comment]
Hi @gilbertoss,

Should not you report this issue in the plugin issue tracker instead?
You could also give a try in Stack Overflow.

Providing a reproduction example in each case would also help people understanding the issue.

**Comment by gilbertoss** [comment]
Ok @ghybs. 
You're right, I'll try in Stack Overflow.
Sorry and thanks!

**Comment by gilbertoss** [comment]
The problem was in lib Leaflet.StyledLayerControl. Was made a Merge Requests for the developer [here](https://github.com/davicustodio/Leaflet.StyledLayerControl/pull/38)
