### ISSUE TITLE
L.Layer.remove is not final

### ISSUE THREAD

**Issue by Marco-Bronner** [Leaflet/Leaflet#5621]
## How to reproduce

- Leaflet version I'm using: 1.1.0 and 1.0.3
- Browser (with version) I'm using: Firefox 52.2.1, Google Chrome 56.0.2924.87
- OS/Platform (with version) I'm using: Windows 10
- step 1
Add any amount of marker to a map.
- step 2
at runtime remove a marker
- step 3
use layer control to deactivate the layer holding the marker you just removed
- step 4
use layer control to active the layer holding the marker

## What behavior I'm expecting and which behavior I'm seeing
expecting: the marker should be removed 
seeing: the marker is visible again, clickable, can be interacted with

## Minimal example reproducing the issue
(click anywhere on the map -> marker appears
click the marker -> marker disappears
open layer control, top right, uncheck 'Cities'
open layer control check 'Cities')

http://playground-leaflet.rhcloud.com/qapi/1

**Comment by perliedman** [comment]
Hi and thanks for reporting!

`remove` might be a bit confusing in this particular case, but note that [the docs for `remove`](http://leafletjs.com/reference-1.1.0.html#layer-remove) says:

> Removes the layer from **the map** it is currently active on.

(Emphasis added by me.)

This means that in the example you link to, the `remove` call does indeed remove the marker from the map, but does not remove it from the `LayerGroup` you've also added it to. This means, next time the group is added to the map (for example by enabling it from the layer control), this marker will once again be added to the map.

A better way would be to remove it from the group, using the group's `removeLayer` method, instead of the marker's `remove` method.
