### ISSUE TITLE
Mouse Wheel Zoom Experience Changed

### ISSUE THREAD

**Issue by marioatmicello** [Leaflet/Leaflet#5622]
I'm seeing a different zooming experience on leaflet 1.1.0 compared to 1.0.0 when using the mouse wheel.

If I slowly move the mouse wheel forward / backward and change the zoom one level at a time I do not see any issue.

However, if I quickly spin my mouse wheel in either direction, the map completely disappears, then reappears after the desired zoom level is set. 

This happens on tiles that have already been loaded into the browser so I ruled out the possibility that this is a case of tiles that have no been loaded yet.

The "expected" behavior here is to have the tiles either be blurry or much smaller (based on whether I am zooming in or out) before the desired zoom level tiles could replace the current zoom level tiles.

I see this on leafletjs.com using Chrome, Edge and Firefox (all latest or close to it )

**Comment by perliedman** [comment]
Hi!

It does indeed look like we have some kind of regression here:

* looking at 1.0.0, zooming in quickly clearly shows "blurry" tiles until new ones have loaded: http://playground-leaflet.rhcloud.com/kiwus/
* using latest Leaflet doing the same shows grey background until new tiles load: http://playground-leaflet.rhcloud.com/dada/

I would be suspicious of #5431. Lets look at what happens if we back out that patch first, otherwise I'll guess we have to bisect to track this down.

**Comment by oliverheilig** [comment]
@perliedman  yes, can confirm this. Reverting the changes fixes the regression, but reintroduces the missing tiles. Again, searching for the code where these tiles are actually evicted...

**Comment by oliverheilig** [comment]
@perliedman I've reverted the patch #5634 and found the real cause for #5381

**Comment by perliedman** [comment]
Should be fixed by #5634, that was just merged.
