### ISSUE TITLE
Double-tap with Chrome on Android does not work

### ISSUE THREAD

**Issue by andrea06** [Leaflet/Leaflet#5627]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Chrome 58 or 59
- OS/Platform (with version) I'm using: Android 4.4

## What behaviour I'm expecting and which behaviour I'm seeing
Double-tap (e.g. zoom in) does not work
## Minimal example reproducing the issue

Leaflet home page example

**Comment by perliedman** [comment]
Hi and thanks for reporting on this! That does indeed look like a bug.

Checking this playground example, double tap zoom works as expected with latest Leaflet when run in edit mode: http://playground-leaflet.rhcloud.com/debu/edit?html,output - but switching to view mode makes double tap stop working: http://playground-leaflet.rhcloud.com/debu/ . A bit perplexed by this, we will have to investigate what's going on here.

**Comment by guillaumebof** [comment]
I have the same problem, double tap don't zoom on chrome 59 / android 6.0, neither in edit mode on : http://playground-leaflet.rhcloud.com/debu/edit?html,output

**Comment by jjimenezshaw** [comment]
I reproduced it on my Ubuntu 16.04, Chromium  60.0.3112.78, using the "device mode" (to fake a mobile or tablet). I don't know how reliable is this mode, but double-tap works in other pages in this mode.

**Comment by jjimenezshaw** [comment]
Since when is this happening? (Leaflet and Chrome versions)

I have been testing this web https://playground-leaflet.rhcloud.com/belu/edit?html,output in some browsers. It shows the events, and obviously doesn't show dblclick on Chrome in Android.
And I guess that I got some changes that fix it. I am not really sure. Let me show you:

The changes remove the browser brand checks from `DomEvent.DoubleTap.js` and `DomEvent.js`. Maybe it is a regression (#5180 or others). Again, I am not sure if this fix completely the problem.
```javascript 
diff --git a/src/dom/DomEvent.DoubleTap.js b/src/dom/DomEvent.DoubleTap.js
index 733096e..31ae930 100644
--- a/src/dom/DomEvent.DoubleTap.js
+++ b/src/dom/DomEvent.DoubleTap.js
@@ -19,7 +19,7 @@ export function addDoubleTapListener(obj, handler, id) {
                var count;
 
                if (Browser.pointer) {
-                       if ((!Browser.edge) || e.pointerType === 'mouse') { return; }
+                       if (e.pointerType === 'mouse') { return; }
                        count = _pointersCount;
                } else {
                        count = e.touches.length;
@@ -38,7 +38,7 @@ export function addDoubleTapListener(obj, handler, id) {
        function onTouchEnd(e) {
                if (doubleTap && !touch.cancelBubble) {
                        if (Browser.pointer) {
-                               if ((!Browser.edge) || e.pointerType === 'mouse') { return; }
+                               if (e.pointerType === 'mouse') { return; }
                                // work around .type being readonly with MSPointer* events
                                var newTouch = {},
                                    prop, i;
diff --git a/src/dom/DomEvent.js b/src/dom/DomEvent.js
index 01ae59e..09be848 100644
--- a/src/dom/DomEvent.js
+++ b/src/dom/DomEvent.js
@@ -89,8 +89,7 @@ function addOne(obj, type, fn, context) {
                // Needs DomEvent.Pointer.js
                addPointerListener(obj, type, handler, id);
 
-       } else if (Browser.touch && (type === 'dblclick') && addDoubleTapListener &&
-                  !(Browser.pointer && Browser.chrome)) {
+       } else if (Browser.touch && (type === 'dblclick') && addDoubleTapListener) {
                // Chrome >55 does not need the synthetic dblclicks from addDoubleTapListener
                // See #5180
                addDoubleTapListener(obj, handler, id);
```
I have tested on Chromium 60 (Ubuntu, and simulated device), Chrome 59 (Android), Firefox 54 (Ubuntu), Firefox 55 (Android), and Edge 40 (Windows 10). It works there, and dblclick only appear once.

These are the events triggered on every browser shown using the link above (doing doble click or tap once):

* Chromium 60 Ubuntu
Leaflet 1.2.0+master.c63b014
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.78 Chrome/60.0.3112.78 Safari/537.36
pointerdown pointer (mouse)
mousedown mouse (1)
pointerup pointer (mouse)
mouseup mouse (1)
click mouse (1)
pointerdown pointer (mouse)
mousedown mouse (2)
pointerup pointer (mouse)
mouseup mouse (2)
click mouse (2)
**dblclick** mouse (2)

* Chromium 60 Ubuntu (simulated device)
Leaflet 1.2.0+master.c63b014
Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.78 Mobile Safari/537.36
pointerdown pointer (touch)
pointerup pointer (touch)
click mouse (0)
pointerdown pointer (touch)
**dblclick** synthetic
pointerup pointer (touch)

* Chrome 59 Android
Leaflet 1.2.0+master.c63b014
Mozilla/5.0 (Linux; Android 7.1.1; Aquaris X5 Plus Build/NMF26F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36
pointerdown pointer (touch)
pointerup pointer (touch)
click mouse (0)
pointerdown pointer (touch)
**dblclick** synthetic
pointerup pointer (touch)

* Firefox 54 Ubuntu
Leaflet 1.2.0+master.c63b014
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
mousedown mouse (1)
mouseup mouse (1)
click mouse (1)
mousedown mouse (2)
mouseup mouse (2)
click mouse (2)
**dblclick** mouse (2)

* Firefox 55 Android
Leaflet 1.2.0+master.c63b014
Mozilla/5.0 (Android 7.1.1; Mobile; rv:55.0) Gecko/55.0 Firefox/55.0
mousedown mouse (1)
touchstart touch
touchend touch
mouseup mouse (1)
click mouse (1)
mousedown mouse (1)
touchstart touch
**dblclick** synthetic
touchend touch
mouseup mouse (1)

* Edge 10 Windows 10
Leaflet 1.2.0+master.c63b014
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
pointerdown pointer (mouse)
pointerup pointer (mouse)
click pointer (mouse)
pointerdown pointer (mouse)
pointerup pointer (mouse)
click pointer (mouse)
**dblclick** pointer (mouse)

I hope it was useful.

**Comment by jjimenezshaw** [comment]
@perliedman Do you see any regression on this change?
This looks really like #5180, and it was a mess.
(I can do a PR if you want)

**Comment by perliedman** [comment]
@jjimenezshaw Thanks for looking into this!

Must say I'm _really_ scared to touch that code, a lot of browser weirdness going on there. I think we need to at least test with some versions of Internet Explorer (at least IE 11, but preferably also older ones).

**Comment by jjimenezshaw** [comment]
@perliedman Yes, I'm scared too. There are tons of corner cases.
At least we know now that Chrome in Android is not triggering `dblclik` events on its own, and we are not simulating them via `addDoubleTapListener`. And it is easy to reproduce in the computer.

Also, I think it is strange that we check the Browser type in two different places, while we can do in once. It sounds more coherent.

Is there any way to patch those changes I did above using https://playground-leaflet.rhcloud.com/ ? It would be great to create a fiddle there, and anybody can test.
BTW, https://playground-leaflet.rhcloud.com/ only includes until Leaflet 1.0.3

**Comment by perliedman** [comment]
@IvanSanchez any chance you can find the time to give  some guidance regarding this?

**Comment by IvanSanchez** [comment]
@perliedman @jjimenezshaw Maybe you folks should check older versions of Chrome/Chromium. As far as I remember, the blink engine did in fact fire native `dblclick`s as of version 55. I'm gonna make a wild guess and say that this behaviour must have been changed in a later version.

**Comment by IvanSanchez** [comment]
Please see my notes on https://github.com/w3c/pointerevents/issues/171 - I'm pretty sure I double-checked the data in that table when I wrote that.

**Comment by andrea06** [comment]
I understand that the double-tap with Chrome >55 and Leaflet 1.0.3 on Android works.

**Comment by jjimenezshaw** [comment]
@IvanSanchez @perliedman I think it may be a regression in Chrome for Android (and it is perfectly simulated on the device simulator on the computer's Chrome). I was not "here" when #5180 was posted, but I see pictures of Chrome in a mobile phone. It looks like somebody tested Chrome on Android.

As you say in w3c issue, "... that requires browser sniffing which, as we know, is a Bad Idea™"

I have just tested in an old Android device with Chrome 56.0.2924.87 (on leafletjs.com homepage) and it doesn't work either.

If we always subscribe the function `addDoubleTapListener` (I mean, not discarding Chrome) and discard  `if (Browser.pointer && e.pointerType === 'mouse') { return; }` is not enough to not get duplicated `dblclick`s, but get every case?

I am getting confused on which events are the browsers triggering... :disappointed: 

@andrea06 Go to https://playground-leaflet.rhcloud.com/belu/edit?html,output, and select Leaflet 1.0.3 (and click on "Run with JS". You will see the difference on the "minus" symbol on the zoom control). It is also failing in Android Chrome.

**Comment by jjimenezshaw** [comment]
BTW, who maintains https://playground-leaflet.rhcloud.com ?
Adding libraries Leaflet 1.1.0 and 1.2.0 would be great.

**Comment by IvanSanchez** [comment]
@jjimenezshaw That'd be me. But lately I cannot spend much time on it, so I'd gladly hand over the keys. Do you think you'd have time for managing the playground?

**Comment by jjimenezshaw** [comment]
I have tested in (another) Android with Chrome 58.0.3029.83, and it doesn't work.

Leaflet 1.2.0+HEAD.7730948
Mozilla/5.0 (Linux; Android 4.3.1; Nexus 7 Build/JLS36I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Safari/537.36
pointerdown pointer (touch)
pointerup pointer (touch)
mousedown mouse (1)
mouseup mouse (1)
click mouse (1)
pointerdown pointer (touch)
pointerup pointer (touch)
mousedown mouse (1)
mouseup mouse (1)

The same with Leaflet 1.0.3:

Leaflet 1.0.3
Mozilla/5.0 (Linux; Android 4.3.1; Nexus 7 Build/JLS36I) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Safari/537.36
pointerdown pointer (touch)
pointerup pointer (touch)
mousedown mouse (1)
mouseup mouse (1)
click mouse (1)
pointerdown pointer (touch)
pointerup pointer (touch)
mousedown mouse (1)
mouseup mouse (1)

**Comment by jjimenezshaw** [comment]
@IvanSanchez about playground I wrote you an email.

**Comment by geoloep** [comment]
I can confirm the existence of this issue in Chrome 60.0.3112.107 for Android. Firefox 55.0.2 on Android works fine. Leaflet 1.0.3 works fine in Chrome on Android.

Using the device mode in chrome on ubuntu both 1.0.3 and 1.2.0 do not register double clicks. 

Firefox 55 on ubuntu works both a normal mouse and a simulated touch device, mirroring the experience on Android.

The results of the test page are the same as those of jjimenezshaw

**Comment by nat-p** [comment]
I got the other problem - **zoom out** on Chrome for Android with Leaflet 1.0.3. _Zoom in_ is work for me.
Could you fix this asap? or any solution update on this issue?

**Comment by perliedman** [comment]
@nat-p sounds like a completely different issue, so no need to post that here. Also highly unlikely it isn't related to your app: zoom out definitely works in the general case. If you think this is a Leaflet issue, and can supply a reproducible test case, please open a new issue.

Also, please refrain from things like "fix this asap". This is an open source project, things get fixed when people have time and resources to address issues. If this is important to you, either fix it yourself, find someone who can fix it for you, or wait.

**Comment by geoloep** [comment]
```diff
diff --git a/src/dom/DomEvent.DoubleTap.js b/src/dom/DomEvent.DoubleTap.js
index a5fb25d..eb1351d 100644
--- a/src/dom/DomEvent.DoubleTap.js
+++ b/src/dom/DomEvent.DoubleTap.js
@@ -19,7 +19,7 @@ export function addDoubleTapListener(obj, handler, id) {
                var count;

                if (Browser.pointer) {
-                       if ((!Browser.edge) || e.pointerType === 'mouse') { return; }
+                       if (!(Browser.edge || Browser.chrome) || e.pointerType === 'mouse') { return; }^M
                        count = _pointersCount;
                } else {
                        count = e.touches.length;
@@ -38,7 +38,7 @@ export function addDoubleTapListener(obj, handler, id) {
        function onTouchEnd(e) {
                if (doubleTap && !touch.cancelBubble) {
                        if (Browser.pointer) {
-                               if ((!Browser.edge) || e.pointerType === 'mouse') { return; }
+                               if (!(Browser.edge || Browser.chrome) || e.pointerType === 'mouse') { return; }^M
                                // work around .type being readonly with MSPointer* events
                                var newTouch = {},
                                    prop, i;
diff --git a/src/dom/DomEvent.js b/src/dom/DomEvent.js
index 8cd34d9..16a7f81 100644
--- a/src/dom/DomEvent.js
+++ b/src/dom/DomEvent.js
@@ -89,8 +89,7 @@ function addOne(obj, type, fn, context) {
                // Needs DomEvent.Pointer.js
                addPointerListener(obj, type, handler, id);

-       } else if (Browser.touch && (type === 'dblclick') && addDoubleTapListener &&
-                  !(Browser.pointer && Browser.chrome)) {
+       } else if (Browser.touch && (type === 'dblclick') && addDoubleTapListener) {^M
                // Chrome >55 does not need the synthetic dblclicks from addDoubleTapListener
                // See #5180
                addDoubleTapListener(obj, handler, id);
```

These changes work for me on

- Chrome 60.0.3112.107 on Android
- Chrome 60.0.3112.78 on Ubuntu
- Firefox 55.0.2 on Android
- Firefox 55.0.2 on Ubuntu
- Edge 40.15063.0.0 on Windows 10
- IE 11.0.9600.18666 on Windows 8

I tried simulating touch screens where applicable. 

This changes as little as possible but is probably equivalent to the proposal of @jjimenezshaw . I'm not really sure what the use of the browser check on lines 22 & 41 is. This bug is bad for the user experience on mobile, where double tap functionality will be expected by most users. What steps are needed to advance this issue? Would love to contribute to finding a fix, unfortunately I'm not overly familiar with the code in question.

I'm almost wondering if it would not be easier to always simulate double tap/click and completely ignore double click events of the browsers.

**Comment by jjimenezshaw** [comment]
I have tested (leafletjs.com) again in Chrome 61.0.3163.98 in Android 7.1.1, and it is still failing.
After two mayor release updates (whatever it means), there is no change in Chrome, so I do not expect any future change from Chrome team on this regard :(

**Comment by johnd0e** [comment]
> Double-tap (e.g. zoom in) does not work

I do not observe any issue in recent Chrome on Android.
