### ISSUE TITLE
Non-point Path with "icon" in styles generates error on click event

### ISSUE THREAD

**Issue by BARNZ** [Leaflet/Leaflet#5635]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: Chrome 59.0.3071.115
- OS/Platform (with version) I'm using: Windows 10

## What behaviour I'm expecting and which behaviour I'm seeing

- I expect no js error to occur as done in previous versions of leaflet (before 1.1.0). 
- I currently see the following error: `Uncaught TypeError: s.getLatLng is not a function`

## Minimal example reproducing the issue

Please see this minimal jsfiddle to reproduce: https://jsfiddle.net/btyLfmke/3/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

### Error can be traced to `src\Map.js:1356`
`var isMarker = (target.options && 'icon' in target.options);`

**Comment by BARNZ** [comment]
In my case, the data is geojson fed straight into a geojson layer. Each feature can sometimes have an `icon` property as extra information for separately rendering icon markers on top of the feature.

![image](https://user-images.githubusercontent.com/2202345/28251080-db86c13c-6ac9-11e7-8a11-79a3a06d3d5e.png)

**Comment by ghybs** [comment]
Hi @BARNZ,

Thank you for the detailed bug report with test case!

Indeed the test in src code that you highlight makes it possible to have a conflict with an "icon" custom style set by the application developer.

It should be quite simple to improve that check so that it becomes immune to such conflict.
But I wonder which property would be the most appropriate in this case? @perliedman 
We could use for example [`target._initIcon`](https://github.com/Leaflet/Leaflet/blob/v1.1.0/src/layer/marker/Marker.js#L177), which appears only in `Marker` class, and is still linked to an icon, like the current test.
Updated JSFiddle: https://jsfiddle.net/btyLfmke/4/

I guess we avoid a straight forward `target instanceof Marker` for some reason?

**Comment by perliedman** [comment]
Hm, maybe too imprecise, but how about just looking for the existence of an `getLatLng` method, which seems to be what we're after anyway? That should have the advantage that also `CircleMarker`s (that don't have icons) are covered, but possibly also `Popup`s - don't know if that would be a problem.

**Comment by perliedman** [comment]
We _do_ have `instanceof` in `Map` already: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L242, but perhaps there is some reason not to use it here, perhaps dig into the history of that line to see if there appears to be a reason.

**Comment by ghybs** [comment]
Hi @perliedman,

Existence of `getLatLng` would indeed be `true` for `CircleMarker`, but also for `Circle` (besides `Popup`, `Tooltip`, and obviously `Marker`).
It therefore solves this bug as well, but changes the behaviour for these layers: now the popup opens at the layer's center instead of at the exact mouse click position: https://jsfiddle.net/btyLfmke/6/

Not very problematic for `CircleMarker` (could even be a better behaviour?), but for Circles I am not sure we want to steer away from other vectors' behaviour?
Because `Circle` can be large at high zoom, opening popup at its center might pan the map far away from the click position: https://jsfiddle.net/btyLfmke/7/ (click somewhere on the green Circle at this zoom)

**Comment by ghybs** [comment]
About usage of `instanceof`: you are right, it was indeed used before at this very line:
https://github.com/Leaflet/Leaflet/blob/v1.0.3/src/map/Map.js#L1322

It has been changed during the ES6-ify refactoring:
https://github.com/Leaflet/Leaflet/commit/fb535af00362a20b906bea8c1d26e39edb0c26ea#diff-607b516b5121104eef3007cb5727e69cR1353

I guess this one got a special treatment (whereas all other modifications are really just a simple replacement of the global reference) to "prevent cyclic loop on Map imports", as the commit description suggests?
`Marker.js` imports `Layer.js` which imports `Map.js`.

**Comment by ghybs** [comment]
Note: even though having a cyclic loop of imports is [not a problem for Rollup](https://github.com/rollup/rollup/wiki/Cycles) and Leaflet Rollup build performs without issue, the resulting bundle does not work and fails tests (when replacing the line to use back `instanceof Marker`).
