### ISSUE TITLE
contributions not visible in fullscreen map using chrome on android

### ISSUE THREAD

**Issue by guillaumebof** [Leaflet/Leaflet#5636]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: chrome 59
- OS/Platform (with version) I'm using: android 6
- visit : http://leafletjs.com/examples/mobile/example.html

I'm expecting to see the contributions on the right bottom of the map, but i don't.

**Comment by ghybs** [comment]
Hi,

Good catch!

It seems that the attribution control is present but not visible, just under the visible screen.

![leaflet-mobile-attribution](https://user-images.githubusercontent.com/12232803/28257340-11d42c6e-6adb-11e7-8f65-b7d25c1d236e.png)

The CSS `height: 100vh` does not account for the presence of the address bar in mobile Chrome.
Because the map takes the entire visible screen, there no way to "scroll down" and hide that address bar.

Maybe changing it to `100%`, which does account for the address bar?

**Comment by guillaumebof** [comment]
indeed, with "height: 100%" the contributions are visible. so it's not a leaflet bug ? i'm sorry for the mistake !

**Comment by ghybs** [comment]
Not a bug in Leaflet library itself, but definitely a room for improvement in Leaflet website.
So this issue is still relevant here.

Just need to make sure the fix works on all platforms.

**Comment by perliedman** [comment]
Nice analysis!

I think we can be pretty certain `height: 100%` will work on all platforms, it's what I normally use for fullscreen maps. I was actually a bit confused why we use `100vh` in some places and what the difference was, but now I at least know one difference between them...

**Comment by wilsonsilva80** [comment]
Any file specific you want me to help changing it or just replace everywhere `height: 100vh` to 100%

**Comment by perliedman** [comment]
@wilsonsilva80 Did some searching on this, and while it's arguably better to use `100vh`, I think going with `height: 100%` for all fullscreen examples is best now.

Apparently, the recalculation of view height when the navigation bar is hidden/shown in Chrome is now considered a bug: https://bugs.chromium.org/p/chromium/issues/detail?id=428132
