### ISSUE TITLE
Feature suggestion: Fractional TileLayer

### ISSUE THREAD

**Issue by HarelM** [Leaflet/Leaflet#5641]
I'm looking into migrating a desktop application that can generate tiles and maps into a web based application, I was hoping to use leaflet for this as I really like the development experience with it (Kudos BTW).
One of the key features for printable maps is the ability to scale the map in a non integer zoom level to facilitate for example a 1:10000 view ratio which does not sit on integer zooms.
I know that as of leaflet 1.0 zoom can be made fractional but as far as I can understand from the documentation and light code reading the tile layer is still using non fractional tiles.
My question is if there is a tile layer class I can configure the zoom fractions for fetching the tiles.
The reason for that is that the desktop application can generate tiles according to rules that are defined in fractional zoom to facilitate better quality maps.
This might be a plugin candidate, I'm not sure, I won't mind trying to help out if you'll guide me a bit where to start looking in the code.
Thanks again for a great product!

**Comment by perliedman** [comment]
Hm, this sounds like it might be a case for [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet): since you're using print maps, I guess you might have other projections than spherical mercator as well.

In Proj4Leaflet, you can set up arbitrary resolution/scale for each zoom level independently, so it doesn't necessarily have to follow the steps used by Leaflet's default.

This can of still be used together with Leaflet's non-integer zoom levels, of course.

Would that be a solution for you?

**Comment by HarelM** [comment]
I've read the readme file of the project and I'm not 100% sure it covers my needs.
What I want to do is create a server that can server tiles in any zoom level (not just integers) and present them on a map.
For example when a user is at latlng (0,0) and sets zoom to 10.111 I want leaflet to call the server for tiles at address `www.mysite.com/tiles/10.111/0/0.png` the server on the other had will either generate the tile on the fly or serve from local cache (probably a local folder called 10.111/0 and a file called 0.png, but that's implementation details).
So the projection is done on the server side and not on the client side.
Does it make more sense now?

**Comment by perliedman** [comment]
Ok. I don't think I understand why you need to use fractional zoom levels for this. It sounds to me like there would be two general options:

1. you have fixed zoom levels, but many more than Leaflet use by default (where the additional zoom levels would be "in between" the normal zoom levels). For fixed levels, it doesn't really matter if they are fractional or integer: as long as they are fixed, you could enumerate them and make them be integers. For this case, as long as you provide your own scale/resolutions (either through Proj4Leaflet or by just implementing your own CRS), and Leaflet would work as it is now, with integers zoom levels, just not the same scales/resolutions as you have now
2. you don't have fixed zoom levels, but allow more or less any arbitrary zoom levels. For this case, I think tiling and caching stop making much sense: tiling and zoom levels work well since we know the same tiles are likely to be reused and it therefore makes sense to cache or even seed the cache in advance; with arbitrary levels, it's much less likely that anything in the cache will ever be reused, it can grow enormously and there's no way to seed it since we don't know what will be requested. This is more or less exactly the scenario for a classic WMS service, which allows arbitrary images of any scale to be requested.

For option 2, I think you're best off to have a WMS server and maybe a plugin that supports fetching new images even at non-integer zooms. I'm not sure if this is already supported by one of the existing WMS plugins, but it sounds like it should be straight forward to implement otherwise.

**Comment by HarelM** [comment]
I see. Thanks for the detailed response!
I'll try and see which option is easier for me to implement.
I believe this answer should cover my needs (unless there isn't a WMS plugin that supports this, in this case I'll open an issue at the relevant plugin repository).
