### ISSUE TITLE
Drag panning inertia executes even if pan movement is paused at the end

### ISSUE THREAD

**Issue by mystica555** [Leaflet/Leaflet#5652]
## How to reproduce

- Leaflet version I'm using:
Latest (1.1.0) - whatever both Craigslist and CellMapper Beta maps are using
http://leafletjs.com/ demo maps
craigslist.org - "map view" of sales/houses/etc
cellmapper.net/testmap/
- Browser (with version) I'm using:
Chrome 58
- OS/Platform (with version) I'm using:
Sabayon Linux - Gentoo derivative - rolling release

Click and hold mouse button on map 
Drag Map to point you want it, perhaps quickly
Remove finger from button

## What behaviour I'm expecting and which behaviour I'm seeing
Expected behavior: Map just stays in place
What I am seeing: Map pan continues further

## Minimal example reproducing the issue
http://leafletjs.com/ demo maps

Edit 2017-07-21: explicit reference to example, removed all caps text

**Comment by ghybs** [comment]
Hi,

Thank you for your bug report.
There is no need to yell at people :-)

**Steps to reproduce:**
1. Pan the map very quickly and keep the mouse pressed / finger touch down (panning slowly also triggers the bug, but less dramatically).
2. Instead of releasing at the end of the quick movement (as done when counting on inertia to get the map keep on moving), pause the mouse / touch at the same location for some time (e.g. 1 or 2 seconds), in order to try to "cancel" the inertia.
3. Release the mouse / finger touch, expecting the map to remain at this position.
4. Actually the pan inertia now takes effect, as if there had been no "pause" in the mouse / touch movement.

This behaviour seems to be present since version `1.0.0-beta.1`, but absent from `0.7.7` and below, whereas inertia was already implemented.

Examples:
- Version `1.1.0`: http://playground-leaflet.rhcloud.com/poco/1/edit?html,output
- Version `0.7.7`: http://playground-leaflet.rhcloud.com/haye/1/edit?html,output
