### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lat' of undefined

### ISSUE THREAD

**Issue by swanghao** [Leaflet/Leaflet#5678]

**Comment by yohanboniface** [comment]
Hi,

Thanks for using Leaflet.
I'm closing here, as this issue is missing a description, thus a way for us to help.
Feel free to reopen when you have more details to provide.
Also remember that this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).
