### ISSUE TITLE
Wrong relatedTarget on mouseout event (to close tooltip except if mouseout towards tooltip)

### ISSUE THREAD

**Issue by robertomlsoares** [Leaflet/Leaflet#5720]
## How to reproduce

- Leaflet version I'm using: 1.1.0
- Browser (with version) I'm using: IE 11 or Firefox 54
- OS/Platform (with version) I'm using: Windows 7

Open the fiddles below and hover over the markers while checking the console. The fiddle with Leaflet 0.5.1 works as expected but the one with Leaflet 1.1.0 doesn't,

## What behaviour I'm expecting and which behaviour I'm seeing

The `relatedTarget` should be the popup but it's another element (the map container).

## Minimal example reproducing the issue

This fiddle uses Leaflet 0.5.1 and works as expected (check the console while hovering over markers or simply notice that the popups are not closed when going with the mouse from the marker to the popup): http://jsfiddle.net/3JbNY/106/

This one is exactly the same as the one above but it uses Leaflet 1.1.0 and as you can see, it doesn't work anymore; and if you check the console, the `relatedTarget` element is not the popup on 90% of the times (very rarely it actually is the popup): http://jsfiddle.net/3JbNY/105/

What is the correct behavior here? Why was that changed? Shouldn't the `relatedTarget` on `mouseout` always be the element you're exiting into?

PS.: I asked a question on SO about this, check it out if you want more information or if you know a solution that doesn't rely on `relatedTarget`. https://stackoverflow.com/questions/45755984/why-doesnt-leaflet-provide-the-correct-relatedtarget-element-on-mouseover-event

**Comment by robertomlsoares** [comment]
Ok, so since 0.5.1 is quite an old version I decided to go check which one is the latest working version for this. It still behaves correctly in the v.1.0.0-rc.1 version but starts breaking in the v.1.0.0-rc.2 version.

I'll try to find what caused the change between those two versions.
Does anyone agree that this behavior is odd? I can help find and/or fix the problem but if the maintainers think that this is not a bug then I can move on to trying to find another solution.

**Comment by robertomlsoares** [comment]
So, I think this is caused by this change: #4599

On version 1.1.0, I changed the value of `pointer-events` to `auto` on the CSS class `leaflet-tooltip` (**not** the pane) and it works as I expected.
Now remains the question of what should be the desired outcome here.

**Comment by perliedman** [comment]
Hi, thanks for looking into this and providing a detailed description! As you say, #4599 is probably the key here: for most applications, this change, making the popup tip pass through pointer events is an improvement, but in your specific use case it becomes problematic since it actually looks like the event is on the map, not on the popup's tip.

Unless you have a better suggestion, I would say that overriding `pointer-events` on `leaflet-tooltip` like you've already done is probably the best solution here. Most apps are not concerned with pointer events on the popup's tip.

**Comment by robertomlsoares** [comment]
Glad to help!

For now, I'll just override the CSS on my app. I thought I'd point it out for discussion because when I was googling how to keep the tooltip/popup open when hovering over it, I saw some people trying to do the same, so it _may_ be a common feature, and the fiddle I posted is a nice way to accomplish it.

But anyway, I'm glad it's easy to fix it by just overriding a CSS class. :)

**Comment by ghybs** [comment]
Hi @robertomlsoares,

Nice finding!

For the record, your use case is to auto close a popup (or a tooltip) on marker "`mouseout`" event, _except_ when the `mouseout` is towards the associated popup / tooltip.

Therefore the new Leaflet behaviour (introduced by #4599) makes your initial solution fail, because `mouseout` event no longer supplies `toElement` or `relatedTarget` (hence your issue title).

Here is an updated JSFiddle that includes the solution to override `pointer-events` CSS:
http://jsfiddle.net/3JbNY/107/

**Comment by ghybs** [comment]
> it _may_ be a common feature

but:

> Most apps are not concerned with pointer events on the popup's tip.

Sounds to me like a rationale for making it a plugin?

**Comment by robertomlsoares** [comment]
Hello, @ghybs,

Yeah, you described the problem really well. Thanks for the fiddle, btw!

I agree that it's a good idea for a plugin, I might try to make one later when I have some more time, but for now I'm just glad the issue is out there in the open and hopefully people will stumble upon this later, it's quite an easy solution even without a plugin (it was just hard to find 🙂).

**Comment by johnd0e** [comment]
Closed in favor of #4596.
