### ISSUE TITLE
Optional ESC key popup close

### ISSUE THREAD

**Issue by Mickyfen17** [Leaflet/Leaflet#5727]
I came across a scenario with the default functionality on the `esc` key for popups. Inside of our popup we have an image gallery which can be made fullscreen. 
The issue that I came across was when the image gallery is fullscreen and the user presses the `esc` key, the popup will close from behind the image gallery also closing the gallery itself. This taking the user back to the map.
I checked out that docs and couldn't pinpoint a way to disable this default functionality (unless I've missed it) so to get around this I just removed the default `map.closePopup();` method on our application.
I was wondering if this default `esc` key functionality could become optional? Set to `true` as default.
By adding and a key `escKeyClose` within [the options object](https://github.com/Leaflet/Leaflet/blob/5ce473bab65be772e0cc6e25020c95ffba2fe5b2/src/layer/Popup.js#L43-L97) and modifying [this conditional](https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.Keyboard.js#L165-L166).

It was a fairly straight forward process to replicate the above modification locally in our app.

**Comment by IvanSanchez** [comment]
Maybe one could add a new `closeOnEscapeKey` option to `L.Popup`, and make the keyboard handler check the value of that option before calling `map.closePopup()`. Sounds like a straightfoward change.

@Mickyfen17 would you be willing to submit a PR for this?

**Comment by Mickyfen17** [comment]
@IvanSanchez Yeah, happy to implement this tonight.

**Comment by gogosanka** [comment]
I dont mean to butt in, but does the popup create a new popup instance when
going full screen? If not then perhaps the escape is simultanepusly closing
the fullscreen and the popup at once due to browser behaviors as well as
custom functionality.

On Aug 22, 2017 1:28 PM, "Michael Fenwick" <notifications@github.com> wrote:

I came across a scenario with the default functionality on the esc key for
popups. Inside of our popup we have an image gallery which can be made
fullscreen.
The issue that I came across was when the image gallery is fullscreen and
the user presses the esc key, the popup will close from behind the image
gallery also closing the gallery itself. This taking the user back to the
map.
I checked out that docs and couldn't pinpoint a way to disable this default
functionality (unless I've missed it) so to get around this I just removed
the default map.closePopup(); method on our application.
I was wondering if this default esc key functionality could become
optional? Set to true as default.
By adding and a key escKeyClose within the options object
<https://github.com/Leaflet/Leaflet/blob/5ce473bab65be772e0cc6e25020c95ffba2fe5b2/src/layer/Popup.js#L43-L97>
and modifying this conditional
<https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.Keyboard.js#L165-L166>
.

It was a fairly straight forward process to replicate the above
modification locally in our app.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Leaflet/Leaflet/issues/5727>, or mute the thread

**Comment by Mickyfen17** [comment]
The popup shows on the click of a map marker, within the popup we have an image gallery, that image gallery can be made full screen. When it's made fullscreen the popup still exists on the DOM, which includes the default `esc` `closePopup` function. Thats where my issue lies, there is no `esc` event attached to the image gallery so if the user does click that key expecting the image gallery to close, it will instead close the popup where the image gallery is rendered from, taking the user back to the map.
I don't want to remove the popup from the DOM when the images are fullscreen as the user should still see the popup once the fullscreen image gallery is closed. Which is the reason I have disabled the default function attached to the `esc` via the popup.
Hope this all makes sense.

**Comment by cherniavskii** [comment]
Looks like issue can be closed now ;)
