### ISSUE TITLE
.getBounds().pad() not working with negative values

### ISSUE THREAD

**Issue by Shooshte** [Leaflet/Leaflet#5741]
This referes to a 2 year old issue found here:
https://github.com/Leaflet/Leaflet/issues/2673

The problem:
When passing negative values into the .pad() function, the result is not smaller than the current map container (-10 and 10 produce results that differ only slightly in size, but are both bigger than the map)

Steps to reproduce:
Open the leaflet homepage map

Enter:
```
L.rectangle(map.getBounds().pad(-10)).addTo(map)
L.rectangle(map.getBounds().pad(10)).addTo(map)
```
into the console

Zoom out, see two rectangles bigger than the actual map at the time of drawing.

**Comment by CalvinWilliams1012** [comment]
I beleive that should fix the issue. However it may give a new issue as it does not check if the value is <-100 or >100.

**Comment by danzel** [comment]
I think the issue here is your understanding of what the function does.

The parameter `bufferRatio` is a percentage, where 1 = 100%.
So 10 means, pad 1000% bigger, and -10 means -1000% bigger (which would be slightly smaller than 1000% I think).
To make it smaller you need to use a negative number that is between 0 and -0.5.
Padding by 0 would not change the size, padding by -0.5 would make it size 0.
(I think? Maybe 0.33333 would make it size 0)
This doesn't really make a lot of sense though, haha :). I don't think `.pad()` is designed for making a `LatLngBounds` smaller.
Maybe we could have another function that takes a percent, and resizes the box to that percent of the original size?

**Comment by CalvinWilliams1012** [comment]
@danzel Ya you're right I tested it on the leaflet main page with rectangles as you can see in my mspaint pic 
![image](https://user-images.githubusercontent.com/15316956/29905263-8ff01e3c-8ddb-11e7-88e2-ccfd21cfcc84.png)

You can close/deny my pull request as I see what the function is for now. I am unsure of if we should add a new function for percentResize but I would be willing to add it :)

**Comment by IvanSanchez** [comment]
I don't think this is a bug, it's just a misunderstanding of what the method does, and the fact that we are using the word "percentage" in the docstrings rather than "ratio".

Some clarification in the docstrings for that method (e.g. `Returns bigger bounds created by extending the current bounds by a given ratio in each direction. For example, a ratio of 0.5 extends the bounds by 50%. Negative values yield smaller bounds instead.` or something like that) would prevent this confusion in the future.

@CalvinWilliams1012, maybe you would like to make such a change in the documentation?

**Comment by CalvinWilliams1012** [comment]
@IvanSanchez I am not sure how this projects doc's work yet I hope that comment is fine on multiple lines if not I can put it on one line, even though that makes it look gross :)

**Comment by IvanSanchez** [comment]
@CalvinWilliams1012 I think #5748 looks good enough. You can always [run `jake docs` to build the documentation](https://github.com/Leaflet/Leaflet/blob/master/CONTRIBUTING.md#api-documentation) and check for yourself 🙂
