### ISSUE TITLE
Tiles disappear when zooming in with fractional zoom levels

### ISSUE THREAD

**Issue by Eschon** [Leaflet/Leaflet#5751]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome 60.0.3112.113, Firefox 55.0.2
- OS/Platform (with version) I'm using: Mac OS X 10.11.6
- open this demo: http://playground-leaflet.rhcloud.com/muy/edit?html,output
- zoom in using the '+'-Button or double click

## What behaviour I'm expecting and which behaviour I'm seeing

I'm expecting the normal zoom animation instead the tiles disappear and load again when zooming is finished.

## Minimal example reproducing the issue

http://playground-leaflet.rhcloud.com/muy/edit?html,output

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by perliedman** [comment]
Hi! This does indeed look like a bug in 1.2.0. My guess is that it's related to #5622, which was introduced in 1.1.0 IIRC. It's fixed in master, and it appears the issue you're reporting is already fixed in latest: http://playground-leaflet.rhcloud.com/rili/edit?html,output

Closing this since it's already fixed.

**Comment by Eschon** [comment]
Yeah seems to be fixed. Thanks for looking into it.
