### ISSUE TITLE
zoom-buttons and searchbox do not scale down on responsive design

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [Leaflet/Leaflet#5754]
Hello,

I am using the qgis2web plugin for qgis which uses Leaflet to create interactive maps.
The map itself is responsive: it scales down nicely when viewing on a mobile phone.
However, several elements such as a titlebox, the zoom buttons, layers list (or legend) do not scale down.
So on a mobile phone the titelbox and zoom buttons and the other elements block a large portion of the screen and overlap each other.
See for instance this map I have made.
[https://groenebij.nl/Kaarten/GDAW](url)

How do I make those elements responsive as well?

**Comment by perliedman** [comment]
Hi there!

I don't think I would agree with your description of what "responsive" constitutes: it sounds as if you would expect the zoom controls and layer list to be smaller on a small screen. This is somewhat opposite of responsive, to me: to be able to use these controls, they _need_ to be large enough for the user to interact with them on a small screen with their fingers.

Having said that, this is not something controlled by Leaflet, it's up to the application author, in your case the qgis2web plugin.

If you look at the code of the page you linked to, it has this line in the `<head>` section:

```html
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
```

This is indeed the recommended setting to make the map work well on small device screens, to make sure the scale is sensible and the controls usable. If you remove this line, the page will look more like on a desktop, and the controls will most likely be very small. If this is what you prefer, just remove this line.

Anyway, I'm closing this, since it's not really a Leaflet issue, but up to the application.
