### ISSUE TITLE
Strange marker pop up on page load.

### ISSUE THREAD

**Issue by mdeetz90** [Leaflet/Leaflet#5786]
Hello, seems like a small error or maybe I scripted something wrong but I couldn't find anything on the issue. When I initially load my map to a specific lat/long a marker appears clicked by default. However when I use .locate({setView: true}); no makers are clicked by default. I'd like nothing to appear by default on the initial page load so it just shows markers not their pop up. It only does this with one marker and not all of them so I am lost. The marker isn't scripted any differently than the others. I was wondering if anyone has any idea what can cause this. I am a novice when it comes to this as well. 

Edit: It appears to be the last marker in my list that this happens to, I deleted the one popping up and then the new last one started doing it. That should add some additional info.

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
