### ISSUE TITLE
Using inline svg as the base layer

### ISSUE THREAD

**Issue by KfirShainholtz** [Leaflet/Leaflet#5800]
Hello everyone,
Currently, I serve a map with an imageOverlay base layer.
Right now, I need to use an svg instead of the current png imageOverlay,
and to alter the svg css (like, changing opacity for the nearest places (paths in the svg) etc), dynamically,
so basically, I need to control the actual map svg style dynamically.

I've decided I need to use an inline svg to alter the style of the svg,
instead of an image with an svg source.

I tried replacing the leaflet created image overlay with an actual inline svg at runtime.
it worked, but the zoom control won't affect the layer anymore,
and switching layers is a bit buggy.
is there any inside capabilities of leaflet to support this kind of requirement?

adding a fiddle to explain it better http://jsfiddle.net/dh5wgu2x/

**Comment by perliedman** [comment]
Hi and thanks for using Leaflet!

Please note that this is our issue tracker, where bugs and feature requests and posted and discussed. For questions on how to use Leaflet and other support, you're better off using [stackoverflow](https://stackoverflow.com/) or [gis.stackexchange.com](https://gis.stackexchange.com/).

Having said that, I know some other people have used `ImageOverlay´ with SVG images with some mixed success. In most cases, if you want vector data, actually using Leaflet's vector features is preferred instead of using SVG.
