### ISSUE TITLE
Provide a fallback provider for missing tile layer

### ISSUE THREAD

**Issue by MrSohey** [Leaflet/Leaflet#5810]
Leaflet version : 1.2.0

More an improvement than a bug, but currently the fallback "errorTileUrl" for TileLayers only allows for an image to replace the missing tiles, but you can't request another provider for the tiles.
For instance, if I want to get tileLayers from my own server, but in case it's down, load google maps instead. 

Here is what I wanted to achieve : https://jsfiddle.net/cLvcfw34/
As you can see, the parameters aren't replaced and therefore the fallback is failing.

I have slightly change the code to allow for another provider as a fallback (inspired by https://github.com/ghybs/Leaflet.TileLayer.Fallback) as follow : 

I added in createTile function
`tile._originalCoords = coords`

And in replaced _tileOnError by:
`
_tileOnError: function (done, tile, e) {

		var errorUrl = this.options.errorTileUrl;
		if (errorUrl && tile.getAttribute('src') !== errorUrl) {
			//tile.src = errorUrl;
			this.setUrl(errorUrl)
			this.getTileUrl(tile._originalCoords)
		}
		done(e, tile);
	}
`

As errorTileUrl is already used for image loading, would it might be useful to provide another option such as "fallbackUrl" for instance (and prevent for infinite looping if the fallback fail as well it should be replaced by errorUrl).

I hoped I did not miss something already in place. If you find this feature useful I can try to make a pull request.

**Comment by perliedman** [comment]
Hi!

It looks like you already found @ghybs' fallback plugin - is there anything in particular that makes your suggested approach preferable compared to just using that plugin? In general, we try to keep Leaflet lean, and although I do understand your use case, I don't think it's that common, and better suited as a plugin than in Leaflet's core.

Also, a word of warning: using Google's tiles directly in a Leaflet map is a violation of Google's license, you need at least to use something like [Google Mutant](https://gitlab.com/IvanSanchez/Leaflet.GridLayer.GoogleMutant) to display their tiles in Leaflet (although I wouldn't bet on the legality of even that).

**Comment by ghybs** [comment]
Hi @MrSohey,

FWIW there is a fork of that plugin that sounds to do what you are looking for:
https://github.com/BenjaminVadant/Leaflet.TileLayer.Fallback
> Plugin for Leaflet. Tries to load from another url if the first one is not available.

```javascript
var myTileLayer = L.tileLayer.fallback([url,urlFallback], options);
```

I have not reviewed whether that fork works as advertised or not, neither how it avoid the infinite looping case you mentioned.

Since there seems to be at least 2 people needing this functionality, it might be interesting turning it into a proper Leaflet plugin.
Or the functionality could be merged into the original plugin, with a kind of configuration to say whether the fallback should use a different URL, or lower zoom.

Please feel free to submit a PR on https://github.com/ghybs/Leaflet.TileLayer.Fallback, I would be happy to review it and eventually to merge it.

**Comment by MrSohey** [comment]
Hi !

I have not seen the mentioned forked, I'll take a look at it !

I felt like the plugin was a bit too much code for a functionality that could be done with the addition of just a few liens of code, but I guess there might be more checking to do than I did (even though I mentioned it, I did not prevent infinite looping nor add a second fallback with an image). I'll try to tweak the plugin adequately :)

Thank you for the warning @perliedman, I did not know. I guess I'll switch to OSM then.

**Comment by Bibo-Joshi** [comment]
Hi. I stumbled over this old thread while searching for a solution to display tiles from a fallback source in case my free plan at stadiamaps runs out of credits. I see that https://github.com/ghybs/Leaflet.TileLayer.Fallback/pull/6 was closed and https://github.com/BenjaminVadant/Leaflet.TileLayer.Fallback mentioned above has been deleted.

I came up with the following solution, which works fine for me so far (had a bit of help from chatgpt tbh, since I'm not overly familiar with JS …). The idea is not to simply set the tile url as `src`, but to check the http status first. Setting the `src` to the base64 blob avoids requesting the image again in case of a success. A simple error event listener for the image element does not suffice, since 429 status codes from stadia are not treated as exception since stadia still returns a placeholeder image.

<details>

```js
function setSrcWithStatusCheck(tile, url, fallback_url) {
    function setSrc(effective_url) {
        tile.src = effective_url;
    }

    // Make the request to fetch the image content
    fetch(url)
        .then(function (response) {
            if (!response.ok) {
                // Handle non-OK responses
                setSrc(fallback_url);
            } else {
                // Convert the image content to base64
                return response.blob();
            }
        })
        .then(function (blob) {
            return new Promise(function (resolve, reject) {
                var reader = new FileReader();
                reader.onloadend = function () {
                    resolve(reader.result);
                };
                reader.onerror = reject;
                reader.readAsDataURL(blob);
            });
        })
        .then(function (dataUrl) {
            // Set the source of the image using the base64 data URL
            setSrc(dataUrl);
        })
        .catch(function () {
            // Handle network errors
            setSrc(fallback_url);
        });
}

class Fallback extends L.TileLayer {
    constructor(urlTemplate, options, fallbackUrl) {
        super(urlTemplate, options);
        this.fallbackLayer = L.tileLayer(fallbackUrl, options);
    }

    createTile(coords, done) {
        const tile = super.createTile(coords, done);
        this.fallbackLayer._tileZoom = this._tileZoom;
        tile._originalCoords = coords;

        setSrcWithStatusCheck(tile, tile.src, this.fallbackLayer.getTileUrl(coords));

        return tile;
    }
}
```

</details>

Example usage:

```js
const stamen_toner = new Fallback('https://tiles-eu.stadiamaps.com/tiles/stamen_toner_background/{z}/{x}/{y}.png', {
    minZoom: 1,
    maxZoom: 16,
    attribution: '&copy; <a href="https://www.stadiamaps.com/" target="_blank">Stadia Maps</a> &copy; <a href="https://www.stamen.com/" target="_blank">Stamen Design</a> &copy; <a href="https://openmaptiles.org/" target="_blank">OpenMapTiles</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
}, 'https://tile.openstreetmap.org/{z}/{x}/{y}.png');
```

I don't have any ambitions on sending a PR or providing this as standalone package, just wanted to share this here in case someone ever finds it usefull :)
