### ISSUE TITLE
`moveend` fires prematurely, before adjusting/rounding of lat/lng occurs

### ISSUE THREAD

**Issue by yeedle** [Leaflet/Leaflet#5821]
A known issue with `setView` and `panTo` (see https://github.com/Leaflet/Leaflet/issues/426 and https://github.com/Leaflet/Leaflet/issues/5512 for example) is that it often sets the view to a slightly rounded lat/lng on higher zoom levels.

The issue is that the `moveend` event fires before the rounding occurs. Which means that if I set up an `once` event listener to fire on `moveend`, it will fire prematurely, and my events will occur not in the right time. (In my use case, I'm using `moveend` to open a modal, and automatically close it when the user moves the map. In the cases that rounding occurs, the modal opens and closes immediately because the latlng are rounded and the map moves after `moveend` has already been fired.)

## How to reproduce
- Leaflet version I'm using: Leaflet 1.2
- Browser (with version) I'm using: Chrome 61
- OS/Platform (with version) I'm using: Ubuntu 16.4

set up an event listener on `moveend` and then call `setView` while continuously calling `getCenter`, and watch how the center gets updated even after `moveend` has been called.

## What behaviour I'm expecting and which behaviour I'm seeing
I'm expecting `moveend` to fire after rounding has occured and the map won't move anymore.
I'm seeing `moveend` being fired and the map being moved ever so slightly afterwards.

## Minimal example reproducing the issue
click on the map once, see the lat/lng that `moveend` get's fired at. Click it again, and see the actual rounded lat lng. (This is tricky, because rounding is based on several factors like device size and pixel density so the bug will only occur under certain conditions)
http://jsfiddle.net/Yeedle/04y19h84/

**Comment by perliedman** [comment]
Hi, 
thanks for reporting this and providing an example illustrating the issue (but please use a recent version in your example - the fiddle uses Leaflet 0.7.2 which is _really_ old - fortunately the same issue exists in the latest version as well).

After looking at this, I think I don't share your assesement that this is because `moveend` is fired before the rounding, but rather that two different methods for moving the map are used.

The first move, which changes zoom and center drasticly, does not pan or animate the zoom, but rather just moves the center and zoom in one step. Using this method, you get the _exact_ center coordinate that you asked for.

The second move, however, will try to use `pan` instead, since the movement is very small (in fact 0). Due to various floating point inaccuracies (I think it might be because of multiple roundings in the internal calculations, but not sure yet), the pan is calculated to about 1 pixel instead of the expected 0, causing the map's center to change every so slightly.

**Comment by perliedman** [comment]
I think this line is the problem: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L1527 - using `_floor` here will, for negative offsets, round _away_ from zero, while I guess the intention is to round _towards_ zero. This causes a small negative offset (-0.25 in my case) to be rounded to -1 pixels, causing a very small pan.

**Comment by yeedle** [comment]
My apologies for using an older version. I used a jsfiddle fork from a different hello world example, and I thought I updated the leaflet version but apparently I didn't. 

Just to supply context for why I thought the bug is a premature firing of the 'moveend' event: In my actual application (which is way more involved and complicated than my jsfiddle example), I have an event listener attached to 'moveend' that logs the center coordinates of the map once a move is over. On the click of a marker on the map, an event listener is attached to 'moveend' using `once` which will open a modal on the screen, and then uses `flyTo` to center the map around the clicked marker. Once the modal is open, an event listener is again attached to 'moveend', also using 'once', which closes the modal if the map is moved.

I have observed that for some markers on my map the modal immediately opens and then closes. The even listener that logs the center coordinates fired right after the modal opened, which led me to believe it's a premature firing of  'moveend'. I can try to create a jsfiddle of this if it will help confirm that the bug is indeed with flooring negative offsets away from zero.
