### ISSUE TITLE
How to make the labels show at all times as text above/under the markers?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [Leaflet/Leaflet#5827]
With a lot of work, I've managed set up a Leaflet map for my private use. I was able to figure things out eventually, but there's one IMPORTANT detail which still isn't solved:

How do I make Leaflet ALWAYS show the little label (I load in a GeoJSON file) instead of only showing it when you either actively click on a marker or hover the mouse cursor over it? I want them to ALWAYS show! That's the only way I could possibly get a sane visual overview of the map. Having to hover over each marker to know what it means is frankly almost worthless.

I really have been looking through the documentation. I find not one word about this, not one example, nothing. Even though this ought to be the most common use for any map, no?

**Comment by cherniavskii** [comment]
Hey @FjicdeiwFeiej!
Just set Popup's [`autoclose` option](http://leafletjs.com/reference-1.2.0.html#popup-autoclose) to false, when binding popup to marker.

Please note that this issue tracker is used for bugs. For support or questions please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet).

**Comment by FjicdeiwFeiej** [comment]
I've now spent another 30 minutes searching and looking and trying things. Can't get it to work. I don't wanna insult you, but it's really infuriating when the documentation makes no sense. This is what I have:

L.geoJSON(actualData).bindTooltip(function (layer)
{
	return layer.feature.properties.name;
}).openTooltip().addTo(bookmarks);

**Comment by cherniavskii** [comment]
See [`bindTolltip` method documentation](http://leafletjs.com/reference-1.2.0.html#layer-bindtooltip).

**Comment by FjicdeiwFeiej** [comment]
}, { autoClose: false } ).openTooltip().addTo(bookmarks);

No difference. The labels don't show up unless you hover them. I have no clue what you want me to do.

**Comment by ghybs** [comment]
Hi @FjicdeiwFeiej,

While we can certainly understand that the documentation may not fit your way of thinking (everyone is different after all), this is an Open Source project. Therefore if something does not match your expectation, we are open to constructively discuss about it, and we are even more eager for [Pull Requests](https://yourfirstpr.github.io/)!

Showing consideration is definitely how you could help things go your way, rather than threatening like you might do for paid solutions (and even in such cases it may not work).

Finally, a more appropriate place to ask for help in your case would very probably be [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet), as stated by @cherniavskii.

For instance, you would probably be interested in that post:
https://stackoverflow.com/questions/43780990/leaflet-labels-when-upgrading-to-1-0-3/43781206#43781206

**Comment by yohanboniface** [comment]
http://leafletjs.com/reference-1.2.0.html#tooltip-option

`permanent: true` is what you are looking for.

**Comment by FjicdeiwFeiej** [comment]
"permanent: true" made the LAST tooltip show up. All the other ones are gone. Sigh...

Why is it so hard to get my point across? I don't want "tooltips" at all: I want little labels that ALWAYS show. Like any map I've ever seen in my entire life except for Leaflet, which has somehow not thought of this the-most-basic-possible feature, but every other feature? I don't get it.

**Comment by perliedman** [comment]
@FjicdeiwFeiej not sure if this is a language problem or what, but to me it sounds like you're screaming at the people trying to help you in their free time. Please note that it _is not our job_ to help you. This project is maintained by volunteers, and mostly unpaid work. Shouting will not get you more help.

Also, as you've already been told, Stackoverflow or GIS stackexchange is the right place for this type of questions, and _if_ you're posting here, please provide code that reproduces the problem you're seeing.
