### ISSUE TITLE
Map not responsive if maxZoom is > maxNativeZoom in leaflet > 1.0.3

### ISSUE THREAD

**Issue by barbalex** [Leaflet/Leaflet#5833]
## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Google Chrome 61.0.3163.100 
- OS/Platform (with version) I'm using: Windows 10

Try to zoom the map with leaflet version 1.2.0: https://plnkr.co/edit/3CszXfN7E1ZuSoJSdJog?p=preview

Try to zoom the same map with leaflet version 1.0.3: https://plnkr.co/edit/OvZ88JXjVZfFZWARE0wo?p=preview

## What behaviour I'm expecting and which behaviour I'm seeing

The map should remain responsive, even if maxZoom > maxNativeZoom

See also comments following https://github.com/Leaflet/Leaflet/issues/5644#issuecomment-335219206

**Comment by ghybs** [comment]
Thank you for the separate report.

If my understanding is correct, the 2 plunkers you provide are demonstrations of the same issue as #5644, i.e. tiles not loading if `[minNativeZoom; maxNativeZoom]` and `[minZoom; maxZoom]` do not overlap.

> In my actual app the map does actually draw until it reaches maxNativeZoom, but as soon as zoom > maxNativeZoom the tab becomes unresponsive.

Please can you provide more details about this other issue and a reproduction case?
Otherwise I doubt we could investigate what could be causing such issue.
I could not get any tab freezing in Chromium or Firefox (Ubuntu) with the provided Plunkers.

**Comment by barbalex** [comment]
Sorry for not being clear enough. I also hat a lot of trouble to save plunkers. Is it better now?

**Comment by ghybs** [comment]
Thank you for the updated Plunkers.

If my understanding is correct, you have a "standard" case where `maxNativeZoom` is within `[minZoom; maxZoom]`.
```javascript
L.tileLayer(urlTemplate, {
  minZoom: 0,
  maxZoom: 22,
  maxNativeZoom: 18
})
```
That should _normally_ be well covered by the released Leaflet version, but there is always the possibility for a bug of course.

After correcting the PR code so that it is usable directly within a browser, I could not reproduce your issue in Chromium or Firefox (Ubuntu):
https://plnkr.co/edit/4uhCi3qgqGpRfZHOdEQj?p=preview
Tried with `master` version (at https://github.com/Leaflet/Leaflet/commit/93be1ae0a72737e98fe5b61b8090174f7128cb61), `v1.2.0`, with and without PR #5634 re-applied.

**Comment by barbalex** [comment]
Yep, your plunker (https://plnkr.co/edit/4uhCi3qgqGpRfZHOdEQj?p=preview) does not display this behaviour.

It is not quite clear to me why mine (https://plnkr.co/edit/3CszXfN7E1ZuSoJSdJog?p=preview), using v1.2.0, behaves differently though.

Oh. I just realized: I had copied `<script src="PR5634.js"></script>` from your plunker. Without that my plunker works fine. Even when I use the exact same settings as in my project.

So it remains a mistery why in my project tabs freeze when using `v1.2.0` but not when using `v1.0.3` :-(

**Comment by barbalex** [comment]
To be more precise: My project freezes the tab the moment zoom is > maxNativeZoom. And the layers configuration is:

```js
import React from 'react'
import { TileLayer } from 'react-leaflet'

const OsmColorLayer = () => (
  <TileLayer
    url="//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
    attribution="&copy; <a href=&quot;//osm.org/copyright&quot;>OpenStreetMap</a>"
    maxNativeZoom="19"
    minZoom="0"
    maxZoom="22"
  />
)

export default OsmColorLayer
```

**Comment by ghybs** [comment]
I see you are using Leaflet through react-leaflet.

Please have you investigated the possibility that the issue might come from this wrapper library?
Please understand that we do not provide support ourself for such wrappers.

I do not exactly know how react and react-leaflet work unfortunately.
I hope the string values that you pass to options like `maxNativeZoom` are parsed into integers when provided to Leaflet.

That being said, since you say that just upgrading Leaflet from `1.0.3` to `1.2.0` triggers your bug, it is possible that something changed in Leaflet internally, that react-leaflet was using and now gets broken.
The closer I could see from the current situation would be issue https://github.com/Leaflet/Leaflet/issues/5316 with its associated PR https://github.com/Leaflet/Leaflet/pull/5319.

**Comment by barbalex** [comment]
@ghybs You are right, it is react-leaflet that causes this behaviour. I could finally isolate it clearly: https://github.com/PaulLeCam/react-leaflet/issues/396

**Comment by barrycarter** [comment]
https://github.com/Leaflet/Leaflet/issues/5895#issuecomment-486815449 may or may not be helpful.
