### ISSUE TITLE
Cannot click layers with a z-index lower than Canvas

### ISSUE THREAD

**Issue by hoisingtonp** [Leaflet/Leaflet#5886]
* Browser and version:

Firefox 52.3.0

* Version of Leaflet (`L.version`):

1.0.3

* Version of esri Leaflet (`L.esri.VERSION`):

Undefined

Steps to reproduce the error:

1. Create a map pane at a z-index higher than that of the overlayPane (will require CSS).
2. Create a canvas, use it to render some circleMarkers and add them to the newly-created pane.
3. Create a polygon with "{ interactive: true}" and an on-click event, add it to the map (not the newly-created pane).

What happens is the polygon does not receive click events.

I was expecting the polygon to be able to receive click events. When I remove the canvas, polygons receive click events just fine.

Is this a limitation of using a canvas to render geometry?

NOTE: I want the the canvas to display *over* the overlayPane (where the polygon is, by default, added), so that it receives click events first.

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[RequireJS](http://requirejs.org/)

**Comment by perliedman** [comment]
Hi,

yes, this is a known limitation of how Canvas works in the browser. Since the canvas is just a bitmap, the browser will treat it as an opaque layer and not let any pointer events pass through it. So, putting a canvas layer on top of other layers will prevent the other layers from receiving pointer events (and this is not specific to Leaflet, but rather how the DOM works).

There are some hacks to work around this if you dig around the issues here and on Leaflet.VectorGrid, but in general there's not much we can do about this, so I'm going to close this.

**Comment by hoisingtonp** [comment]
Good to know--thanks!

**Comment by iTyphoons** [comment]
12
