### ISSUE TITLE
Leaflet tiles doesn't display in IE, whereas Firefox, Chrome, Opera is fine.

### ISSUE THREAD

**Issue by Akshay-Hegde** [Leaflet/Leaflet#5906]
- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using: Chrome, Firefox, Opera worked nicely, but when tested with IE-10, tiles doesn't display, its just gray.
- OS/Platform (with version) I'm using: Centos - fine, windows IE-10 tiles doesn't display

To see how, use below url in IE and Firefox / chrome.

## Here is example :

http://jsfiddle.net/rgkojo8m/

http://jsfiddle.net/gqojh93q/

![IE-10](https://user-images.githubusercontent.com/7464492/32659711-ff923110-c645-11e7-8b2c-1e00062ea250.png)

![Chrome](https://user-images.githubusercontent.com/7464492/32659710-ff613ea2-c645-11e7-8ebe-f9165f0c69f4.png)

**Comment by IvanSanchez** [comment]
Can not reproduce: `tiles.nio.org` does not resolve to an IP address.

If I were you, I'd look into the DNS configuration for that webserver. Otherwise check TLS versions in your webserver (IE10 cannot connect to webservers with the latest recomendations about crypto).

Not a Leaflet issue as far as I can tell.

**Comment by Akshay-Hegde** [comment]
It was not DNS issue, it was IE issue, tiles were 24-bit PNG, so I converted all png to jpg, now working fine.
