### ISSUE TITLE
Flickering when zooming more than one zoom step at a time.

### ISSUE THREAD

**Issue by AndreasSchmid1** [Leaflet/Leaflet#5937]
Zooming in or out very fast with the mouse wheel (more then one zoom step at a time) causes flickering (nearly every tile is unloaded before the new zoom level starts loading tiles).
This causes unattractive zoom effects. 
When it is not browser specific you can reproduce this issue with the sample provided at http://leafletjs.com/.

**Comment by smedasn** [comment]
Would be interested in this feature/bugfix as well

**Comment by ghybs** [comment]
Hi,

Thank you for your message.
When reporting an issue, please make sure to properly fill the issue template, even if the bug is not browser / OS / version specific (simply list the versions you have tested on).

It highly helps in understanding the situation and making sure we have enough information to investigate.

**Comment by ghybs** [comment]
## How to reproduce

- Leaflet version I'm using: 1.1.0+
- Browser (with version) I'm using: Firefox, Chrome
- OS/Platform (with version) I'm using: Kubuntu 16.04
- step 1: add a Tile Layer
- step 2: zoom more than 1 level in/out at a time, e.g. programmatically or with the mouse scroll wheel quick enough.

## What behaviour I'm expecting and which behaviour I'm seeing

- Expected: after zoom, tiles are scaled in/out until new tiles are loaded.
- Seen: if zoom change > 1, old tiles are pruned before new tiles are loaded and displayed.

## Minimal example reproducing the issue

Leaflet 1.1.0: https://plnkr.co/edit/GPIDJunYNNoa0R3EvmYf?p=preview
Leaflet 1.2.0: https://plnkr.co/edit/oBnpgcTAfXSBSOYYXwz0?p=preview
Use the button below the map to programmatically change the zoom level.

Leaflet 1.0.3 seems not affected by this bug: https://plnkr.co/edit/JC03JkS2H2tFobcpgsRB?p=preview

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by ghybs** [comment]
PR https://github.com/Leaflet/Leaflet/pull/3815 introduced an extra zoom change check, besides the map option [`zoomAnimationThreshold`](http://leafletjs.com/reference-1.2.0.html#map-zoomanimationthreshold)
https://github.com/Leaflet/Leaflet/blob/944f2de3a8932a2347acb33f72b83080c4f1b031/src/layer/tile/GridLayer.js#L452
See https://github.com/Leaflet/Leaflet/pull/3815#issuecomment-138537247 as for why threshold of 1 instead of re-using `zoomAnimationThreshold`.

However this PR is present in all v1.0.0-beta.2+ versions, so there should be something else that makes this bug visible on 1.1.0+ but not on 1.0.3…

**Comment by IvanSanchez** [comment]
OK, somebody please `git bisect` this thing to find the root cause.

**Comment by cherniavskii** [comment]
Tested it locally on current master branch and looks like it is already fixed:
![peek 2017-11-27 19-20](https://user-images.githubusercontent.com/13808724/33282247-64ee7f4a-d3a8-11e7-933e-91228820fd49.gif)

**Comment by tvfire** [comment]
did you test "Increase zoom by 2" as well?

**Comment by cherniavskii** [comment]
Yes, it works as expected

**Comment by mourner** [comment]
@ghybs @AndreasSchmid1 can you confirm the issue is no longer present in the master version?

**Comment by ghybs** [comment]
Yes the issue is fixed in current master: https://plnkr.co/edit/E0aaMSGgOkiHhx4jqTDY?p=preview

In fact it sounds like a duplicate of https://github.com/Leaflet/Leaflet/issues/5622

I positively confirm that this was fixed by PR https://github.com/Leaflet/Leaflet/pull/5634
https://plnkr.co/edit/kZ3yX7ssmamhyucoTjiV?p=preview

**Comment by AndreasSchmid1** [comment]
I can confirm an improvement but i cannot see that the issue is gone completely. If you zoom around with the mouse wheel heavily you will still notice periods where no tile is loaded in the viewport.

**Comment by ghybs** [comment]
@AndreasSchmid1 That is the effect of map's [`zoomAnimationThreshold`](http://leafletjs.com/reference-1.2.0.html#map-zoomanimationthreshold) option.

**Comment by AndreasSchmid1** [comment]
@ghybs ok thanks for info I will try that!
