### ISSUE TITLE
Disable Start and End Marker on GPX track

### ISSUE THREAD

**Issue by labneu** [Leaflet/Leaflet#5983]
Hello,

how can i Disable Start and end Marker  on GPX Track, i am using Leaflet whis Open Streetmap ( ODS_OSM

Thanhs for Anwser

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.
