### ISSUE TITLE
Leaflet canvas remove() bug

### ISSUE THREAD

**Issue by louMoxy** [Leaflet/Leaflet#6030]
I am removing a canvas map using map.remove() and creating a new canvas map and I am getting the error: 
`Uncaught TypeError: Cannot read property 'clearRect' of undefined`

I have created a codepen to show the issue, just uncomment the mymap.remove(); and comment out the setTimeout and you will see the error. 
https://codepen.io/moxy/pen/QaeKdp

```js
const mapId = document.getElementById("leaflet");
const removeButton = document.getElementById("remove");

var mymap = L.map(mapId, {
  renderer: L.canvas(),
  layers: [
		new L.TileLayer('//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
			'attribution': 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors'
		})
	]
}).setView([51.505, -0.09], 13);

var circle = L.circle([51.508, -0.11], {
  color: "red",
  fillColor: "#f03",
  fillOpacity: 0.5,
  radius: 500
}).addTo(mymap);

// setTimeout(() => mymap.remove(), 10); // Works as expected
mymap.remove();  // Throws an error
//removeButton.addEventListener("click", function(event) {
//  mymap.remove(); // Works as expected
// });
```

**Comment by IvanSanchez** [comment]
This is a race condition. What normally goes on here is that a canvas renderer triggers a `requestAnimationFrame` over at https://github.com/Leaflet/Leaflet/blob/510c3e7ba73ae7efb779f847a898e1f0f2cf2268/src/layer/vector/Canvas.js#L202 , so that everything is drawn *during the next frame*.

In this case, the map (or the canvas renderer) is removed during that request for the animation frame, so the delayed call to `_redraw` is trying to get the drawing context, which has already been destroyed.

There are several approaches to this, but I feel that the cleanest is to call `[Util.cancelAnimFrame](http://leafletjs.com/reference-1.3.0.html#util-cancelanimframe) (this.__requestRedraw)` in `L.Canvas._destroyContainer`, next to https://github.com/Leaflet/Leaflet/blob/510c3e7ba73ae7efb779f847a898e1f0f2cf2268/src/layer/vector/Canvas.js#L71


This bug seems that can be triggered programatically, so if anybody wants to fix this, I encourage to do Test-Driven Development for this one. Add a unit test over at https://github.com/Leaflet/Leaflet/blob/master/spec/suites/layer/vector/CanvasSpec.js , make sure it fails with the same error message, then fix the bug, then check if the tests pass.

**Comment by matthewtboyle** [comment]
@IvanSanchez 

So I am getting a similar error to this, but it is not from the removal of a map. Attached is a screenshot:![Image](https://github.com/user-attachments/assets/f2dc7b53-ab4e-42ca-877a-17840641a66b)

This is not happening consistently, and unfortunately its on a machine that I don't have direct access to. (hence the image being a photo that was taken of the screen).

What I know:
This is happening in leaflet-src.js in the _clear function ( per screenshot ).
The canvas is undefined for some reason.
When putting a breakpoint in this function and interacting with the map, it seems like it's only being hit when polygons have to be redrawn because of a map zoom/pan.
The last time this error happened was when the map initially loaded, without any user interaction (set zoom does get called during our map initialization). It DID have to show polygons.

I cannot personally reproduce it, which is the first thing I have tried to do. I am sorry that I can't give more information, so I understand if this amount of information is not enough. I am just looking for a way to potentially reproduce, or scenarios that you may know of that could cause this?

Could this have anything to do with a monitor's refresh rate? The only reason I ask is because I do see this warning:

`Warning: Be sure always to use the first argument (or some other method for getting the current time) to calculate how much the animation will progress in a frame — otherwise, the animation will run faster on high refresh-rate screens. For ways to do that, see the examples below.`

https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame
