### ISSUE TITLE
Mousedown event is not fired in leaflet popup 

### ISSUE THREAD

**Issue by rustam87** [Leaflet/Leaflet#6044]
i have leaflet popup and in this popup i have plugin([baronjs - custom scroll ](https://github.com/Diokuz/baron)) which dont work when i mousedown on baron scroll. I'm  thinking it happen because leaflet dont give mousedown event to bubble to leaflet popup.

console.log('mousedown') is not fireing;
```
this.map.on('popupopen', (e) => {
			 $(e.popup._container)[0].addEventListener('mousedown', () => {
				console.log('mousedown');
			 });
		});
```

but

console.log('mouseup') is fireing;
```
this.map.on('popupopen', (e) => {
			 $(e.popup._container)[0].addEventListener('mouseup', () => {
				console.log('mouseup');
			 });
		});
```

 Can i resolve this problem7

## How to reproduce

- Leaflet version I'm using: 1.2.0
- Browser (with version) I'm using:  55.0.2883.87 (64-bit)
- OS/Platform (with version) I'm using: Ubuntu 16.04
- Open popup when click to marker
- Mousedown

**Comment by IvanSanchez** [comment]
I removed the usage of jquery and I can confirm this is reproducible.

See https://plnkr.co/edit/hsckBhBzNnnY4zRPmFIY?p=preview

```
map.on('click', (e)=>{
  map.openPopup("Hello world!", e.latlng)
})

map.on('popupopen', (e) => {
  console.log(e.popup.getElement());
  
  L.DomEvent.on(e.popup.getElement(), 'mousedown click mouseup', (ev)=>{
    console.log(ev.type, ev);
  })
});
```

**Comment by IvanSanchez** [comment]
I'm gonna guess that this is due to `L.Popup._initContainer()` calling `L.DomEvent.stopPropagation()`, which in turns adds an event handler to the `mousedown` event. *Maybe* the event handler for `stopPropagation` runs first and prevents the user-defined event handler from firing? I'm not sure right now.

**Comment by brandiqa** [comment]
Am also facing a similar problem. I can't call any click events inside the popup. Has a solution been or a workaround been found yet?

**Comment by nuragic** [comment]
FYI

I have a similar problem... Inside the popup I need to use a custom select component, but unfortunately it doesn't work due to the `disableClickPropagation()` logic... I managed to make it work (for me at least) making this small change:

https://github.com/Leaflet/Leaflet/compare/master...nuragic:disableClickPropagation

_(I pushed the `dist` folder as well so I can use that branch directly from my package dependencies)_

It doesn't make any test fail, but I don't feel very confident to open a PR... let me know in case you think it would be enough and I'll open it. Any feedback is welcome anyway. Cc @IvanSanchez 

Cheers! 😄
