### ISSUE TITLE
detectRetina and maxZoom = no tiles

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [Leaflet/Leaflet#6059]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Mobile Chrome
- OS/Platform (with version) I'm using: Android 5
- Configure TileLayer with any maxZoom (in my case 20) and detectRetina=true
- Zoom to the max zoom on a device that matches detectRetina

## What behaviour I'm expecting and which behaviour I'm seeing

Expected: Visible Tiles
Seeing: No Tiles (no tileload events fired) - seems detectRetina would like to fetch maxZoom+1 which is blocked. I would suggest regular loading on maxZoom, ignoring detectRetina then

## Minimal example reproducing the issue

- Open: http://jsfiddle.net/sfe3gy3t/4/
- Zoom one level in => Grey map

There are other issues addressing this problem, but closed without a real solution.
https://github.com/Leaflet/Leaflet/issues/939

**Comment by ghybs** [comment]
Hi,

The workaround is currently simple: set your Tile Layer `maxZoom` option to 1 level higher than your map, as described in https://github.com/Leaflet/Leaflet/issues/939#issuecomment-194632280:
```javascript
var map = L.map('mapid', {
  maxZoom: 15
}).setView(latlng, 14);

L.tileLayer(urlTemplate, {
  detectRetina: true,
  maxZoom: 16 // 1 level higher than the map's maxZoom
}).addTo(map);
```

Live example: https://plnkr.co/edit/ECDefmcQRFR0rDS0KpAp?p=preview
(your JSFiddle uses old versions of Leaflet, and for some reason JSFiddle currently does not enable me changing the external resources)

When you explicitly specify `maxZoom` on your map, it is no longer affected by its Tile Layers' `maxZoom`, so you can safely set it to a higher value without affecting the map even for users not having a high pixel ratio device.

The behaviour you describe has much probably been there since the introduction of the `detectRetina` option (PR https://github.com/Leaflet/Leaflet/pull/586).

If you _do_ want to restrict the Tile Layer `maxZoom` to lower than the map `maxZoom`, you can define it by checking the `L.Browser.retina` flag, so that devices with either standard or high pixel ratio will be able to use the Tile Layer on the same zoom ranges (map-wise):
```javascript
L.tileLayer(urlTemplate, {
  detectRetina: true,
  maxZoom: L.Browser.retina ? 12 : 11 // 1 level higher for high pixel ratio device, because it will be decremented automatically.
}).addTo(map);
```

If your tile source does not have tiles for the extra zoom level, you should specify the [`maxNativeZoom`](http://leafletjs.com/reference.html#gridlayer-maxnativezoom) option, so that the Tile Layer loads tile from the previously available zoom level instead (as you suggested in your report):
```javascript
L.tileLayer(urlTemplate, {
  detectRetina: true,
  maxZoom: L.Browser.retina ? 12 : 11,
  maxNativeZoom: L.Browser.retina ? 10 : 11 // 1 level LOWER for high pixel ratio device.
}).addTo(map);
```
Live example: https://plnkr.co/edit/YxIhnMDfHKNhXmnfHhiy?p=preview

**Comment by bopoh13** [comment]
This code is already in the library. If there are no other ideas, then the issue can be closed.
https://github.com/Leaflet/Leaflet/blob/5ffe20792148a6dff6fbb7b6447de664050af083/src/layer/tile/TileLayer.js#L96

**Comment by IvanSanchez** [comment]
No action to be taken, then (other than wait for a release which includes that change)

**Comment by ghybs** [comment]
Hi,

I apologize as I guess I should have already closed this issue then.
Maybe I was waiting for OP's feedback in case I misunderstood something.

Just for the record, there is no need to wait for a new release: the pinpointed line had always been there (since the introduction of the `detectRetina` option in PR #586).

**Comment by eric-burel** [comment]
Hi, the documentation of `maxNativeZoom` is definitely unclear on this.

"Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled."

Currently, it is not the maximum zoom number the tile source has available, or at least "zoom" is not correctly defined here. Since in Retina mode the fetched zoom will be altered to handle an higher resolution, it is the "maximum zoom number the tile source has available **, minus 1 when retina is detected**".

I don't know how to phrase it, but you see my point, it is not obvious from this definitiation that we should do `L.Browser.retina ? 11 : 12` for instance.

**Comment by johnd0e** [comment]
> "maximum zoom number the tile source has available **, minus 1 when retina is detected**".

It shouldn't be like this.
But retina code is far from perfect, so.. all is possible.
Please re-check your observations, and open new issue, providing reproducible sample (on some public sandbox, as suggested by issue template).

**Comment by eric-burel** [comment]
There is not much to add to @ghybs comment actually, the quickfix with `maxNativeZoom` is fine. Changing the behavior now would be more consistent with the documentation, but will probably raise tons of issues in end applications, all the more that tile loading is not the first thing you unit test.
That's why I thought changing the documentation a bit would be the simplest approach.

**Comment by johnd0e** [comment]
Well, I can agree for `maxZoom`.
But that gets too weird for `maxNativeZoom`.
We need to decrement it's value for retina. For what sake? There is no logic.
That was good enough as dirty workaround only.

**Comment by eric-burel** [comment]
Ok so then the reproduction from @ghybs is all what you need, this is the exact same issue: https://plnkr.co/edit/YxIhnMDfHKNhXmnfHhiy?p=preview

To simulate retina manually, it seems that you can zoom in the browser, it will increase `window.devicePixelRatio` to a value over 1.
However, I haven't been able to either produce a reliable unit test for this, or to find the root cause of this issue with `maxNativeZoom`, as only `maxZoom` is mutated when retina is detected. My best guess is that somewhere, `maxNativeZoom` is compared to `maxZoom` and the mutation of `maxZoom` in retina mode makes it slightly wrong.

**Comment by bopoh13** [comment]
@eric-burel Replace `detectRetina: true,` in your code with `detectRetina: (L.Browser.retina ? true : false),` and remove code `maxNativeZoom: L.Browser.retina ? 11 : 12`. Perhaps this will solve your issue.
