### ISSUE TITLE
Create image with wms layer

### ISSUE THREAD

**Issue by JePedrosa** [Leaflet/Leaflet#6067]
Hello, I'm using leaflet and I wanted to create an image when the user clicks on a button, I always create it, except when I have a WMS layer loaded on the map that gets stuck. Somebody could help me?

Thank you

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
