### ISSUE TITLE
 EPSG:4326 points off from correct spot on map (custom tiles).

### ISSUE THREAD

**Issue by rfeie** [Leaflet/Leaflet#6080]
Hi there. I am filing an issue here because it seems like if this is not a bug it might be the best place to get further guidance as to whether/how I am able to fix this.

I am working on updating our map from OpenLayers 2 to Leaflet. I have my own set of tiles that are working correctly on OL2 but on leaflet any point I draw seems to be incorrect (further south and east than it should be). The projection is EPSG:4326. Since the points aren’t drastically far off from the actual point I am not sure what is going wrong. My hunch is its related to the projection. When I update the tileSize to 512.575 and the points look mostly correct but I am not sure why.

NOTE: Per the documentation (http://leafletjs.com/reference-1.3.0.html#crs-crs) I can see I do not have  "two 256x256 pixel tiles covering the whole earth at zoom level zero”. Could that cause this problem?

I have already asked on stackexchange and tried to reach out to a couple people who have a lot of experience in Leaflet to see if they had any suggestions to no avail:
https://gis.stackexchange.com/questions/272820/leaflet-points-off-from-correct-spot-on-map

Thank you!

Here is a working version of EPSG:4326: https://codepen.io/rfeie/pen/zRXemM
Here is my version with the custom tiles: https://codepen.io/rfeie/pen/ZrZwjR

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: OS X

**Comment by IvanSanchez** [comment]
The tilelayers are offset. Not a leaflet bug.

![image](https://user-images.githubusercontent.com/1125786/36982046-1a8e03f6-208f-11e8-9c62-4d9179c7a60b.png)

---

> I can see I do not have "two 256x256 pixel tiles covering the whole earth at zoom level zero”. Could that cause this problem?

Because the tiles are double the size, you have two such tiles at zoom level 1, i.e.:

http://xio-test-tiles.s3-website-us-west-2.amazonaws.com/layers/base_map/L01/R00000000/C00000000.jpg and 
http://xio-test-tiles.s3-website-us-west-2.amazonaws.com/layers/base_map/L01/R00000000/C00000001.jpg
