### ISSUE TITLE
Map fails to render correctly if created on an element that isn't yet part of the document tree

### ISSUE THREAD

**Issue by mberndt123** [Leaflet/Leaflet#6088]
Hi,

I noticed a behaviour in Leaflet that I consider a bug. Consider the following code: it creates a div element, inserts it into the document tree and then renders a map into it.
```javascript
      var div = document.createElement("div")
      div.setAttribute("id", "myMap") // my stylesheet contains the formatting for this ID
      document.body.appendChild(div)
      var map = L.map(div).setView([51.505, -0.09], 13)
      L.tileLayer("http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png").addTo(map)
```
This works fine. But if I create the map _first_ and _then_ insert it into the document tree like so
```javascript
      var div = document.createElement("div")
      div.setAttribute("id", "myMap") // my stylesheet contains the formatting for this ID
      var map = L.map(div).setView([51.505, -0.09], 13)
      L.tileLayer("http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png").addTo(map)
     document.body.appendChild(div)
```
then I get completely broken rendering. The map is mostly grey except for a very narrow stripe of map material on the left edge of the div. Panning leads to map fragments being rendered here and there, but there's never a complete map to be seen. When I resize the browser window, it fixes itself and works flawlessly from then on.

So why am I even trying to do that? Because I'm using a library that helps with DOM manipulation. This library expects me to create and initialize elements, but will take care of inserting them into the document tree itself, hence I can't control the order.

**Comment by cherniavskii** [comment]
Hi Matthias!

Before map container is added to DOM, it's size is 0 x 0 px. Use [map.invalateSize()](http://leafletjs.com/reference-1.3.0.html#map-invalidatesize) after adding container to DOM in order to recalculate container size.

P.S. In the future, please ask questions on [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet). Github issues are used for reporting bugs.
If you really sure it's Leaflet issue, please fill up issue template and provide link to minimal example reproducing the issue.
