### ISSUE TITLE
Inconsistency: CircleMarker is not a Marker

### ISSUE THREAD

**Issue by martinRenou** [Leaflet/Leaflet#6130]
## What behaviour I'm expecting and which behaviour I'm seeing

It looks like an inconsistency that `CircleMarker` is not a subclass of `Marker`. It is also weird for me that `Circle` is a subclass of `CircleMarker`, I think it should directly extend `Path`.

**Comment by mourner** [comment]
This is by design. Perhaps "Marker" part in the name is misleading, but I wanted to accentuate the presentational aspect of the circle as opposed to the `Circle` class. It still doesn't have much in common with the way Marker works (because vector items are handled very differently than simple DOM elements in Leaflet).

`Circle` is a subclass of `CircleMarker` because it reuses its logic. I'm open to a PR that makes it directly extend `Path` if you don't duplicate much code.
