### ISSUE TITLE
Drop support for Internet Explorer

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet#6136]
> **Note**: Support for IE is being dropped in [v2.0](https://github.com/Leaflet/Leaflet/milestone/39)!

I think it's really time to discuss dropping support for IE8, and also possibly 9 and 10. These browsers are supported by few web sites these days, and for users who really need to support them, we can point to older versions of Leaflet.

Maintaining support for olders IE versions is a pain, and it appears we rarely test it anyway (we broke IE8 in a previous release without noticing and nobody really told us).

**Comment by perliedman** [comment]
Some discussion on our IE support in this thread: #4745.

**Comment by IvanSanchez** [comment]
I guess it's time to [run this informal poll again](https://twitter.com/LeafletJS/status/685052811374129152)?

**Comment by mourner** [comment]
I'm up for dropping IE8 support, and agree that we can just offer older versions of Leaflet for people who need to support it. Even jQuery no longer supports that version (https://jquery.com/browser-support/), so people using such a browser should expect the majority of the web to be mostly broken.

We should consider dropping support for IE9 and IE10 too. I just fetched the latest data from http://gs.statcounter.com/ and the breakdown is as follows:

- IE 11: 2.7%
- IE 10: 0.11%
- IE 9: 0.11%
- IE 8: 0.17%

All the IE8–10 values dropped by 2x in the last year.

**Comment by tomhughes** [comment]
I had a look at the openstreetmap.org statistics at the request of @IvanSanchez and our numbers for yesterday are:

* IE 11: 9% (11128 visitors)
* IE 10: 0.1% (99 visitors)
* IE 9: 0.2% (198 visitors)
* IE 8: 0% (4 visitors)
* IE 6: 0% (2 visitors)

I suspect anything before IE9 barely works other parts of the site anyway, if it's actually functional at all.

**Comment by codeofsumit** [comment]
I'd vote for dropping everything below IE11.

**Comment by franciscop-invast** [comment]
I would say that libraries websites such as openstreetmap.org are *not* representative; some developers will be doing sanity checks on those pages to make sure they work. Before considering any library and if there's a demo, I open it in the browsers I need to support to make sure the basics are working. Now this implies IE11, but before I would use browserstack to open libraries demos in other browsers, very likely slightly tweaking the analytics.

**Comment by septatrix** [comment]
Pinging @mourner because I think a year and a half later it may be time to again discuss this and come to a conclusion?

**Comment by amb26** [comment]
I second dropping support for IE < 11 so that we can move forward on issues like https://github.com/Leaflet/Leaflet/issues/4745 - cheers!

**Comment by jonkoops** [comment]
In my opinion we can drop support for all versions of Internet Explorer in version 2. Right now the focus for Leaflet is to decrease our giant backlog of issues and PR before deciding what is next in terms of deprecation.

**Comment by jonkoops** [comment]
Support for Internet Explorer 11 [will be dropped](https://docs.microsoft.com/en-us/lifecycle/products/internet-explorer-11) on Jun 15th 2022. I suggest we drop support for Internet Explorer entirely in V2, which should be released after that date.

I propose we move to accept this proposal. @mourner @IvanSanchez @Falke-Design WDYT?

**Comment by jonkoops** [comment]
My main problem with IE11 is it's [crippled support](https://kangax.github.io/compat-table/es6/#ie11) for anything modern JavaScript. Going forward I think our lowest possible compile target should be ES2015.

**Comment by Malvoz** [comment]
It'll be interesting to see the poll results, however, dropping IE completely means less considerations and an improvement to the overall workflow. People can still user older versions of Leaflet if they want to support IE.

**Comment by jonkoops** [comment]
If anything dropping support will incentivize people to stop supporting it all together.

>  "Be the change you wish to see in the world." – not Mahatma Gandhi

**Comment by jonkoops** [comment]
Another reason why we might want to drop support for Internet Explorer is that our tooling is no longer working in newer versions (see https://github.com/Leaflet/Leaflet/pull/8204#issuecomment-1114878906). Some dependencies are already held back simply to keep this support around.

**Comment by jonkoops** [comment]
The final results from the [Twitter poll](https://twitter.com/LeafletJS/status/1518606186521804800) are in, I think we have enough information to make an educated decision. I am personally in favor for dropping it for the following reasons:

- Only 9.7% of responses have indicated the desire to keep supporting Internet Explorer (these users can keep using 1.x).
- We are [holding back](https://github.com/Leaflet/Leaflet/blob/bcc59e54cd9e657f660fe29b710a565ea346c7a7/.github/dependabot.yml#L11-L17) several dependency upgrades due to the need to support Internet Explorer.
- We can't use more modern and optimizable ECMAScript syntax that allows us to align with modern expectations of developers (such as [Classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)).
- We have a lot of crufty code around to support older browsers (not just IE), this will allow us to trim down Leaflet instead of shipping this code to browsers that can't do anything with it.
- We have a lot of [open issues](https://github.com/Leaflet/Leaflet/labels/ie) around Internet Explorer support that can be closed.
- Support for Internet Explorer 11 [will be dropped](https://docs.microsoft.com/en-us/lifecycle/products/internet-explorer-11) on June 15th 2022 by Microsoft itself.

For that small percentage of users that are still in need to support Internet Explorer, they can simply stick to Leaflet 1.x. I speculate their projects are not likely to be upgraded fast as the whole ecosystem is breaking away from IE. This also provides more fuel to the fire towards their stakeholders to just get rid of this dinosaur of a browser.

**Comment by Falke-Design** [comment]
I think we should make a V1.9 release with a few fixes with the most important things and then we make a V2 release with dropping all IE versions. **BUT** we don't add other features from the [Roadmap](https://github.com/Leaflet/Leaflet/discussions/7729). We have to much open PRs and issues.

**Comment by jonkoops** [comment]
So in essence we'd just use the 'v2' version as a way to drop support for older browsers without actually adding any new features. I think that is perfectly valid, and it would reduce the impact of the release in terms of massive changes.

**Comment by mourner** [comment]
> So in essence we'd just use the 'v2' version as a way to drop support for older browsers without actually adding any new features. I think that is perfectly valid, and it would reduce the impact of the release in terms of massive changes.

@jonkoops yep, that was my plan for v2 all along :) see https://github.com/Leaflet/Leaflet/issues/7704#issuecomment-953972098

**Comment by jonkoops** [comment]
Sounds good to me :+1:

**Comment by jonkoops** [comment]
I think we're all in agreement here that we want to drop support for all versions of Internet Explorer so I am marking this proposal as accepted.

**Comment by jonkoops** [comment]
Closing this as we just branched off for v2, so we can consider this resolved.
