### ISSUE TITLE
We need to maintain our own plugins and our own ecosystem

### ISSUE THREAD

**Issue by Jerry-goodboy** [Leaflet/Leaflet#6141]
like VUE, REACT, we should maintain our own plugins and solutions to build our own ecosystem

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.

**Comment by ghybs** [comment]
BTW: Vue is funded by people through Patreon, and React is funded by Facebook.

@Jerry-goodboy please would you consider funding Leaflet, so that maintainers have an incentive in doing such work?
