### ISSUE TITLE
Zoom home offset if sidebar is open

### ISSUE THREAD

**Issue by valeriodeluca** [Leaflet/Leaflet#6167]
Hi guys, this is my webmap:

www.mainjoin.eu/map/santiago/

Everything works perfectly: sidebar(v2), autopan, popup content go in sidebar panels fine.

Only a few trouble. At top right I have zoom home button.
When sidebar is close everything go fine: zoom home button center my map.
When sidebar is open the zoom home makes the same thing but the sidebar hide part of my center map.
I'd like a little right-offset on result of zoom home button when sidebar is open.
Something like: 

if sidebar.close() = true
	zoomhome
else
	zoomhome.offset

Any advices are welcome, thanks!
Valerio

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

From your description, you would probably be interested in that post on GIS SE:
https://gis.stackexchange.com/questions/218102/how-do-i-zoom-pan-to-a-leaflet-map-such-that-the-given-point-is-off-center/218111#218111

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.
