### ISSUE TITLE
fitBounds latitude issue (Fiji issue)

### ISSUE THREAD

**Issue by dantaex** [Leaflet/Leaflet#6172]
## How to reproduce

- Leaflet version I'm using: 1.3.1, and also 1.2.0
- Browser (with version) I'm using: Chrome 66.0.3359.181, Fireox 60.0.1
- OS/Platform (with version) I'm using: OSX 10.11.6 and Linux Ubuntu 14.04
- To reproduce you have to add two markers in the edge of the world, one with positive long and one with negative long. For example in Fiji, we have places with lat,lng like 
-16.853, -179.915 
and another one like 
-16.802, 179.990
Both places are very close to each other but the radical difference in longitude is what I think is the key.
Check source code in here 
https://kipulab.github.io/leaflet-fiji-issue/

**Comment by IvanSanchez** [comment]
This is tricky, because a bounding box with its boundaries at latitudes e.g. -160° and 160° can either mean this:

![imagen](https://user-images.githubusercontent.com/1125786/40654619-18c1436a-633f-11e8-8202-a7e1e2258727.png)

or this:

![imagen](https://user-images.githubusercontent.com/1125786/40654642-2bac8a98-633f-11e8-855f-0b289f1c144e.png)

So Leaflet wouldn't know what the developer/user wants in each case. I'm afraid that changing this behaviour to be "smarter" would incur in side effects. I think we discussed in the past about the first component of a `L.LatLngBounds` forcefully being the westernmost, and the second component being the easternmost, but I think we just kept the status quo (which might be the nicer thing to do).

I do remember some preliminary work about repositioning **markers** around the antimeridian, using the map's center as the threshold for all the `L.LatLng.wrap()` calls (instead of wrapping/modulo'ing everything into the CRS bounds).

This is also a nice moment to remind that GeoJSON polygons have [winding order](https://tools.ietf.org/html/rfc7946#section-3.1.6), but nobody really cares. Specifically, Leaflet will try to render anything instead of enforcing the winding order of polygons. The case for `LatLngBounds`s is the same IMO.

The workaround here is to add `360` to the coordinate, e.g. instead of
```
L.rectangle([[ 40,160],[-40, -160]]).addTo(map);
```

do

```
L.rectangle([[ 40,160],[-40, -160+360]]).addTo(map);
// or
L.rectangle([[ 40,160],[-40, 200]]).addTo(map);
```

(Yes, you can have things with latitudes outside the `-180, 180` range and stuff will work as long as it's not markers or tiles)

**Comment by IvanSanchez** [comment]
On this subject, we might want to do something like a "Pacific CRS" and see how that works with data far from Greenwhich and around the antimeridian, like:

```
L.CRS.EPSG3857.Pacific = L.CRS.EPSG3857.extend({
    wrapLng: [0, 360]
});
var map = L.map('containerid', {crs: L.CRS.EPSG3857.Pacific});
```

**Comment by andrewhodel** [comment]
It also needs to be added, based on the content from issue #7582 that Marker accepts coordinates beyond -90 to 90 and -180 to 180.

It should produce an error when that happens.

**Comment by IvanSanchez** [comment]
After digging through a few old issues, I'm gonna close this as a duplicate of https://github.com/Leaflet/Leaflet/issues/4919 , and also related to https://github.com/Leaflet/Leaflet/pull/1293.

> It should produce an error when [coordinates beyond -90 to 90 and -180 to 180] happens.

No, there will be no error in such as case, as per https://github.com/Leaflet/Leaflet/issues/4919#issuecomment-247537065 . 

That would also break the workarounds explained in https://stackoverflow.com/questions/38820724/how-to-display-leaflet-markers-near-the-180-meridian/ and https://stackoverflow.com/questions/40532496/wrapping-lines-polygons-across-the-antimeridian-in-leaflet-js.
