### ISSUE TITLE
Set z-index of marker popup (tooltip) such that it appears outside the bounding div of the map, rather than it being hidden once it hits the map border.

### ISSUE THREAD

**Issue by kalyanixraut** [Leaflet/Leaflet#6181]
How to set z-index of marker popup (tooltip) such that it appears outside the bounding div of the map, rather than it being hidden once it hits the map border when zooming or panning.

**Comment by IvanSanchez** [comment]
Not possible with the current architecture.

Fixing this would require changing the way the map container spawns map panes, changing the `overflow: hidden` style on such containers, which would overcomplicate z-index and map pane management.

This would also spawn a whole new set of problems regarding visibility of off-map elements: When should such a tooltip (or marker, or whatever) be hidden? Length from the map container's border? (Too much CSS) Whenever the point gets off the screen? (More event handlers) Whenever the whole tooltip/marker gets off the map? (need to fetch the size of it dinamically, maybe even with mutation observers)

It sounds like an "easy" feature request, but when looking at it a bit closer it creates a set of not-very-well-specified edge cases. I'll close as "Won't fix", because I don't think it's worth the effort, and we maintainers can't really devote resources to this.

**Comment by IvanSanchez** [comment]
Also: see https://developer.mozilla.org/en-US/docs/Glossary/Stacking_context

**Comment by tristanisginger** [comment]
A work around is to use the mouseovet event to create your own absolutely positions tooltip using the containerPoint variable
