### ISSUE TITLE
Marker popup flashing when use slideto plugin 

### ISSUE THREAD

**Issue by Ma7m00d** [Leaflet/Leaflet#6194]
Hello everyone 
I am building tracking application 
and I face a problem with marker popup when using slideTo.js plugin to animate marker movement 
so the scenario is when new point comes I should read the information and update the marker popup due 
these information while marker is moving but this cause the popup to flash or blink 
like attached image 
![aa21](https://user-images.githubusercontent.com/40431501/41661204-d333f81e-74a6-11e8-8cdf-06b0fa0d3e8f.gif)

my code is 
`marker._popup.setContent($('<div>').append($(popup).clone()).html());`
each time new location come 

please help

**Comment by zhen1991** [comment]
Hi!
why not to update information every 60 seconds or every 100 meter so i think it will not be like that !
now you are calling information every second so its why you face this !

**Comment by Ma7m00d** [comment]
actually I update information every 20 seconds but I think the real problem is the clustering of marker 
because when I removed the marker from cluster it worked fine
how to solve this with clustering

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

I will close this ticket since the issue does not appear when you remove the clustering.

I see that you had already posted it on Stack Overflow: https://stackoverflow.com/questions/50950174/leaflet-markers-popup-blinking

You should very probably directly add your image into that post (instead of linking to an external server), and a reproducible example there (e.g. you can use https://leafletjs.com/edit).
When you do not add enough information in your question, you will likely get no answer and can even get down-voted.
