### ISSUE TITLE
How to fix and drop marker with leaflet in Ionic?

### ISSUE THREAD

**Issue by rsa408** [Leaflet/Leaflet#6212]
By using Google map API in ionic I can fix marker in the center and drop when clicking over the marker to set origin/target position how can I do with leaflet. please.

 ```
#centerMarker {
    width: 22px;
    height: 40px;
    display: block;
    content: ' ';
    position: absolute;
    top: 50%;
    left: 50%;
    margin: -40px 0 0 -11px;
    background: url('https://maps.gstatic.com/mapfiles/api-3/images/spotlight-poi_hdpi.png');
    background-size: 22px 40px; 
    pointer-events: none;   }
```
Drop Marker Function:

```
DropMarker(){  
  let source = "origin";
   let image = 'assets/img/Untitled-1.png';   
   let marker = new google.maps.Marker({    
    map: this.map,
    animation: google.maps.Animation.DROP,
    position: this.map.getCenter(),
    draggable: true, icon: image
  }); 
```
I am using leaflet Js ver: 1.3.1

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

I see that you have already posted it on SO:
https://stackoverflow.com/questions/51087545/how-to-fix-and-drop-marker-with-leaflet-in-ionic
You probably got no answer yet because people may not understand what you are trying to achieve.
You should consider adding more explanations, some screenshots / sketches, and a live example, e.g. using CodeSandbox or StackBlitz.

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* Angular / AngularJS
* Leaflet for R
* Joomla
* WordPress
* Drupal
* Rails
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* etc.

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
