### ISSUE TITLE
leaflet-1.3.1  On the longitude and latitude problems caused by CRS

### ISSUE THREAD

**Issue by shmen** [Leaflet/Leaflet#6215]
## How to reproduce

- Leaflet version I'm using: 1.3.1
- Browser (with version) I'm using: chrome
- OS/Platform (with version) I'm using: windows 10

    const map = L.map('emap', {
             crs: L.CRS.EPSG4326,
             center: [
                 31.90059,
                 120.584663
             ]
    });

and

  const map = L.map('emap', {
             center: [
                 31.90059,
                 120.584663
             ]
    });

After setting the CRS, the center point and the latitude and longitude are different. Because of the data reasons, the latitude and longitude obtained by the CRS:EPSG4326 are consistent with the default values. What is the solution?

**Comment by ghybs** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

Please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

Sharing a live reproduction example (e.g. using https://leafletjs.com/edit) that automatically shows the bug with comments can highly increase the possibility of successful investigation.

You can also add annotated screenshots, sketches, animated captures, etc.

**Comment by ghybs** [comment]
I will re-open once enough information has been provided.
