### ISSUE TITLE
Large gap when enabling tile wrapping with CRS.Simple

### ISSUE THREAD

**Issue by zorun** [Leaflet/Leaflet#6292]
## How to reproduce

- Leaflet version I'm using: 1.3.3
- Browser (with version) I'm using: chromium 68.0.3440.106
- OS/Platform (with version) I'm using: Linux

I am experimenting with leaflet to render a large panorama photo, using `L.CRS.Simple` like https://leafletjs.com/examples/crs-simple/crs-simple.html and generating tiles for my large image.
It works fine, although I had to pad the tiles on the edge so that they are also 256x256 pixels (otherwise leaftlet would stretch them).

However, when trying to render a 360° panorama (i.e. enabling wraparound), there is a gap at the point where it wraps:

![leaflet-pano-gap](https://user-images.githubusercontent.com/731144/44301057-385a1780-a311-11e8-949b-382e97a2b0ec.png)

Here is what I would expect, created manually with Gimp (here with a 1px border to see the wrapping point):

![leaflet-pano-gap-expected](https://user-images.githubusercontent.com/731144/44301195-f7630280-a312-11e8-9d7f-816664106d34.png)

I have added edges to my tiles to see where the issue comes from:

![leaflet-pano-gap-edges](https://user-images.githubusercontent.com/731144/44301061-45770680-a311-11e8-9c82-6b9cda54bc87.png)

Basically, I tell leaflet to wrap at the width of my image, but it instead wraps only at the next tile, thus creating a large gap.

Here is my code:

```
var SimpleWrapCRS = L.extend({}, L.CRS.Simple, {
    wrapLng: [0, image_width],
});

panoLeaflet = L.map('pano', {
    crs: SimplePano,
    center: [-image_height/2, image_width/2],
    zoom: -4,
    minZoom: -8,
    maxZoom: 3,
});
var tileLayer = new L.TileLayer('mytiles/{z}-{x}-{y}.jpg', {
    minZoom: -8,
    maxZoom: 3,
    maxNativeZoom: 0,
    opacity: 1.0,
    noWrap: false,
    bounds: [[0, 0], [-image_height, image_width]], // Avoid loading inexistant tiles (generating lots of 404)
});
panoLeaflet.addLayer(tileLayer);
```

`image_width` is the total width of the original image, in pixels, **without** counting the padding of the last tile.

## Minimal example reproducing the issue

I can create a jsfiddle or something else, but only after making sure this is really a bug!

**Comment by zorun** [comment]
Now that I think about it, I basically want a "fractional tile" for the last tile before the wrapping point.

It seems like it would be difficult to do with the current GridLayer design?

I guess this issue does not happen with regular maps, because zoom levels are built so that tiles divide exactly the world size?

**Comment by ghybs** [comment]
Hi @zorun,

This looks to me like a slightly incorrect usage of Leaflet, not a Leaflet bug.

As you figured out, the GridLayer system and its wrapping feature assume that your grid size matches the size of your image when divided by a power of 2.
See the [Quadtree](https://en.wikipedia.org/wiki/Quadtree) / [QuadTile](https://wiki.openstreetmap.org/wiki/QuadTiles) scheme and also the Leaflet tutorial about [Zoom levels](https://leafletjs.com/examples/zoom-levels/). I am sure you can find plenty more resources online about this topic.

The usual workflow to convert a big image into tiles, while ensuring no horizontal padding is necessary (which would create a gap when wrapping, like illustrated in your screenshots), is to _resize it_ so that at zoom 0, it fits a single tile perfectly (round pixels size number):
1. Divide your image width by 2 `n` times, until you reach an acceptable tile size at zoom 0 (usually between 200 and 300).
2. Round the number and multiply it back by 2^`n`, to get the width your image should have.
3. Resize your image accordingly.
4. Tile your image into a tileset.

Depending on your project specificities, you might already be good by using an appropriate [`tileSize`](https://leafletjs.com/reference-1.3.4.html#gridlayer-tilesize) option on your Tile Layer.

If you need further help in your project, please feel free to use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).
