### ISSUE TITLE
I got the favicon.ico error server responded with a status of 404 . Do any one know why?

### ISSUE THREAD

**Issue by tmh12345** [Leaflet/Leaflet#6299]
## How to reproduce

- Leaflet version I'm using:1.3.3
- Browser (with version) I'm using:Google Chrome
- OS/Platform (with version) I'm using:window 10
- step 1
- step 2

## Minimal example reproducing the issue

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

Using http://leafletjs.com/edit.html or any other jsfiddle-like site.

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
