### ISSUE TITLE
Question: L.control witht radio buttons for some overlay layer?

### ISSUE THREAD

**Issue by tomber42** [Leaflet/Leaflet#6342]
Sorry, not a bug.. a question

Is there a possibility with L.control to add some overlay layers with a radio button instead of checkbox? Because in my project i want to add some diffrent markers to choose , but only one should be active on the map.

Tom

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

**Comment by ghybs** [comment]
The [Layers Control](https://leafletjs.com/reference-1.3.4.html#control-layers) can use any kind of Layers.
The "base layer" and "overlay" difference is only in which section they appear in the Control:
- base layers appear on top with radio buttons
- overlays appear on bottom with checkboxes.

**Comment by smartm0use** [comment]
Create a second `L.Control.Layers`, with your "overlays" as "base layers", or use `groupedlayercontrol` plugin.
More information here: https://gis.stackexchange.com/questions/267605/leaflet-api-select-one-overlay-at-a-time-like-base-layers
