### ISSUE TITLE
leaflet.js - _addItem: function(t) - checkbox - first entry - checked

### ISSUE THREAD

**Issue by Jefferson-goxts** [Leaflet/Leaflet#6343]
Hello Community&Devs.

maybe you would like to help me.
I like to select automatically the first entry in my overlays.js ---> var labels = [];

Someone have a reason for this?

File leaflet.js / Line: 2075:
t.overlay ? ((i = document.createElement("input")).type = "checkbox", i.className = "leaflet-control-layers-selector", i.defaultChecked = o) : i = this._createRadioElement("leaflet-base-layers", o), this._layerControlInputs.push(i), i.layerId = n(t.layer), mt(i, "click", this._onInputClick, this);

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.
