### ISSUE TITLE
setView takes ages at certain conditions, examples provided

### ISSUE THREAD

**Issue by fralik** [Leaflet/Leaflet#6346]
## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Chrome (69.0.3497.92 (Official Build) (64-bit)), Firefox 62.0
- OS/Platform (with version) I'm using: Windows 7, 64-bit

## What behaviour I'm expecting and which behaviour I'm seeing

After I add markers to map, I click on a button 'show first marker', which sets map view to the first marker. I am expecting a map to set on a new view quite fast. What I see is a delay of 10-30 seconds.

I see this as not a pure leaflet bug, but something strange is going on here. Seems like a simple inclusion of sql.js messes everything up. Not sure how they can interfere. 

## Minimal example reproducing the issue

- [x] this example is as simple as possible
- [ ] this example does not rely on any third party code

I've prepared two jsfiddle examples.
- [Markers from JSON](https://jsfiddle.net/fralik/n0t4m3fb/) works as expected.
- [Markers from JSON with SQL.js included](https://jsfiddle.net/fralik/xo3q1jpz/) doesn't work.

**Comment by IvanSanchez** [comment]
Cannot reproduce on Firefox 62.0 on Linux. A peformance flame chart shows that loading the markers into Leaflet.MarkerCluster takes roughly the same amount of time, 0.5sec.

**Comment by fralik** [comment]
Tried it out on Firefox 62.0 on Linux. I still see the same problem. The problem is not in marker loading, but it appears once I click on 'show first marker', i.e. when I try to setView on the first already loaded marker.

**Comment by ghybs** [comment]
Hi @fralik,

You are using [`removeOutsideVisibleBounds`](https://github.com/Leaflet/Leaflet.markercluster#enabled-by-default-boolean-options) option from [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster) plugin in your [faulty example](https://jsfiddle.net/fralik/xo3q1jpz/), but not in your [working one](https://jsfiddle.net/fralik/n0t4m3fb/).

> **removeOutsideVisibleBounds:** Clusters and markers too far from the viewport are removed from the map for performance.

Adding it (i.e. setting it to `false`) in your working example makes it "fail": https://jsfiddle.net/n0t4m3fb/63/
Removing it from your faulty example makes it work: https://jsfiddle.net/xo3q1jpz/5/

Expected behaviour of turning off that option of that plugin.
It only shows that loading thousands of icon-based Markers makes the browser struggle, which is a known limitation of Leaflet, and one of the rationale for using a clustering plugin and keeping that option on.
