### ISSUE TITLE
map.fitBounds() / map.getBoundsZoom() deliver wrong values after resizing map

### ISSUE THREAD

**Issue by Superslub** [Leaflet/Leaflet#6354]
## Problem 
map.fitBounds() and map.getBoundsZoom() deliver wrong values after resizing the map (especially if the map is decreased in size).

## How to reproduce
Example code here: https://jsfiddle.net/MaxHeadroom/s6h40xrn/
0.) enable js console output of your browser
1.) decrease the size of the map area
2.) click "run"
3.) increase size of map area -> the map automatically adopts zoom level to the orange rectangle
4.) decrease the size of the map area -> map.fitBounds() fails ....

(used Leaflet Version: 1.3.4)

**Comment by ghybs** [comment]
Hi,

First of all, congratulations on your first issue on GitHub! :smile: 

In your code example fiddle, you use [`map.setMinZoom()`](https://leafletjs.com/reference-1.3.4.html#map-setminzoom), which expectedly prevents the map (hence [`map.fitBounds()`](https://leafletjs.com/reference-1.3.4.html#map-fitbounds)) from going to a lower zoom to adjust to the container's decreased size:
> Sets the lower limit for the available zoom levels

Removing the `minZoom` restores the behaviour that you would have expected: https://jsfiddle.net/s6h40xrn/45/

As for [`map.getBoundsZoom()`](https://leafletjs.com/reference-1.3.4.html#map-getboundszoom), your example shows that it is also affected by the specified `minZoom`, which may or may not be the expected behaviour.
If you wish to argue on that, please open a new issue.
