### ISSUE TITLE
draw-order of geoJSON features

### ISSUE THREAD

**Issue by marcellangmaier** [Leaflet/Leaflet#6369]
- Leaflet version I'm using: 1.3.4

How can I explicitly specify the draw order of geoJSON features? I have several point features with overlapping icons. When zooming In and Out, the order changes sometimes.

What I have already tried to do:
* Added the features to the geoJSON layer in the order oldest first, newest first.
* Call bringToFront or bringToBack in the onEachFeature function

I have read the documentation and found custom map panes. Do I really have to create a pane for each feature?

The attached image illustrates my problem: I want the green marker above the red above the grey one. Always.

![feature_order](https://user-images.githubusercontent.com/26068556/46862768-eec01180-ce15-11e8-8397-c91104a332ea.PNG)

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

In your case, it sounds like you are using icon-based Markers.
In that case, their `z-index` is automatically adjusted based on their latitude.
You can also use their [`zIndexOffset`](https://leafletjs.com/reference-1.3.4.html#marker-zindexoffset) and/or [`riseOnHover`](https://leafletjs.com/reference-1.3.4.html#marker-riseonhover) options.
Custom map panes is also a possible solution.
If you need further help, please ask on Stack Overflow.
