### ISSUE TITLE
images cant display in google chrome,opera,firefox

### ISSUE THREAD

**Issue by cs89gr** [Leaflet/Leaflet#6379]
helloo

i use this manual to add some image in my maps and if i follow this code the working fine .

here the code :

var imageUrl = 'newark.png',
    imageBounds = [[40.712216, -74.22655], [40.773941, -74.12544]];
L.imageOverlay(imageUrl, imageBounds).addTo(map);

in my case i use png format images but that images if i use google chrome,opera,firefox browser don't display my image in map and show me broken image message if i use Microsoft edge browser then all work fine and the image work fine.

any idea how can i fix that problem ?

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

**Comment by ghybs** [comment]
[Developer Tools](https://developers.google.com/web/tools/chrome-devtools/) might already give you some debugging hints.

If you need further help, open a question on Stack Overflow with what you get from the browser console and a reproduction example.
