### ISSUE TITLE
make a circle-based hole into a polygon with a L.circle()

### ISSUE THREAD

**Issue by Itemshopp** [Leaflet/Leaflet#6390]
After a lot of researches I couldn't find a way to make this work.
I suppose `myPolygon = L.polygon([polygonCoords, circleCoords], myOptions).addTo(map);` should work but how do you retrieve circleCoords from initial `L.circle(circleCenter, circleOptions)`?

Actually, I read nothing about this in the Leaflet documentation

I hope I'm a really bad reader, thanks for your enlightments

_Originally posted by @Itemshopp in https://github.com/Leaflet/Leaflet/issue_comments#issuecomment-433458278_

**Comment by ghybs** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features.
For questions on using Leaflet, please use [Stack Overflow](https://stackoverflow.com/questions/tagged/leaflet) or [GIS Stack Exchange](https://gis.stackexchange.com/questions/tagged/leaflet).

If you are _really_ sure that this is a bug in Leaflet, please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

**Comment by ghybs** [comment]
If you want to make a circle-shaped hole in your polygon, you should interpolate the hole with discrete points and supply this array of points as hole ring to your polygon.

**Comment by Itemshopp** [comment]
Thanks a lot for your answer, I thought it was a bug because a similar issue was created 5 years ago and also closed by your leaflet team saying it was implemented [ cfr: https://github.com/Leaflet/Leaflet/issue_comments#issuecomment-433458278 ] but nothing I tried worked.

If you think the best way is to translate the circle in a circle-shaped polygon, then nothing has been implemented about it and I'm sorry for my false issue.

Thanks a lot for your help
