### ISSUE TITLE
Asynchronous adding of layer groups to map doesn't update the layers control

### ISSUE THREAD

**Issue by amwolff** [Leaflet/Leaflet#6400]
## How to reproduce

- Leaflet version I'm using: (latest) 1.3.4
- Browser (with version) I'm using: Safari 12.0 (14606.1.36.1.9) & Chrome 69.0.3497.100
- OS/Platform (with version) I'm using: macOS 10.14

1. Set up dictionary of layer groups
2. Add that dictionary to Control (as in https://leafletjs.com/examples/layers-control/)
3. Asynchronously, programmatically add these layer groups to map

This was _somewhat_ mentioned in #1165, but eventually closed due to inability to reproduce the issue.

## What behaviour I'm expecting and which behaviour I'm seeing

I'm expecting to see all the layer groups checkboxes set and to layers control behave as if they were added manually. In my minimal example the layers control doesn't get updated (checkboxes not set, switching manually after looks fairly strange) - I believe this isn't expected behavior.

## Minimal example reproducing the issue

https://next.plnkr.co/edit/LM8n99LALT1PxOIb

**Comment by ghybs** [comment]
Hi,

What happens is that you use a "dummy" layer added into your Layers Control, that programmatically adds or remove the other actual layers as part of its `"add"` and `"remove"` listeners.

By doing so, you are interfering with the Layers Control sync (actually, it does not sync because it thinks you let it manage the Layers by clicking in one of its inputs, whereas you performed more on your side).

If the "dummy" layer is added programmatically (instead of having the user manually clicking on its checkbox in the Layers Control), the syncinc works as expected:
https://next.plnkr.co/edit/0TD3yBanmdZucmXS

A simple workaround is to use a timeout:
https://next.plnkr.co/edit/zzRVd6I04jlp93TL

Note that the provided default Layers Control targets "simple" use cases.
You might be able to find plugins that provide features more in line with your usage:
[Leaflet plugins > Map interaction > Layer switching controls](https://leafletjs.com/plugins.html#layer-switching-controls)

Or if you have some ideas to improve the default Layers Control, PR is welcome! :smiley:

**Comment by amwolff** [comment]
@ghybs Thank you for the detailed response. Now I think I might have misunderstood the logic of the Layers Control backend. Also thanks for the provided workarounds. 🥇
