### ISSUE TITLE
toBounds function is not working properly

### ISSUE THREAD

**Issue by imudin** [Leaflet/Leaflet#6406]
- I'm reporting a bug, probably asking for help too;

## How to reproduce

- Leaflet version I'm using: 1.3.4
- Browser (with version) I'm using: Chrome and others too
- OS/Platform (with version) I'm using: macOS Movaje 10.14
- Steps:
1. `npm i leaflet -S`
2. `import L from 'leaflet'`
3. `import 'leaflet-path-transform'`
4. created a polygon and added to map by `polygon.addTo(map)`

## What behaviour I'm expecting and which behaviour I'm seeing
throws 
```
'TypeError: Cannot read property 'x' of undefined
   at Bounds.intersects
'
```

I have debugged step by step and I found the `toBounds` function is not working properly.
```
function toBounds(a, b) {
 if (!a || a instanceof Bounds) {
  return a;
 }
 return new Bounds(a, b);
}
```

Here even `a` is valid bounds `a instanceof Bounds` is returning `false` 
and returning `new Bounds(a, b)` which `b` is `undefined`

**Comment by ghybs** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

Please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

Sharing a live reproduction example (e.g. using [Plunker](https://leafletjs.com/edit), [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.io/)) that automatically shows the bug with comments can highly increase the possibility of successful investigation.

Furthermore, if the bug involves another library / plugin, please make sure first that the bug is not due to how that library uses Leaflet; in particular you should file the issue first on their repo.

**Comment by imudin** [comment]
@ghybs It is hard to show this with reproduction example. Yes, you are right, it involves other repo vue2-leaflet. Please refer [this issue](https://github.com/KoRiGaN/Vue2Leaflet/issues/281). As you see , this is giving different leaflet instance when versions are not same.  I still think without this leaflet library support, it will be hard to solve it. Can we do something else instead of `instanceof Bounds`, `instanceof LatLngBounds` or `instanceof LatLng`? Or other wrappers like vue2-leaflet should fix the bug themselves?

**Comment by lordfuoco** [comment]
Chiming here too since I am working on the wrapper.

I don't think is an issue in leaflet itself, and even by removing instanceOf it may create other, even more hidden bugs.
We can continue on the issue in vue2-leaflet I think.

**Comment by boolinlin** [comment]
I also encountered this problem, but not on vue2-leaflet.

My problem is that leaflet is introduced in both project and component, but the two leaflets are different.

**Comment by boolinlin** [comment]
The error message is the same as yours, and this problem is fixed by ensuring that only the same leaflet is introduced into both project and component.

**Comment by lordfuoco** [comment]
@boolinlin you can also be sure by adding a webpack alias and so forcing one single instance of leaflet no matter what.

**Comment by pharaohlxvi** [comment]
We solved this issue by testing if a behaves similar to Bounds by checking if .min and .max exist:

`function toBounds(a, b) {
        if (!a || a instanceof Bounds || (a.min && a.max)) {
                return a;
        }
        return new Bounds(a, b);
}`

I think this is a safe fix, because if a and b are LatLng's, they shouldn't have .min and .max

**Comment by anykeyanykey** [comment]
multiple instances of 'leaflet' in my case
webpack building
