### ISSUE TITLE
Error Attempted to load an infinite number of tiles 

### ISSUE THREAD

**Issue by mikebronner** [Leaflet/Leaflet#6416]
- [X] I'm reporting a bug, not asking for help; support questions like "How can I do X with Leaflet?" will be closed (use [Stack Overflow](http://stackoverflow.com/) or [gis.stackexchange.com](http://gis.stackexchange.com/) for questions)
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behaviour is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

## How to reproduce
- Leaflet version I'm using: 
- Browser (with version) I'm using: Chrome 70.0.3538
- OS/Platform (with version) I'm using: Windows 10
- Unclear how to reproduce this, I am getting bug tracking error logs from users.

```
Error Attempted to load an infinite number of tiles 
    node_modules/leaflet/dist/leaflet-src.js:11116:37 e._update
    node_modules/leaflet/dist/leaflet-src.js:11082 e._onMoveEnd
    node_modules/leaflet/dist/leaflet-src.js:593 e.fire
    node_modules/leaflet/dist/leaflet-src.js:3303 e.panBy
    node_modules/leaflet/dist/leaflet-src.js:4531 e._tryAnimatedPan
    node_modules/leaflet/dist/leaflet-src.js:3181 e.setView
    node_modules/leaflet/dist/leaflet-src.js:3293 e.panTo
    node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1:25596 c.setCenter
    node_modules/vue2-leaflet/dist/vue2-leaflet.min.js:1:1493 c.o.(anonymous function).custom.r.$watch.deep
    node_modules/vue/dist/vue.common.js:3235 Xe.I3G/.Xe.run
```

**Comment by IvanSanchez** [comment]
> Unclear how to reproduce this, I am getting bug tracking error logs from users.

Then we have no idea of what's going on.

**Comment by IvanSanchez** [comment]
Possibly related https://github.com/Leaflet/Leaflet/pull/5477, #5478 and https://github.com/Leaflet/Leaflet/issues/5479 - that very specific error message was added back then.

**Comment by hanneolsen** [comment]
I came accross this issue while googling the exact same error message, I can give some insight into how to trigger it.

The map used to trigger it was straight-forward, just a simple map with a tile layer and markers. I got the error message when setting `map.fitBounds(array)` where `array` only contained one array element of coordinates For example:

This works:
```
map.fitBounds([
    [40.712, -74.227],
    [40.774, -74.125]
]);
```

This will cause `Uncaught Error: Attempted to load an infinite number of tiles`:
```
map.fitBounds([
    [40.712, -74.227]
]);
```

The solution was to use `map.setView` instead of `map.fitBounds` if `array` contained only one item.

**Comment by IvanSanchez** [comment]
> This will cause `Uncaught Error: Attempted to load an infinite number of tiles:`
> ```
> map.fitBounds([
>     [40.712, -74.227]
> ]);
> ```

@hanneolsen No it won't. See https://plnkr.co/edit/jdnUKmxEtgERNMKYerbp?p=preview

**Comment by hanneolsen** [comment]
@IvanSanchez You're right, projection config I used was needed to reproduce it. The plunkr below won't throw the error for some reason, but the same code running in Chrome (version 62) throws it.
https://next.plnkr.co/edit/XwZauqd9OECpkltt?preview

Hope the example makes sense. I'm new to leaflet and map coding in general.

**Comment by ArSn** [comment]
I stumbled over this as well today and after some digging I found that this happens when you assign the `zoom` value to a string that looks like a float (in my case it was) `"13.5"` which was accidentially passed as a string. 

Weird thing though is that THIS zoom (with the string) actually works well, but the next zoom (I am assuming calculating the next zoom level based on that string, `13.6` in my example) then lead to the error. 

Agreed, this was my mistake, and I did not dig deeper than this so I am not entirely sure what leaflet does here, but maybe it could be enforced that no stupid people (like me) are just passing strings?

**Comment by brunoclima** [comment]
This usually happens when you set the view without defining zoom or defining zoom incorrectly

**Comment by msschl** [comment]
I came across the same issue. I get this error on this call:

```js
this._map.flyTo(highlighted.searchResult.coordinates, { animate: true });
```

coordinates is of type `L.LatLng`.

**Comment by igorchernenko92** [comment]
Also bumbed into that problem when using setZoom

**Comment by vlanz** [comment]
I solved this problem on a `.fitBounds(latlng)` call by adding the maximal possible zoom to the options `.fitBounds(latlng, {maxZoom: 28})`. You can find the max zoom by counting the amount of zoom levels you provided when setting up the CRS for the map, e.g in my case:
```
crs = new Proj.CRS(
..., 
{
    resolutions: [4000, 3750, 3500, 3250, 3000, 2750, 2500, 2250, 2000, 1750, 1500, 1250,
      1000, 750, 650, 500, 250, 100, 50, 20, 10, 5, 2.5, 2, 1.5, 1, 0.5, 0.25, 0.1]
...
  })
```

**Comment by dagfs** [comment]
I'm probably working on a problem similar to @hanneolsen with a custom map and projection.

The solution we ended up with was to specify min and max zoom levels when initiating the Leaflet map.
I think this approach is beneficial as it should cover other situations other than the fitbounds case.

`L.map("map", { crs: projection, minZoom: 3, maxZoom: 16 })`

**Comment by grinapo** [comment]
Same happens when you make a typo as
`setView( [47.6127, 18.8871, 14] )`
instead of 
`setView( [47.6127, 18.8871], 14 )`

**Comment by marcuus** [comment]
Yes I got this when I upgraded leaflet to 1.9.2 and vue-leaflet 0.6.1. Thank you dagfs for the solution.

**Comment by Falke-Design** [comment]
We should check this again.

**Comment by aentwist** [comment]
We are using [@vue-leaflet/vue-leaflet](https://www.npmjs.com/package/@vue-leaflet/vue-leaflet) 0.6.1 to interface with leaflet using Vue components. This broke for us between leaflet 1.8 and 1.9. If this case will be helpful in addressing this issue, then I can get a little more specific.

**Comment by Musa-kabeer** [comment]
Please Developers,give a clear give a clear explanation on how to solve this issue.

**Comment by Falke-Design** [comment]
After I digged into this error, it is a pretty clear case. This happens only for custom projected maps. Also it makes no difference which Leaflet version. I tested it down until `1.6.0` - always the same error.

Leaflet tries to get the scale of the zoom, for this it calls the `scale` function of `proj4leaflet-crs` to get the scale of a zoom level for a resolution which is not available. So you need to set the `maxZoom` of the map to the amount of `resolutions - 1` (because of starting with 0).

```
var map = L.map('map', {
	crs: crs(),
	center: [0, 0],
	zoom: 0,
	maxZoom: resolutions.length - 1 // <--------------- This line
});
```

Error: https://plnkr.co/edit/5WaYrCWyEtDEoASH
Fixed: https://plnkr.co/edit/otztxuMrUjSGixdm

**This needs to be fixed in https://github.com/kartena/Proj4Leaflet**! Leafet core is the wrong place to fix this.

**Comment by Notanotherdotcom** [comment]
If anyone comes across this whilst using tiles from Ordnance Survey, the solution seems to be to set the maxZoom of your Leaflet map to 9 - anything higher and you'll encounter this error message.

**Comment by Viktor27081988** [comment]
187 du und deine Kollegen seid alles arsch ficker ! Ich hoffe euch kriegt das C.D.S. Zu packen und filetieren jeden vonEuch die Haut vom Gesicht ! Ihr pisser
                
If anyone comes across this whilst using tiles from Ordnance Survey, the solution seems to be to set the maxZoom of your Leaflet map to 9 - anything higher and you'll encounter this error message.
