### ISSUE TITLE
Touch interactions broken after zooming/panning Openseadragon on the same page

### ISSUE THREAD

**Issue by YorkshireChemist** [Leaflet/Leaflet#6419]
If an Openseadragon image ([https://openseadragon.github.io/](https://openseadragon.github.io/)) is on the same page as a Leaflet map, touch interactions with the Leaflet map get broken after touching the image. This only affects touch devices.
Tested on Chrome (70.0.3538.110) on Moto G4 phone.
Example is at [https://jsbin.com/sobecabati/edit?output](https://jsbin.com/sobecabati/edit?output)
When the page is loaded, Leaflet map can be panned/zoomed with one/two fingers. After touching the image below the map, it becomes impossible to pan the Leaflet map with one finger, as Leaflet thinks that there are two fingers on the map. Touching the image again stops all touch interactions with the map (presumably, Leaflet thinks that there are at least three fingers on the map).
Touch interactions with the rest of the page are OK.

**Comment by cherniavskii** [comment]
It's definitely related to how `DomEvent.Pointer.js` handles pointer events.
Turns out, events coming from openseadragon are stored in `_pointers` object

https://github.com/Leaflet/Leaflet/blob/37cc38648af8c5b3f54829247fc35b565bf2740e/src/dom/DomEvent.Pointer.js#L87-L90

and they're not removed from there (maybe openseadragon stops events propagation or something).

https://github.com/Leaflet/Leaflet/blob/37cc38648af8c5b3f54829247fc35b565bf2740e/src/dom/DomEvent.Pointer.js#L98-L101

Since `Draggable` checks `event.touches` length and there's a lot of touches coming from openseadragon, at some point map stops dragging

https://github.com/Leaflet/Leaflet/blob/37cc38648af8c5b3f54829247fc35b565bf2740e/src/dom/Draggable.js#L127-L138

I'm not sure which side should fix that.
Also, it's easy to break something in `DomEvent.Pointer`, since it fixes IE pointer events issues.

One thing that came to my mind is to check the `target` of pointer event before storing it in `_pointers` object, and store it only if it's not outside of map container.
But note, that I'm not sure that I understand properly how `DomEvent.Pointer.js` works.

**Comment by YorkshireChemist** [comment]
@cherniavskii is absolutely right. Changing  `_globalPointerDown` to the following works without any noticeable side effects on my phone (Chrome 71.0.3578.99 on Moto G4):
```
function _globalPointerDown(e) {
	if (e.target._leaflet_id) {
	    _pointers[e.pointerId] = e;
	    _pointersCount++;
	}
}
```
However I have not tested widely; I don't know how `DomEvent.Pointer.js` works and so it will take someone knowledgeable to make this into a proper solution!

I think Leaflet should fix this issue as it could be caused by any other rogue script on the same page, not just openseadragon.

I think checking just the target of the pointer down event and not that of the pointer up event is the right thing to do. In other words, Leaflet should register all pointer up events even if the target is not the map, but it should register pointer down events only if they originate on the map.

**Comment by johnd0e** [comment]
The issue is not reproduced in 1.6.0
https://jsbin.com/vazegom/edit?output
