### ISSUE TITLE
Add support for HDPI, XHDPI... displays

### ISSUE THREAD

**Issue by zdila** [Leaflet/Leaflet#6449]
Currently Leaflet supports retina displays, which is something like MDPI and uses 2x scaling. Nowadays mobile displays are even more dense. Setting `detectRetina: true` makes the map sharper, but it is still slightly blurred on HDPI, XHDPI, XXHDPI etc displays.

Please see attached images. One is from Locus where HDPI is used (3x) and the other is from webapp using Leaflet with `detectRetina: true` (2x). Please zoom them to 100% before comparing to see the difference because browser scales them down on this page.

Leaflet:
![leaflet](https://user-images.githubusercontent.com/636095/50546061-bb756d80-0c21-11e9-98ed-a50187debf89.png)

Locus:
![locus](https://user-images.githubusercontent.com/636095/50546062-bb756d80-0c21-11e9-84e8-ce2dc0b57e42.png)

**Comment by zdila** [comment]
@cherniavskii what should the example contain? Layer with `detectRetina: true` and TMS URL with HDPI (3x) map?

**Comment by cherniavskii** [comment]
@zdila basically it should allow us to reproduce the issue by simply opening the link, while being as simple as possible

**Comment by zdila** [comment]
https://next.plnkr.co/edit/DMfyuQdwaWrVfeRH

Please open it on mobile with HDPI (or denser) display, make a screenshot and view it on regular PC screen with scaling 1:1.

For getting tiles for higher DPI please update number `2` to eg `3` in the following link: http://tiles-ng.freemap.sk/scaled/2/{z}/{x}/{y}
Please note that such tiles are now rendered on the fly.

**Comment by cherniavskii** [comment]
Thanks Martin!

`detectRetina` is `TileLayer` option, not a `Map` option:

```diff
var map = new L.Map('leaflet', {
	layers: [
		new L.TileLayer(
			L.Browser.retina
      ? 'http://tiles-ng.freemap.sk/scaled/2/{z}/{x}/{y}'
      : 'http://tiles-ng.freemap.sk/{z}/{x}/{y}', {
			'attribution': 'Map data © <a href="http://openstreetmap.org">OpenStreetMap</a> contributors',
+                        detectRetina: true,
		}),
	],
	center: [48.948886, 21.429133],
	zoom: 14,
-	detectRetina: true,
});
```

Make sure you're using it properly.
Here's working example: https://next.plnkr.co/edit/rDJaKo6Ay2j8XVOd

**Comment by zdila** [comment]
Yes, my bad. I'll update the plunk soon.

**Comment by cherniavskii** [comment]
@zdila with `detectRetina` used properly, is there still an issue?

**Comment by zdila** [comment]
@cherniavskii yes, it is. Please see this picture zoomed @ 100%. It is slightly blurred.

![screenshot_2018-12-30-16-50-14-182_com android chrome](https://user-images.githubusercontent.com/636095/50548806-3dca5580-0c53-11e9-805c-9edaf489bd9a.png)

**Comment by zdila** [comment]
I would propose to keep `detectRetina` option just for backward compatibility but introduce a new parameter like `tileScale` which could contain arbitrary number. API user would be responsible for providing it - eg. by using `window.devicePixelRatio` combned with availability of scales for tiles he would like to serve. I can try to implement it and create a pull request if you like.

**Comment by zdila** [comment]
I was able to modify Leaflet to support scale of 2, 4, 8, ... In case of 3 I was unable to conpute `zoomOffset`. Still Locus is able to support such scale. See attached file which should be unzipped and put to `/CARD_ROOT/Locus/mapsOnline/custom/fm.xml`. Docs for Locus: http://docs.locusmap.eu/doku.php?id=manual:advanced:customization:online_maps

**Comment by cherniavskii** [comment]
I'm not familiar with Locus, but let's keep that aside for a while.

---

`detectRetina` option is a "hack".
The only use case for it that comes to my mind is situation, where you're dealing with tile provider, which  doesn't serve larger tiles. `detectRetina` will definitely make your map look sharper. But it has a downside - all labels and icons are significantly smaller, which is not cool.

---

On the other hand, if tile provider can serve bigger tiles - it's even better.
Most of tile providers that serve bigger (e.g. 512x512px) tiles follow the convention: `{z}/{x}/{y}{r}.png`.
Where `{r}` is tile resolution ratio (not sure if it's called that way, but that's how I understand this) - e.g `@2x`. Regular tiles have 256x256px resolution, `@2x` - 512x512px and so on.
In this case the only change developer should do is:

```diff
new L.TileLayer(
-  'https://tile.provider.url/{z}/{x}/{y}.png',
+  'https://tile.provider.url/{z}/{x}/{y}{r}.png',
}),
```
Leaflet does support `{r}` param - see [TileLayer url template docs](https://leafletjs.com/reference-1.3.4.html#tilelayer). Here's the corresponding Leaflet code that handles that:

https://github.com/Leaflet/Leaflet/blob/5c9bb5abe800ff6bbfa34f2e16eb36479e5308b6/src/layer/tile/TileLayer.js#L169-L176

Until this point everything works fine.

---

If I understand correctly, what you are trying to do is to use `@3x` or higher scale instead of `@2x`.
In order to achieve that, your tiles provider should serve larger tiles. `@2x` generates 512x512px tiles, therefore `@3x` should generate 768x768px tiles.

Assuming tile provider serves `@3x` tiles, it's possible to use them like this:

```js
new L.TileLayer(
  'https://tile.provider.url/{z}/{x}/{y}{r}.png',
  r: Browser.retina ? '@3x' : '',
}),
```

And this will work as well.
Working example: https://next.plnkr.co/edit/Hs4wThtMWzJWVkOS

---

Note that your tile provider:
1. Doesn't follow `{r}` convention, which is not a big deal - we can still handle it:

```js
new L.TileLayer(
  'https://tile.provider.url/scaled/{r}/{z}/{x}/{y}.png',
  r: '2',
}),
```
2. Tiles from `scaled/1` and `scaled/2` have the same size.
I assume that's the root of the issue you're struggling with, but IMO Leaflet has nothing to do with that.


This is how I see it, please correct me if I'm missing something.

**Comment by zdila** [comment]
@cherniavskii Thanks for your exhausting analysis. I'll try to update the tileserver to provide larger tiles and close this issue if it works.

**Comment by cherniavskii** [comment]
Also note, that it is possible to combine `detectRetina` *and* larger ratio tiles.

**Comment by cherniavskii** [comment]
@zdila I'm closing it for now, feel free to reopen if necessary
