### ISSUE TITLE
geoJSON layer accepts invalid polygon object

### ISSUE THREAD

**Issue by ka7eh** [Leaflet/Leaflet#6494]
**Expected behavior**
A geojson polygon feature with less than 4 coordinates must raise error.

**Current behavior**
Leaflet accepts such feature as a valid geojson object.

**Environment**
- Leaflet version: 1.4.0
- Browser (with version): N/A
- OS/Platform (with version): N/A

**Additional context**
A geojson polygon feature must have at least four coordinates, and the first and last items in the coordinates list must be the same. So the following object is considered invalid:
```json
{
  "type": "Polygon",
  "coordinates": [[[-0.5, -0.5], [0.5, 0.5], [-0.5, -0.5]]]
}
```
But leaflet treats it as a valid object.

**Minimal example reproducing the issue**
See `scripts.js` in the this example: https://plnkr.co/edit/IpLcBvzV2D1akpzlKiA5?p=preview

**Comment by ronikar** [comment]
I looked at the code, the current behavior occurs because `L.Polygon` allows you to pass polygon with 3 points. There is a comment in the code: 
``` javascript
 Note that points you pass when creating a polygon shouldn't have an additional last point equal to the first one — it's better to filter out such points.
```
I agree with you and think `geoJSON layer` should raise error if geojson is invalid. 
I don't really know how to check if geoJson is valid, so if someone can add references it will be nice.

**Comment by ronikar** [comment]
I looked at the code, the current behavior occurs because `L.Polygon` allows you to pass polygon with 3 points. There is a comment in the code: 
``` javascript
 * Note that points you pass when creating a polygon shouldn't have an additional last point equal to the first one — it's better to filter out such points.
```
I agree with you and think `geoJSON layer` should raise error if geojson is invalid. 
I don't really know how to check if geoJson is valid, so if someone can add references it will be nice.

**Comment by IvanSanchez** [comment]
Closing because https://github.com/Leaflet/Leaflet/pull/6507#issuecomment-462133506
