### ISSUE TITLE
Map tiles out of order/too many

### ISSUE THREAD

**Issue by Beauyoung** [Leaflet/Leaflet#6503]
Hello all! I'm fairly new to JS, and leaflet all together. I started putting together a map based on GTA V, and using leaflet to do it, with Google API implementation. It loads the map and markers and layers all fine, but to the side of it, randomly left or right, it adds extra tiles all out of order, so it's not quite like the wrapped or continuous world. In the link below is a snippet I took of it. the 2 bits on the left are reversed, out of order, and the more I zoom in that area, the worse it gets, but the map on the right is fine, and stays fine through any zoom level. Any help would be greatly appreciated.

![](https://i.imgur.com/2ORGkM6.jpg)

**Comment by nr072** [comment]
Could you kindly provide your code?

**Comment by Beauyoung** [comment]
Absolutely, the site the map is located at is bythebry.com/map.html. Code is linked.

map.html: https://pastebin.com/nejs4W7n
leaflet.css: https://pastebin.com/p9pAfBYx
leaflet.js: https://pastebin.com/nYjAyMZC

**Comment by nr072** [comment]
@Beauyoung
 
It is better (and a very good practice) not to provide the entire source code. The best way way is to find out the part that is creating the problem and provide only that (n a stripped-down manner).

Do you think you can isolate the specific part of Leaflet that is creating the problem? (Maybe it is the creating of a tile layer, or maybe Leaflet Search is causing it.) You may then be able to identify the cause and solve the problem by yourself. If the problem still remains, I will be happy to be able to help.

**Comment by IvanSanchez** [comment]
Yeah, this is a simple case of Leaflet requesting tiles with negative tile coordinates, and the webserver replying with a `HTTP 301` redirect, similar to [this case](https://stackoverflow.com/questions/50156462/leaflet-and-shifted-tiles-when-loading-from-a-server-and-not-local/50157594).

Use the `bounds` option of `L.TileLayer` so that Leaflet will request tiles withing the given box.

Also, I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["http://www.chiark.greenend.org.uk/~sgtatham/bugs.html"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html). It will improve your bug-reporting skills.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
