### ISSUE TITLE
Custom HTML popups

### ISSUE THREAD

**Issue by mikkelbfriis** [Leaflet/Leaflet#6566]
**Is your feature request related to a problem? Please describe.**
I find it annoying, that Leaflet is a good alternative to Google Maps, however I'm kind-of getting the feeling that it's missing a "custom html popup feature"

**Describe the solution you'd like**
I want to be able to add my own custom popup-html.

**Describe alternatives you've considered**
Injecting straight into to the dom, to replace the popup

**Comment by IvanSanchez** [comment]
There's https://leafletjs.com/reference-1.4.0.html#popup-setcontent already. If that's not enough, I suggest having a look at https://leafletjs.com/plugins.html#search--popups , so you can see how other people make Leaflet plugins for more customized popups.

**Comment by mikkelbfriis** [comment]
The idea of this was to be able to replace the entire default popup HTML, not just the content

**Comment by IvanSanchez** [comment]
Then I think you should look into extending `DivOverlay` (which is the base for both tooltips and popups) to suit your needs.

I don't think we want to offer a border-less `DivOverlay` at this point, as that would confuse users when it comes to positioning. Otherwise we're looking at https://github.com/Leaflet/Leaflet/issues/4259
