### ISSUE TITLE
Android 4.1.2 API Webview not loading map

### ISSUE THREAD

**Issue by VCodepp** [Leaflet/Leaflet#6575]
I added  "window.L_DISABLE_3D = true;" before leaflet.js
only the area with the map does not work.

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.

**Comment by VCodepp** [comment]
I revise the question and open it again.
