### ISSUE TITLE
dasdasdas

### ISSUE THREAD

**Issue by freedomchensir** [Leaflet/Leaflet#6600]
--------------^ Click "Preview" tab for a nicer view!

We use GitHub as an issue tracker.
For usage and support questions, please check out resources below:

1. Read Leaflet documentation: https://leafletjs.com
2. For support questions like "How can I do X with Leaflet?" please search or ask questions on StackOverflow or StackExchange using Leaflet tag:
  - https://stackoverflow.com/questions/tagged/leaflet
  - https://gis.stackexchange.com/questions/tagged/leaflet

Thanks!

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
