### ISSUE TITLE
emergency ！！！

### ISSUE THREAD

**Issue by yangyang158** [Leaflet/Leaflet#6687]
1.Can be integrated into WeChat small programs?
2.Do you have an offline download interface?

**Comment by mindfocus** [comment]
1.  一点也不emergency
2.  npm了解一下？

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
