### ISSUE TITLE
Click events don’t work in the shadow DOM on iOS

### ISSUE THREAD

**Issue by remcohaszing** [Leaflet/Leaflet#6705]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**

- Create a shadow root.
- Append the leaflet CSS to the shadow root.
- Create a node for Leaflet.
- Attach a map to the node.
- Add a click handler to the map.
- Append the node to the shadow root.

**Expected behavior**

The click handler is triggered

**Current behavior**

The click handler isn’t triggered when using Safari (or Chrome) on iOS.

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Safari
- OS/Platform (with version): iOS 10.3.1

**Additional context**

It works as expected in Chrome on desktop, Safari on desktop, and Chrome on Android.

**Minimal example reproducing the issue**

https://next.plnkr.co/edit/9WB2YBaVIWv4nQgv

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
And I assume that other DOM events are fired by the shadow DOM elements? Is `L.DomEvent.on` behaviour as expected, or failing?

**Comment by remcohaszing** [comment]
The following code works as expected:

```js
const root = document.createElement('div');
document.body.appendChild(root);
const shadowRoot = root.attachShadow();
const node = document.createElement('div');
node.style.width = '300px';
node.style.height = '300px';
node.style.backgroundColor = 'blue';
L.DomEvent.on(node, 'click', () => {
  node.style.backgroundColor = node.style.backgroundColor === 'blue' ? 'red' : 'blue';
});
shadowRoot.appendChild(root);
```

**Comment by zmullett** [comment]
I've also observed this. It works as expected on desktop Chrome/Safari, as well as Android Chrome, but not working as expected on iOS 12.4 using Chrome 75.0.3770.103 and Leaflet 1.5.1. I've observed that the event is indeed dispatched from within map/handler/Map.Tap.js, but does not arrive when observed using L.Map.on().

@remcohaszing did you find the root cause or a workaround?

**Comment by remcohaszing** [comment]
No, unfortunately not. If I do, I’ll report back here.

**Comment by zmullett** [comment]
Pull request https://github.com/Leaflet/Leaflet/pull/6788 resolves the issue for me at least.

For posterity: Prior to this I investigated whether it was possible to polyfill the [PointerEvent](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent) feature missing on iOS using [pepjs](https://www.npmjs.com/package/pepjs), but this led to undesired behavior (map scrolling/zooming stopped working).

**Comment by IvanSanchez** [comment]
As per #6972, this seems to be reproducible in Chrome 79 for Android as well.

**Comment by RuarriS** [comment]
My workaround was to disable tap altogether
`
        if (mymap.tap) {
            mymap.tap.disable();
        }
`

**Comment by remcohaszing** [comment]
We have been noticing the same issue in Chrome for Android and the emulated mobile mode for Chrome on Desktop since we bumped leaflet from 1.5.1 to 1.6.0.

**Comment by Riwaz** [comment]
Hi, we have bumped into this issue as well and the cause is that Leaflet's Tap handler is listening for `touchstart`/`touchend` on `document` where the event bubbles after shadow DOM retargeting (i.e. `event.target` is not the original target). Not sure if this was obvious to everyone from the discussion above...

* event registration - https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.Tap.js#L82
* incorrect target extraction - https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.Tap.js#L90
* simulating click on incorrect element - https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.Tap.js#L96

If you are not using context menus it is pretty safe for you to disable Tap handler using map option `{ tap: false }`.

**Comment by johnd0e** [comment]
`tap` handler is legacy. It breaks many things.
See #7026.
