### ISSUE TITLE
Clicking on label of leaflet-control-layers does not work

### ISSUE THREAD

**Issue by khryniewiecki** [Leaflet/Leaflet#6713]
var version = "1.5.1+HEAD.2e3e0ff";

**leaflet-src.js line 5218**
There is: _on(input, 'click', this._onInputClick, this);_
Should be: _on(input, 'change', this._onInputClick, this);_

**Comment by ghybs** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

Please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

The Layers Control behaves as expected on my Chrome, i.e. layer is switched on/off when clicking on the label instead of the radio/checkbox. Typically testing on Leaflet tutorial page for Layers Control https://leafletjs.com/examples/layers-control/

What OS and browser have you tested on please?

**Comment by johnd0e** [comment]
Close due to lack of feedback
