### ISSUE TITLE
fitBounds() is not working for large number of leaflets

### ISSUE THREAD

**Issue by vigneshb17** [Leaflet/Leaflet#6767]
If I set a fitBounds() for more than 100 leaflets . I used a ajax loader to set fitBounds in my mapbox . After completing ajax loader , my mapbox is set to default image of mapbox . I doesn't set fitBounds for leaflets. Afterwards , I set a maxBounds for leaflets . It is working but It displays random dimension in mapbox . It doesn't cover all leaflet's location

Mycode: (in coffee.erb)
setFitbounds = ->
  group = L.featureGroup(incidentMarkerLayers)
  window.map.fitBounds group.getBounds()

Code Definition:
         incidentMarkerLayers is an array which contains all leaflets latitude and longitude

My leaflet version :
v-1.0.0

**Comment by ghybs** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

Please provide a [more effective bug report](https://www.chiark.greenend.org.uk/~sgtatham/bugs.html), and in particular all the information requested in the issue template (provided when you create a new issue), so that we can effectively investigate and hopefully resolve it.

Sharing a live reproduction example (e.g. using https://leafletjs.com/edit) that automatically shows the bug with comments can highly increase the possibility of successful investigation.

You can also add annotated screenshots, sketches, animated captures, etc.

**Comment by vigneshb17** [comment]
Thanks for the reply, that issue was resolved.
