### ISSUE TITLE
tooltip binded to polygon disappear when zoom in or zoom out

### ISSUE THREAD

**Issue by spade69** [Leaflet/Leaflet#6779]
**Steps to reproduce**
-  Bind tooltip to polygon and zoom in. I'm attaching jsfiddle examples.
-  bind tooltip to an existing leaflet map object, and call polygon's openTooltip() method.
- and i pass tooltip option like that: 
```
      tooltipOption: {
        opacity: 0.9,
        offset: [5, 5],
        sticky: true,
        permanent: true,
      },
```

**Expected behavior**
tooltip should occur at the map, and keeping open when zoom in or zoom out.

**Current behavior**
tooltip disappear when zoom in or zoom out

**Environment**
- Leaflet version: 1.5.1
- Browser (with version):  Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- OS/Platform (with version):  Mac OS Mojave Version 14.14

**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.
``

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code

**Comment by akkana** [comment]
I'm having this problem too. I have a map that has lots of irregular polygons (voting district boundaries), and if you zoom in to a specific area, like to find the area you live, the tooltip is now offscreen so you can't see what district you're in.

Small example: http://shallowsky.com/javascript/leaflet/leaflettooltip.html

I've tried to work around this by using a popup rather than a tooltip, thinking that I could calculate the popup coordinates, check whether they were onscreen, and if not, use the mouse coordinates instead; but I haven't been able to find a way to position a popup so that it's over the polygon, the way the tooltip is. e.target.getBounds().getCenter() may be outside the polygon (as in the polygon in the example). The tooltip does a good job of choosing coordinates near the center of the polygon, but still inside the polygon -- except it fails if that near-center point is off screen. Is there a way to get that near-center coordinate that the tooltip uses and check whether it's off screen?

**Comment by johnd0e** [comment]
@akkana
It looks like completely different problem.
You better open separate issue for it.

**Comment by akkana** [comment]
Okay, filed issue 7040.

**Comment by johnd0e** [comment]
@spade69 

Unable to reproduce.
