### ISSUE TITLE
Memory leak with vectorGrid layer interactive mode enabled

### ISSUE THREAD

**Issue by enorvaisa** [Leaflet/Leaflet#6814]
**Steps to reproduce**

- navigate to https://jsfiddle.net/evaldas_norvaisa/fm87d9re/19/ (simple project which loads only vector layer)
- zoom in/out map at least 10 times
- check memory consumption with task manager or performance tool

**Expected behavior**
Recovered memory after GC using interactive:true mode

**Current behavior**
After 25 times zoom in+zoom out:

Memory consumption with interactive:true
![interactive](https://user-images.githubusercontent.com/39566746/65328072-1a1eb500-dbbe-11e9-8ab9-26b0ad1fffa5.png)

Memory consumption with interactive:false
![noninteractive](https://user-images.githubusercontent.com/39566746/65328164-5a7e3300-dbbe-11e9-8a9b-43807d1dd77e.png)

**Environment**

- Leaflet version: 1.5.1
- Browser (with version): Chrome 76.0.3809.132 
- OS/Platform (with version): Windows 10

**Comment by perliedman** [comment]
Hi,

this sounds like an issue with Leaflet.VectorGrid, not Leaflet itself, since GC looks ok unless you enable this specific feature in VectorGrid. You should open an issue for VectorGrid. (Although I am sorry to say it is not really maintained at the moment, so be prepared to do some work if you need this addressed.)

Closing, but feel free to give more details if you think this is a Leaflet issue.
