### ISSUE TITLE
Leaflet-routing-machine

### ISSUE THREAD

**Issue by skn-hyn** [Leaflet/Leaflet#6831]
**Hello !**
I use _Leaflet_ library with _Angular 7_ (typeScript) for the first time,
for `leaflet routing machine`, I use this block of code, I have this error have you any idea ? :

 
component.ts :
```
L.Routing.control({
      waypoints: [L.latLng(48.8534, 2.3488), L.latLng(44.837789, -0.57918),],
      routeWhileDragging: true,
      show: true,
      language: 'fr',
      geocoder: L.Control.Geocoder.nominatim(),
      autoRoute: true
    }).addTo(this.mapInstance);
```

![Capture](https://user-images.githubusercontent.com/33116806/66061153-c9507a00-e536-11e9-9189-7f422cbb9181.PNG)

**Comment by perliedman** [comment]
Hi, this is clearly not a Leaflet issue.

Please open an issue with Leaflet Rounting Machine. But also, since I am a maintainer of that plugin, please provide some more information on what you think the issue is: just a short piece of code together with a screenshot of a stacktrace is very hard to do something with.
