### ISSUE TITLE
Circle below new tile if using setLatLng on move event

### ISSUE THREAD

**Issue by christianvoigt** [Leaflet/Leaflet#6833]
- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- Add a circle to a Leaflet map
- Add a move listener and reset circle position to current map center
- Use the mouse to drag the map in any direction until new tiles are loaded. Move the new tiles to the center of the map without releasing the mouse button.

**Expected behavior**

The circle should always stay on top of any new tiles loaded during panning.

**Current behavior**

The circle will be below any new tiles. Only on releasing the mouse button (on moveend) will it be on top of the tiles again.

**Environment**
- Leaflet version: 1.5.1
- Browser (with version): Chrome Version 77.0.3865.90
- OS/Platform (with version): Windows 10

**Minimal example reproducing the issue**

https://jsfiddle.net/1pxsolidblack/4w7y1j9p/1/

- [x] this example is as simple as possible
- [x] this example does not rely on any third party code

**Comment by ghybs** [comment]
Hi,

Thank you for the detailed issue and reproduction example!

This seems not due to new tiles, but "just" the clipping of vector layers outside viewport during drag.
You have the same behaviour when removing the Tile Layer from your example:
https://jsfiddle.net/jhvpfzkr/

See explanations in issue #2814

=> you can decrease the probability of this effect being visible by instantiating your map with a renderer with increased [padding](https://leafletjs.com/reference-1.5.0.html#renderer-padding) option (you my need to upggrade to Leaflet 1+)
