### ISSUE TITLE
Lower z-index values

### ISSUE THREAD

**Issue by hugo-dlb** [Leaflet/Leaflet#6911]
**Is your feature request related to a problem? Please describe.**
Leaflet uses z-index values that are extremely high by default (500-1000).
This means in any application, if you want to display something over leaflet (like a dialog), you need to set a z-index higher than 1000, this is not ideal.
The user does not want to have leaflet at the top of all other elements.

**Describe the solution you'd like**
Lower the values of Leaflet z-index usage.
e.g:
1000 becomes 100 or 10.
500 becomes 50 or 5.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Example of the issue:
https://i.imgur.com/xNkGz0v.png
In this screenshot, leaflet appears over a modal/dialog and its backdrop because the z-index of leaflet is set to 1000.

**Comment by IvanSanchez** [comment]
No; the approach then is to set a `z-index` in the map's container, in order to keep track of the different [stacking contexts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). The z-index values of the map panes inside the stacking context of a map container are independent of the z-index values of the map container itself in an outer stacking context.

**Comment by hugo-dlb** [comment]
Thanks @IvanSanchez , I did not know about the stacking context.
My bad! Everything works fine with your approach.
