### ISSUE TITLE
Rendering artifacts with polygons

### ISSUE THREAD

**Issue by scMarth** [Leaflet/Leaflet#6945]
When I try to add polygon data that uses the WGS84 reference system, I am seeing some rendering artifacts if I don't use outlines. (I make the outlines opacity 0).

This problem shows up on Chrome, Firefox, and Edge.

Here is what the map looks like:

![Leaflet-artifacts](https://user-images.githubusercontent.com/22603557/71125765-6ddc7280-219c-11ea-80f8-71a798463aa5.png)

As you zoom in, some of them start to disappear:

![Leaflet-artifacts2](https://user-images.githubusercontent.com/22603557/71125840-906e8b80-219c-11ea-97d3-ac2dde229cd0.png)

If you zoom in enough, they will disappear.

For reference, I have tried mapping the same data using ArcGIS Javascript:

![Esri-artifacts](https://user-images.githubusercontent.com/22603557/71125925-b98f1c00-219c-11ea-8af1-e3f95f571539.png)

- [x] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [x] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce / Minimal example reproducing the issue**
I have created some sample projects that pull from the same polygon data:

ArcGIS Javascript: https://jsfiddle.net/sdMarth/bu2przoh/1/
Leaflet: https://jsfiddle.net/sdMarth/tjm76ors/2/

**Expected behavior**

I expected the rendering to be more consistent with different zoom levels.

**Current behavior**

There are many rendering artifacts, but they go away if you zoom in close enough.

**Environment**
- Leaflet version: 1.6.0
- Browser (with version): Chrome Version 79.0.3945.79 (Official Build) (64-bit), Firefox 67.0.2 (64-bit), Microsoft Edge build 18362
- OS/Platform (with version): tested on Windows 10, Fedora 31

**Comment by IvanSanchez** [comment]
Ah, the good ol' artefacts of [antialias gamma](https://github.com/mapnik/mapnik/wiki/PolygonSymbolizer).Not much can be done about it, though.

Ultimately this is caused by the way browsers render SVG graphics (via `L.SVG`) or `<canvas>` paths (via `L.Canvas`). I'm assuming that arcgisjs is using some form of WebGL renderer (which treats subpixel rendering/antialias and compositing in a whole different way). With [multisampling subpixel rendering](https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing) for the vector edges, there is no need for *one-minus-destination-alpha* per-pixel compositing, so the artefacts tend to go away. There were attempts at a Leaflet WebGL vector renderer, but those have been [abandoned](https://github.com/IvanSanchez/Leaflet.gl) ever since.

A very hacky work-around is to disable antialiasing altogether on SVG with the [`shape-rendering` CSS attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering), by doing something like this and then triggering a re-render by panning the map:

```
var renderer = L.svg();

var mymap = L.map('mapid', {
  crs: L.CRS.EPSG4326,
  renderer: renderer
}).setView([36.6777372, -121.6555013], 13);

setTimeout(function(){
	renderer._container.style.shapeRendering = 'crispEdges';
  console.log(renderer._container);
}, 500);
```

I'm afraid this is a limitation of how browsers do SVG and `<canvas>`, and since antialias behaviour can't be tweaked further, there is no way to fix it. (Short of putting hours of work back into a WebGL vector renderer for Leaflet).
