### ISSUE TITLE
Accessibility issue with the layers menu

### ISSUE THREAD

**Issue by cbayerlein** [Leaflet/Leaflet#6946]
Describe the bug
As a physically disabled user and developer I have an accessibility issue with the overlay menu (in the top right corner of the map). The menu automatically closes when I move the mouse 'wrongly'. I don't know what is exactly causing the menu to close. I use assistive technology (speech recognition) to control the mouse pointer, thus it's not so easy to move the pointer smootly. Can I somewhere change the JS to make the menu stay open until I explicitly close it (e. g. by clicking outside)?

To Reproduce
Hower mouse over overlay menu to open it. Move mouse. At some stage, the menu will close by itself.

Expected behavior
Menu should stay open until manually closed.

System Information

Webapp frontend on Chrome.

**Comment by IvanSanchez** [comment]
I think you're referring to `L.Control.Layers`, detailed in [its own tutorial](https://leafletjs.com/examples/layers-control/).

Developers using Leaflet can set the [`collapsed` option of `L.Control.Layers`](https://leafletjs.com/reference-1.6.0.html#control-layers-collapsed) to control the behaviour. In particular, something like...

```js
var layersControl = L.control.layers(
  baseLayers,
  overlayLayers,
  { collapsed: false }
);
```

...will make the layers control "stay on" forever. Developers are always free to use a [different method of displaying layer switchers using plugins](https://leafletjs.com/plugins.html#layer-switching-controls).

Having a third behaviour for the collapsable layers control (clicking outside instead of just hovering outside) is interesting. Maybe you might want to create a separate feature request for that, keeping in mind the new information explained here?

In regards to accessibility, please keep in mind that the default collapsible `L.Control.Layers` can be navigated via keyboard: tab-focus on the collapsed layers control, then enter, then tab-focus on the set of radio boxes or on the checkboxes. While I would agree that adding an invisible buffer around the controls to prevent `mouseout`s and help with inaccurate clicks would be nice, it would make the behaviour of some plugins (toolbars, etc) inconsistent (and since the controls are navigable via keyboard, I think it's not urgent to spend effort on that).
