### ISSUE TITLE
The first click will not trigger the mouse down event in chrome

### ISSUE THREAD

**Issue by mingio** [Leaflet/Leaflet#7007]
I make a little modified on the example: [crs-simple](https://leafletjs.com/examples/crs-simple/crs-simple-example1.html). 

I add a rectangle on a map. And there is a mousedown event listening on the rectangle. I add the options to map: renderer: L.canvas() and preferCanvas: true.

After I drag and drop the map, when I first click the Rectangle nothing happens. When I click the rectangle second time, the mousedown event is fired. But the first click should fire mousedown event also.

After I comment out the following lines, the program works.
```
renderer: L.canvas()
preferCanvas: true
```

Chrome  73.0.3683.86 x64
Leaflet: 1.6

Here is the code: 

```
<script>
    var map = L.map('map', {
        crs: L.CRS.Simple,
        renderer: L.canvas(),                                                      
        preferCanvas: true,  
    });

    var bounds = [[0,0], [1000,1000]];
    var image = L.imageOverlay('https://leafletjs.com/examples/crs-simple/uqm_map_full.png', bounds).addTo(map);

    map.fitBounds(bounds);

    // define rectangle geographical bounds
    var bounds = [[500, 500], [750, 750]];
    // create an orange rectangle
    var device = L.rectangle(bounds, {color: "#ff7800", weight: 1, fillOpacity:1}).addTo(map);

    function onDeviceMouseDown(e) {
        alert("You clicked the map at " + e.latlng);
    }

    device.on('mousedown', onDeviceMouseDown);
</script>

```

**Comment by johnd0e** [comment]
Try it online https://output.jsbin.com/dileyuy

Not reproduced with touch (with dev tools in desktop Chrome)

**Comment by johnd0e** [comment]
Click handled here:
https://github.com/Leaflet/Leaflet/blob/d843c3b88486713827d7e860b58bdba75bfbd5a2/src/layer/vector/Canvas.js#L351

And on first click after drag `this._map._draggableMoved(layer)` is `true`, that's why we miss first click.

I will try to find out what's going on in `_draggableMoved`

**Comment by johnd0e** [comment]
https://github.com/Leaflet/Leaflet/blob/d843c3b88486713827d7e860b58bdba75bfbd5a2/src/dom/Draggable.js#L87-L95

Here is sort of race condition: this handler is executed too late, because it is propagated event.
Perhaps simplest solution would be subscribing to capture phase.
But it appears not so simple, as we do not have 'capture' argument in leaflet api: https://leafletjs.com/reference-1.6.0.html#domevent

Not a big issue, as we can use `addEventListener` directly: it should be [available](https://caniuse.com/#feat=addeventlistener) from IE 9.
and Canvas is also [available](https://caniuse.com/#feat=canvas-text) from IE 9

**Comment by johnd0e** [comment]
The issue is not reproduced with current `master`.

**Comment by johnd0e** [comment]
Ok, with touch enabled the bug is not reproduced, but I found that it's just a matter of coincident: 2 different bugs neutralized each other.

1. When `Browser.touch` and `Browser.pointer` both are `true`, our `touchstart` handlers in fact listens for `pointerdown`event.
   It is bug: #7058.
   https://github.com/Leaflet/Leaflet/blob/d843c3b88486713827d7e860b58bdba75bfbd5a2/src/dom/Draggable.js#L24
   It is bug: in result, for every single mouse down our handler process both events: 1. pointer 2. mouse. Same for mouse up.

2. `_onClick` in Canvas is listen for `mouseup` (may be this is wrong too, as our intention is handle 'click').
   But pointer event come first, so code `_onUp` in `Draggable` is processed earlier, and all works fine.

So to really get rid of the bug we need fix race condition.

**Comment by mingio** [comment]
Your support is greatly appreciated.
