### ISSUE TITLE
If popper.js was loaded, a maximum call stack size exceeded error occurs

### ISSUE THREAD

**Issue by HeyJude1** [Leaflet/Leaflet#7127]
When popper.js is loaded together with leaflet.js, a `maximum call stack size exceeded` error occurs. 

Is it Leaflet's or popper's "fault"? 
What should be done to solve it?

**How to reproduce ([demo](http://jsfiddle.net/eht3vcqp/))**  

**html**
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/cjs/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.js"></script>
<link rel="stylesheet" href ="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.6.0/leaflet.css" />
<div id="map" style="height: 500px; width: 80%;"></div>
```
**js**
```
var osm = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png');
var map = L.map('map').setView([51.505, -0.09], 13).addLayer(osm);
```
**console output**
```
Uncaught RangeError: Maximum call stack size exceeded
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
    at getComputedStyle (popper.min.js:1)
```

**Comment by mondeja** [comment]
You are loading a CommonJS module of `popper.js` and CommonJS will not work in the browser. Replace `https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/cjs/popper.min.js` for `https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/umd/popper.min.js` resource url and will work.

**Comment by HeyJude1** [comment]
@mondeja, absolutely right, thanks!

**Comment by hadynz** [comment]
> You are loading a CommonJS module of `popper.js` and CommonJS will not work in the browser. Replace `https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/cjs/popper.min.js` with `https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.0/umd/popper.min.js` resource url and will work.
> 
> This isn't an issue with Leaflet and should be closed.

I'm building a Chrome Extension that is dynamically inserting a [MUI Autocomplete](https://mui.com/material-ui/react-autocomplete/) (uses Popper under the hood) component in a page and getting the same error `Uncaught RangeError: Maximum call stack size exceeded
    at getComputedStyle (popper.min.js:1)`.

I'm curious to understand more about the [previous answer](https://github.com/Leaflet/Leaflet/issues/7127#issuecomment-626316082). Why is it that an infinite loop occurred when the `cjs` version of the popper library was loaded instead of the `umd` library? You'd think that an exception is thrown stating that popper was not found?
