### ISSUE TITLE
Update Leafdoc

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7134]
[Latest](https://github.com/Leaflet/Leafdoc/blob/gh-pages/package.json) Leafdoc is still [unpublished](https://www.npmjs.com/package/leafdoc) on npm, so Leaflet documentation is building with outdated Leafdoc.

The issue is already [reported](https://github.com/Leaflet/Leafdoc/issues/39) a year ago.

Besides of functionality, outdated Leafdoc currently is the source of critical vulnerabilities reported by npm during install (see https://github.com/Leaflet/Leaflet/pull/7133#issuecomment-625873697).

**Comment by mondeja** [comment]
I think that [this pull](https://github.com/Leaflet/Leafdoc/pull/50) can be merged to remove a security vulnerability during install. 
This [Leaflet issue](https://github.com/Leaflet/Leaflet/issues/7021) has been closed but the error persists with current Leaflet master because Leafdoc has not been released after [removing sander dependency](https://github.com/Leaflet/Leafdoc/pull/48), that was the source of the error.

So yes, we need a new Leafdoc version published in NPM:

- Bump Leafdoc version to `1.6.0`.
- Publish it on NPM.
- Bump Leafdoc version dependency in Leaflet `package.json`.

**Comment by IvanSanchez** [comment]
I've been working on some (IMO much-needed) cleanup of the leafdoc regexes. Before publishing a new Leafdoc version, I'd appreciate any review of https://github.com/Leaflet/Leafdoc/pull/52

**Comment by Falke-Design** [comment]
Version 2.3.0 of Leafdoc released on npm: https://www.npmjs.com/package/leafdoc
