### ISSUE TITLE
Calling bringToBack should also affect Tooltip

### ISSUE THREAD

**Issue by ludik0** [Leaflet/Leaflet#7149]
**Is your feature request related to a problem? Please describe.**
In my Applications all Polygons have a permanent tooltip. If two polygons are at the same spot, you can use a double click to "shuffle" trough all the Polygons at this spot using "bringToBack". bringToBack works and the underlying polygon is shown, but is now labeled wrong because the label was not send to back.

**Describe the solution you'd like**
Calling "bringToBack" on a layer should also adjust the zindex of the layers tooltip.

**Describe alternatives you've considered**
Add a bringToback method to the tooltip, to call it manually.

**Additional context**

I would love to help, if you could provide some guidance, thank you !

**Comment by IvanSanchez** [comment]
I disagree. Both `L.Popup` and `L.Tooltip` already have a `bringToFront()` method (inherited from `DivOverlay`), so you could call `myPolygon.getTooltip().bringToFront()` or even chain everything in `myPolygon.bringToFront().getTooltip().bringToFront()` to get the same effect.

There is, however, a documentation mismatch on the methods inherited from `DivOverlay`, and maybe other maintainer(s) have a different take on this feature, so I'll leave this open.

**Comment by johnd0e** [comment]
> so you could call `myPolygon.getTooltip().bringToFront()` or even chain everything in `myPolygon.bringToFront().getTooltip().bringToFront()` to get the same effect.

That's right.
Still, I agree that it's natural to expect from Leaflet to handle such things automatically.

But.. in order to implement such functionality correctly a lot of code should be overseen, to keep many very different cases consistent.

E.g.: what if tooltips are not permanent, and we call `bringToFront` programmatically (for inactive polygon)?
Or what if the tooltip belongs to FeatureGroup.

The things are not so straight-forward as it might seem.
