### ISSUE TITLE
Double Click Zoom on Leaflet 1.7 and IOS 13 not works

### ISSUE THREAD

**Issue by Bitxenio** [Leaflet/Leaflet#7185]
My App hangs on IOS 13 on zooming an CodenameOne app, I tried the library 1.7 and works fine.

The problem is with this new library the Double Click Zoom dont work, on IOS 12 works fine.

Regards

**Comment by IvanSanchez** [comment]
Well, 1.7 hasn't been released yet, so you should be more specific.

Also be aware of my standard disclaimer about bugs not involving a webpage and a browser:

> In this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
>* React
>* Ractive
>* AngularJS
>* Bootstrap
>* Leaflet for R
>* Joomla
>* Wordpress
>* Ionic
>* Cordova
>* Vue
>* Electron
>* Polymer
>* TypeScript
>* D3
>* Folium
>* ...etc
>
>Please understand that we only have the time and energy to test Leaflet in plain web browsers.

So, does double-click zoom work on Safari on iOS13 on a webpage using either Leaflet 1.6 or a build from the latest `master`?

**Comment by ivanov-v** [comment]
> Well, 1.7 hasn't been released yet, so you should be more specific.
> 
> Also be aware of my standard disclaimer about bugs not involving a webpage and a browser:
> 
> > In this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
> > 
> > * React
> > * Ractive
> > * AngularJS
> > * Bootstrap
> > * Leaflet for R
> > * Joomla
> > * Wordpress
> > * Ionic
> > * Cordova
> > * Vue
> > * Electron
> > * Polymer
> > * TypeScript
> > * D3
> > * Folium
> > * ...etc
> > 
> > Please understand that we only have the time and energy to test Leaflet in plain web browsers.
> 
> So, does double-click zoom work on Safari on iOS13 on a webpage using either Leaflet 1.6 or a build from the latest `master`?

I use 1.7, and zoom breaks my app. Links and buttons stop clicking.

**Comment by johnd0e** [comment]
@Bitxenio @ivanov-v 

Please check debug console for errors.

**Comment by Malvoz** [comment]
- The information in this bug report is too vague.
- Response to feedback from maintainers is vague or lacking.
- And with little demand from the community for a bug fix, this is perhaps either app-specific or specific to iOS 13 which must've been resolved since.

@Bitxenio, @ivanov-v If you can reproduce this bug in later versions of iOS with Leaflet v1.8.0 we can re-open this issue. Although I encourage you to file a new bug using the [bug report form](https://github.com/Leaflet/Leaflet/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug_report.yml) to ensure all necessary information is provided.
