### ISSUE TITLE
Unable to load a tpk file with leaflet. Want to load offline map with tpk file in directory. Help!

### ISSUE THREAD

**Issue by ayushkul** [Leaflet/Leaflet#7212]

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
