### ISSUE TITLE
could not able to remove grid layer

### ISSUE THREAD

**Issue by darda-ergo** [Leaflet/Leaflet#7237]
![image](https://user-images.githubusercontent.com/61325474/90340190-35858080-e018-11ea-9577-d7727bc080f9.png)

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
