### ISSUE TITLE
GeoJSON Tutorial would be more realistic using GeoJSON file not JS File

### ISSUE THREAD

**Issue by flywire** [Leaflet/Leaflet#7281]
[GeoJSON Tutorial](https://leafletjs.com/examples/geojson/) would be more realistic using a `.GeoJSON` file rather than a `.js` file.

**Comment by alvarolozano** [comment]
I agree with you! But `L.geoJSON` is designed to work with JS objects... In order to load a `.GeoJson` file, additional steps are required (data fetching).

An option might be to use an external Ajax library (https://github.com/calvinmetcalf/leaflet-ajax) which extends L.geoJSON lib by adding data fetching capabilities -> `var geojsonLayer = L.geoJson.ajax("buildings.geojson");`

**Comment by Malvoz** [comment]
See also https://github.com/Leaflet/Leaflet/issues/7254.

**Comment by mann-codes2014** [comment]
Hi, I think, we can import a **GeoJSON** file as geojson files also have **.json** extension. After that we can parse that JSOn to simple Javascript object and use with **L.geoJSON**.

**Comment by jonkoops** [comment]
I don't see the need to put this into separate JSON file, the code is about how to display GeoJSON. The manner in which is retrieved is up to the user.
