### ISSUE TITLE
Flat earth view

### ISSUE THREAD

**Issue by julientype** [Leaflet/Leaflet#7282]
with a zoom flat isometic earth we would not have a repeat flat map....

like a clock you would simply spin it an zoom down.....

it needs to be an  isometic world view as you zoom in 2 or 3 layers it becomes flat or stay  isometic...

with the  isometic  flat earth  map  you could draw a moon  object and run trajectory data..... or earthquake data.... or fires.....
a flat earth map is  just an unwrap globe as you zoom in 

Fake 3d ...... you simply spin the map wheel and zoom down...
map edge has N S E W S spin it and it changes........

you now added a programmable tiled sky layer..... 
like where is the sun.... or moon in the sky at your angle .... the data is online.....

with   isometic map  layers i could build a layer on the map at full zoom in... zoom out and its gone....
zoom in and tigger. loads....
https://www.mapeditor.org/

**Comment by IvanSanchez** [comment]
Hi, I'm closing this issue because the quality is not good enough. I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make good bug reports.
