### ISSUE TITLE
Update docs for creating custom icon

### ISSUE THREAD

**Issue by Stuart88** [Leaflet/Leaflet#7300]
This is a very old and as yet unsolved issue. (https://github.com/Leaflet/Leaflet/issues/534)

Current docs say [custom icon should be of the form](https://leafletjs.com/reference-1.7.1.html#icon):

```js
var myIcon = L.icon({
    iconUrl: 'my-icon.png',
    iconSize: [38, 95],
    iconAnchor: [22, 94],
    popupAnchor: [-3, -76],
    shadowUrl: 'my-icon-shadow.png',
    shadowSize: [68, 95],
    shadowAnchor: [22, 94]
});
```

However it seems to be the the only way to make this work is to instantiate via `new`, i.e.

```js
var myIcon = new L.Icon({
    iconUrl: 'my-icon.png',
    iconSize: [38, 95],
    ...
});
```

It took a lot of googling to find this out!

**Comment by IvanSanchez** [comment]
Calling `L.icon(stuff)` is the same as calling `new L.Icon(stuff)`, since https://github.com/Leaflet/Leaflet/blob/bfe7c689cd25333778a68fa46eb1e5dfad921b66/src/layer/marker/Icon.js#L163-L165

Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays failure to create a custom icon via `L.icon()`?
