### ISSUE TITLE
HeatmapWithTime is visualized in the back of overlay image

### ISSUE THREAD

**Issue by JavierParada** [Leaflet/Leaflet#7314]
HeatMapWithTime is visualized in the back of the overlay image, even after including <style>.leaflet-heatmap-layer{z-index:300 !important}</style> in my html.

According to https://github.com/python-visualization/folium/issues/1201, including this <style>.leaflet-heatmap-layer{z-index:300 !important}</style> in my html should bring the Heatmap to the front. However, that did not work.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.

**Comment by Dakcser** [comment]
If anybody else has problem with HeatMapWithTime drawing data behind ImageOverlay. Instead of using above mentioned line of HTML code which tries to push heatmap layer foward.

You can instead push ImageOverlay back with code <style>.leaflet-image-layer{z-index:-1 !important}</style> (Index -1 sets image back of the stack).
![Sieppaa](https://user-images.githubusercontent.com/50385519/229619110-6dcb1d32-edeb-4024-b4c6-4c1850d67c34.PNG)
