### ISSUE TITLE
event.latlng on click outside of map works inconsistent for north/south and east/west

### ISSUE THREAD

**Issue by tirli** [Leaflet/Leaflet#7348]
- [X] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [X] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [X] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
- create map with tiles that has noWrap turned on. 
- add `mousedown` event handler. 
- add a marker to `event.latlng` coordinates
- click outside the map (above and on the left)

**Expected behavior**
`event.latlng` snaps to map bounds on all 4 sides outside of the map.

**Current behavior**
`event.latlng` snaps to map bounds on north/south, but doesn't do it on east/west

**Environment**
- Leaflet version: 1.7
- Browser (with version): Chrome 86
- OS/Platform (with version): Linux (don't think it is platform or browser specific)

**Additional context**

Seems like this code is responsible for doing projecting (snapping)
https://github.com/Leaflet/Leaflet/blob/68ef9eafd33c08e54af5f190cedabb950ec67266/src/map/Map.js#L1006-L1009

**Minimal example reproducing the issue**

https://plnkr.co/edit/L0vEOtbPufB1UeTa

![image](https://user-images.githubusercontent.com/7783308/100007510-dbdde080-2dd4-11eb-8c01-07357f35068a.png)

- [X] this example is as simple as possible
- [X] this example does not rely on any third party code

**Comment by IvanSanchez** [comment]
This is behaviour as intended, not a bug. Options given to tilelayers on a map don't affect behaviour of the map itself (except `min`/`maxZoom`).

Either use the map's `maxBounds` option, clamp the marker coordinates when clicked, or use `wrapLatLngLng`.

**Comment by tirli** [comment]
@IvanSanchez but `maxBounds` doesn't affect event handlers in any way. Or you propose to handle it manually based on `maxBounds`?

**Comment by IvanSanchez** [comment]
You can:

- Clamp the longitude in the code that spawns the markers
- `wrapLatLng` the latlng in the code that spawns the markers
- Check if the markers are inside a given `LatLngBounds` and throw an error if not
- [Hack the code for `L.Projection.SphericalMercator` so that longitude is clamped in a similar way than is done with the latitude](https://plnkr.co/edit/pCT6KAEwOjce84Hh)
- Hack the code for `L.Projection.SphericalMercator` so that latitude is **not** clamped (so behaviour is *consistent* across both axes, which was your complaint)

In any case, the current default behaviour is the desired one.
