### ISSUE TITLE
setZoom not working

### ISSUE THREAD

**Issue by JeffDerk** [Leaflet/Leaflet#7384]
Seems to only happen when setting certain zoom levels?

Map initialized with zoom level 18 and then executing
```
map.setZoom(10, { animate: true });
map.setZoom(11, { animate: true });
console.log(map.getZoom()); // results in 10
```

Seems like it is caused because _this_ is undefined here: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L1674

**Comment by johnd0e** [comment]
@JeffDerk Please do not ignore issue template and provide all the required info, otherwise we are unable to help with your problem.
Closing for now.

**Comment by johnd0e** [comment]
- [ ] I've looked at the [documentation](http://leafletjs.com/reference.html) to make sure the behavior is documented and expected
- [ ] I'm sure this is a Leaflet code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [ ] I've searched through the issues to make sure it's not yet reported

**Steps to reproduce**
Steps to reproduce the behavior:
- step 1
- step 2
- ...

**Expected behavior**


**Current behavior**


**Environment**
- Leaflet version:
- Browser (with version):
- OS/Platform (with version):

**Additional context**


**Minimal example reproducing the issue**

Please create an example using https://leafletjs.com/edit.html or any other jsfiddle-like site.

- [ ] this example is as simple as possible
- [ ] this example does not rely on any third party code
