### ISSUE TITLE
Examples are not mobile-friendly

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7420]
- [x] https://leafletjs.com/examples/layers-control/example.html
Layers control is out of view on mobile.
  (Edit: Fixed in https://github.com/Leaflet/Leaflet/pull/7950)
- [x] Todo: check the rest of examples
  (Edit: Fixed in https://github.com/Leaflet/Leaflet/pull/7950)
- [ ] [Responsive media elements](https://github.com/Leaflet/Leaflet/issues/7420#issuecomment-1023022670)

_(Edited by @Malvoz)_

**Comment by jalajcodes** [comment]
I'd like to work on this @johnd0e

**Comment by johnd0e** [comment]
Sure, feel free to contribute

**Comment by HRSArgyropoulos** [comment]
Hi. Please bear in mind that i am completely new in this amazing world of collaborating. 

I had a look at this issue, that seems to be also causing issues in the official webpage in [examples > layers-control](https://leafletjs.com/examples/layers-control/).
The reason behind this issue is that the iframe element in the table of the [layers-control page](https://leafletjs.com/examples/layers-control/) and the div with id "map" in the example.html document have a fixed value.

Thus, my suggestion would be;

- Change the css inside <style></style> of the example.html document of the map selector to this;

```
#map {
 max-width: 600px;
 width: 100%;
 height: 400px;
}
```

- Change the iframe width in the [layers/control page](https://leafletjs.com/examples/layers-control/) from 600px to 100%

`<iframe src="example.html" width="100%" height="416"></iframe>` 

- We should also set the iframe to have a max-width style so the map aligns in the center of the container in bigger screens like so;
```
iframe {
 max-width: 600px;
}
```

**Comment by HRSArgyropoulos** [comment]
@johnd0e Have a look when you are able to so i can continue this fix as all examples in the tutorial html pages have mobile responsive issues. I also wanted to change this
```
<iframe src='{{ include.url }}'
	width='{% if include.width %}{{ include.width }}{% else %}616{% endif %}'
	height='{% if include.height %}{{ include.height }}{% else %}416{% endif %}'></iframe>
</td></tr>
```
in frame.html in else to width=100% as mentioned above but i am not sure what other iframes we have in docs (youtube videos etc).

**Comment by HRSArgyropoulos** [comment]
(ignore previous commits/branch) i made some changes to try to fix the overall responsiveness of examples in mobiles.

**Comment by kaushikjatin** [comment]
I was going through this issue and I found that the map doesn't covers the full width in the PC.It looks dull to see the map sticked on the top left corner of the page.
Go to this link in the PC -> [https://leafletjs.com/examples/layers-control/example.html](url) and see the map attached at top left corner.

**Comment by branko-stankovic** [comment]
> I was going through this issue and I found that the map doesn't covers the full width in the PC.It looks dull to see the map sticked on the top left corner of the page. Go to this link in the PC -> [https://leafletjs.com/examples/layers-control/example.html](url) and see the map attached at top left corner.

That's because its width is set to 600px. It needs to scale with the window, so it could work both on mobile and desktop.

**Comment by johnd0e** [comment]
> I found that the map doesn't covers the full width in the PC

I do not think that it is bad,

**Comment by Malvoz** [comment]
@johnd0e Responsiveness of maps was fixed in https://github.com/Leaflet/Leaflet/pull/7950. We can keep this issue open to fix responsiveness of media elements:

- [ ] The standalone `<video>` under https://leafletjs.com/examples/video-overlay/#:~:text=To%20display%20this%20video
- [ ] Some `<img>` elements across different pages

They just need `max-width: 100%` I believe, so I guess it's just a matter of preference of how to apply those styles:
- A CSS class for responsive media elements
- Inline `style=""` on these elements
- A generic selector, e.g. `.tutorials img, .tutorials video { max-width: 100%; }` (this is probably too brittle)
