### ISSUE TITLE
Content Security Policy: style-src 'unsafe-inline'

### ISSUE THREAD

**Issue by louis123562** [Leaflet/Leaflet#7511]
hey,

i would like to use leaflet without allowing the csp

`style-src 'unsafe-inline'`

Are there any approaches on how this is possible?

I use latest 1.7.1 version.

Thanks in advance :)

**Comment by Malvoz** [comment]
The [`'unsafe-hashes'`](https://w3c.github.io/webappsec-csp/#unsafe-hashes-usage) source expression is more secure than [`'unsafe-inline'`](https://w3c.github.io/webappsec-csp/#ref-for-grammardef-unsafe-inline) because it only allows inline styles controlled by the specified hashes in your policy, as opposed to all inline styles.

**Comment by Malvoz** [comment]
Although in an ideal world Leaflet would not use inline `style` attributes nor `data:` URIs (https://github.com/Leaflet/Leaflet/issues/6113):

> [`unsafe-inline`](https://w3c.github.io/webappsec-csp/#ref-for-grammardef-unsafe-inline)

> developers SHOULD NOT include either `'unsafe-inline'`, or `data:` as valid sources in their policies. Both enable XSS attacks by allowing code to be included directly in the document itself; they are best avoided completely.

**Comment by louis123562** [comment]
i will check for unsafe-hashes, thank you so far

**Comment by Malvoz** [comment]
Closing per my previous comment.
