### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by huntr-helper** [Leaflet/Leaflet#7580]
👋 Hello, we've received a report a potential high severity security issue in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit the following links for more advisory information:
  - https://huntr.dev/bounties/1-other-Leaflet/Leaflet
  - https://huntr.dev/bounties/2-other-Leaflet/Leaflet

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by zer0h-bb** [comment]
Hi,

Can the two submissions https://huntr.dev/bounties/1-other-Leaflet/Leaflet/ and https://huntr.dev/bounties/2-other-Leaflet/Leaflet/ be validated in the huntr.dev plateform if you consider those issues ?

Best regards,
zer0h

**Comment by Falke-Design** [comment]
![grafik](https://user-images.githubusercontent.com/19800037/163557727-f33da86e-9353-4751-8757-157fff77ea39.png)

**Comment by Falke-Design** [comment]
Do we want to do something? I see not the need of doing it

**Comment by Malvoz** [comment]
If anything, it'd be additions/updates to docs.

**Comment by Malvoz** [comment]
> https://huntr.dev/bounties/1-other-Leaflet/Leaflet

This looks like a duplicate of https://github.com/Leaflet/Leaflet/issues/6465 (potential for XSS in the attribution).

> https://huntr.dev/bounties/2-other-Leaflet/Leaflet

This is the potential for XSS in popups.

If such content was based on user-input, developers could use a CSP and/or sanitize the HTML to mitigate XSS. Leaflet could provide docs to make developers aware of potential XSS issues and mitigation methods. I've added an item to the wish list of tutorials: https://github.com/Leaflet/Leaflet/issues/4239#issuecomment-1159533719.

**Comment by gernia** [comment]
Hello,

we recently encountered an XSS on a website that we did a pentest on, which was caused by the `bindPopup` and `bindTooltip` functions. Even though leaflet does not offer the function of having user input, a library should be safe per default and consumer developers don't necessarily expect the content of a popup or tooltip to interpret HTML including event handlers. 

I know this issue is probably fixed in leaflet 2.0 as you are migrating from innerHTML, but  leaflet 1.9.4 still is the main version currently used. There should definetly be a warning in the documentation and better yet you could use `DOMPurify.sanitize()` in for example the `_updateContent` function, which would just remove all event handlers. If you want to keep the possibility of event handlers in the popup content, another option would be to add a parameter which per default would enforce safe behaviour.
