### ISSUE TITLE
Plugin.md: Merge plugins PRs, use `tabs` and update links

### ISSUE THREAD

**Issue by Falke-Design** [Leaflet/Leaflet#7801]
I think it would be good if we "update" the plugin page. Means that we replaces blanks with `tabs` and updating corrupt `urls`.
But first all open PRs should be merged, else we will have merge conflicts.

I created a script to get all [corrupt links](https://florianbischof.net/leaflet/links.html). Not every suggestion / redirect is correct but it is a start.

TODOs:
- [ ] Merge [PRs](https://github.com/Leaflet/Leaflet/pulls?q=is%3Aopen+is%3Apr+label%3Aplugins)
- [ ] Replace blanks with tabs
- [ ] Update urls. [corrupt links](https://florianbischof.net/leaflet/links.html)

Plugins PRs ready to merge:
- [x] #7786

Any many others with merge conflicts or with blanks. (Maybe we can merge them with blanks and then updated manually by me)

**Comment by mourner** [comment]
We also want to do at least minimal quality control on the plugins that get merged into the list, so that it doesn't list things that are not maintained / broken / not making much sense.

**Comment by Falke-Design** [comment]
I would say this also includes an English description, what do you think? Example: https://github.com/wandergis/leaflet-echarts

**Comment by IvanSanchez** [comment]
Since the leaflet website uses github pages under the hood, and in turn that uses Jekyll, there's the option of leveraging [Jekyll collections](https://jekyllrb.com/docs/collections/).

This means a rebuild of the *whole* plugins page, and turning each line of the plugins table into a separate markdown document. The plus side is that each plugins is a separate small markdown file, so conflicts go down and it'd be possible to add more attributes (e.g. version compatibility) to each plugin.

**Comment by Falke-Design** [comment]
Reference #5387

**Comment by Falke-Design** [comment]
But then we would have around 500 seperate files. We can also split it by the topics into seperate files.

I like the suggestion because then the data and layout are different things. Also for future things like adding a search for tags, version, npm etc.

**Comment by Falke-Design** [comment]
Fixed by moving the plugins into seperate files #7805
