### ISSUE TITLE
Toggle layer control with on click event

### ISSUE THREAD

**Issue by mugambi40** [Leaflet/Leaflet#7869]
I would wish if there was a way to toggle layer control with a click event instead of the mouseover event. I have tried to play around with the library and change one line on DomEvent.js and it works. See the code below:

`var mouseSubst = {`
 ` // mouseenter: 'mouseover', //original code`
 ` mouseenter: "click", //Changed this line`
  `mouseleave: "mouseout",`
  `wheel: !("onwheel" in window) && "mousewheel",`
`};`

Am not sure if it will bring adverse effect on the rest of the functionalities.

**Comment by Falke-Design** [comment]
You don't need to go that deep. You cna simply add a click listener on the layer-control container:
```
var control = L.control.layers({
	'OSM': OSM_Mapnik,
	'OSM BW': OSM_BlackAndWhite
}, null, {
	collapsed: false
}).addTo(map);

control.collapse();
L.DomEvent.on(control.getContainer(),'click',()=>{
	L.DomUtil.hasClass(control.getContainer(), 'leaflet-control-layers-expanded') ? control.collapse() : control.expand();
});
```
https://plnkr.co/edit/CohBtCiHqhUfDwDm


With `collapsed: false` you disable the mouseover listener.

I will close this because it can be done with the few lines from above and closing of the expanded layer-control per click will be never easy and comfortable . Clicking only works on the border, in the middle always a text is clicked and then the `click` is not propagated, because it toggles a checkbox.
