### ISSUE TITLE
Specifying precision or number of digits supplied by .toBboxString() ?

### ISSUE THREAD

**Issue by chrisjdixon** [Leaflet/Leaflet#7935]
We're using `map.getBounds().toBBoxString()` to get a string populating a URL like "in_bbox=149.88621046168862,-36.95980343898053,149.94247247798498,-36.93023814568345".

This works as expected but with 12 digits on each point this is specifying a location to the precision of 0.0001mm which is around 100 times the diameter of a red blood cell. We don't need this level of precision and although I'm unsure if this impairs performance it looks silly.

We haven't found any options for `.toBboxString()` in [the documentation](https://leafletjs.com/reference-1.6.0.html#latlngbounds-tobboxstring) and we're wondering if it's possible to limit the number of digits. Is this possible?

**Comment by IvanSanchez** [comment]
The performance considerations are negligible IMO. Since the purpose of `toBBoxString()` is to populate URLs, and not to be used on anything user-facing (i.e. it doesn't matter if it "looks silly"), it's hard to find a motive to change the current behaviour.

You can always hack together something like `toBboxString().split(',').map(str=>str.substr(0,10)).join(',')` if you want, though.
