### ISSUE TITLE
When will the canvas complete the rendering? Is there any event for that. 

### ISSUE THREAD

**Issue by shenzhuxi** [Leaflet/Leaflet#7987]
I'm trying to modify the colour in the canvas and didn't found a clear event mentioned about the end of the rendering. 

Here is a simple example https://jsfiddle.net/nk8sw29p/. 

If the map was dragged, the moveend event will be triggered and the colour will be replaced. But it won't work for zooming although moveend event was triggered. 

Since the document mentioned that "add | Event | Fired after the layer is added to a map", I tried this https://jsfiddle.net/nk8sw29p/1/

I found that the colour was changed for a brief moment with either drag event or zoom event but can't stay. To see it, I need to put a breakpoint at:
```
        ctx.putImageData(imageData, 0, 0);
        return;
```
So I wonder what's the moment for the canvas to complete updating certain layer. Is there anything like "rendercomplete" in openlayers https://openlayers.org/en/latest/apidoc/module-ol_render_Event-RenderEvent.html?

**Comment by IvanSanchez** [comment]
https://leafletjs.com/reference.html#renderer-update

Do read the code around https://github.com/Leaflet/Leaflet/blob/0b8ce652ba7b519d52851aed443c11c8afe8df90/src/layer/vector/Canvas.js#L125-L126

If there are race conditions using this approach, consider subclassing `L.Canvas`, and wrap the `_redraw` private method so that a custom event is fired after redraws.
