### ISSUE TITLE
Amazon CDN gives 403 while trying to load leaflet

### ISSUE THREAD

**Issue by rcarroll0452** [Leaflet/Leaflet#8074]
The URL https://leafletjs-cdn.s3.amazonaws.com/content/leaflet/master/leaflet.js used to work until recently. It is now giving AccessDenied response. 
Reporting here since I'm not sure if this is a bug or if I'm unaware of any policy changes.

Thanks.

**Comment by reddoxster** [comment]
Is it possible for a redirect temporarily please? We are facing this issue as well and since we used this in our sample code for years, we expect 100s of users' websites & maps will be down..

Since it's a CDN and I think we got the reference to this link from an old leaflet sample, we (and I think everyone else) would expect that link to work at least..

**Comment by reddoxster** [comment]
I expect https://github.com/Leaflet/Leaflet/pull/7921 broke this - fully support change of language for inclusiveness, but no reason to break CDN links that have worked for years..

**Comment by jonkoops** [comment]
#7921 is not the reason why this broke, it seems to me that https://github.com/Leaflet/Leaflet/pull/8046#issuecomment-1065390527 would be the reason. @mourner you are the only one with access to the CDN, could you restore this directory?

That said, nobody should ever rely on the `main` version of Leaflet. It takes the latest development state, which can break at any time due to bugs or changes in the API between major versions. Use a versioned CDN instead.
