### ISSUE TITLE
updating the popup content on popupopen

### ISSUE THREAD

**Issue by pcpatfire** [Leaflet/Leaflet#8130]
I'm trying to update the popup content associated to a marker (in the `pointtolayer` function when adding a GeoJSON overlay) in the `popupopen `event handler, with the following code:
```
const addTest = () => {
  const container = document.getElementById(containerID);
  container.innerHTML = "<p>TEST</p>"
}

popup.setContent(`<div id="${containerID}"></div>`) //popupContent)

marker
  .bindPopup(popup)
  .on("popupopen", function (popup) {
    console.log(popup);
    addTest();
  });
```
The first time I click on a marker the popup content is not updated. If I click again, while the popup is open, the popup content is updated.

Using the debugger, I noticed that also during the first click event handling the popup is updated, but before the completion of the same click event handling it is restored to the previous value.

What's wrong in my code? Or is a Leaflet issue?

**Comment by Falke-Design** [comment]
Is working fine for me: https://plnkr.co/edit/q9Eo7elzRUoKcNP3 
Are you sure that you are using Leaflet Version 1.7.1 or newer?

**Comment by pcpatfire** [comment]
Yes, I am using Leaflet Version 1.7.1.

In my code  I'm defining the marker popup in the function passed to the `pointToLayer` option  of `L.GeoJson()`.
Can this make the difference?

**Comment by Falke-Design** [comment]
Please share your code and if possible make a demo here: www.leafletjs.com/SlavaUkraini/edit.html

**Comment by IvanSanchez** [comment]
It might be either to a user's error by now keeping track of the variables involved (I'm kinda tired of linking to an explainer of how JS closures work), or it might be due to Leaflet firing the `popupopen` event before the container has been actually added to the DOM (but then, a `getElementById()` call would return `undefined`, and something should throw an error).

In any case:  the container for a popup can be reliably fetched, even if it hasn't been added to the DOM, by:

```
foo.on('popupopen', function(ev) {
  var popupContainer = ev.popup.getElement();
});
```

Also note one can use `L.Popup`'s `setContent()` in a similar fashion by using `ev.popup.setContent()`.

I'm partial to closing this as "not a Leaflet bug" since it's perfectly possible to update a popup's content from an event related to that popup.

**Comment by pcpatfire** [comment]
Probably it is "not a Leaflet bug", but i fixed my problem doing something "strange" with a Leaflet marker method:
```
marker
  .bindPopup(popup)
  .on("popupopen", function (popup) {
    console.log(popup);
    addTest();
    this.setPopupContent();
  });
```
I just added the line `this.setPopupContent();` after popup content update, which shouldn't (?) do anything... but it is actually doing something, in Falke-Design's demo too. In fact the popup rendering is different, with or without that call. 
I don't know why, maybe someone can try to figure out.
Check this demo with a longer line of text in the popup: https://plnkr.co/edit/egZnvbHMjPAK1gHY
If you comment out the added line of code,  the popup content is the same but is differently rendered. 
In my case it is correctly set to my "exepcted" content.

**Comment by Falke-Design** [comment]
This Your suggestion is very tricky and not a clean workaround. 

**Why is happening?**
Leaflet defines the size of the popup based on the content, but you changing the DOM directly without letting Leaflet know, that the content has changed, because of this the width of the container is not growing.
When you call `setPopupContent()` the caclucation for the size of the container is triggered but without passing an argument you set the content variable in Leaflet to `undefined`. Now functions like `getPopup().getContent()` not working anymore.

The right way would be this:
```
const addTest = () => {
	popup.setContent(`<div id="${containerID}"><p>This is a longer line of text!</p></div>`) //popupContent)
};

marker
	.bindPopup(popup)
	.on("popupopen", function (popup) {
		console.log(popup);
		addTest();
	});
```

I close this "error" because of a wrong usage of the API.

**Comment by pcpatfire** [comment]
You are right that it was a very tricky suggestion. But I found a workaround with a correct usage of the API.

```
popup.setContent(`<div id="${containerID}-wrap"><div id="${containerID}"></div></div>`) //popupContent)

marker
  .bindPopup(popup)
  .on("popupopen", function (e) {
    addTest();
    const innerHTML = document.getElementById(containerID+"-wrap").innerHTML;
    this.setPopupContent(innerHTML);
    alert(e.popup.getContent());
  });
```
I add a wrapper to the previous popup content and then I pass the `innerHTML `of the wrapper to `setPopupContent`. Now Leaflet knows the DOM changed and getContent is working properly.
Check the demo here: https://plnkr.co/edit/egZnvbHMjPAK1gHY
