### ISSUE TITLE
how can I get correct container point in Retina screen?

### ISSUE THREAD

**Issue by edgexie** [Leaflet/Leaflet#8185]
![image](https://user-images.githubusercontent.com/18474752/165015678-caba70db-8bc4-4e6e-a2dc-b15604df6704.png)
I saw canvas width and height are twice of canvas style width and height.
when I transfer map.latLngToContainerPoint function, then use the return values to  draw a circle to canvas renderer, the circle is not at correct position.
many thanks

**Comment by Falke-Design** [comment]
Can you please create a [demo](https://leafletjs.com/SlavaUkraini/edit.html)

**Comment by edgexie** [comment]
@Falke-Design  in this [demo](https://plnkr.co/edit/tL4sbvfJQku2rP1r) , the canvas circle is not at the marker position

**Comment by Falke-Design** [comment]
![canvas_circle](https://user-images.githubusercontent.com/19800037/165047531-1ce73e59-c4f8-4b8c-b8bc-5c6572fd3660.gif)

**Comment by IvanSanchez** [comment]
> Why is canvas element width double of style width?

Because https://github.com/Leaflet/Leaflet/commit/674d9ae4d350b193c544503803feb1398a6a3fee.

`latLngToContainerPoint` *et al* all return CSS pixels, not screen pixels, and that's expected. The `HTMLCanvasElement` needs to have its size in screen pixels.

I fail to see how this is a bug. The only actionable thing here would be to replace the docstrings of `latLngToContainerPoint` *et al* so they read "CSS pixel" instead of the slightly ambiguous "pixel".

**Comment by edgexie** [comment]
@IvanSanchez thanks
my screen is 2k , and I set system config display zoom to 150%. In this case, how can i get the `CSS pixel`  from latLng, so that I can render circle at the marker position?
![image](https://user-images.githubusercontent.com/18474752/165053571-e12524ac-ce3e-4ab2-806f-b6c520d6874f.png)

**Comment by edgexie** [comment]
@Falke-Design another question, L.canvas mouse event failed. click event is in the demo at line 96. any ideas?

**Comment by jonkoops** [comment]
Closing this issue as it doesn't seem to be a bug in Leaflet. If you are looking help with specific issues I'd recommend using Stack Overflow or the discussions.
