### ISSUE TITLE
Edge canary 102: offset in SVG hit detection

### ISSUE THREAD

**Issue by arieldr** [Leaflet/Leaflet#8208]
With recent release of Microsoft Edge Canary version (as of date 2/May/2022, version 102.0.1243.0) it seems like when moving the mouse it is and hovering over a marker there is a gap between the place of the marker and the mouse location.

As can be seen here, if you move the mouse in the borders of the marker, the cursor icon will change between finger and hand mode in the wrong location

https://codesandbox.io/s/canaryleaflet-forked-nu5vdx

Need to try this using Microsoft Edge Canary version (I am forced to use Ms.Edge browser). It works ok using Google Chrome.

**Comment by IvanSanchez** [comment]
OK, so there's a cross-post in https://stackoverflow.com/questions/72089960/leaflet-with-edge-canary-recent-version-mouse-and-markers-glitch-gap-shift , and you're not reporting which version(s) of Leaflet this is reproducible in, neither which platform(s) (windows, linux, mac).
Please don't ignore the bug report template, and edit your bug report to add this information.

**Comment by arieldr** [comment]
Sorry, this is my first time.
Where is that template?
I am working with : 
Windows 10, 
Leaflet (any: 1.6.0, 1.7.1, 1.8.0), 
Microsoft Edge Canary (recent version 102.0.1243.0).

![mouseAndMarkerGap](https://user-images.githubusercontent.com/57740222/166317011-6768781a-b6da-41cf-af84-00fbfa9384dc.jpg)


Thanks, Ariel

**Comment by IvanSanchez** [comment]
> Where is that template?

When any user clicks on the green buttons to create a new bug report, they are ultimately taken through https://github.com/Leaflet/Leaflet/issues/new?assignees=&labels=&template=bug_report.md . If you haven't seen that, you're using a weird way to open new bug reports.

Second: Use screenshots instead of photographs taken from a phone.

Third: That's not a marker (`L.Marker`), that's a circle (`L.Circle`).

Fourth: I'm suspecting this might be related to https://github.com/Leaflet/Leaflet/issues/8185 , since at first sight it seems that the offset is aligned to the top-left corner of the map container... but `L.Circle`s use a `L.SVG` renderer by default, so the hit detection logic in `L.Canvas` should not be triggering.

The REPL at codesandbox is good (minimal reproducible examples are **very** good), but that's using parcel and babel under the hood. I'm wondering if that's messing up with the `L.Browser.SVG` autodetection somehow.

So, since I don't have an Edge browser ready right now, and this requires a bit more info to knwo what's going on, I'm gonna ask what are the values of `window.devicePixelRatio`, `L.Browser.retina`, and `L.Browser.SVG` in your environment.

**Comment by arieldr** [comment]
1. I just clicked new issue and did not get to that step, now I see I do reach that step.
2. I used a photo because a screenshot will not show the mouse pointer
3. Agree
4. I am running on a desktop pc, the values requested are as following:
window.devicePixelRatio = 1 
L.Browser.retina = false 
L.Browser.SVG = true 

Thanks

**Comment by IvanSanchez** [comment]
Confirmed in a Win10 VM with edge canary 102.0.1243. Seems like an upstream bug, since the hitbox of SVG elements is OK in the edge DOM inspector.

Cannot test in Linux, since there's no canary releases for that platform.

**Comment by arieldr** [comment]
Hi,

Just an update. The issue evolved to the "Dev" version of Ms. Edge too  (build 102.1245.3)

**Comment by Malvoz** [comment]
I'm not able to reproduce this in Edge v102.0.1245.44, are you?

(@IvanSanchez I removed the https://github.com/Leaflet/Leaflet/labels/ie label as the intention is to close out all IE-only issues once support for IE has been dropped.)

**Comment by arieldr** [comment]
All versions of Edge have resolved the problem so it no longer exists

**Comment by Malvoz** [comment]
Thanks for checking @arieldr!
