### ISSUE TITLE
leaflet.dialog plugin : bug with leaflet 1.8 (working with 1.7)

### ISSUE THREAD

**Issue by astomas** [Leaflet/Leaflet#8231]
link to the original issue: [https://github.com/NBTSolutions/Leaflet.Dialog/issues/27](https://github.com/NBTSolutions/Leaflet.Dialog/issues/27)

in [http://nbtsolutions.github.io/Leaflet.Dialog/](http://nbtsolutions.github.io/Leaflet.Dialog/), calling new Leaflet 1.8 API (04/2022) results in the following error:
" Uncaught TypeError: Cannot read properties of undefined (reading '0') ... at dialog_plugin.html:60:16 "
dialog_plugin.html:60 : " var dialog = L.control.dialog().setContent(contents).addTo(map); "
Possible cause of the error: in 'leaflet.dialog.js' , line180:
' _initLayout: function() { var className = "leaflet-control-dialog", container = (this._container = L.DomUtil.create("div", className));'
=> container variable is empty in 1.8 because in function initialize(), l.12 'this.options = JSON.parse(JSON.stringify(this.options));' is now empty ( this.options is null)
I have found a workaround: when creating the control.dialog object with leaflet 1.8, pass all options values:
var dialog = L.control.dialog({ size: [ 300, 300 ], minSize: [ 100, 100 ], maxSize: [ 350, 350 ], anchor: [ 250, 250 ], position: "topleft", initOpen: true }).setContent("hello").addTo(map);

**Comment by IvanSanchez** [comment]
Not a Leaflet bug.

**Comment by IvanSanchez** [comment]
Since you've been fumbling to write meaninful bug reports, I'm gonna point you towards:
- ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) 
- ["http://www.chiark.greenend.org.uk/~sgtatham/bugs.html"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)
- [The Secret Life of Open Source Developers](https://media.ccc.de/v/bucharest-322-the-secret-life-of-open-source-developers)
