### ISSUE TITLE
GeoJSON has 'renderer' property, but is not documented

### ISSUE THREAD

**Issue by hoetmaaiers** [Leaflet/Leaflet#8289]
### Checklist

- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this change hasn't been suggested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Which documents need updating?

https://leafletjs.com/reference.html#geojson-option

### Motivation

The GeoJSON options have an option `renderer`. Are they unique for the GeoJSON class or do they inherit from `Path`. This is inclear to me.

Also @types/leaflet is missing this option.

### Suggested changes

Add `renderer` option to `GeoJSON options` interface. Or have Geosjon inherit from `Path` if this is the case.

**Comment by IvanSanchez** [comment]
> The GeoJSON options have an option `renderer`.

No, they don't. `L.GeoJSON` inherits from `FeatureGroup` and `LayerGroup`, which are **not** `L.Path`s. `L.GeoJSON` does not take a `renderer` option at instantiation time.

If you mean "The `L.Path`s spawned by a `L.GeoJSON` have a `renderer` option because they're `L.Path`s", then that's already covered by https://leafletjs.com/reference#geojson-pointtolayer and https://leafletjs.com/reference#geojson-style .

Also: It's OK if you're not a native english speaker... but please, *please*, use the interrogation mark (`?`) key on your keyboard when you're writing a question.

**Comment by hoetmaaiers** [comment]
Excuse me for the missing question mark!

About L.GeoJSON not taking a `renderer` option at instantation time... I am defining this at instantation time to allow the `tolerance` to be defined. 

When defining tolerance only on the `L.map` instance this has no effect on the Geojson drawn paths.
This [CodeSandbox](https://codesandbox.io/s/leaflet-geojson-tolerance-t7cspp?file=/src/index.js) makes this clear.
If you uncomment the tolerance defined in the `customPaneRenderer`, tolerance is changed to 10.
