### ISSUE TITLE
Is it possible to be non-political?

### ISSUE THREAD

**Issue by MrCatEsq** [Leaflet/Leaflet#8295]
### Checklist

- [X] I've searched through the [plugins](https://leafletjs.com/plugins.html) to make sure this feature isn't already available, or think it shouldn't require a plugin.
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this feature hasn't been requested already.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Motivation

Now we can see expressive banner on the main page of the leaflet's site. I perfectly understand the author and his patriotic feelings. This war is terrible. The fact of the Russian military invasion of Ukraine is beyond doubt. The author has every right to express support for the defending side and encourage others to do the same. On the other hand what is written on the site is not confirmed by independent sources. For example, tens of thousands of killed civilians. Independent sources can't confirm this:
1. https://www.ohchr.org/en/news/2022/06/ukraine-civilian-casualty-update-17-june-2022
2. https://en.wikipedia.org/wiki/2022_Russian_invasion_of_Ukraine#Casualties_and_humanitarian_impact

As a result, the website banned on the territory of Russian Federation by their goverment. I assume that this creates problems for the developers, most of whom are unlikely to support the actions of the Russian regime. It also shrinks the project's audience and slows down the progress of free software. Nobody wins in this situation.

### Suggested solution

For my part, I filed an appeal with the Russian Prosecutor General's Office with a request to reconsider the position on blocking the site, because it is a useful tool that is important and useful to the whole world. I also ask you to rewrite the text in a more neutral way, I hope this helps in solving the problem.

**Comment by Malvoz** [comment]
I'm closing this, because I'm certain that @mourner is not interested in changing the statement.

**Comment by MrCatEsq** [comment]
> I'm closing this, because I'm certain that @mourner is not interested in changing the statement.

I would like to hear the opinion of the community on this issue. Perhaps this will change your mind. It is unlikely that an attempt to ignore and silence the problem corresponds to the ideals of freedom that Ukrainians are now fighting for. And, most importantly, I am not suggesting that the statement be changed, I am suggesting that the statement be corrected in accordance with reality and in a more neutral way.

**Comment by mourner** [comment]
> For example, tens of thousands of killed civilians. Independent sources can't confirm this:

From the source you cited, UN officially confirms 4.5k civilians killed, but with the following note:

> OHCHR believes that the actual figures are considerably higher, as the receipt of information from some locations where intense hostilities have been going on has been delayed and many reports are still pending corroboration. This concerns, for example, Mariupol (Donetsk region), Izium (Kharkiv region), Popasna, Lysychansk, and Sievierodonetsk (Luhansk region), where there are allegations of numerous civilian casualties.

In Mariupol alone, local city council estimates 22,000 civilians killed at the minimum — these are just the ones in known mass graves, there are many bodies remaining under the ruble or in improvised graves all over the city. Because of ongoing hostilities and occupation of large parts of Ukraine, UN doesn't have access to confirm any of the biggest casualty areas, and Russia works day and night to conceal its war crimes.

However, this is beside the point, because Leaflet's statement doesn't intend to be perfectly neutral. It's very much personal, and as the project's author and leader who can do whatever he wants with it, I intend to leave it this way.

> As a result, the website banned on the territory of Russian Federation by their goverment.

You're being disingenuous here. Websites have been banned for much less — even for just calling war a war, so making adjustments to the statement to make it less strongly worded won't make a difference in the slightest.

> It also shrinks the project's audience and slows down the progress of free software. Nobody wins in this situation.

The statement helps spread awareness and direct donations to support Ukraine, indirectly helping me and my family _stay alive_ — so I think it far outweighs any potential benefit from Russian participation in the project, which was already insignificant at best before the 2022 invasion.

**Comment by Tyrrrz** [comment]
> I assume that this creates problems for the developers, most of whom are unlikely to support the actions of the Russian regime

Are we still entertaining these claims? Sounds like a lot of confidence in a statement that has no statistical basis, but that has a lot of anecdotal evidence to the contrary.

**Comment by japplegame** [comment]
> I would like to hear the opinion of the community on this issue.

You should not trust a package whose author allows himself to relay propaganda in open source code.

**Comment by bartfeenstra** [comment]
> I would like to hear the opinion of the community on this issue

As a longtime Leaflet user, as a longtime Open Source maintainer, and as a longtime human being, I support these changes. If you feel like you want to avoid any mention of one country invading another, I'd like to suggest you find another library or go off-grid entirely. ❤🇺🇦

**Comment by Firefishy** [comment]
❤️🇺🇦👍

**Comment by jonkoops** [comment]
@mourner I suggest we lock this conversation as this will not produce any discussion worth our attention.
