### ISSUE TITLE
i am using https://github.com/stefanocudini/leaflet-search

### ISSUE THREAD

**Issue by pouemes** [Leaflet/Leaflet#8323]
i am using https://github.com/stefanocudini/leaflet-search
with leaflet  1.7.1 and 1.8.0  with firefox its impossible to scroll on the search result (with other browsers no problem)

in this example https://opengeo.tech/maps/leaflet-search/examples/geojson-layer.html
try to search with firefow m then scroll, it work because on this page its with a previous version of leaflet here 1.3.0

with firefox, it work until version 1.6.0, after it work only with others browsers, but with firefox, it only scroll the map

_Originally posted by @pouemes in https://github.com/Leaflet/Leaflet/discussions/8322_

**Comment by pouemes** [comment]
i really think that it's not because of the plugin

**Comment by Falke-Design** [comment]
This is a issue with the plugin / Firefox, because it uses the old [mousewheel](https://github.com/stefanocudini/leaflet-search/blob/15b4c295c935c6c227781fca05c6a6daa113c621/src/leaflet-search.js#L362) event listener instead of  `wheel` to prevent zooming on the map. Firefox doesn't fire `mousewheel` anymore: https://plnkr.co/edit/sbrPjG2j2GRJ3Av0

You use this simple workaround:
```
 your code ....
// adding the controller to the map
map.addControl( searchControl ); // or searchControl.addTo(map);

// disable zoom scrolling in the search container
L.DomEvent.disableScrollPropagation(searchControl.getContainer());
```

**Comment by pouemes** [comment]
A great thank it work in changing mousewheel by wheel in the plugin
thank you fake-design
