### ISSUE TITLE
Layer list gets cut off when many layers (or small map)

### ISSUE THREAD

**Issue by jtreml** [Leaflet/Leaflet#845]
The list of layers in the layer control doesn't scroll when larger than the size of the map (either because of many layers or a small map viewport) and just gets cut off. This means many of the layers are no longer reachable to be activated / deactivated. Apart from this, obviously, it doesn't look all that nice either.

My suggestion would be to simply go for natural overflow handling by the browser, i.e. allow for scroll bars to appear once the layer list gets to large. Only problem is, with the styles as they are, I haven't found simple, tiny, 3-line solution to the problem but always had to touch quite a few of the style to achieve this.

Maybe someone has some suggestions here?

**Comment by benmbutler** [comment]
Is it possible to alter the "leaflet-control-layers" parameters from R in order to allow for scrolling in the layers box? I can do it manually by inserting the following code into the html file, as suggested,

`<style type="text/css">`
`.leaflet-control-layers {`
`max-height: 600px;`
`overflow: auto;}`
`</style>`


however it would be really useful to do it directly from R.

**Comment by ghybs** [comment]
Hi @benmbutler,

Thank you for your request.
This issue tracker is for the core Leaflet library.

Bugs and feature requests for 3rd party integrations should be addressed on their respective source.
In your case (R), I believe it should be https://github.com/rstudio/leaflet

If you are sure there is a bug in Leaflet itself, please open a new issue.
