### ISSUE TITLE
Release 1.9.2

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8522]
Creating this issue to coordinate the release of 1.9.2. cc @mourner @Falke-Design @Malvoz

**Comment by mourner** [comment]
Looks like nothing's missing, we can proceed. Copying the checklist here to track:

## Releasing a new version of Leaflet

- [ ] Ensure all https://github.com/Leaflet/Leaflet/labels/blocker issues and pull requests are resolved.
- [ ] Update [the changelog](https://github.com/Leaflet/Leaflet/blob/main/CHANGELOG.md) since last release and commit.
- [ ] Run `npm version <patch | minor | major>` (this will bump the version in `package.json` and create a new tag).
- [ ] Run `git push --follow-tags` to push the commit created by NPM to Github (together with the tag).
- [ ] Wait for the CI to complete and follow the logs to make sure it runs successfully.
- [ ] Verify that the release was correctly published to NPM by checking:
  - [ ] [Leaflet NPM package page](https://www.npmjs.com/package/leaflet)
  - [ ] files on [Leaflet unpkg page](https://unpkg.com/leaflet@latest/)
- [ ] Make a new release on [Leaflet's GitHub release page](https://github.com/Leaflet/Leaflet/releases/) with the most important parts of the changelog

### Updating docs after the release

- [ ] Make a new branch for the update
- [ ] Write a blog post about the new release and put it in `/docs/_posts/`
- [ ] [Click here to save a snapshot](https://web.archive.org/save/https://leafletjs.com/reference.html)
of the version of docs prior to this release to the Internet Archive's Wayback Machine
(and optionally, add a link to the snapshot in `docs/reference-versions.html`).
- [ ] Run `npm run docs` to generate the new `docs/reference.html` and update integrity hashes in `docs/_config.yml`
- [ ] Update link to latest release in `docs/download.md`
- [ ] Update the announcement section in `docs/index.html`
- [ ] Commit all the changes and submit a PR for someone to review

**Comment by Falke-Design** [comment]
@jonkoops looks good for me

**Comment by Falke-Design** [comment]
Maybe we want to merge #8523 it's a problem sinse 1.8.0

**Comment by jonkoops** [comment]
#8523 has been added, I will get started on the release.

**Comment by jonkoops** [comment]
@mourner @Falke-Design got a PR up for the changelog (#8526), let me know what you think.

**Comment by mourner** [comment]
@jonkoops made a few edits in https://github.com/Leaflet/Leaflet/releases/tag/v1.9.2 changelog for clarity — probably worth moving over to `changelog.md`.

**Comment by Falke-Design** [comment]
We forgot to include #8523

**Comment by mourner** [comment]
@Falke-Design no, it was included — see https://github.com/Leaflet/Leaflet/commits/v1

**Comment by mourner** [comment]
Ah, right, the changelog — that too!

**Comment by Falke-Design** [comment]
> @Falke-Design it is included in the release, but it looks like it was forgotten in the release notes.

Yes sorry, that was what I ment

**Comment by jonkoops** [comment]
@mourner @Falke-Design I added a PR to update the docs #8527.

**Comment by mourner** [comment]
Updated the release notes with the popup bug too.

**Comment by jonkoops** [comment]
I'll create another PR to update the change log.

**Comment by jonkoops** [comment]
I think we're good with all the release tasks so I am closing this issue.

**Comment by Falke-Design** [comment]
Thanks!
