### ISSUE TITLE
LatLngBounds.contains() giving incorrect 'false' on projected map

### ISSUE THREAD

**Issue by anton-seaice** [Leaflet/Leaflet#8715]
### Steps to reproduce

1. Define a map using a custom CRS
2. Define newBounds = L.latLngBounds() with bounds within the map
3. Execture map.getBounds().contains(newBounds)

### Expected behavior

Result is true

### Current behavior

Result is false

### Minimal example reproducing the issue

https://jsfiddle.net/anton_seaice/cmnuqkvs/170/

```html
<script src="https://unpkg.com/leaflet-polar-graticule@0.1.1/L.Graticule.min.js" integrity="sha256-qcx0lAi/Z5A1QY1n74v2fjE4BDRHtTMyJOcdsvbRudU=" crossorigin="anonymous"></script>
```

```js
const proj = 'EPSG:3031';
const proj4= '+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs';
const crsOpts={
		resolutions: [8192, 4096, 2048, 1024, 512, 256], 
		origin: [-4194304, 4194304],
		bounds: L.bounds (	[-4194304, -4194304],	  [4194304, 4194304]	)
	} ;
  
let crs= new L.Proj.CRS(proj, proj4, crsOpts) ;

var map = L.map('map', {  crs:crs,  center: [-90, 0],  zoom: 0 });
 
L.graticule({ intervalLat: 10, intervalLng: 30, latBounds: [-90,-55], centerLonLabels:true }).addTo(map) ; 
 
myBounds = L.latLngBounds([-80,-60], [-80,120]) ;

L.polyline([[-80,-60],[-80,60], [-80,120], [-80,240], [-80,-60] ]).addTo(map) ;

console.log(map.getBounds().contains(myBounds))
```

### Environment

- Leaflet version: 1.9.2
- Browser (with version): Chrome 108
- OS/Platform (with version): Windows 10

**Comment by IvanSanchez** [comment]
This is... actually behaviour as expected, as strange as it might sound at first.

`L.LatLngBounds` works on geographical coordinates (i.e. EPSG:4326), **not** on projected coordinates. For the common use cases (displaying a map in EPSG:3857 web mercator), this is no problem. 

But your bounding box, `[-80,-60], [-80,120]` is a problem here - it has zero area when interpreted in EPSG:4326. Which becomes a problem.

Also see what happens when drawing those bounds with a `L.Rectangle`, compared to the rectangle in your example:

```js
myBounds = L.latLngBounds([-80,-60], [-80,120]) ;
L.polyline([[-80,-60],[-80,60], [-80,120], [-80,240], [-80,-60] ]).addTo(map) ;
L.rectangle(myBounds, {color: 'red'}).addTo(map);
```

![imagen](https://user-images.githubusercontent.com/1125786/207856317-b1260e14-d9d3-43fa-a630-7d6ce6ba1bd7.png)

You'll need to perform the [spatial relationship](https://en.wikipedia.org/wiki/DE-9IM) operations in the projected CRS - and you'll have to be somewhat careful about reprojecting geometries.

**Comment by anton-seaice** [comment]
Thanks Ivan

Just in-case anyone searches this later ...


I looked in the [bounds](https://github.com/Leaflet/Leaflet/blob/main/src/geometry/Bounds.js) code and all it does is compare min x and min y.

See line 135;
```
return (min.x >= this.min.x) &&
		       (max.x <= this.max.x) &&
		       (min.y >= this.min.y) &&
		       (max.y <= this.max.y);
```

Which is not an accurate calculation of contains over the poles (and maybe in other projected scenarios). (e.g. in my map bounds, min lat and max lat are both approximately -40)

I think [Geo-extent](https://github.com/DanielJDufour/geo-extent) attempts to address this in a projection aware way, but I haven't tested it.
