### ISSUE TITLE
Replace as many `for...in` loops as possible with `for...of`

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8843]
Enable of the [`guard-for-in`](https://eslint.org/docs/latest/rules/guard-for-in) rule and fix as many cases as possible by replacing them with a `for...of` loop instead.

_Originally posted by @jonkoops in https://github.com/Leaflet/Leaflet/issues/8840#issuecomment-1426855332_

**Comment by alope107** [comment]
I took a quick look over all the linting errors that enabling `guard-for-in` brings up, and I don't think any of the remaining ones can be resolved by switching to a `for...of`. They're all errors related to using unguarded `for...in` loops over objects. Fixing these requires adding guards instead of changing the loop type. 

If there's an appetite for it, I would be happy to open a PR that enables the linting rule and adds the suggested `if ({}.hasOwnProperty.call(foo, key))` in all of the 39 problematic places. Just let me know and assign this issue to me if you'd like 🙂

**Comment by jonkoops** [comment]
Sounds good @alope107. I'd also prefer to use [`Object.hasOwn()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) wherever possible.

**Comment by mourner** [comment]
> Fixing these requires adding guards instead of changing the loop type.

Alternatively, we could do `for (const item of Object.keys(obj))` instead of `for ... in` + guards. Modern JS engines optimize for cases like this so they shouldn't be slower most of the time.

**Comment by alope107** [comment]
I like the suggestion @mourner. Either way introduces some extra boilerplate, but I think using `Object.keys` clutters things a bit less. What do you think @jonkoops?

As an additional thought, is there anywhere that the convention of using `Object.keys` should be documented for other contributors so that future code uses it? The lint rule will help, but I imagine a lot of people's first instinct will be like mine to use `hasOwn` or `hasOwnProperty` to quell the error.

**Comment by alope107** [comment]
Looking at it closer, we can't just use `Object.keys(obj)` because this will cause an error if `obj` is `undefined` or `null`. We could add some extra null-checking, but then it starts to be more complicated than the guard anyway. Doing more research online, it does seem like adding the guard is the idiomatic way to do it, so I'll make the PR follow that convention.

**Comment by alope107** [comment]
Took a first pass a PR, let me know what you think 🙂
