### ISSUE TITLE
Leaflet flickering on zoom 

### ISSUE THREAD

**Issue by MuhammadHashir28** [Leaflet/Leaflet#9037]
on Zoom Flicker /Shake happen please help me fix this  
http://assistcenter.gg/map

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[plunkr](https://leafletjs.com/edit) that displays this behaviour?

**Comment by Falke-Design** [comment]
The problem occurs in `setPosition` here after the `zoom` event: https://github.com/Leaflet/Leaflet/blob/6a06b4bd9b1cfdf53206c9bb180e416d08247ddc/src/layer/ImageOverlay.js#L239

I'm pretty sure that it has somthing todo with react, because it looks like the image is set to [0,0] and then it moves to the position. It is more visible if you are on a high zoom level. 

Is working fine in vanilla Leaflet: https://plnkr.co/edit/zavJTk7WwOUlcBFN

Please create a demo on stackblitz or codesandbox (with only the code to reproduce this issue) and then make an issue in `react-leaflet`.

**Comment by MuhammadHashir28** [comment]
Urfortunatletly code cannot able to be deployed can this be fix using some animation.
