### ISSUE TITLE
Stopped woking with leafmap on displaying Satellite imagery

### ISSUE THREAD

**Issue by pabhermoso** [Leaflet/Leaflet#9321]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

If you open this (https://huggingface.co/spaces/giswqs/Streamlit) webapp  for example, you see the leafmap is not displaying correctly.

### Expected behavior

Should load satellite imagery from Openstreetmap

### Current behavior

Does not load.

### Environment

- Leaflet version: 
- Browser (with version): Chrome
- OS/Platform (with version): Mac

**Comment by IvanSanchez** [comment]
This is the repo for Leaflet, not for Leafmap (https://leafmap.org/ / https://github.com/opengeos/leafmap ).

Please read ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) before opening a bug report there.

**Comment by IvanSanchez** [comment]
Since Leafmap is a python wrapper for Leaflet, this earns the blanket "issues in the JS core only" response.

---

Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Bootstrap
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* TypeScript
* D3
* Folium
* NativeScript
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropriate repo.
