### ISSUE TITLE
bringToBack/Front not working in Canvas

### ISSUE THREAD

**Issue by bryanmills** [Leaflet/Leaflet#974]
When using Canvas rendering bringToBack/Front appears to be ignored. I'm seeing this behavior in version 0.4.4.

Is there a workaround for this?

Thanks.

-bryan

**Comment by zhujy8833** [comment]
Hi guys,

Is there any updates on this feature? Currently I have a project needs to use Leaflet Canvas option, I want to place `layer1` first and `layer2` later so it would render `layer2` on top of layer1.
I tried: 
```
featureGroup.addLayer(layer1);
featureGroup.addLayer(layer2);
```
However, it turned out that `layer1` was rendered on the top, and I guess there are some events triggered `_updatePath` on `layer1`, which made it repaint and eventually layer it covering `layer2`. I wonder if `bringToFront()` could be one option that I can give a shot.
Any suggestions are welcome.

Thanks in advance.

**Comment by sainsb** [comment]
+1

**Comment by jbccollins** [comment]
+1
